### ISSUE TITLE
French translation should be usual and common French

### ISSUE THREAD

**Issue by trebmuh** [tootsuite/mastodon#10025]
It looks like the French translation of Mastodon is managed by people who are wanting to promote/enforce the "gender-neutral" thing. Despite some people may feel hurt by this, the "gender neutral" form isn't an official one. At all.

I understand here that some people are wanting to promote/enforce this way of practicing the language for "the good" but it's definitely not a right way of doing so. At the top of that, Mastodon deserve to be readable/usuable by **any** French reader, not only the "I'm OK with gender-neutral reading" French readers. And the reverse is right too, any French reader deserves to be able to use Mastodon in French, not only the "I'm OK with gender-neutral reading".

My proposition is: make the basic French translation, the common and usual one (ie: no gender-neutral), and allow people who want it to have a "gender-neutral" version if they want to (like it exists for some software with English, English-American, English-Australian, Simple-English,...).

A bit of background here: #9405 which has avoided a bunch of fixes for the French translation, which is bad in my opinion, because those were relevant.

**Comment by Cassolotl** [comment]
The proportion of queer, trans and nonbinary people is *much* higher on Mastodon. By making "official" French the default you'd be making a lot of people feel alienated and unwelcome - people who have been heavily involved in building community on Mastodon and who have been contributing to code since the early days.

Plus, the fediverse in general is pretty counter-cultural, and "official" French is one of the cultures folks are countering, presumably?

**Comment by Technowix** [comment]
Also, there is lot of officials papers that are written in "inclusive French" now, instead of putting the feminine in parenthesis.
While I would alway by okay in reducing the use of median points when possible (ugly necessary hack of the language I would say).

I honestly don't see improvements in using, say, "abonné(e)s" instead of "abonné•e•s".

**Comment by ThibG** [comment]
As far as I know, the French translation is indeed, and has always been “managed” by people who want to promote gender-neutral language, and I do not think that is an issue.

I think the current state of the translation manages to be especially concise and readable while being consistently gender-neutral.

It is possible that some part of the translation could be changed to replace some uses of the “·e” form by simpler gender-neutral nouns or adjectives. I think such changes would be welcome, but giving up on gender-neutral language would not be.

As for having multiple variants of the French translation, I do not think this would be worthwhile, and, should that happen anyway, I see no reason not to have the gender-neutral variant be the default.

**Comment by 0xa** [comment]
- That a handful of purists refuse to consider it the official form is not relevant to whether or not we should use it.
- I don't think it's actually any less accessible that a "no gender-neutral" version, that's mostly your own bias and you shouldn't believe it's a general rule until properly proven.
- Keeping the old behavior as the default would expose people less to the neutral form, by requiring an explicit action to select it, which will not help getting them used to it. It's like saying if we want to be considered in the language used we have to go change an obscure setting. Why, when you can make it neutral and move on.

**Comment by nighteyesfool** [comment]
Just to add on to this, if we never expose people to more inclusive forms of writing, how can you expect the norm to evolve?

**Comment by goofy-mdn** [comment]
Hi [trebmuh](/trebmuh)
I would suggest to reverse your proposition

> make the ~~basic~~ **_gender-neutral_** French translation, and
> allow people who want it to have a ~~gender-neutral~~ _**official**_ version if they want to

and as things are you are perfectly allowed to propose academic French in your instance, it is just a bunch of files to browse and edit here and there.
Fediverse is a new experience, I feel this is a pretty good occasion to push slowly the norm to evolve. I don’t feel it would hurt anyone so cruelly not to find strict standard French in this environment.

**Comment by nclm** [comment]
I am too very strongly against switching to a non-inclusive variant of French.

What we can certainly do, is improve the way the inclusiveness is done, notably by replacing some of the “⋅e” by épicène words, as suggested earlier by ThibG. For instance in #8401, I made a trial of using “membre” instead “utilisateur⋅rice” and “pseudonyme” instead of “nom d’utilisateur⋅rice”. Those were examples, but along these lines we can certainly reduce a little the number of middle dots. The locale should certainly reads nicely, but it hasn’t intrinsically to do with inclusive writing.

In the worst case if there’s a feeling that some people might not accept it, we can indeed have a variant French translation, something like “Français (classique)” or “Français (traditionel)”, as goofy-mdn is suggesting. (@Gargron: is it possible for a locale to be a variant of another, so that when strings are missing it fallbacks to the other locale, rather than to English?). I’m not convinced is needed, but if others are like trebmuh and prefer it, that can be a workaround.

**Comment by nclm** [comment]
I am too very strongly against switching to a non-inclusive variant of French.

What we can certainly do, is improve the way the inclusiveness is done, notably by replacing some of the “⋅e” by épicène words, as suggested earlier by ThibG. For instance in #8401, I made a trial of using “membre” instead “utilisateur⋅rice” and “pseudonyme” instead of “nom d’utilisateur⋅rice”. Those were examples, but along these lines we can certainly reduce a little the number of middle dots. The locale should certainly read nicely, but it doesn’t intrinsically have to do with inclusive writing.

In the worst case if there’s a feeling that some people might not accept it, we can indeed have an optional variant French translation, something like “Français (classique)” or “Français (traditionel)”, as goofy-mdn is suggesting. (@Gargron: is it possible for a locale to be a variant of another, so that when strings are missing it fallbacks to the other locale, rather than to English?). I’m not convinced it is needed, but if others are like trebmuh and prefer it, that can be a workaround.

**Comment by trebmuh** [comment]
Well... I didn't know that gender-neutral form was that much of an ideology for some. Crazyness.

Just answering one for all: 
> I don't think it's actually any less accessible than a "no gender-neutral" version, that's mostly your own bias and you shouldn't believe it's a general rule until properly proven.

... French dictionaries, French languages for the last few centuries, ...etc but "there is no more blind person that the one who doesn't want to see".

Honestly I don't care about what people are doing with their mucous membrane, and I feel here that using the so-called "gender" language for the own need of a few bunch of people is really not welcoming for all the others. That makes Mastodon, a self-centered communities. Too bad, I though it was open.

Have a nice fake-revolution people, see you on earth on day maybe.

**Comment by Lertsenem** [comment]
Keeping the text gender-neutral is a stated goal of Mastodon's french translation managers. Since this is a software intended to be used by people of any gender, I see no reason for that to change.

Now, as I understand it, the author would like to move some terms to a more traditional (rather than "official", since language is a matter of description, not prescription) form of gender-neutrality such as "abonné(e)s" instead of the more recent form "abonné·e·s". I do not favour such a change: I find the use of the interpunct much more readable than the old parenthesis by keeping the typography lighter, while leaving the feminine "e" mark on equal footing with the rest of the word.

**Comment by AirDur** [comment]
> , French languages for the last few centuries, ...etc but "_there is no more blind person that the one who doesn't want to see_".

The new Académie française's new dictionnary will have 28 000 more words than the last one, released on 1935. 
For the last few centuries, french evolved a lot, and very quickly. It's not an ideology, a "fake-revolution" (what the hell is it ?), it's a fact.
Source : https://fr.wikipedia.org/wiki/Dictionnaire_de_l%27Acad%C3%A9mie_fran%C3%A7aise#Neuvi%C3%A8me_%C3%A9dition

You should check the concept of Modern Language. French isn't Latin. It's not a dead language.

**Comment by trebmuh** [comment]
Thank you for taking the time to talk to me in a way which is that respectful of the suggestion I was making here.

**Comment by AirDur** [comment]
What you did is a fallacy of composition. You're taking a behavior from a part of Mastodon for the behavior of all Mastodon. It's a common sophism. 

Moreover, talking about respect - while i didn't insult, aggress or harass you - is a passive-aggressive method to illegitimate my argument. I hope you'll reconsider this and you'll think about what I said, and not how I said.

Have a good day.
