### ISSUE TITLE
Installation / Setup Guide?

### ISSUE THREAD

**Issue by dinosaw** [tootsuite/mastodon#1012]
Does anyone have an installation / setup guide for this? The docs mentioned here seem to explain bits and pieces, but fail to put the pieces of the puzzle together. I've tried setting it up with both processes (Docker/Docker-Compose and Nginx production guide) but have ran into issues due to incomplete or unclear information in the documentation.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by lae** [comment]
The `Vagrantfile` has a list of instructions in it, if that helps.

**Comment by ashfurrow** [comment]
Our [production guide](https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Production-guide.md) and corresponding DOcker/Vagrant/Heroku guides have been updated substantially since this issue was opened. If it's okay with you, @dinosaw, I'm going to close the issue. Please feel free to re-open (or open a new issue) if the guides can clarify anything.
