### ISSUE TITLE
Giphy Intregation

### ISSUE THREAD

**Issue by vibhi19** [tootsuite/mastodon#10364]
It would be awesome to have Giphy intregation so we can use it without downloading GiF and uploading it manually. 

Its fun to reply to someone with GiF 

<img src="https://media.giphy.com/media/d1E1r63qgSv5L8GY/giphy.gif" >

**Comment by m4sk1n** [comment]
Relying on proprietary service for something as unimportant as GIFs?

**Comment by trwnh** [comment]
Mobile keyboards and browser extensions already integrate Giphy. There is no reason for Mastodon to do so as well.

**Comment by Xoldie** [comment]
Can you explain more about browser extensions? Thanks
> Mobile keyboards and browser extensions already integrate Giphy. There is no reason for Mastodon to do so as well.

**Comment by vibhi19** [comment]
> Relying on proprietary service for something as unimportant as GIFs?

What issue people have here with centralized services?   Its not useless when its fun

**Comment by m4sk1n** [comment]
>What issue people have here with centralized services?

So, leave Mastodon and go back to Twitter lmao

**Comment by vibhi19** [comment]
> Mobile keyboards and browser extensions already integrate Giphy. There is no reason for Mastodon to do so as well.

People overfacebook and twitter whatsapp can also think like that but they added because they understand non tech savvy people want it . not everyone into using third party keyboard or extension

**Comment by vibhi19** [comment]
> > What issue people have here with centralized services?
> 
> So, leave Mastodon and go back to Twitter lmao

<img src="https://media.tenor.com/images/77091c9904f632688a828ebbff0d8fe4/tenor.gif" >

**Comment by coreyreichle** [comment]
> > Relying on proprietary service for something as unimportant as GIFs?
> 
> What issue people have here with centralized services? Its not useless when its fun

While there may be a use case, and it may be fun, it is inherently dangerous to the user, since giphy now knows what users use mastodon, and which instances they use.

**Comment by Gargron** [comment]
Giphy integration requires an API key. That is, API key that every server admin would have to independently acquire. It is bothersome, and most admins won't do it because the value proposition is not seen as important by the current community. This feature request would be a good plugin idea, if there was a plugin system (but there isn't)

**Comment by trwnh** [comment]
GIPHY for Chrome: https://chrome.google.com/webstore/detail/giphy-for-chrome/jlleokkdhkflpmghiioglgmnminbekdi?hl=en
GIPHY for Firefox: https://addons.mozilla.org/en-US/firefox/addon/giphy-search/

On mobile, GIPHY is also integrated into Gboard, Swiftkey, Fleksy, etc., or you can download the GIPHY app and enable the GIPHY keyboard if your desired keyboard doesn't have integration.

As there are a variety of ways to access GIPHY that don't require integrating it into Mastodon directly, it's far better to use one of those instead if you want that functionality.

**Comment by Timothyjchambers** [comment]
BTW, here is how Signal added Giphy but worked to respect user privacy:

https://signal.org/blog/giphy-experiment/

**Comment by Beheadedstraw** [comment]
A feature that literally every other social service has and yet, for some reason, the devs are forcing web users to use round about ways (and forcing use of certain web browsers) to implement said feature... I'm going to +1 giphy addon. Not everyone is a mobile user that has easy access to add gifs nor wants to stick with the chrome and firefox extensions.

If privacy really was an issue here we wouldn't peddle browser extensions to implement said feature.

**Comment by Liquidream** [comment]
I too would still be interested in something like this.
Alas, the GIF button on Android's GBoard doesn't seem compatible with Mastodon app (says "doesn't support image here" or similar)
Still, would be gr8 to also have a similar option in web client - to negate having to separately search, dbload, upload GIFs (for ppl like the that enjoy expressing ourselves through such media 😊)
Thanks!

**Comment by lanzz** [comment]
> Relying on proprietary service for something as unimportant as GIFs?

We obviously need a Fediverse alternative for Giphy

**Comment by Vapok** [comment]
> On mobile, GIPHY is also integrated into Gboard, Swiftkey, Fleksy, etc., or you can download the GIPHY app and enable the GIPHY keyboard if your desired keyboard doesn't have integration.

Except you can't....

![image](https://user-images.githubusercontent.com/1264136/201263254-655aa407-0ac6-4d88-892c-fef466260bbd.png)

**Comment by Vapok** [comment]
I think the problem with the current mentality around not supporting GIPHY, is that as admins (me) we're going to see continued and increased use of people still downloading the GIF and uploading it, regardless of the thinking here in this thread.  That's going to actually increase my hard drive space usage, and possibly make it even so that I have multiple different types of the same GIF laying around making caching moot.

When the simple fix is to render and support external links from GIPHY or TENOR so that those links render appropriately. Then the link is the only thing stored, not the image asset.

**Comment by crusy** [comment]
+1, Mastodon needs this. I‘m on iOS and cannot use one workaround (and they‘re not more than a workaround) mentioned here.

And as user count keeps increasing, the argument of @Vapok gets even more important.

**Comment by zerojay** [comment]
> > Relying on proprietary service for something as unimportant as GIFs?
> 
> We obviously need a Fediverse alternative for Giphy

As someone that can take or leave GIF/Giphy type support, I feel like the one real problem with adding support for GIFs is that you absolutely know there won't be text descriptions on those GIFs, further alienating those that need to use screen readers and such and making the fediverse less accessible in general, as we all know a lot of people will use them.

A Fediverse alternative would be excellent, especially if those GIFs from this alternative came with default text descriptions since it's not like the individual GIFs would change and would allow those using screen readers to join in on the fun.

**Comment by Beheadedstraw** [comment]
> 

The problem is using an **_extremely_** small subset of a population to use as an excuse to not implement what is basically a standard social feature. I get sticking it to the man, but it's not like giphy is directly charging money from mastodon admins or users either. A federated image sharing platform sounds like a nightmare to implement let alone maintain, because naturally users will eventually migrate to using one server anyways that's considered reliable.
