### ISSUE TITLE
Browse Other Instances' Public Timeline

### ISSUE THREAD

**Issue by sturmen** [tootsuite/mastodon#1053]
As a user on one of the many smaller instances, sometimes I'm interested in checking out the "local culture" of other instances and perhaps finding new people to follow. I'd like a way to browse these other instance's timeline and discover new people, and remote follow them to add to my personal timeline.

Such a feature would obviously be a privacy toggle by the instance admin, but I think it would enable greater discovery across instances.

* * * *

- [✔️] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by padpanik** [comment]
I was just thinking the same, that would be the most cool feature. That would help everyone to undestand better the Instance things. 

I don't know how to vote for that feature, but count my vote in !!!

After one day on mastodon, what i like is the public stream global and local but i'm frustated to not be able to switch on different local instance (and yes instance admin just should have a private switch).

**Comment by ryanleesipes** [comment]
Everyone in my office has requested this feature! Just giving it another +1 with this comment!

**Comment by trwnh** [comment]
#1189 and #1143 are duplicates.

**Comment by krainboltgreene** [comment]
Marked the others as duplicates.

**Comment by madCdan** [comment]
+1

**Comment by thor-the-norseman** [comment]
I've been trying to find Norwegians to follow on my new Norwegian instance. It's really hard to find people across the network. A public timeline would really help.

**Comment by foozmeat** [comment]
pulling in my comment from a dupe issue:

Thinking about implementation...a rough, incomplete, unordered todo list:

* boolean flag in admin settings (some places may not want a public timeline shown)
* copy and modify the public user template for rendering the timeline
* only show local, public, non-reply toots
* route it under `/public`?

**Comment by Shnoulle** [comment]
> only show local, public, non-reply toots

If you give admin choice : 3 option : none / only public and nonreply toot / public + reply + favorites (boost) and repeat.

In my opinion

**Comment by 2aucka05** [comment]
This just makes sense!

**Comment by Scrxtchy** [comment]
I wonder if this should be called the `Remote Timeline`
I like it since it will allow me to discover content more easily from specific instances

**Comment by zorun** [comment]
I just implemented a proof of concept for this "remote timeline" feature.  The code is in https://github.com/zorun/mastodon/tree/remote-timeline-1.3.3 and here are some screenshots:

![mastodon-remote-demo1](https://cloud.githubusercontent.com/assets/731144/25776308/3255103c-32bb-11e7-9722-91abf9355b5a.png)

![mastodon-remote-demo2](https://cloud.githubusercontent.com/assets/731144/25776309/32579dd4-32bb-11e7-81e0-637d7735432b.png)

It's really just a proof of concept:

 - the remote instance is hard-coded (`mastodon.social` in the code, `pawoo.net` in the screenshot);
 - there is no automatic refresh, because the streaming API currently requires authentication (see #2006).

**Comment by Shnoulle** [comment]
@zorun : great if you already have a mastodon account :) but it didn't fix 
https://github.com/tootsuite/mastodon/issues/1436 or https://github.com/tootsuite/mastodon/issues/1143 :)

Maybe this feature must be separated in 2 : 

1. Show public local TL on home page (with option for admin and for each user) (see pawoo fork for an example)
2. Allow to “load” a external public time line in mastodon

**Comment by kevinmarks** [comment]
I built a viewer for this a while back: http://www.unmung.com/mastoview?url=mastodon.social&view=local

**Comment by koyuawsmbrtn** [comment]
like @zorun said, i want to see everything in the public timeline, not just the posts of the connected instances. maybe there should be something, which puts all instances together in the public timeline for a better federation. that's what i meant. creating a new instance ends up in a lonely public timeline.

**Comment by Cassolotl** [comment]
Public timelines are now viewable on the /about page before logging in or registering, so this can now be closed, right?

**Comment by zcdunn** [comment]
> As a user on one of the many smaller instances, sometimes I'm interested in checking out the "local culture" of other instances and perhaps finding new people to follow. I'd like a way to browse these other instance's timeline and discover new people, and remote follow them to add to my personal timeline.

There's still no way for a user to view the local timeline of another instance. The timeline on the /about page defaults to federated timeline so new users get a full view of the network, according to @Gargron.  I'd like to be able to add a remote instance's local timeline as a column on my instance, which would let me participate in the culture of an instance without having to create a new account for every interest I have.

**Comment by Cassolotl** [comment]
Ohhh I see what you mean! That seems different to the first post, though.

**Comment by aa-m-sa** [comment]
I like the ideas showcased in this PR! My personal ideal would be to be able to follow several smaller instances and maybe some larger ones with ease.

The ability to preview the local timeline before joining instance would be nice. To some extent this is currently achievable with 3rd part tools such as http://www.unmung.com/mastoview?url=mastodon.social&view=local .

However, even with that feature, AFAIK you'd still need to individually check each instance to see what happens there, which is a hassle. So I like the "remote timelines" idea too, it would be even better improvement. Ideally, you'd could simultaneously observe several timelines in single view *a la* Tweetdeck.

**Comment by Cassolotl** [comment]
@aa-m-sa Since 1.6 (or maybe earlier) you can see the instance's public federated timeline on the /about page, I think?

**Comment by zer0her0** [comment]
I also think this feature would be awesome as it would also aid in discovery. While federated timeline was fine at first, on any large instance it just flows way to quickly and full of things I'm not interested in & I started creating accounts on all the instances that I was interested in to find and follow people on the local timeline. This would keep me from filling other instances w/ accounts and help me find more people to follow! There are clients that already support this it would be nice to see it be server side and therefore synced across apps/machines.

**Comment by D4nte** [comment]
Agree with the proof of concept to be able to add a remote timeline.
However I see it more as a discovery tool than anything else.

**Comment by ashemedai** [comment]
I would like to add my +1 to having an option to have a specific instance's local timeline to view. There's a few that are very focused in content and I do not necessarily want to follow everyone on that iknstance, but would be interested in monitoring the instance's local timeline. Federated timeline is too high noise for me and will only decrease is usefulness as the userbase grows.

**Comment by LC43** [comment]
i'm a new user ( on mastodon.social ), hope I can provide some feedback:

- I found that, in order to join other instances, I would have to create a new user. This is very frictious. It would also mean that my alias could be unavailable in some of them, but I guess this is a consequence of the model.

- As pointed before, the federated(?) timeline is too noisy, auto-refreshes and very alienating. 

- I don't understand why i have to have multiple tabs, one for each instance.

- I wanted to follow ( remote-follow ) a user on another instance , but it's pending approval from someone / something.

- I can't link my profile between instances.


I have other critiques with the UI, but i'll leave it for another issue, thanks for reading.

**Comment by nightpool** [comment]
@LC43 

By having an account on mastodon.social, you're *already* interacting with users on other instances. It's like email—you don't need an account on yahoo.com to send email there. You don't need to have multiple tabs or multiple users.

> I wanted to follow ( remote-follow ) a user on another instance , but it's pending approval from someone / something.

if the user has set their account to private, they're required to approve followers. this is the same as how twitter works.

**Comment by LC43** [comment]
thanks @nightpool for your reply regarding the following users!

As for my other points, I wanted the featured that is being discussed here: to be able to replace (every) column with other instances timelines, not just #tags. If i want to join masto.pt and see its local timeline, i have to register and have a tab open there, and one for each instance that i already joined.

I'll do a bit of research, in case i'm doing it wrong, and so to not add noise to this issue.

**Comment by nightpool** [comment]
There are website that will show you this, but my opinion is that if you want to view the instance timeline of another instance as part of your day-to-day browsing of the service, you should sign up for an account on it. Otherwise you have this issue where a small number of users are "performing" for a much larger audience, and there's no way for the users *viewing* that timeline to "join in", and post things to that timeline. this leads to very awkward possible community issues.

I think the biggest concerns here will be solved by groups, maybe?

**Comment by aa-m-sa** [comment]
@nightpool 

> Otherwise you have this issue where a small number of users are "performing" for a much larger audience, and there's no way for the users viewing that timeline to "join in", and post things to that timeline. this leads to very awkward possible community issues.

This is a very good point that I had not thought about before. In that case handling several accounts on several instance should be made easier and more low-effort. In other words, the UI should suggest an easy workflow for participating on many instances.

* I think ability to browse all your accounts on several different instance in the same UI would still be more useful feature, instead of a need to keep e.g. one browser tab per instance.
* The profile text is often too small to include links to your presence on other instances, especially if you have several accounts.

Is there already related Issues on these feature requests or should new issues be created?

**Comment by remram44** [comment]
People making instances about a specific topic is the main reason we want this, but perhaps a different fix is necessary. Maybe birdsite's "list" feature would be better than creating instances?

**Comment by nightpool** [comment]
see also #139

**Comment by aa-m-sa** [comment]
@remram44 

>People making instances about a specific topic is the main reason we want this, but perhaps a different fix is necessary. Maybe birdsite's "list" feature would be better than creating instances?

I think the topic / localized instances are a good thing, just the UI experience is suboptimal (Topic instances encourage Mastodon to be a true federation of local servers and communities that develop on them, than "yeah we support federation in theory, but in practice everybody registers on the most famous main instance").

**Comment by NathanHawks** [comment]
I was routed here because I created a dupe issue and I feel like the issue has been overthunk. All I need is:

- If I can already see public toots from a specific instance
- Let me make/nav-to a column filtered down to those toots

Possible easy-as-pie implementations:

- a search symbol like @instance.host
- a dropdown filter in Global Timeline

**Comment by feoh** [comment]
I'm with @NathanHawks - I think the low hanging fruit nature of this would make it an excellent way to showcase Mastodon's distributed nature to newcomers and veterans alike, and allow the individual nature of some of its sub-communities to really shine.

**Comment by fsnk** [comment]
What I'd like to see is local timelines treated like a special case read-only !group that people could remote subscribe to read.

**Comment by Cassolotl** [comment]
>I hear a lot about "participating in the timeline discussions" which doesn't make sense to me since it's just an chronological aggregate stream of all the public posts on a server, not threaded or anything

This, and replies don't go to the public timelines either, so you don't see a whole discussion - only the originating posts.

**Comment by NathanHawks** [comment]
Some people here are clearly top professionals at overthinking simple things until they're unrecognizable. There's nothing deep to understand here, but apparently at no point do some of you arrive at the simple and obvious thought the rest of us all stopped at.

How is this in any way hard to understand?
- Federated Timeline = useless firehose that will only get worse
- Leaving accounts everywhere = non-solution and bloats the instances

Making it a group = bad idea, requires others to modify their behavior

Waiting for others to use tags = bad idea, requires others to modify their behavior

@fsnk Nobody's confused about what a local timeline is. It's a convenience nobody can have unless they're on the same server as you. That's a problem.

I estimate this conversation has consumed about 40x more effort that it would take to implement the caveman-obvious solution everyone wants.

**Comment by NathanHawks** [comment]
@fsnk "Participating in the timeline discussion" sounds to me like someone is confused from overthinking. That phrase has no meaning or bearing IMO. So to put that problem to bed by giving it meaning: **If** I can see a public toot, **then** I can reply to everyone currently involved in that conversation; I am therefore "participating in the timeline discussion".

This is of course already possible -- but not remotely convenient or user friendly **for particular use cases**. One such use case, is the current topic of conversation: people want it to be convenient and user friendly to "participate in the timeline discussion" of another server.

The solution is basically:

- clone the code for the Federated Timeline
- add a filter for the specific server
- done
- done
- no really it's done
- that's all
- just that
- and then it's done

Hopefully that was, yknow, detailed enough.

**Comment by gegeweb** [comment]
I don't know if this suggestion has already been made, I'm not very good at searching through the bug list.

The possibility for each administrator to exchange public feeds between instances would be a good idea.
A bit like the feeds on the Usenet network, with the possibility to filter or restrict the subscription to certain keywords.

I'm administering my personal instance, single user, and running a robot to feed the public timeline doesn't seem like a good idea. But in this case it requires a lot of subscriptions and interractions to federate well.

**Comment by corbindavenport** [comment]
^ That is my issue as well. I'm running my own instance, which means the federated timeline is just a mirror of my own timeline.

**Comment by gegeweb** [comment]
@corbindavenport Not exactly.
From what I understand, in the general public thread, there is:

- original messages to which one of the users of the instance replied.
- shared publications (boost, rettoot) by local users and users followed by local users
- Local user publications
- User publications followed by local users

In this state, when an instance starts, the history is empty.
Local thread seems to be a mirror of general public thread (federated timeline).
Since one user on the instance start to share and interract with others, no federated. Publications remain local, and it is difficult to find other users to follow or share with.
And it is difficult for other instances to know the local users.

In my opinion, as it stands, this is not really a decentralized network, federated, but not decentralized.
I don't know how the federation works with the Diaspora* network, but it seems to be closer to a truly decentralized and federated network. Because local publications are distributed to other pods, you can find other pod users, interact with them and follow keywords to start filling in the timeline.

If, however, the network is federated and pseudo-decentralized, how its work encourages it to join a large instances, which means that it concentrates on only a few access points.

For me, the only truly decentralized network remains the Usenet network thanks to the feeds system between server and flood diffusion through all peer-to-peer connections between servers (the peers).

That's why I think the direct exchange of public feeds between servers would be a good thing, and offer real decentralization. And if the profile could be federated and used from any access point, there would no longer be dependencies on a specific instance.

But maybe it's not the original purpose.

My [own principal instance](https://stoneartprod.xyz/about/more), started in November, 2017 federates at this time with 438 other instances. And [my testing instance](https://mastodon.gegeweb.org/about/more) (to undestand how federation works) with only one user following only the user of my principal instance, only with 15 other instances.

Have a good day (morning here) and Happy new Year to all.
And already thanks to all for this hard work, specially to the FreeBSD port maintener. ;)

**Comment by trwnh** [comment]
While revisiting this... Isn't the public timeline essentially exposed via `/api/v1/timelines/public` with the `local` parameter? Is there anything technical that remains, or does it just need to be implemented in the Mastodon web-app? I am inclined to assume the latter, since Tootdon has the ability to browse local timelines.

**Comment by wxcafe** [comment]
Instances that are up to date have their federated timelines displayed on the about page now anyways. I'm pretty sure this is implementable as a column but as said in the discussion there's no real benefit to it and it's easy to work around it for now. Closing.

**Comment by gegeweb** [comment]
@wxcafe 
Did I miss something?
I just upgraded to version 1.0.0-beta.2, and I don't see the federated timeline on the about page.

**Comment by Cassolotl** [comment]
Public timelines on /about pages was added in [1.5, in August 2017](https://github.com/tootsuite/mastodon/releases/tag/v1.5.0), if that helps?

**Comment by gegeweb** [comment]
@wxcafe shame on me! I'ts a mistake. I confused it with Peertube. ;)
I do have the public timeline on the about page of my Mastodon instance!

Sorry for the noise.

**Comment by Cassolotl** [comment]
@gegeweb No worries! :)

**Comment by arilando** [comment]
Why has this completely obvious feature not been added yet? Is there an app for desktop that has this feature?

**Comment by remram44** [comment]
@arilando keep in mind that Mastodon is an open-source project being provided to you for free. Please understand that no one owes you anything, and if this isn't here yet, it's because no one got around to making it. Feel free to help.

**Comment by BasixKOR** [comment]
I'm wondering why this issue has been closed. It is not available until now...

**Comment by Tagadda** [comment]
The public timeline in /about is configurable. It's up to the admin to choose between Local, Federated, or no timeline.

![mastodon](https://user-images.githubusercontent.com/36127788/40780680-7fa815c2-64d9-11e8-97b1-ad5a6ecfaeef.png)

**Comment by MichaelTunnell** [comment]
@wxcafe 

> I'm pretty sure this is implementable as a column but as said in the discussion there's no real benefit to it and it's easy to work around it for now. Closing.

I could not disagree more!

There is no benefit to it? I am on the main mastodon.social instance and I would like to see the timeline of a smaller instance and interact with that. Going to the website of that instance and reading the latest in the about section without having the ability to interact with it is not very useful at all.

I would like to interact with another instance more so than the main instance I am on. I joined before this smaller instance existed so I dont want to lose what I already have but I would like to interact with this instance as well. Right now, I can only interact directly with people of the instance or look at the incredibly cluttered federated timeline.

The local timeline of mastodon.social is just as cluttered as the entire federated timeline so I'd like to see the timeline of another instance that is focused on a topic that I am interested in. Right now, this is just not possible and thus this thread should not be closed, in my opinion.

**Comment by DSDeniso** [comment]
How can this issue be closed? This is really useful.

**Comment by Scrxtchy** [comment]
It was closed 4 months ago

**Comment by Scrxtchy** [comment]
Ask for it to be opened, not closed

**Comment by remram44** [comment]
@DSDeniso see #6942

**Comment by DSDeniso** [comment]
@Scrxtchy Sorry. I was unclear. What I meant was "how come this issue has been closed".

**Comment by DSDeniso** [comment]
@remram44 Are you sure that was the reason that this issue was closed?

**Comment by crashb** [comment]
As a relatively new user, I'd like to weigh in: **this functionality seems absolutely crucial!**  I think it's reasonable to say that each person who joins Mastodon will have multiple interests.  From what I've seen, each Mastodon instance can only cater to a subset of those interests!  In a perfect world, there might be an instance that's perfectly tailored to an individual's interests, but realistically this seems very unlikely.

As a (fictitious) example, let's say I'm a new user interested in movies.  I sign up for an account at movies.social (or whatever).  I'm also interested in video games, so I'd like to engage with the users on games.social (or whatever) - but now I discover I can't do that without visiting the incredibly cluttered Federated timeline, which shows me posts on **every** conceivable topic!  Of course, I could make another account on games.social, but I'd lose my profile and followers, and _requiring_ users to create multiple accounts for their varied interests strikes me as a counter-intuitive design decision.

Being able to browse other instances' local timelines seems like the simplest and most intuitive solution to this problem.  I'd urge the developers to take another look at this issue!

**Comment by naught101** [comment]
It would be good if the default behaviour of the preview on the About page was set to show only local toots. As it stands, if I visit any random instance, nearly all of them show the federated timeline, which is very similar on many instances, so I get basically the same thing on each, and don't get any feel for the local culture.

Another option might be to show two separate previews on the about page.

Is this the place to discuss this, or does it make more sense to open a separate issue?

**Comment by arilando** [comment]
Why exactly is this labeled closed?

**Comment by eloquence** [comment]
@wxcafe closed it and provided a rationale, but I agree with the earlier comments that a more convenient view of remote instances' timelines from your home instance would be a great feature to encourage exploration and to help users discover communities, users and posts. As it is, you have to use hacks like http://www.unmung.com/mastoview for this purpose. So I would argue for re-opening, as well. @Gargron any thoughts?

**Comment by Noxmiles** [comment]
So, can I View other instances Local Timeline now or why is it closed?

**Comment by Scrxtchy** [comment]
Use your eyes and find out! 📄 👀

**Comment by tmladek** [comment]
I'd like to add my voice to the people saying this is definitely a feature worth implementing; it doesn't make sense for me to create a separate account on each of the instances that I'm interested in just so I am able to see what they publish. That's not how federation is supposed to work.

**Comment by dmend** [comment]
I also want to add to the dogpile.  I think implementing this feature would enhance the usability of Mastodon as a whole.  The alternative of creating a new account on every instance you're interested in is a terrible user experience.

**Comment by bobcanthelpyou** [comment]
I love that feature, it is already implemented in the Mastalab Android client, it is possible to 'follow' other instances to browse the other public timelines and interact with all those amazing toots. Could suggest the client on Android https://gitlab.com/tom79/mastalab/

But i miss that feature within the desktop browser, too. It is really annoying to open the public timeline of another instance and can't interact with the toots. So sad :(

**Comment by ealgase** [comment]
Going to also add support and say that this is still important and (probably) easy to implement.

**Comment by mattcoxonline** [comment]
I notice that https://mastodon.social/public exists showing the Federated timeline.

You could use the same layout / format and create https://mastodon.social/local which then shows posts from that instance.

**Comment by MichaelTunnell** [comment]
@mattcoxonline this would be an improvement and some instances have a local timeline listed on their About pages . . . it is still rather worthless from the user perspective because I want to use it in my dashboard rather than having to go to each instance separately, that's a rather ancient method of consumption at this point.
