### ISSUE TITLE
Polls Not Hidden In Content Warning

### ISSUE THREAD

**Issue by Fidgetcetera** [tootsuite/mastodon#10569]
### Expected behaviour
When writing a poll in a content warned post, I expect the poll to be inside the content warning, like how media is hidden by it.

### Actual behaviour
Polls are not hidden behind the content warning at all, and display regardless of "show more" status.

### Steps to reproduce the problem
1. Make a poll in a post with a content warning.
2. Open web interface.
3. Observe.

### Specifications
Mastodon 2.8.0, firefox 66.0.2 64-bit on Ubuntu 18.10.

**Comment by Fidgetcetera** [comment]
https://sins.center/@Fidgetcetera/101918850985003278 made an example post which shows a way that polls can contain content that should really be behind a cw, just in case it's necessary.

**Comment by Cassolotl** [comment]
It looks like https://github.com/tootsuite/mastodon/pull/10563 fixes this issue, but I don't know if it will get merged, I just thought I should mention it.

**Comment by Fidgetcetera** [comment]
It would fix it!

**Comment by Fidgetcetera** [comment]
(and the other parts are good too tbh)

**Comment by Cassolotl** [comment]
If #10563 isn't getting merged, maybe there could be a PR just for putting polls under CWs?

People seeing triggering content that should be behind CWs has been made a higher priority in the past, so could a priority label be added to hopefully attract attention sooner?

**Comment by Cassolotl** [comment]
So there's [a fix coming](https://github.com/tootsuite/mastodon/pull/10685), and I'm not 100% sure what it's like because Gargron ignored my request for a screenshot, but it *looks like* the poll will remain visible but the text of the poll options will be replaced by letters? (What is an alphabetic letter? Is it different from a normal letter?)

I'm concerned that this will add confusion and remain messy, rather than making things tidier and clearer. It's also not clear whether people will be able to vote before opening the CW (i.e. before being able to read the question and the answer options).

I just posted [a poll with a CW](https://queer.party/@cassolotl/102144073194618249), and got replies complaining about the weirdness. Obviously the new feature of switching poll options for numbers when the CW is closed isn't out yet, but it really seems like people think visible poll options outside closed CWs is weird. I don't feel good about the fix. Switching potentially triggering text out for A, B, C, D is probably good for preventing MH doom, but if I've interpreted the PR correctly I think #10563 would be a lot better.

**Comment by Gargron** [comment]
Yeah I don't like my A/B/C/D fix after all, although primarily because it can't be hooked up to the "show more" button on public pages. But then, none of the solutions probably could be, that button is outside React/Redux. I am not convinced about the "hide everything" approach either, I think there is value in polls and pictures standing out from other posts when scrolling/skimming. Dunno what to do.

**Comment by Cassolotl** [comment]
You know how people's `@usernames` are shown under the "show more" button when it's closed? Maybe that but a symbol for video, a symbol for poll, a symbol for images. Something eye-catching but not an entire poll or a black box? I can't think of a way to make it look nice but maybe someone else can.

Or, the blurry image previews are much better than a black box! Something like that but for polls too, somehow?

I definitely get the dilemma, stuff gets much less attention when it's hidden under a CW. :/

**Comment by nightpool** [comment]
the blur idea is kind of cute:

![image](https://user-images.githubusercontent.com/233815/58376190-b7305080-7f32-11e9-8b43-08d3da8dc59f.png)

we might want some sort of fallback for browsers that don't support `filter` though, and i'm not 100% convinced this is the Best Solution, just an interesting one.

**Comment by Cassolotl** [comment]
As long as it doesn't inadvertently show results to people who haven't voted! :) Thanks for the mock-up, it is really cool!
