### ISSUE TITLE
Domain blocks cannot be upgraded

### ISSUE THREAD

**Issue by joyeusenoelle** [tootsuite/mastodon#10608]
### Expected behaviour

As a server admin, when I go to /admin/domain_blocks/new, I should be able to *change* the severity of a domain block (i.e. from Silenced to Suspended or vice versa).

### Actual behaviour

As a server admin, when I go to /admin/domain_blocks/new, attempting to change the severity of a domain block returns an error, with the text under the **Domain** field "has already been taken".

I have to go back to the list of blocked domains (at /admin/instances?limited=1), find the domain in question, *undo* the existing domain block, and then set a new block severity at /admin/domain_blocks/new .

### Steps to reproduce the problem

1. Silence an instance through the interface.
2. Attempt to suspend that instance through the interface.

### Specifications

This occurs in v2.8.0.

**Comment by ThibG** [comment]
Unfortunately, there are conceptual issues with downgrading (or undoing) an instance block: an instance block works by individually suspending every user of that instance, as well as making sure that any newly-discovered user of that instance gets blocked too. Undoing the block will stop marking newly-discovered as suspended, and optionally, will unsuspend all users of that instance (no matter *why* they were suspended in the first place). Downgrading a suspend to a silence would cause the same problem of either requiring unsuspending everyone no matter why they were suspended, or only affect newly-discovered accounts. While that issue is not the one described here, I think that's a blocker.

I am also not sure how to design the interface to avoid accidentally downgrading an active domain block. But I guess we could at least link to the active domain block in the error message to avoid one of the hoops?

**Comment by joyeusenoelle** [comment]
The interface already asks if you want to unsuspend/unsilence all of the affected accounts. See the attached image. It wouldn't be a stretch to add "change suspension to silence for all affected accounts", and it would be one line of SQL to perform that change.

![Screenshot from 2019-05-01 12-25-13](https://user-images.githubusercontent.com/4139417/57028387-f8239680-6c0c-11e9-90ab-a83c178a248e.png)

Alternately, it's reasonable to suggest that a new column be added to the `users` table: `manual_admin_action` or something similar, to mark, if a user is suspended or silenced, whether it was done through the admin interface or because of a domain block. That would obviate the problem entirely; just add `where manual_admin_action = 'f'` to the SQL statement.

As for accidentally downgrading an active domain block, yes, I think amending the error message is the way to go.

**Comment by ThibG** [comment]
Regarding the new column, I'm working on a slightly different way to do it: https://github.com/tootsuite/mastodon/pull/10660

I'm concerned also about the different options (reject reports, reject media, etc.). Maybe we could accept changes if they are strictly an upgrade in severity, and display an error with a link if they are a downgrade?

**Comment by ThibG** [comment]
Modified #10663 to transparently allow domain block upgrades, but not downgrades

**Comment by joyeusenoelle** [comment]
That sounds good to me.

**Comment by ThibG** [comment]
I think this has been addressed fully, as domain blocks can now be edited, which allows upgrades and downgrades.
(Creating a new domain block for an already-blocked domain will still error out in case of a downgrade, though, in order to prevent accidental downgrades)
