### ISSUE TITLE
Used text sizes can be too small.

### ISSUE THREAD

**Issue by Golutazem** [tootsuite/mastodon#10749]
In order for text to be easily legible by the user, the text must be at least as large as he has configured. For this reason, absolute sizes should be avoided and any text sizes specified should be greater than 1em or 1rem. This is an accessibility issue, but not only for a few people.

**Comment by ZoeBijl** [comment]
@Golutazem do you have any articles about this? As far as I know all modern browsers will scale text no matter the unit they’re defined in.

**Comment by nightpool** [comment]
@ZoeBijl Understanding WCAG 2.0 has a throw-away line that says "Avoiding scaling font sizes smaller than the user-agent default (future link)" (under the Additional Techniques for 1.4.4). Considering that I couldn't find any similar language in the Advisory Techniques for 2.1, my guess is that this is old advice that has since been discarded. However, as I wasn't able to find the specific context/changeset in which the language was added, i'm not able to say for certain.

**Comment by ZoeBijl** [comment]
Required minimums aside (because you’re right in saying that line has been removed): I was wondering if there is a need for setting sizes in `em`. Because I don’t think there is. Not an accessibility related one as far as I know. But I’m always happy to learn. So that’s why I asked @Golutazem.

**Comment by Golutazem** [comment]
Using a relative unit, such as em or rem for scaling is necessary because the user sets their size in px or pt. There is no other way (AFAIK) to set the size relative to the user's setting.

**Comment by nightpool** [comment]
@Golutazem that hasn't been true since like 2005
