### ISSUE TITLE
"Drop instead of hide" does not drop boosts

### ISSUE THREAD

**Issue by trwnh** [tootsuite/mastodon#11090]
https://elekk.xyz/@noelle/102277364003949228

**Comment by ThibG** [comment]
Looking at the backend code, it should work.
However, filters don't have a retroactive effect on the backend, so in the case described in the link, the toot was already in the TL when the filter was added, and thus filtered client-side.
Now, “drop instead of hide” should probably hide the status even if it's filtered client-side…
