### ISSUE TITLE
add google cloud storage support in addition to S3

### ISSUE THREAD

**Issue by nergdron** [tootsuite/mastodon#1110]
I see S3 support for shared media storage across multiple linked Mastodon instances. This is great! but it'd be nice to also have Google Cloud Storage support for running on their cloud / Kubernetes.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
Doesn't Google Cloud Storage have a S3-compatible API? In that case you simply need to specify `S3_ENDPOINT`

**Comment by nergdron** [comment]
Ah, you're right! I didn't realize that! Should work fine, thank you!

**Comment by jviide** [comment]
Sorry to resurrect an already closed issue, but it appears that Google Cloud Storage is having hard time with the "Expires" header set in `config/initializers/paperclip.rb`. Otherwise Google's S3 compatibility layer seems fine - changing the line

```ruby
Paperclip::Attachment.default_options[:s3_headers]     = { 'Cache-Control' => 'max-age=315576000', 'Expires' => 10.years.from_now.httpdate }
```

to

```ruby
Paperclip::Attachment.default_options[:s3_headers]     = { 'Cache-Control' => 'max-age=315576000' }
```

was enough to convince Google Cloud Storage to cooperate.

I created pull request for this #1886 in case it's ok to drop the header.
