### ISSUE TITLE
Cannot scroll with the keyboard upon pageload

### ISSUE THREAD

**Issue by technomancy** [tootsuite/mastodon#11274]
### Expected behaviour

When first loading the page, pressing pagedown or the down arrow key should scroll the page down as it does on other sites.

### Actual behaviour

Nothing seems to happen when you press the down arrow or the pagedown key.

### Specifications

I'm seeing this on the 2.9.2 release of Mastodon with the new "simple" frontend, which is very nice apart from this problem. It seems to occur in both Chromium and Firefox on my Debian system.

### Relevant info

This seems similar to #3395 except that was about the mobile view instead of the new "simple" UI.

**Comment by cbayerlein** [comment]
I also experience this behavior. At page load, the focus is in the input box for a new toot. I have no idea how to focus the content in simple mode, so that pgup/pgdwn work - at least not without a mouse.  This is an accessibility issue and especially important for people who dependant on keyboard input.

**Comment by johannesgunnar** [comment]
Possibly related to https://github.com/tootsuite/mastodon/issues/10991

Also possibly related to my problem with scrolling (on 2.9.3), but I seem to be unable to scroll with my mouse unless I move my mouse over the center column. Scrolling anywhere else results in nothing happening. Compare this to other similar sites and you will see that the expected behaviour is for the middle column to scroll all the time no matter where you place your cursor.

Note that page up/page down can be made to work if you manage to click somewhere on the middle column, but it's not trivial as most things there are clickable links.

**Comment by ykzts** [comment]
Resolve with #11208

**Comment by technomancy** [comment]
Not sure why this was labeled wontfix, but I can confirm it has in fact been fixed on 3.0.1; thanks.
