### ISSUE TITLE
Disable unauthenticated API access while turning off timeline preview

### ISSUE THREAD

**Issue by yingziwu** [tootsuite/mastodon#11289]
### Pitch

After turning off timeline preview on site settings, the ``/api/v1/timelines/public`` should disable unauthenticated access meanwhile.

### Motivation

Today I found [a website](http://www.unmung.com/mastoview?random=1) that can view the timeline of each instance, even if this instance close timeline preview.
To protect the privacy of users,  after turning off timeline preview on site settings, the ``/api/v1/timelines/public`` should disable unauthenticated access meanwhile.

**Comment by fediuser1232** [comment]
Disagree.  One of the best factors about the Fediverse is its openness (no need to login to view someone's followers, their replies, etc), and making the public timeline available is part of that.  If you don't want your posts to show on the public timeline, make them unlisted, otherwise, accept that public posts **are public** and will be shown **publicly**.

**Comment by lfuelling** [comment]
So `/api/v1/timelines/public` should not be public? 
In that case it should also not be called `public`.

**Comment by phryk** [comment]
@fediuser1232: I think that's bollocks. If the administrator of an instance already decided to hide the public timeline, then obviously that was a conscious decision which the corresponding API endpoint should honor as well. This is especially important for instances specialized for members that have a need for heightened privacy (think LGBT, people of color, radical leftists. etc.).

**Comment by lfuelling** [comment]
@phryk but those users can simply post unlisted and their stuff is hidden from the public timeline. 

IMO: If you left your window open it's not the house manufacturer's obligation to make sure nobody takes the stuff inside. you close them, because you know that. Same applies to post privacy.

**Comment by brortao** [comment]
@lfuelling the instance admin can choose whether to show the public (federated) timeline, the public (local) timeline, or nothing at all.

as far as i can tell the codebase as-is, the upcoming authorized fetch mode will disable unauthenticated API access (i may be wrong)!

**Comment by umonaca** [comment]
We ran a instance where the majority of users are more concerned about the privacy of the contents. We made a lot of changes to the code, including [this commit](https://github.com/umonaca/mastodon/commit/0bfb0943869218a779c82d718a4b2a0820f3c811) which just blocks any unauthorized access to `/api/v1/timelines/public`. Logged in users are never affected, while tools like Fedilab and [unmung](http://www.unmung.com/mastoview)  are blocked so that anyone outside of our instance cannot directly access our local public timeline.
Our code may look a bit confusing - you may want to use something like [this](https://stackoverflow.com/questions/4877931/how-to-return-an-empty-activerecord-relation) instead to return an null relation.

**Comment by shioko** [comment]
@fediuser1232 So may be users could have a choice to show their toots only on local timeline? I think compulsory openness is not so different as privacy violation.
btw I'd like to set toot privacy in this way ↓

![](https://s3.us-west-1.wasabisys.com/bgme-mstdn-media/media_attachments/files/000/621/562/original/3da7f2cf6befa47f.png)

*If I only checked 'local timeline', my followers in other instance cannot see my toot, some time we just want to talk on local timeline and these toots will be confused to others.

**Comment by brortao** [comment]
@shioko that's a separate issue; please search before posting a new feature request in an existing thread. https://github.com/tootsuite/mastodon/issues/861

**Comment by buyiyihu** [comment]
I have a similar issue that I think better posted here to avoid duplication.
At the landing page, a unathorized visitor can see the admini account at the right bottom, click it you wiill go to the home page of the admin with a url: "domain.com/@admin" . Two problems here: 

1. The admin can hide follwing and follwers, but TOOTS are still visible, I have gone through the docs and settings, findiing no way to hide them.
2. If modifying the url, say changing the `@admin` to any other `@username`, it will go straight to the user's home page, with all toots visible.

Could this be a privacy issue? I hope the admin can have the right to control the visibility of toots to unauthorized visitors

Thanks, great job !

**Comment by lfuelling** [comment]
@buyiyihu public posts are public. 

If you only post "followers only" with the admin user, no osts will be visible on the profile.
