### ISSUE TITLE
/api/v2/search will always return ones own account, no matter the offset

### ISSUE THREAD

**Issue by connyduck** [tootsuite/mastodon#11365]
TL;DR searching for your own account breaks pagination

### Expected behaviour

When I search for my own username with Search v2 api and a really high offset, I get no results.

```https://mastodon.social/api/v2/search?type=accounts&q=connyduck&resolve=true&limit=20&offset=300&following=false```

```
{
    "accounts": [],
    "statuses": [],
    "hashtags": []
}
```

### Actual behaviour

```https://mastodon.social/api/v2/search?type=accounts&q=connyduck&resolve=true&limit=20&offset=300&following=false```

```
{
    "accounts": [
        {
            // my own account
        }
    ],
    "statuses": [],
    "hashtags": []
}
```

My own account is always returned, no matter what offset I send in.

### Steps to reproduce the problem

Send a search request for your own username and any offset. 

### Specifications

Could reproduce on multiple mastodon instances, all running v2.9.2.
Problem does not occur when the search query does not return my own account.

**Comment by ThibG** [comment]
Hm, this is because the search endpoint will return the account matching exactly the query if there is one.
That is, if you have a user whose name is exactly “connyduck” on your local instance, it will always return just that, it's a different query than the one affected by offsets.

This behavior is probably not expected from users, thought, we should probably restrict the exact match logic to full handles, not just bare usernames.

**Comment by connyduck** [comment]
Okay, yes, the bug occurs with every exact match, not only my own username.

But how am I supposed to use this API? I cannot reliably detect that there are no more results if it will always return results.

**Comment by ThibG** [comment]
I guess as a workaround, you should ignore the exact match :/
