### ISSUE TITLE
Federation description/notes

### ISSUE THREAD

**Issue by BenLubar** [tootsuite/mastodon#11470]
### Pitch

This comes in two forms:

- Add an "instance description" field that can be set for remote domains that can be shown publicly in #11298

- Allow moderators to leave notes on domains just like how they can leave notes on users currently:

    ![A text box labelled "Describe what actions have been taken, or any other related updates..." with a button below it labelled "Leave Note"](https://user-images.githubusercontent.com/4257305/62395405-ba008080-b535-11e9-9927-f5d4eb6cf622.png)

### Motivation

I currently have about 3 pages of domain blocks, and being able to describe *why* I blocked a domain will be very useful in the future for me and for anyone who wants to use my block list to help decide on federation issues.

**Comment by ichi-i** [comment]
It sounds good on paper, but what if this tool would be abused to incite blocks on certain instances?

Very often I see instances getting blocked just because of one user that belongs to it (wouldn't it be better to suspend said user and contact their instance admins in such case? - but I digress).

Such notes would encourage snowballing of instance blocking, which will inevitably result in some small instances getting effectively unfairly cut off from the federation.

This obviously would happen in the minority of cases as I am sure that if this tool is created most of the notes and blocks would be warranted. But it is also necessary to think about the implications of creating a block button that is easy to press.

**Comment by brortao** [comment]
i think this may be resolved by https://github.com/tootsuite/mastodon/pull/11515?
