### ISSUE TITLE
Dream feature: "like" and "save" separately

### ISSUE THREAD

**Issue by Cassolotl** [tootsuite/mastodon#1178]
At the moment there's the star button, which saves a post for you to read later. But at the moment sometimes people are using it to kinda say "I like this post and I appreciate you for writing it but I don't actually want to say anything to you."

I do it! It's clumsy but I feel so awkward just replying with a smile emoticon. And it bugs me that in order to send someone good vibes I have to also save the post. I'd like to keep my saved posts only for posts I know I will look at later, while *also* sending good vibes to the writer.

So what I'd love is a heart button next to the star, that *doesn't* save the post for you to look at later, but it *does* transmit some affection-waves across the internet to the person who wrote the thing, to appreciate them writing it or to send good feelings.

I think there are other sites that do something like this; the main one I know of is Ravelry.com:

![screen shot 2017-04-07 at 19 13 43](https://cloud.githubusercontent.com/assets/6607512/24813562/59fa0f54-1bc6-11e7-9932-618f9fec16a3.png)

Edit: After more discussion, I'm also feeling like I'd like it if saves were private. So, private saves and public likes.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Pajn** [comment]
One variant of this is to support reactions, either in a Github and Facebook way of a set of Emojis or (which I much prefer) the Slack way of reacting with any Emoji.

**Comment by James-Firth** [comment]
Another example would be reddit where one can upvote a post to show approval and save separately.

I think either that system or the Slack "react" would be great! (I also have no problems with the current star system).

Though the Slack reaction system has a lot of pros/cons. I could see the UI being cluttered for a popular post or requiring you to move to a new interface like Facebook does.

**Comment by Cassolotl** [comment]
Oh yeah! Reaction emojis. If we had more space I would be in favour of that. But I think with such a small area in the UI just a heart would be fine for me. And upvote/downvote kinda makes me sad that people would be able to downvote stuff - I like the idea of keeping things positive!

**Comment by James-Firth** [comment]
Yeah a small heart for a like/fav and a floppy or something for saving posts for later. 

Oh sorry I didn't mean to imply I'd want a down vote feature! I just meant that reddit has both a save and an update button for posts

**Comment by Cassolotl** [comment]
@James-Firth 

>Oh sorry I didn't mean to imply I'd want a down vote feature! I just meant that reddit has both a save and an update button for posts

Ohhh yeah that makes sense! I do like that about Reddit. :) Thanks for clarifying!

**Comment by James-Firth** [comment]
No problem!

Hope this issue gains traction, I've definitely found myself using the star as a "+1/like/agree" type action myself.

**Comment by davidak** [comment]
>upvote/downvote kinda makes me sad that people would be able to downvote stuff 

@Cassolotl it's strange for me that you don't value negative feedback. when it's constructive it's an opportunity to improve yourself (if you like) or just know that others have a different view.

i personally value every feedback, maybe the negative, but constructive even more. i can't improve when everyone says "everything you do is perfect".

for reddit it makes totally sense to see what idea/topic is important but it might be different for a social site.

(sorry for beeing off-topic)

I also use the star or heart (on the birdsite) to "+1/like/agree" but also to bookmark. But i think when i bookmark a post, it is also important to me. When i have read it and it actually isn't that great i still can remove it from my favorites.

I think it is important to keep the UI simple. So maybe keep it like it is.

**Comment by Cassolotl** [comment]
Just [spotted](https://mastodon.xyz/users/HerraBRE/updates/97718):

> One of the problems shared by many social media platforms, is the "pile on" effect. Someone says something dumb and the entire Internet shows up on their doorstep to mock them.
> 
> Twitter has this problem in spades, it's one of the reasons it has a bad reputation for harassment.
> 
> As far as I know, there is nothing technically preventing the same problem here in the #fediverse though.
> 
> If it became a social norm to just star people who have already responded instead of piling on, that would help.

I'm posting it because it's evidence that people are using the star/save function to show approval of something or otherwise socially signal. There is clearly a need for "liking" something overtly that doesn't involve saving the post the way the star button currently does. If I did what this person is suggesting, my saved posts would be a mess of agreement and disagreement posts with no context, not helpful at all - and yet the alternative is "piling" onto people I agree or disagree with.

**Comment by nightpool** [comment]
[I had a long convo with @Cassolotl about this on masto](https://cybre.space/@nightpool/565482)

Summarizing here some of the main points I made:

 - expecting a social networking site to be a bookmarking site is probably a bad idea in the long run—things change, disappear, and are otherwise ephemeral. If you want to save something for later, it almost needs to be outside of mastodon

 - Likes/favs/florps have a definite social purpose because *everything* on this site has a definite social purpose. it's a social media site, and our brains are wired for interpreting everything we see as a social signal from another person (even when this wiring doesn't actually work that well)

   Therefore, **any** action taken by a user on this site will end up serving a secondary social purpose—approval, signaling, or otherwise. 

 - Likes ALSO have a purpose of saving something for later, but it's still a social action and will be interpreted through prevailing social norms.

 - If you want *private* saves, you should use something like Keep. Adding a "saves" feature to mastodon has a very large chance of increasing user confusion (what's the difference? which one is which? how do I intuit this? how does it make these affordances available to me?) for a feature that is only tangentially related to the core purpose of the platform—a social media website—seems like a big ask.

 - Furthermore, any "saves" feature built into mastodon would always be worse then a purpose-built software. How much organization should we add? should users be able to tag saves? sort them? add notes to them? What happens when a post gets deleted?

Now, I'm not saying that this would be a **bad** feature to add. I'm just saying that there are many other services that fill this niche better, and it's pretty non-central to mastodon's core purpose. I would much rather people look into [more permanent ways of archiving content they want to keep](https://archive.org/web/)

**Comment by Cassolotl** [comment]
Totally. I just want a way to "like" something *without* saving it, and I like to use my saves for something else. I kinda get a lot better why it is the way it is, and I also just still like my/Reddit/Ravelry's way better!

**Comment by cphuntington97** [comment]
I would like a "Bookmark" (or "Save") icon visible on each post (see Instagram). When the icon is clicked, the post would be saved in my private list of bookmarked posts. The posting user would not be notified that I have bookmarked their post.

My use case is that sometimes someone will post a video, but I can't watch it because I'm at work. Or maybe they have referenced some literature which I would like to investigate but I'm currently busy with another task. I currently use extra-mastodon tools (like browser bookmarks and google keep) to meet this need, but I think that building this functionality into mastodon makes mastodon a better and more useful website.

Also, I didn't realize my "Favourites" were saved until I read this thread. I use "Favourite" as a social signal to say, "I read your post." My list of Favourites is so cluttered with posts that it is completely useless as a bookmarking tool.

**Comment by Moke-RS** [comment]
>  I just want a way to "like" something without saving it, and I like to use my saves for something else. 

Exactly this.

**Comment by SoniEx2** [comment]
1. What's this about saving posts? I just use browser bookmarks... (you can even sort the saves into folders, subfolders and deeply-nested folders!)
2. "Negative feedback" is only useful if the person actually describes the problem, otherwise it's only good as destructive feedback - aka not good at all. (see: "likes is no" vs "I wish liking and saving were separate features")
    Sure, if we're talking, like, hateful messages, then destructive feedback is a reasonable response, but in any other case it's not much different from a hateful message, honestly.

**Comment by Cassolotl** [comment]
>What's this about saving posts? I just use browser bookmarks... (you can even sort the saves into folders, subfolders and deeply-nested folders! also if you implement a save feature you better implement deep nesting! because, well for one I'm autistic and I like categorizing things :P but also I love deep nesting.)

Saving things as bookmarks with folders sounds cool. And being able to back things up is indeed useful for many people. I guess what I'm feeling is, if the function does indeed save stuff and it is indeed possible to use it just for saving things, I would like that to be meaningful.

At the moment some people use it to save things, some people use it to express a liking or approval without particularly wanting to save, and some people use it for both. It's not like this conflation causes conflict, but it might cause miscommunication (since it's *sometimes* nonverbal communication in a text-based medium, which can be confusing) and it means that if I want to express approval for something I also have to save it and clutter up my saves.

If there is a save function on the site itself I shouldn't *have to* have a separate save function in my browser, I feel! And when I save things for later perusal/consumption on the site itself (ie: not as a bookmark), for convenience (ie: stored on the site upon which the saved things are hosted), I don't really want that to be a public thing.

**Comment by SoniEx2** [comment]
*incoming long rant about multiple saving and categorization systems*

Reddit has a save feature, which happens to be completely useless to me (I'm sure there are ppl who are ok with it, but I'm not one of them). This is your usual saving feature.

Reddit Gold adds simple categories but it's still mostly useless to me and you can only save things once. This is a slight improvement over the above.

Github Issues have labels. You can apply multiple labels (good), but you can't have nested labels. Instead of having a "type" label with "enhancement" and "bug" sub-labels, you need to have "type-bug" and "type-enhancement" and so on. And if you add in priorities? "priority-1" "priority-2" "priority-3" are all separate labels, instead of being 3 sublabels within a "priority" label. This would still be a huge improvement over what Reddit and Reddit Gold provides. In fact, even TweetDeck (maybe Twitter?) supports something like this - you can create "collections" of tweets and add a tweet to multiple collections!

Github itself doesn't have categorization. Your only options are users and organizations, and so you have 1000 repos within one user and no way to group related repos together.

Bitbucket is slightly better - altho users don't have categorization options, teams (equivalent to github organizations) do. Repos can be categorized under projects, similar to aforementioned Reddit Gold saving.

And then, we have browser bookmarks. The ultimate categorization system.  
Not only can you nest folders indefinitely (sometimes restricted by your OS or filesystem, but not always), you can have a bookmark in multiple folders, and, on some systems, you can even have the same folder in multiple folders! Browser bookmarks make most websites' saving features completely useless! :D 

*end rant*

**Comment by Cassolotl** [comment]
#4106 seems like a feature request for reaction emojis, which could be relevant!

**Comment by Chronister** [comment]
This just came up again (well, I felt the need for it again and posted about it), so I thought I'd try to bring in some new arguments in support of it. I'll be calling the feature "Saves" in this post, though other terms could and should be considered for maximal clarity.

First: why do posts need to be saved? The reasons will vary slightly between people but the basic idea is that a particular post has information, art, links, etc that are relevant enough to you that you think you might want to come back to it later. In my case, it was someone's art I'd seen earlier today that I wanted to see again to analyze technique and style. It could also be information about an event, a piece of news, a link to a particular blog post on another site, a song title and artist + album, an announcement about e.g. a zine release, or so on.

Second, why not browser / client / addon side? There are a lot of things that are perfectly fine to delegate to clients. Interface-specific settings, for example. However there are also a lot of things that we prefer to be integrated with the software for a variety of reasons. Take lists, for example -- clients could easily implement lists with no serverside support, but we rather them be at least collated and persisted across clients by the server so that we can view them consistently across any client. Saves, I think, are similar. I could bookmark the post in my browser, but that requires bringing up the detail view for a post, unlike a "like", and doesn't persist across devices (unless I'm using a browser on all platforms that has bookmark-syncing, but that of course excludes the possibility of using a native mobile client). I could copy and paste a link to an external tool like Keep, but that has the same issues with the added snarl of making sure I have the right link, and not to mention getting links from mobile apps is either cumbersome or impossible. It's been well established that leaving the platform can detract highly from the practicality of some actions, and I argue this is one of them.

Third, feature scope. I think we agree that making actions public and visible gives them social meaning, and since "favourite" has already become overloaded it's probably best if "Save" doesn't fall into something between Boost and Favourite in terms of relative intensity. So I say keep them private, like Lists. A saved post just tells your own mastodon server to store it in a list, like Florps, but not deliver any Activity to anyone. 

So let's talk UI, since it seems to be a sticking point (specifically the web UI). I agree that adding more visible actions on each post would likely result in confusion, and minimalism is desirable whenever possible. It's also probably infeasible to make save organization serve everyone's needs, since people find different mechanisms affordant / memorable / manageable / etc. However, we can at least try to capture a lowest common denominator to at the minimum have a feature which is usable and useful for the majority of people. So here's what I'm thinking.

![image](https://user-images.githubusercontent.com/1606822/34203222-2b65fbe8-e52f-11e7-99f0-a76e87daf63c.png)

The top version, as you might have imagined, seems a bit cluttered and adds a piece of UI that is likely only going to be used for a small minority (<=1%) of posts. So that's a no-go. The bottom, though, seems like a good compromise, as we've already delegated less common actions to the extended menu. Also, it's still discoverable, because there are other actions people might want to do to a post (embed it, mute the user in question, etc) that will require them to know about or discover this menu, and "Save" or "Save this post" or "Save for later" is pretty understandable and intuitive.

As for how to view your saved posts, I see a couple good options. 

1) Add a new list/column accessible from the Getting Started menu. This is maximally discoverable since it'll probably be visible right from login, but has the disadvantage of adding _yet another_ thing to this menu, which is already getting to big to see all at once on a lot of devices (open a responsive design view with "nexus 4" in FF for example). But maybe someone has or will have ideas about how to reorganize this UI to make it more useful and this will become more viable.

2) Add it as an extra setting for the "Likes" column. This has the disadvantage of overloading a previous feature with new functionality, but the two things are at least semantically related in that most people are already aware they can go through their list of liked posts as a primitive version of saving them.

Finally, organization. I think just having a serialized list is probably not quite good enough, even though saves are likely to be much less frequent than likes, because part of the idea is to be able to come back to posts much later than is currently possible. So what I'm thinking is to just have a very, very limited scope full text search for only the Saved posts view. The analogy I'm thinking of here is with old emails that you want to find again. Maybe you have a nice hierarchical organization, but when it comes down to it you probably just end up heading to the "Search" bar in your email client with some keywords you remember from the email. This avoids namesearching issues already discussed with full text search, since you have to have already seen the post to be able to search it. It also limits the scope of the search and of potentially indexed records to posts which have been saved by a local user. Between these two limitations, I think it's within scope of implementation and maintains user privacy to a satisfactory degree.

Hopefully this clarifies and downscopes the feature request to a level where it can be seriously considered, because this isn't the first time I've wanted it, and I don't think it'll be the last :P

**Comment by skddc** [comment]
There's a good example for this feature: Instagram has both likes and saves, and for the latter you can even organize saves in collections. They use a bookmark icon under the post (vs the heart for likes).

I use it all the time on Instagram, and I believe it's also one of the most-requested features on birdsite (for all the reasons stated above). Would love to have something like this in Mastodon.

**Comment by Cassolotl** [comment]
I agree with basically all of @Chronister's post. :) I think I would privately "save" a lot less often than I would want to publicly "like" or thank someone for posting, so it makes sense to me that the "save" would be in a menu and the "like" would be at the bottom of each post.

It just doesn't make sense to me that "save for later" would be a public thing - why should other people be able to see what I've saved for later? That seems like a private thing. And if I want to socially signal "hey this is good, thanks for posting it" and that is public, why should it clutter up all the posts I've saved for later?

I don't think I would ever need to see a stored list of "posts I've publicly liked"; if I wanted to see it later I could save it as well, right? But I know people like to have access to things they've done so if being able to see a list of "liked" posts is a thing then that's obviously totally fine. A "saved posts" column could have a toggle: "See liked posts: Y/N." And I could just have it set to N all the time.

I definitely agree that members sorting out their own way to save things is... well, members will definitely not save things so much, because there will be problems, it'll be clunky.

**Comment by skddc** [comment]
> It just doesn't make sense to me that "save for later" would be a public thing - why should other people be able to see what I've saved for later? That seems like a private thing. And if I want to socially signal "hey this is good, thanks for posting it" and that is public, why should it clutter up all the posts I've saved for later?

Other people may use the feature to present collections of specific posts publicly. This could easily just be a privacy setting, which determines if the saved posts are publicly accessible or not.

**Comment by Cassolotl** [comment]
>Other people may use the feature to present collections of specific posts publicly.

I don't think I've ever seen anyone do that. But maybe they would if saved posts weren't cluttered with "thanks!" and "damn I could do with a beer" and "had a great day today!" and whatever else people would probably "like" but not "save"?

I think this is probably more an argument for developing something like Twitter Moments - a curated collection of posts on a particular topic that someone might want to share all together.

**Comment by Chronister** [comment]
These are good ideas, but out of scope for the save feature probably. Let's see if we can focus on a minimal shippable version that addresses the core need and then examine how it interacts with other use cases later on.

**Comment by skddc** [comment]
@Cassolotl I already gave you the example: Instagram saves. Also, ever heard of Pinterest? Just because you don't see yourself using a feature a certain way doesn't mean other people don't. I think it's useful to not speculate about these things and only discuss the functionality itself.

> These are good ideas, but out of scope for the save feature probably. Let's see if we can focus on a minimal shippable version that addresses the core need and then examine how it interacts with other use cases later on.

I think there aren't any new ideas after your post, only the discussion of if the saved posts should be public or not. I might be wrong, but I believe a privacy setting for that wouldn't be overly complex as to be out of scope per se. No?

**Comment by Chronister** [comment]
My concern is that "collection of posts i want to come back to later" and "collection(s) of posts i want to group/curate for public display" are actually two different features, and it may be misleading to say that the only thing needed to bridge them is a privacy toggle. 

The implication of this, to clarify, is that a) the latter case expands the scope to potentially needing multiple collections to address the core functionality desired and b) reintroduces concerns about use skew due to having a public/social function. 

In the interest of avoiding bikeshedding I'll leave my thoughts at that, at least until it looks like some progress is being made towards an actual implementation (or it's been vetoed entirely, in which case I'll add it to my backlog of things to try to implement anyway on cybrespace)

**Comment by Cassolotl** [comment]
Yeah I agree, I think it's probably good to keep things simple and focused here. If this feature happens and then a bunch of people are like "wow I want to be able to put my saved posts in folders and maybe share them publicly" then things can keep moving in that direction - but the bigger and more complicated the feature, the less likely it is to happen or the longer it will take, the less appealing it will be to lots of people (who are finicky), etc.

**Comment by skddc** [comment]
I would never implement folders in the first version. I still don't see any solid argument against making them public here, other than again speculation about what people may or may not do. But hey, whoever implements it can decide this for themselves anyway.

**Comment by skddc** [comment]
I would never implement folders in the first version. I still don't see any solid argument against making them public here, other than again speculation about what people may or may not do. But hey, whoever implements it can decide this for themselves anyway.

**Comment by sophia-park** [comment]
I disagree to be honest. This is better suited to a service like Storify or Pinboard; duplicate functionality with subtle, implied distinctions bulk up the front-end, and add work on everyone's behalf for all potential clients to now support this functionality in the API. I just don't see the necessity of it server-side.

Granted given the posts listed here there's clearly substantial desire for it; as a product, I worry about Mastodon becoming even bulkier with obscure distinctions from feature requests that would  be better served outside the product.

**Comment by skddc** [comment]
There's nothing subtle about saving for later being different than liking something. At all.

**Comment by spaceottercode** [comment]
I put together a very basic userscript if anyone is interested. Runs on Chrome and Firefox (with Greasemonkey). It's nowhere near as full featured as what's discussed here, but everyone's welcome to fork it to include what they like. Currently alpha.

https://github.com/spaceottercode/bookmarktoot

**Comment by skddc** [comment]
Btw, as Mastodon is now a Web Share target in compatible UAs, why not also use the Web Share API for outgoing shares? That way it's easy to send a toot to any save-for-later or note-taking app one might be already using.

**Comment by Cassolotl** [comment]
Related: Enhancement Idea: Bookmarks for Private Use #610

**Comment by Cassolotl** [comment]
From @SoniEx2 over on #6086:

>(aka #1178. Really tho github is being really weird with that issue)
>
>I have made a thread for a trivial change to browsers' already existing bookmark features, which is both more manageable and more accessible than what has been suggested on that thread.
>
>You can find it over at https://discourse.wicg.io/t/simple-bookmarks-api/2487

**Comment by Cassolotl** [comment]
Just spotted *Add a “bookmark” feature #7107*, which seems relevant to our interests. :)

**Comment by saschanaz** [comment]
Would the liked-toot list be public if we ever get like and save separately? I think current Favourite feature in Mastodon in something like private-save-ish-but-not as 1) we cannot see a certain user's favourited toots 2) but still we can see who favourited a certain toot.

**Comment by jeroenpraat** [comment]
Now that Twitter has a bookmark feature, this issue is becoming more relevant and will probably be more requested.

**My use case:**

Many times when I see a toot in my timeline, I don't know yet if I should favorite or boosts it, or just leave it alone. Maybe I have to read it first, cause it is a long article or video. I don't always have time to deep into a subject.

Of course I can favorite it, but that one is to say 'I like it' or 'I agree' or 'well done' to the toot author, mostly when it are the more personal toots (I'm not going to boost personal toots, even if they are public, like 'I went to a hairdresser today, see my new hairdo'. I like to like/favorite that.)

**Feature request and idea:**

* I hereby request a **bookmark** feature.

* I have an idea how to combine this with the existing *favorite* feature. 

  * Rename the icon 'Favorite and bookmark' by default and rename the users 'Favorites' column 'Your bookmarks'. Nothing is changed. The toot author gets a notification and the toots is saved in the 'Your bookmarks' column (formerly know as the 'Favorites' column). 

  * Make it optional that users can split the 'Favorite and bookmark' function into two functions ('Favorite' and 'Bookmark'). In the user settings we can add: 'Do you want to split favoriting and bookmarking?'. 'No' is the default (and current situation), 'Yes' will add a bookmark icon right next to the current favorite icon. 

  * Clicking the 'favorite' icon will notify the original toot author (the current situation), but *not* saved in the 'Your bookmarks' column

  * Clicking the 'bookmark' icon will save it in the 'Your bookmarks' column.  

* I also request a API, so that apps like Mastalab and Tusky can sync the bookmarks.

**Comment by Gargron** [comment]
Fixed in #7107
