### ISSUE TITLE
Put a constraint on follower_count and following_count 

### ISSUE THREAD

**Issue by wxcafe** [tootsuite/mastodon#1180]
So in the database, in the table users, there are two columns named 'follower_count' and 'following_count', and they (obviously) increment when you get a new follower or follow a new person. 

There are no constraints on these columns.

Thus, 
<img width="321" alt="screen shot 2017-04-07 at 19 36 51" src="https://cloud.githubusercontent.com/assets/3009327/24813585/d757d8a2-1bce-11e7-9ead-6e4579dfe15c.png">

and since other instances can't see the total number of followers a user has, only the local followers, and I didn't have a tab of my profile open, well...

https://social.wxcafe.net/@wxcafe/83494

Anyway, I think those should have constraints (also if you know how I can find out my real follower number, that'd be nice. I set something that I think was pretty close but I don't know if it's the right number exactly...)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by wxcafe** [comment]
Found a way to get the numbers of followers back : `select count(id) from follows where target_account_id=<id>;`

**Comment by Gargron** [comment]
There is a rake maintenance task to recalculate these: https://github.com/tootsuite/mastodon/blob/master/lib/tasks/mastodon.rake#L68

Normally you don't need to do that, unless you mess with them like this. I don't consider this an issue, because if you have arbitrary SQL access, of course you can control how all the data looks.

For performance, these counter caches are *amazing*. Counting is one of the most expensive SQL tasks.

**Comment by wxcafe** [comment]
That makes sense. I think it'd be good to have constraints still in case some piece of the code goes wild or someone gets SQLi (it wouldn't make it impossible for them, but a little bit harder) but since you can't get the total counts from other instances the benefit to changing one's follower/following count is pretty low anyway, and if the impact is that important then it makes sense to not have them. 

Thank you 👍
