### ISSUE TITLE
Delay in Toots from other instances

### ISSUE THREAD

**Issue by nsmash** [tootsuite/mastodon#1187]
Hi have noticed a pretty long lag for toots to show up from users, I follow, from different instances. It will show up at the top of my Home feed and say its from 1 hr ago. I checked the profile of user and on their timeline the toot shows up as from 1 hr ago as well. 

* * * *

- [X ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by wxcafe** [comment]
What instance are you on? Do you admin your own? It's probably due to the Sidekiq queues being filled up. You can fix this by adding more workers, if you're an admin. Take a look at https://github.com/tootsuite/mastodon/blob/master/docs/Running-Mastodon/Tuning.md (or tell your instance's admin to do so)
