### ISSUE TITLE
Keep "profile redirect" as a sort of "soft migration"

### ISSUE THREAD

**Issue by trwnh** [tootsuite/mastodon#11913]
mastodon.social 3.0.0rc1 -- cannot set up a profile redirect; "move followers" has replaced it at `/settings/migration`

**Comment by Gargron** [comment]
Yes, that was the profile redirect endgame all along.

**Comment by trwnh** [comment]
What option do users have to indicate that an account is inactive, but without forcing an unfollow-refollow?

**Comment by Gargron** [comment]
Are you saying people were using that as a sort of reversible deactivation feature instead of for moving accounts? That's a bit messy... The feature was created to facilitate moving from account A to account B, and now taking followers with you is part of the definition of moving. If this is not a niche need we could add a checkbox control to the form for whether to transfer followers or not, but I worry that this will overcomplicate the process for those not familiar with fediverse inner workings.

If the demand is for a reversible deactivation, perhaps that feature should be invested in separately. The benefit would be not having to come up with a new account just to activate it. It could cover the #7132 use case.

**Comment by trwnh** [comment]
I'm not sure bunker mode is the same thing here. There's actually several things I see here, all loosely related. First, with profiles:

- "I am currently active at this profile instead" -- this is the old profile redirect
- "Hey unfollow this account and follow this other one" -- this is the current migration / Move handler
- "This is an alt of mine" -- currently not handled, but maybe could be covered by alsoKnownAs / alias?

Then, with content:

- "I will be still be posting from this account sometimes"
- "I will be posting from a different account, but leaving this one up"
- "I am completely abandoning this account and will delete it after the move"

As the non-initiating user, my concerns would be:

- What if I want to remain following both accounts, since old posts don't currently migrate?
- What if I only want to remain following the old account, and do not wish to follow the new account?

I'm not sure how/if those could be grouped into discrete use-cases. Dropping the redirect in favor of the follower-migration is technically more limiting, especially in a "temporary redirect" use-case, since undoing a Move is very expensive (as expensive as the Move itself).

And even with all of this in mind, I feel like all of these are only partial measures because I see the real endgame as having content independent from profiles, and profiles independent from servers. In the same way I can copy emails from one inbox to another over IMAP, or forward received messages from one inbox to another, or set up aliases, I expect to be able to do those things on the fediverse *eventually*.  But in the meantime, I don't really want to lose social expressiveness that existed prior. I've said that the Move handler is too limiting as-is currently, because it focuses entirely on followers and ignores everything else. It's not really "moving" a profile either -- you've still got two profiles instead of one. 

Keeping the "profile redirect" for now is just the easiest thing that can be done, IMO, as a "soft migration" -- a checkbox sounds fine, and perhaps it can even generate a notification either way. But simply having the option would be nice.

**Comment by Gargron** [comment]
> In the same way I can copy emails from one inbox to another over IMAP

That's completely different though because e-mails in your inbox are private, immutable, and just for you. You can delete other people's e-mails (in your inbox), nobody else can interact with them. So it's literally just like taking your own files with you. On a social media platform, it's different, because if someone wants to delete their reply to you, they can, and these posts are displayed to more than just yourself, and people boost, fav, and reply to them, and all of those things can be undone. It's a mess! 

XMPP hasn't solved this either. And XMPP only ever needed to transfer contacts, to be honest, chatlogs are in e-mail territory in the way that they're just files that user can take anywhere. I think that "I moved to x" that makes people re-follow you is the closest to a perfect solution you can get on a federated network.

**Comment by trwnh** [comment]
Maybe the IMAP thing wasn't a 100% clear analogy; I mostly meant doing this with your own content, but at the same time there is still a split between messages that are delivered via ActivityPub vs. published by ActivityPub, and the distinction is not made clear largely because we still don't have backfilling or cross-domain auth. And that largely gets expressed in the ambiguities around "followers-only", because that can be ongoing or at-delivery-time.

But that's all just one aspect, and a very minor one at that -- the "what about old followers-only posts" doesn't really have any bearing on the other aspects of a "soft migrate", especially the ones that don't really have to do with followers. The "temporary redirect" is the case I feel is most threatened by this change.

**Comment by marrus-sh** [comment]
I appreciate making my followers manually re-follow me when I change accounts because it helps my follower account stay fairly fresh (only people actively following me bother re-following, so it clears out unused accounts; I move accounts somewhat often, on the order of once every 6mo–1yr).

If this change is made such that it is not possible to move accounts without bringing over all your followers automatically, I would just stop signalling change-of-accounts (because I don't want follower migration); consequently all of my old accounts would cease to be marked as outdated. This is detrimental to the fediverse, since it means these old accounts will show up in search even though I am not using them.

So I second the idea of having a "soft migration", so that I can mark my outdated accounts properly without the unwanted follower transfer.
