### ISSUE TITLE
New items don't load automatically even when slow mode is disabled

### ISSUE THREAD

**Issue by trwnh** [tootsuite/mastodon#11912]
The "x new items" banner appears even when Slow Mode is unchecked in settings.

mastodon.social 3.0.0rc1

**Comment by Gargron** [comment]
That's how it now works when you're scrolled down and new items appear. Whether it's something we want to keep or not is up to feedback but it's not a bug.

**Comment by trwnh** [comment]
Hmm. I'm kind of conflicted on whether it should be this way. On one hand, it could help with not losing scroll position, but on the other hand, it adds friction when you want to see the newest stuff. And I'm not sure it makes sense to add a "fast mode" to restore the old behavior, either.

**Comment by Gargron** [comment]
Poll: https://mastodon.social/@Gargron/102833436547113620

**Comment by Gargron** [comment]
Well, I've been using this UX for two days now, and I do not like it at all. It was a bad idea coming from the right place. It may solve scroll glitches on the public timeline, but it introduces a whole array of new problems. For example, before it, clicking on header to scroll to top brought you to the very top. Now, it brings you to the button, and upon clicking, it loads the posts above you, so you still have to scroll to top. By the time you reach the top, you may have x new items again. On some timelines it becomes impossible to restore the real-time functionality because you can never scroll to top fast enough. Furthermore, on the very same public timelines, if you don't pay attention and 3,000 new items accumulate, clicking the button freezes your browser tab as it tries to render 3,000 items at once.

It's a bit weird that the poll is heavily in favour of this change. Perhaps the reason I stated for including it was too convincing and people didn't answer how they felt, but how they felt they ought to feel about it.

So, since nobody really asked for it in the first place, I think it would be the right call to just revert this change and keep it the way it was. It could always return later if people truly want it.

**Comment by trwnh** [comment]
I'm guessing that a lot of people would like to see a more robust way of maintaining scroll position, but haven't actually tried the latest code. The bad UX was apparent to me pretty quickly, because I often scroll up and down timelines depending on whether I'm reading from bottom-to-top or from top-to-last-read. So I'd be in favor of having "x new items" appear only when Slow Mode is enabled, with the prior behavior being the de facto "fast mode".
