### ISSUE TITLE
Change domain silence to quarantine inbound follow requests instead of drop them

### ISSUE THREAD

**Issue by kaniini** [tootsuite/mastodon#11958]
### Pitch

After discussing with @Gargron in Discord about my plans to extend Pleroma's quarantine system to optionally require all follow requests from a given instance to be explicitly approved or rejected, Gargron expressed interest in adjusting domain silences to do the same.

### Motivation

Right now, there are scenarios where domain silence feature in Mastodon is too harsh.  Pleroma uses a different strategy for handling these situations which is more granular, but in both cases, API support and UX changes are needed to facilitate the changes, because the original API assumes a UX where follow requests are only approved explicitly if an account is locked.

### Getting There From Here

We need to add `pending_follow_requests` to the Account entity rendered at `/api/v1/verify_credentials`.

If `pending_follow_requests` is greater than zero, then the follow requests UI should be visible.  Alternatively if `locked` is true, then the follow requests UI should also be visible.

**Comment by ThibG** [comment]
Unless I'm mistaken, silencing a domain from Mastodon does not block follow requests, it merely prevents notifications (the follow would still go through automatically if the followed account is not blocked, and can otherwise be manually accepted/rejected).

So in a way, I feel the current way domain silence works would not be “too harsh” but on the contrary, too lax.

In any case, I support of this change, I'm just not sure `/api/v1/verify_credentials` is the best place to do it since it would typically be checked only once in a session. (imho that's another argument for having a proper follow request notification type)

**Comment by kaniini** [comment]
https://git.pleroma.social/pleroma/pleroma/merge_requests/1726 adds the `follow_requests_count` field.  I agree with @ThibG that we should add a follow request type as well, perhaps by extending the follow type with a new field noting it's current disposition.
