### ISSUE TITLE
Emoji Auto-complete + UTF8 representation

### ISSUE THREAD

**Issue by picsi** [tootsuite/mastodon#1199]
![captura de tela de 2017-04-07 18-21-29](https://cloud.githubusercontent.com/assets/23157217/24820622/5e0fcb2a-1bc0-11e7-8bc0-54313d9e9b86.png)

This screenshot was taken from quitter.is, the other side of the federation. Maybe Mastodon handles emoji/unicode in a nonstandard way?

**Comment by kballard** [comment]
How can I reproduce this? I posted a toot consisting of ☑️ and everything looked fine.

**Comment by daprice** [comment]
I don't think the `:ballot_box_with_check:` thing is a standard way of representing emoji, just a set of [keywords](https://github.com/jollygoodcode/emoji-keywords) that some websites use to simplify input on devices that don't have a way of typing the emoji characters natively. I'm guessing Mastodon is using the keywords internally instead of just using them for input and converting them to the actual unicode characters for storage/display.

**Comment by kballard** [comment]
@daprice If I toot `:ballot_box_with_check:` I end up with ☑️, exactly as if I had just tooted ☑️ by itself. Either way, the timeline doesn't florp for me, hence my question about how to reproduce.

**Comment by picsi** [comment]
Not sure how to reproduce it apart from viewing emoji-laden mastodon toots from a GNU social/qvitter instance. I've seen this error other times, I'll be sure to post screenshots when I spot it again.

**Comment by kballard** [comment]
Your screenshot is of a post you made on quitter.is, right? But the screenshot showing the florp appears to be a screenshot of a Mastodon instance. So how is qvitter actually related to reproducing the Mastodon florp?

**Comment by picsi** [comment]
I didn't make the post, I just saw it while browsing my timeline, and came here to report the bug.

**Comment by wxcafe** [comment]
The issue is that Mastodon uses text representations of emojis in the toots instead of the actual unicode character. I see it too when I toot and my mastodon<->twitter bridges tweets `:100:` instead of :100: for example.

**Comment by picsi** [comment]
@wxcafe any specific reason why this choice was made?

**Comment by wxcafe** [comment]
No idea. I think the fix wouldn't be that hard, tho : you simply need to replace the text representation with the actual unicode character at the moment the user clicks the toot button

**Comment by kballard** [comment]
Honestly, I was surprised the text representation even works. I don't think `:foo;` should work unless the UI actually provides auto-complete for that sort of thing, and it also shouldn't work unless there's some way to escape it so the toot actually renders the text `:foo:`.

**Comment by wxcafe** [comment]
I think auto-complete would be nice to have but there's no reason why typing manually :100: wouldn't render :100: and not `:100:` (as github seems to do). Not having a way to escape them is a problem, as we can see here https://social.wxcafe.net/@wxcafe/145533. I had the same problem with Gitlab a few months back and there's an issue with some discussion on their issue tracker https://gitlab.com/gitlab-org/gitlab-ce/issues/26433

**Comment by kballard** [comment]
I think the best way to do this is:

* Don't interpret `:foo:` as text in posts themselves. Just render it as text.
* In the post composer, if someone starts typing `:foo:`, offer auto-complete, and if they select an auto-complete entry, replace the whole thing with the emoji immediately.
* If they don't accept auto-complete, it means they're posting text, not emoji, so don't do anything with it.

Or in other words, make it purely a convenience at edit-time in the UI, but don't try to interpret `:foo:` at post time or when rendering posted toots.

**Comment by wxcafe** [comment]
Agreed, this is what I meant earlier ("you simply need to replace the text representation with the actual unicode character at the moment the user clicks the toot button").

Regarding the auto-complete popup, it should not appear if there's text before the `:`, as it does on github, `2001:` doesn't show the popup. It also shouldn't complete on pressing space, since (for example) french uses 'space colon space' as a standard, instead of the 'colon space'  that is standard in english.

**Comment by wxcafe** [comment]
#776 makes the really good point that if we replace the text description with real emojis at the moment the user clicks toot, the character count should still be one for the entire text description.

**Comment by kballard** [comment]
If we do what I suggest, we won't replace text with emojis when you hit TOOT, instead only doing it when you select from auto-complete, and that means the character count will automatically be correct (because when you autocomplete and it replaces the text with the emoji, the character count will update accordingly).

**Comment by wxcafe** [comment]
Right. Is someone up to do a PR for this? 

Sidenote, textual representation of emojis is also a problem *in* mastodon : 
<img width="194" alt="screen shot 2017-04-11 at 14 32 22" src="https://cloud.githubusercontent.com/assets/3009327/24909477/5aa1c1b2-1ec4-11e7-92df-7ae7f81fbb17.png">

**Comment by picsi** [comment]
pinging @Gargron

**Comment by Shnoulle** [comment]
mastodon already replace `:100:` by the final emoji 👍 only when seen from web , even if must not.

1. Notice on gnusocial/qvitter : `ostatus.shnoulle.net/notice/611194`
2. Repeat on mastodon : `m.sl-network.fr/web/statuses/18008` `:100:` are updated, and must not ...

**Comment by benhamill** [comment]
I think this has changed to something about auto-complete _plus_ UTF8 representations. Yes? Can/should an admin update the title?

My understanding of the current proposal:
* Make " :" pop up an auto-complete dialog for the emoji codes (see emoji.codes).
* Upon selection of an auto-complete option, replace the text so far with the UTF8 representation of the emoji immediately.
* If auto-complete is ignored, do not replace anything.

IDK if there should or even _could_ be something done about/with historical data, though.

**Comment by benhamill** [comment]
Oh. The above 3 points will have the incidental effect that emoji will be stored in the DB and federated out as UTF8 all the time.

**Comment by wxcafe** [comment]
This is *not* a problem as far as I'm concerned

**Comment by wxcafe** [comment]
Looks like the representation of emojis is already utf-8 since v1.2 
<img width="526" alt="screen shot 2017-04-19 at 10 19 40" src="https://cloud.githubusercontent.com/assets/3009327/25170171/e2a78cf6-24e9-11e7-9a44-14c8af981dc7.png">

**Comment by Shnoulle** [comment]
@wxcafe : it can be a problem on some older installation of friendica maybe or some other ostatus client.

Else : gnusocial have a plugin for this (update `:100:` to 💯 )

**Comment by wxcafe** [comment]
I don't see how other people not handling utf8 is a mastodon problem.

**Comment by Shnoulle** [comment]
As far **you** are concerned .... i didn't think of only me (it's OK on my instance), but think of another federate/ostatus tools ....

**Comment by Shnoulle** [comment]
To be clear : if you send emoji on the push request on a tool who break with emoji : you break another tool of a fediverse user.

**Comment by wxcafe** [comment]
look, people who don't support utf8 in 2017 should be held responsible for their own shit

**Comment by benhamill** [comment]
Maybe it's because I only have a loose grasp on how emoji works, but... I don't understand how that HTML snippet indicates that the emoji are represented in utf8. Is it the `alt` attribute or something else? I guess I expected just the bare :100: without the `img` tag stuff, but maybe that's something to do with replacing however the native OS/browser would render it with the Emoji One set?

**Comment by wxcafe** [comment]
The snippet indicates that the browser sees the utf8 representation because the `alt` is :100:, and there's the `img` tag to render it with Emoji One and ensure everyone has a consistent experience (and people who don't have emoji fonts still see them etc, exactly like on twitter for example)

**Comment by stephenburgess8** [comment]
@wxcafe 
> the only things needed now are autocomplete, not replacing the text if it isn't autocompleted, and not replacing if the :: representation if it's inside a word 

The emoji select is using the EmojiOne picker which has limited configurability. https://github.com/tommoor/emojione-picker

I don't see an easy way forward to create a typical text input autocomplete. By typical I mean one of these two options:

1. A select field appears below the input field matching the width of the input field which shows options limited by the input which can be selected
2. A dropdown which appears in a position relative to the input, again only showing the options limited by the dropdown

What about this approach:

When typing, typing `:**` (where `*` represents any character) could trigger opening the existing emoji picker. The characters which triggered the autocomplete could be passed into the search field of the emoji picker and focus could be added there. The biggest problem with this is if they _don't_ want an emoji, this would be annoying. Hitting escape in the EmojiOne picker just clears the search. We'd need to change ESC behavior to close the picker.

Alternatives to that option include:
1. Making a substantial PR to EmojiOne picker to allow for the picker to show without the search input and categories UI
2. Using a different emoji picker
3. Using a different component for the emoji autocomplete (not ideal - what if you set skin tone in EmojiOne. Could we get that info into the autocomplete?)

I would add one more task to this besides autocomplete and not replacing a `:emoji-name:` automatically. That is that when an emoji is currently selected, the emoji name is added to the toot instead of the emoji character. That's happening in the reducer. https://github.com/tootsuite/mastodon/blob/5abd5437665a9453feaf16c45960483add802378/app/assets/javascripts/components/reducers/compose.jsx#L108

Overall, three things:
1. Figure out how to handle autocomplete when using EmojiOne picker
2. Don't replace typed emoji strings with emojis (e.g. :+1: should not show up as 👍 )
3. Don't replace selected emojis with emoji strings, instead pass the character itself

**Comment by kballard** [comment]
I think we can do thing 2 and thing 3 right away. The current behavior is surprising to everyone, as the UI gives no hint that e.g. `:+1:` will show up as an emoji.

Personally, I don't even think we need to support autocomplete at all. A better approach might be to just define a keyboard shortcut that pops open the EmojiOne picker (and puts focus on the search field), although I'm not sure how we'd educate users about the keyboard shortcut. Every service I'm aware of that uses `:foo:` autocompletion for emoji also has non-standard emoji (this is GitHub, Slack, and Discord), so they require the `:foo:` representation. These services also all define textual formatting (such as using backticks for code). Mastodon doesn't have textual formatting, it just has text. And it doesn't have custom emoji either, so the unicode representation works fine. To that end, I'm in favor of just dropping thing 1 entirely and leaving the colon as just another character in a toot and not a gateway to emoji.

**Comment by nightpool** [comment]
I would enjoy autocomplete, but I don't think it deserves priority - high

**Comment by benhamill** [comment]
I'm still strongly in favor of autocomplete, but I agree it's not hipri. On
the other hand, I think the Emoji One project has a JS library for doing
autocomplete that might make it simple to add. I've never used it, so
that's speculation, though.
