### ISSUE TITLE
Mastodon shells out to imagemagick

### ISSUE THREAD

**Issue by sungo** [tootsuite/mastodon#1214]
Watching logs on my instance, I came across the following:

```
[httplog] GET http://oc.todon.fr:443/system/accounts/avatars/000/002/416/original/bd9b5ea5e95ccd79.png?1491471816 completed with status code 200 in 0.20349097000053007 seconds
Command :: file -b --mime '/tmp/8b9ab10f8ddcccd67cb09930010d1a7c20170406-712-rm18rh.png'
Command :: identify -format '%wx%h,%[exif:orientation]' '/tmp/8b9ab10f8ddcccd67cb09930010d1a7c20170406-712-1n1srcs.png[0]' 2>/dev/null
Command :: identify -format %m '/tmp/8b9ab10f8ddcccd67cb09930010d1a7c20170406-712-1n1srcs.png[0]'
Command :: convert '/tmp/8b9ab10f8ddcccd67cb09930010d1a7c20170406-712-1n1srcs.png[0]' -auto-orient -resize "120x" -crop "120x120+0+0" +repage -quality 80 -strip '/tmp/bc9b49a7a3561dee51839fa55a3bb33c20170406-712-1c0699z'
```

It appears that Mastodon downloads user profile images, shelling out to imagemagick, whenever an interaction occurs. Looks like this happens on the first time a user follows another or shows up in the timeline, including remote federated users.

Ignoring the perils of shelling out in the first place, imagemagick is known for being insecure. For example, imagetragick/CVE-2016–3714 ( http://imagetragick.com/ ) can be triggered by running 'identify' or 'convert' on a malicious image.

If I'm reading all this correctly, the worst case scenario is a follow bot with a malicious profile picture. Federated nodes with a vulnerable imagemagick could be compromised remotely with zero interaction or mitigation by the admin or user.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by mike-burns** [comment]
ImageMagick is invoked by the Paperclip gem for image processing. Paperclip uses the Cocaine gem for sanitizing the command-line when shelling out.

Note that you can replace ImageMagick with custom code: https://github.com/thoughtbot/paperclip#custom-attachment-processors

As someone far too familiar with this specific code, I'd rather use ImageMagick (which gets CVEs and fast bug fixes) than a custom-written image processor.

**Comment by krainboltgreene** [comment]
My preference would be to use the much more slim and safe GraphicsMagick, but as is I definitely agree with @mike-burns.

**Comment by krainboltgreene** [comment]
@sungo For what it's worth, paperclip does do image checking by looking at the first few bytes and the file extension.

**Comment by sungo** [comment]
Indeed. That covers us for CVE-2016–3714. I'm more worried about what comes next.

I'm totally not advocating a custom image parser but I'd love to see a solution that didn't involve shelling out.

I think my bigger concern, honestly, is that we're downloading and processing images from remote servers in the background. That opens up a lot of possible vectors regardless of the processing implementation. I'm obviously not an expert here but would it be possible to process the images on the originating server and just pull down preprocessed files?

**Comment by krainboltgreene** [comment]
I share your concern.

We can't assume any processing has been done on another server.

One thing I want to convince @Gargron of using is https://github.com/lacqueristas/lumin as it removes the need for mastodon to do any image processing and we can isolate security vulns away from the database.

**Comment by sungo** [comment]
We could analyze the content we get from the remote server and just refuse to use it if it's not the right dimensions or whatever.

**Comment by krainboltgreene** [comment]
If doing remote image manipulation is out of the question then yes, I would prefer to do extra validation on file data received. @sungo can you detail down what we're not checking, but should be checking?

**Comment by sungo** [comment]
The code is processing the images so they meet certain requirements, yes? Width, height, size, all that fun. I'm just thinking we check that ahead of time and refuse to use remote files that don't match those qualifications.

**Comment by mike-burns** [comment]
(And as a Paperclip maintainer I must add: if you find a way to do extra validation, please let us know!)

> check that ahead of time

I don't totally follow this. Are you suggesting that we ask the browser for this information?

**Comment by krainboltgreene** [comment]
Thanks for your insight @mike-burns.

**Comment by sungo** [comment]
Apologies. The confusion is mine. I'm new to the codebase and things are a bit twisty sometimes. 

Digging through the code, near as I can tell, there is no way to treat the media for a remote user any differently than for a local user. If I'm reading things right, the media is given to paperclip straight away in both cases. If I'm reading things right over in the paperclip source, it performs all its operations by shelling out to imagemagick.  So, as it stands right now, provided I'm not still confused, there is no way to validate the properties of the incoming remote media without downloading the file and shelling out to imagemagick.

At this point, I'm not sure of the right approach. I don't see any low-impact way to avoid trusting remote content from federated instances.

**Comment by timkuijsten** [comment]
I think image processing is complex enough to warrant a sandbox and separate it from all other processes, first and foremost your web server. The minimum approach should involve at least a dedicated system user that is only used to execute the image processor, be it IM, GM or anything else.

If an average delay of 30 seconds is fast enough you can do it simply via cron. Otherwise you have to write a dedicated daemon to do it on demand (maybe what @krainboltgreene mentioned or use docker, although that might be heavy handed).

The point is that if it blows up on certain images (and it will[1]) it only has the privileges of this dedicated user and should not be able to access the database or web server without using yet another exploit.

> My preference would be to use the much more slim and safe GraphicsMagick

I favor GM over IM as well for the same reasons. But I think it's important to realize that there is no such thing as a safe image processing library. Although GM might be more safe than IM, it still has plenty of issues[2]. It forked from IM and they're both huge and complex. Fwiw, a quick count of source lines of code:
GraphicsMagick-1.3.25:
377713
ImageMagick-7.0.5-4:
479488

I wouldn't run any of them without extra precautions.

[1] http://marc.info/?l=oss-security&w=2&r=1&s=imagemagick&q=b
[2] http://marc.info/?l=oss-security&w=2&r=1&s=graphicsmagick&q=b

**Comment by timkuijsten** [comment]
ps. `file` (using magic which is hard to parse) has had it's issues too[1] and it wouldn't be a bad idea to sandbox that process as well.

[1] http://changelogs.ubuntu.com/changelogs/pool/main/f/file/file_5.28-2ubuntu1/changelog

**Comment by expenses** [comment]
Having a config option to specify the processing back-end (IM/GM at least) would be handy.

**Comment by patf** [comment]
One way the image processing could be isolated would be using something like the delayed_paperclip gem. Instead of processing the files immediately, it could be handled by a dedicated sidekiq queue, which could be processed from a separate host. This is probably a good idea anyway as it frees up web workers.

The gem supports returning the original image prior to it being processed. I haven't looked at much of the code that deals with media attachments, but this could be a viable path.

**Comment by patf** [comment]
I did some testing with delayed_paperclip and it seems to work quite well. I still need to test this with S3 and make sure that the original file being returned doesn't break anything else, but once that's done, I'll open a PR for this.

paperclip still shells out to `file` to determine the file types in the web worker to validate the mime type. paperclip uses both `file` and the mimemagic gem for content type detection. If mimemagic is good enough for the content types we care about, I'll check if we can use only mimemagic (which is just ruby) in a custom content type detector instead, but that'll be a separate PR.
