### ISSUE TITLE
Link conversion for self posted toots

### ISSUE THREAD

**Issue by fedione** [tootsuite/mastodon#12162]
Is it normal, or on my server only,  that the "article preview with pictures (?)" is usually visible only after a page refresh?

![fc2f4692c2431146](https://user-images.githubusercontent.com/55923612/66717339-36d29500-edd8-11e9-9d0d-43a21b452fed.png)

**Comment by marrus-sh** [comment]
Normal, for three reasons:

1. The server has to actually fetch the preview before it can show it, so there will always be some delay

2. This delay is actually extended intentionally (see #8445) in order to keep every fediverse server from requesting the preview at the exact same time (potentially overloading small sites).

3. Even after the server has finished fetching the preview, the frontend still won't receive it until the toot is fetched again (either in a different timeline or from a refresh).

The reason why previews show instantly on other sites like Facebook is (1) there is a higher chance that Facebook has already encountered the link before, and (2) Facebook actually starts requesting the link before you click “Post”.

**Comment by fedione** [comment]
So there is no server misconfiguration on my site.

Thanks for this detailed explanation and have a nice day :)
