### ISSUE TITLE
Mentions of users with unicode domain names are not converted to punycode

### ISSUE THREAD

**Issue by sneak** [tootsuite/mastodon#12246]
I'm trying to mention my other account (`@sneak@hæresiar.ch`) on my own instance `@hæresiar.ch` from the public `@tilde.zone` instance but the mention fails.

### Expected behaviour

The mention's domain-part should be converted to punycode.

### Actual behaviour

The mention failed.

### Steps to reproduce the problem

Mention a user @ an IDN

### Specifications

This is from the `@tilde.zone` (not run by me) instance which is running 3.0.0 afaik patched only to increase toot length.

**Comment by f-person** [comment]
@Gargron the issue still exists. This is also the case when clicking the "reply" button. 



### Expected behaviour
The mention's domain-part should be converted to punycode and the mentioned user should be notified about the mention.

### Actual behaviour
The mention's domain part is plain text IDN, not mention. The mentioned user doesn't get a notification and doesn't see the toot on his instance.  

### Steps to reproduce the problem
Mention a user @ IDN or reply to user's toot using the "reply" button.
Here is an example: Tried to reply to @fperson@թութ.հայ's toot first by manually writing @fperson@punycode (https://mastodon.social/web/statuses/103761317985946359), then by using the "reply" button (https://mastodon.social/web/statuses/103761353645759579).


### Specifications
Both instances run the v3.1.2

I use Brave browser on Linux.

**Comment by f-person** [comment]
The issue is probable (as I haven't tested it personally yet) fixed in https://github.com/mastodon/mastodon/pull/16689. Yay!

**Comment by cassieroyal** [comment]
Can you please delete my account 

Sent from Yahoo Mail on Android 
 
  On Thu, Sep 16, 2021 at 11:16 PM, Arshak ***@***.***> wrote:   


The issue is probable (as I haven't tested it personally yet) fixed in #16689. Yay!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
