### ISSUE TITLE
gem update --system times out

### ISSUE THREAD

**Issue by kdmiller45** [tootsuite/mastodon#12335]
Trying to install mastodon, but can't get past this point

gen update --system

ERROR: While executing gem ... (Gem::RemoteFetcher::UnknownHostError)
time out (https://rubygems.org/specs.4.8.gz

I have disabled Ip6 still happens

**Comment by umonaca** [comment]
I don't think it has anything to do with Mastodon. It is a network issue.
Try the following command to test your connection:
```
# Show the DNS servers in use
cat /etc/resolv.conf 

# Suppose you have 8.8.8.8 as DNS server, then
ping -c 8.8.8.8

# Check if your DNS server is working
nslookup rubygems.org 8.8.8.8

# Ping the rubygems.org
ping -c 10 rubygems.org
```

**Comment by kdmiller45** [comment]
cat /etc/resolv.conf       nameserver 127.0.0.53
ping  127.0.0.53 yields responses
nslookup yields
![image](https://user-images.githubusercontent.com/19610991/68545878-7d42f180-038e-11ea-9c40-05c76dc0060c.png)

**Comment by umonaca** [comment]
The ip addresses you provided are all valid and accept pings.
Please report the detailed output of your last step because it shows what address is in use by your operating system. Please use the following command as it skips reverse dns lookup.
```
ping -c 5 -n rubygems.org
```

Besides, run a traceroute and paste the results here:
```
sudo traceroute -n -I rubygems.org
```

**Comment by nightpool** [comment]
We primarily use GitHub as a bug and feature tracker. For usage questions, troubleshooting of deployments and other individual technical assistance, please use one of the resources below:

 - https://discourse.joinmastodon.org
 - #mastodon on irc.freenode.net

Feel free to continue the discussion of the issue here, but i'm going to be marking the ticket as "closed". This won't affect your ability to comment on it, it's just a reflection of the fact that it's not a defect in the mastodon software, just a problem with your individual deployment.
