### ISSUE TITLE
Require Admin/Moderator 2FA

### ISSUE THREAD

**Issue by irlcatgirl** [tootsuite/mastodon#12363]
### Pitch

We should require 2FA to be setup before a user can access administrator / moderator tools. 2FA is relatively straightforward to setup. As a compromise we could also instead have Mastodon send the moderator or administrator a code over email before they can access tools (with either requiring a new code every three hours or a remember this device option) if they do not have 2FA enabled on their account. We could also make this configuration in the `.env.production` file although I do think it should be a featured by default to have the greatest impact. Thoughts?

### Motivation

This would make the moderation and administration tools in the fediverse more secure.

**Comment by Shleeble** [comment]
MFA is wonderful and you should all be using it.. this is a UX thing, I could imagine an onboarding process could include this.. #12365

**Comment by nsuchy** [comment]
> MFA is wonderful and you should all be using it.. this is a UX thing, I could imagine an onboarding process could include this.. #12365

Yes but this issue is to require it for moderators and administrators, to make it mandatory, non-nonnegotiable if you want to use moderator and administrator tools. You'll be either getting a code by email or using a TOTP app.

**Comment by MirceaKitsune** [comment]
I'm neutral on the suggestion in cause, but wanted to add one thing: 2FA is not easy to setup on Mastodon. That's because instead of login a code being delivered by SMS, you're only given one of those checker images which I don't even know what to do with!

I'd agree more if instead of that system, we could have 2FA via a local key file, as I've seen on a few other services. That's a file present only on your hard drive, which you can select and upload when logging in. Perhaps a separate issue should be opened for this idea.

**Comment by nsuchy** [comment]
As for difficulty of setup, emailed codes could work but really they should be avoided incase the email doesn’t have 2FA setup.

SMS 2FA is insecure because of sim swapping attacks. Someone manipulates tech support into transferring your number away to steal accounts. It’s a bad idea and should be avoided. Not to mention we would rely on often unreliable centralized email to sms gateways or an API Service like Twilio that charges a pay fee per sms, this approach goes against the decentralized nature of our software.

U2F support would be nice, as would a PGP Encrypted Email (similar to the key file idea). Feel free to open an issue with that idea and similar ones.

As admin and moderator accounts have access to users personal information (example: Email+IP Address) there’s no excuse to not use 2FA. The right to convenience goes away when you have access to potentially 1000s of internet users personal information.

**Comment by koyuawsmbrtn** [comment]
Support for hardware 2FA keys has been added today. Guess we should start working on this :thinking:
