### ISSUE TITLE
Pressing "back" takes 5 seconds

### ISSUE THREAD

**Issue by impiaaa** [tootsuite/mastodon#12455]
video: https://assets.octodon.social/media_attachments/files/007/882/867/original/25b66c7b66fb7b63.mp4

### Expected behaviour

Pressing "back" should take less than a second.

### Actual behaviour

Depending how far the timeline was scrolled down and how much it has updated since the status was opened, it can take up to a minute or two to fully load the timeline, or just crash the browser.

### Steps to reproduce the problem

Scroll down a timeline some, open a status in detail view, and then press "back."

### Specifications

This is new to Mastodon version 3.

This is in iOS 12, either browser or app bookmark. It seems to work better on Android and desktop browsers.

**Comment by Gargron** [comment]
:grimacing: This sucks, but could only maybe be fixed by making statuses components render faster, which is not guaranteed to be possible. Another idea is that perhaps the intersection-observer based approach is not good enough and we need to switch to react-virtualized, however that means "messing with" native browser scrolling which I think some people in the community dislike.
