### ISSUE TITLE
Manual scroll doesn't work on Windows 

### ISSUE THREAD

**Issue by sapphaos** [tootsuite/mastodon#12607]
### Expected behaviour

Scroll the columns with the mouse

### Actual behaviour

The scrollbar doesn't react

### Specifications

I'm using 3.0.1+ glitch, someone else reported the problem and is using 3.0.1

I'm using Firefox on windows 10
This doesn't seem to happen on Firefox on Ubuntu

Capture of the behaviour here: https://biscuit.town/@Sapphaos/103300086696062102

**Comment by ThibG** [comment]
I'm not sure where to start looking, and I don't have a system where I can reproduce this…

Does the mouse wheel allow you to scroll? If you right-click on the scrollbar, does a menu pop up? If so, does it offer you to inspect an element, and which one?

In the inspector, can you find the `div` element with the `scrollable` class and disable the `contain: strict` rule? What about the `scrollbar-color` rule on the `html` element?

**Comment by ThibG** [comment]
This seems to be caused by the `will-change: transform` rule introduced by #5001 to force mobile browsers to use GPU acceleration for the scrolling containers and improve scrolling performances.

The fact that it interferes with mouse-based scrolling sounds like a bug in Firefox, but I'm not sure we should be using that rule in the first place…

**Comment by ThibG** [comment]
Debian's build of Chromium is lacking the performance tools, so I can't get insight from this… but I'm wondering whether the use of `will-change: transform` for that particular issue is superseded by the fact that we now have the single-column mode with the scroll being managed directly on the root element?

cc @nolanlawson
