### ISSUE TITLE
Decimals cause profile counters to overflow container and wrap to new line

### ISSUE THREAD

**Issue by trwnh** [tootsuite/mastodon#12699]
![image](https://user-images.githubusercontent.com/10606431/71536525-00d08780-28d6-11ea-954a-0a9b3dadd1b3.png)

mastodon.social

I'd consider removing the decimal because it is usually not that significant. Or alternatively, only show 3 significant figures at most, i.e., when the count is 3 digits, do not show the decimal.

3 sig figs | No decimals
--- | ---
![image](https://user-images.githubusercontent.com/10606431/71536574-658be200-28d6-11ea-823a-4c330294502e.png) | ![image](https://user-images.githubusercontent.com/10606431/71536588-76d4ee80-28d6-11ea-9f74-6e245b81e1d4.png)

**Comment by noellabo** [comment]
Pull-requested a fix to change shortNumberFormat to return shorter notation.

1 = 1
12 = 12
123 = 123
1234 = 1.2K
12345 = 12K
123456 = 123K
1234567 = 1.2M
12345678 = 12M
123456789 = 123M
1234567890 = 1234M

Also, when translating Toots, Follows, Followers, it may not be possible to prevent overflow because it may be a longer string.
For this reason, the interval for multiple lines has been adjusted.
