### ISSUE TITLE
Notifications feed shouldn't look the same as the timeline

### ISSUE THREAD

**Issue by alexgleason** [tootsuite/mastodon#1302]
I think it's confusing to new users that the notifications look like another timeline feed wedged between home and the getting started pane.

@marykatefain

**Comment by wxcafe** [comment]
I don't think so, Tweetdeck works exactly the same way, but then maybe to users who have never used tweetdeck...

**Comment by chris-martin** [comment]
It *is* another timeline.

**Comment by anowlcalledjosh** [comment]
At any rate, 25% of my screen is currently taken up by an empty notifications pane. There's a reason notifications are hidden behind a button in every other major social media platform*.

Presumably TweetDeck is targeted at "content creators" that have a constant stream of notifications flowing in. That's a valid usecase; I can see that some people may have tweets targeted at them at the same rate as the people they follow produce tweets, and I don't think that Mastodon should ignore those people. They are the reason that there's anything interesting to read! However, lurking is also a thing that some people do ("content consumers"?), and Mastodon needs to support that too.

*including, off the top of my head, Facebook, Twitter, Google+, Instagram, reddit, Discord, Steam...

**Comment by wxcafe** [comment]
Mastodon supports this. Since the messages are, unlike on facebook, google+, instagram, reddit, discord, steam, etc, limited to 500 chararacters, you don't need more than the home and timelines panes to follow what's going on. The notifications pane can stay up with the latest notifications you received. Twitter web has a horrific UI imo, and the notifications being hidden behind a button for 140 characters messages while 80% of the main screen is empty is only part of this 
![screenshot from 2017-04-19 01-21-27](https://cloud.githubusercontent.com/assets/3009327/25157045/10bbb3a6-249f-11e7-85b9-d8dfe6218911.png)

**Comment by anowlcalledjosh** [comment]
> The notifications pane can stay up with the latest notifications you received

But why does it need to? It _can_, but I care much more about seeing what people are posting now than seeing notifications from last month. IMO, Twitter's UI wouldn't be improved by adding a notifications column in that empty space, since my notifications are as static as the background most of the time (apologies for poor mockup):

![image](https://cloud.githubusercontent.com/assets/9433472/25200650/ff58eacc-2546-11e7-9b5a-8c79f13ce734.png)

Having more horizontal space to read posts would be no bad thing. A typical line of text is currently 30–35 characters, whereas e.g. Twitter wraps lines at about 70 characters. The "correct" line length is apparently [50–60 characters][baymard].

[baymard]: https://baymard.com/blog/line-length-readability

**Comment by wxcafe** [comment]
This mockup is getting there but it's not quite like tweetdeck yet, you'd need more columns :p 
![screenshot from 2017-04-20 01-13-17](https://cloud.githubusercontent.com/assets/3009327/25206249/13992162-2567-11e7-8b42-ecf030735efe.png)
Seriously tho when the frontend becomes more decoupled from the backend it'll become easier to make an alternative UI like this. Right now I don't think it's a priority, but if you want to make the columns larger you can use a simple userstyle that sets `flex-grow: inherit;` on the columns

**Comment by Gargron** [comment]
See #3207 for an option to remove the notifications column

Notifications column itself is not going to change
