### ISSUE TITLE
1 Account saved with web domain instead of local domain in remote instance

### ISSUE THREAD

**Issue by thegcat** [tootsuite/mastodon#13136]
The `toot.kif.rocks` instance is configured with a local domain of  `kif.rocks` according to https://github.com/tootsuite/documentation/blob/archive/Running-Mastodon/Serving_a_different_domain.md This was the case since the first day this instance was online.

It seems one user on our instance has been duplicated on a remote instance but with the web domain instead of the local domain as domain see https://chaos.social/@LenaEine/103708312764209912 and attached discussion. As noted in: There are 2 users in the DB of the remote instance, one with the domain kif.rocks, and one with the domain toot.kif.rocks. Everything else, especially other users from kif.rocks, seem unaffected.

Would anyone have an idea how this might have happened, if a bug from around that time might explain this behaviour, or at least how to debug this? Furthermore, how should the chaos.social administrators best fix this issue? Thanks.

### Expected behaviour

No duplicate users.

### Actual behaviour

A duplicated user.

### Steps to reproduce the problem

We have no idea.

### Specifications

kif.rocks is currently on 3.1, should have been on 3.0 around the time this happened. I would assume this applies to chaos.social as well.

**Comment by thegcat** [comment]
Thank you for the fix! Any pointers on how to deal with existing duplicate/erroneous entries in the DB? Should the remote admin just delete the users with the "wrong" domain?

**Comment by ThibG** [comment]
It's a good question. I would say the best thing to do is to remove the users with the “wrong” domain, but I'm afraid Mastodon could have associated them statuses or followers, in which case the “right” thing would be to re-attribute them to the “correct” user before deleting the wrong one…

**Comment by orithena** [comment]
I'm the affected user. It seems that just removing the b0rken user copy on the remote server (from my point of view) does not work. @ordnung@chaos.social did just that, and it seems that I still cannot be read on chaos.social (I really don't like this, because a lot of my followers are on chaos.social).

**Comment by ThibG** [comment]
Has chaos.social deployed the fix? Do they have a duplicate again for your account? If so and they don't want or can't apply the fix yet, I'd suggest deleting the offending account again then explicitly fetching your profile from the search box. I believe this should fix the issue.

@thegcat did you by any chance restore a previous backup, re-create your instance, or use the `tootctl account rotate` tool?

**Comment by orithena** [comment]
More info: I (@anathem@kif.rocks) cannot be read by my followers on chaos.social since 2019-12-30 (unless they read a boost or I mention them explicitely). It only came up after I mentioned a user on chaos.social who asked whether she should follow both of my accounts, since she does not see any public/initial toot from me since 2019-12-30. Maybe the thread ending with https://chaos.social/@ruru4143/103710799718903737 contains more relevant info (sorry, it's in german).

**Comment by thegcat** [comment]
@ThibG The instance has been running through since day one, without recreation, restoration or anything of the like. `tootctl account rotate` neither, I wouldn't even know what it does 😅

**Comment by ThibG** [comment]
@orithena it appears your chaos.social followers aren't following you anymore, so I suspect the account that actually recorded your interactions on chaos.social was the “wrong” one, that got deleted. So both instances are out of sync and your chaos.social followers should re-follow you, which should the issue going forward.

I'm unsure why that would have happened, though, it seems the bug I fixed might not have been the one that triggered the issue in the first place (it is possible, but not certain).

It is possible that the duplicate account state on chaos.social dates back from far longer, as your account has been around for a long time and even went through the OStatus → ActivityPub upgrade. So I'm not sure when exactly something could have gone wrong, unfortunately.

**Comment by orithena** [comment]
@thibg I'll ask around whether your suspicion holds.

**Comment by nazco** [comment]
Problem is fixed by now. I removed the old account via Account.destroy(id) over the ruby console. After that the correct account was able to toot to our instance again. Still all old toots since the problem occurred in December are lost for our instance because I missed to re-associate them before another try (I tried to delete the account another way yesterday).

**Comment by thegcat** [comment]
Thank you all for the help and the quick fixes!

**Comment by orithena** [comment]
@thibg By now I can confirm that your suspicion does not hold: My old followers from chaos.social still follow me and can now read me again (after the intervention described by @nazco). I'll go informing my new followers from chaos.social since 2019-12-30 about this issue (I still got their follow notifications in my history).

Now my only problem is: How do I detect on which instances this problem with my account still exists? How can we detect which other accounts on different instances may be affected? I have no idea. Is there maybe a process in place that notifies admins to check certain things in their database (maybe via update scripts)?
