### ISSUE TITLE
unable to send messages to anyone or add anyone

### ISSUE THREAD

**Issue by goldenkitsune** [tootsuite/mastodon#13153]
when i try to follow new people it says action not allowed and when i try to send messages to new people it says 504 

expected behavior: should let me follow new people and let me send messages

**Comment by ThibG** [comment]
I closed #13149 because it is likely an issue with the server you are using and not the software.

If you are using a server that is managed by someone else than yourself, please contact them instead.

If you are managing the server, please provide additional information:
- what version of Mastodon are you using?
- does it occur when posting any message, or only when mentioning people? Local or remote?
- do you have any error in puma/mastodon-web's logs? (`journalctl -u mastodon-web`)

**Comment by ThibG** [comment]
Closing again, reopen if you have more information.
