### ISSUE TITLE
No response returned when searching URL

### ISSUE THREAD

**Issue by abcang** [tootsuite/mastodon#13251]
### Expected behaviour

When you enter a URL in the search field and perform a search, the search results are returned in a realistic time.

### Actual behaviour

When a search is performed by entering a URL in the search field, the search result is not returned even after 1 minute or more, and 504 is returned. (confirmed at mastodon.social)

### Steps to reproduce the problem

Enter a URL in the search field to perform a search. (E.g. https://www.youtube.com/ )

### Specifications

Occurs in mastodon.social (v3.1.2)
Probably the same phenomenon is occurring from v3.1.0
https://github.com/tootsuite/mastodon/pull/12336 https://github.com/tootsuite/mastodon/pull/12742

**Comment by ThibG** [comment]
I hadn't noticed that because of the relatively low number of toots my instance had seen, but yeah, that is an issue. I think the feature (being able to find back remote private toots by URL) is important, so we may need an index… I'm just a little uncomfortable with the amount of database usage that would be…

**Comment by Gargron** [comment]
Yeah, I don't want another massive index. It might be cheaper to just always to a HTTP request to get the URI or nothing instead of having another huge index.

**Comment by ThibG** [comment]
Doing an HTTP query won't help you here for private toots

**Comment by ThibG** [comment]
We already perform an HTTP query in every case, we only look into the database if it couldn't find a status.

That wouldn't be a full solution, but maybe we could at least look at the HTTP response code to only do the db query if the fetch failed because of 401, 403 or 404 (and not because, it has nothing to do with an AP object)
