### ISSUE TITLE
Elasticsearch requests time out when using http_proxy with privoxy

### ISSUE THREAD

**Issue by GigaByte4711** [tootsuite/mastodon#13484]
### Expected behaviour

All requests to the ElasticSearch docker endpoint from Faraday go direct to the correct port, bypassing the Tor proxy.

### Actual behaviour

Faraday attempts to make the connection via privoxy and Tor to the configured elasticsearch host. Because the host is local, tor/privoxy cannot route to the service, resulting in a timeout.

### Steps to reproduce the problem

1. Enable elasticsearch and hidden service federation. Ensure the .env variable `http_proxy` is set to the privoxy host.
2. Attempt to run `tootctl search deploy` and watch the timeout.
3. Comment out the `http_proxy` .env variable and re-run `tootctl search deploy`.
4. Deploy activity continues correctly

### Specifications

Mastodon built from Master at commit cd6d851
Running within a docker environment, but I think this may affect non-docker installs too.

**Comment by Gargron** [comment]
Because the ElasticSearch gem does not anywhere make use of our `Request` class which implements `http_proxy` logic, my first guess is that that special env variable is interpreted by the ElasticSearch gem's underlying HTTP library. Either changing the name of the env variable we use for hidden service stuff or disabling that behaviour in the underlying library would be the two available options.

**Comment by Gargron** [comment]
Got it: https://github.com/lostisland/faraday/blob/a285d7a8b6f5f3cfb1d273aef2ed1ac007ef8b1d/docs/usage/customize.md#proxy

**Comment by GigaByte4711** [comment]
Is there anything I can do to help test a fix?
