### ISSUE TITLE
Better upload experience

### ISSUE THREAD

**Issue by koyuawsmbrtn** [tootsuite/mastodon#13549]
### Pitch

Allowing to upload more than four images (perhaps unlimited?) would result in less threads and allows power-users to fully use the platform to their advantage. Also why is there no way to mix media? Pleroma does this for years now, but this change hasn't been in Mastodon.

### Motivation

This change would benifit power users and people who post a lot of images.

**Comment by SuperSandro2000** [comment]
I would be for like 10 not unlimited unlimited.

**Comment by lfuelling** [comment]
It would be really cool if the amount of files was configurable, not locked to some hardcoded value that has to be patched in source like post length, etc.

**Comment by koyuawsmbrtn** [comment]
Yeah somewhere in the `.env` file

**Comment by Sasha-Sorokin** [comment]
If we do allow more than four files, I'd go with teasing three images to the user and replace fourth thumbnail with button that opens gallery (or full screen preview, whatever you call it), because having more than two row of images feels redundant (but may remind of Tumblr, rest in peace...).

![Example screenshot with fourth thumbnail replaced with media icon and label “4+”](https://user-images.githubusercontent.com/10401817/80425563-17333200-890e-11ea-8231-d6363de73f8b.png)

Another concept that I've seen in some Mastodon client is just making a post a carousel itself, we can do this probably with swipeable react panel. I don't remember what client, but found similar thing in [VK](https://en.wikipedia.org/wiki/VK_(service)) articles ([live version](https://vk.com/@debpkg-testing)) and turns out this little bump is would be nice thing to have to alert user like “Hey! I'm scrollable”:

![Example GIF of a carousel](https://user-images.githubusercontent.com/10401817/80426202-747bb300-890f-11ea-89c2-430c883b7877.gif)

**Comment by koyuawsmbrtn** [comment]
Wow, these UI concepts are looking very promising

**Comment by SuperSandro2000** [comment]
> It would be really cool if the amount of files was configurable, not locked to some hardcoded value that has to be patched in source like post length, etc.

Which wouldn't work well with federated instances. If I limit it to 4 and other to 50 I still might have posts with 50 attachements.

**Comment by lfuelling** [comment]
Yes of course. But imo that's by design; the planets in the Mastodon intro are all different for a reason :)

There are instances out there that allow up to 10k chars, have Markdown/HTML support and more than four meta fields. I have yet to encounter federation issues with those.

**Comment by Gargron** [comment]
The limits for both characters and media will remain, because they are gimmicks that make Mastodon feel like Mastodon. With analogue media, the limits are physical in nature. With digital media, they have to be enforced by someone who says "no" to such requests. Why didn't Vine support hosting 4 hour movies? Because they wouln't be vines.

I can't stop you from changing the limits in your own copies of the code, and that's by design. I still think you're making a mistake when you do that, though.
