### ISSUE TITLE
"too many certificates already issued for exact set of domains" Can't Deploy Instance

### ISSUE THREAD

**Issue by b0hem14n** [tootsuite/mastodon#13697]
Hi everyone i did several setup mastodon my VPS :) and now i reached limit of Let's Encrypt SSL and this cause can't deploy my mastodon instance please help.

Error: "too many certificates already issued for exact set of domains"

And when i go to visit my domain  getting this error : " ERR_CONNECTION_REFUSED "

Thank in advance.

**Comment by nightpool** [comment]
We primarily use GitHub as a bug and feature tracker. For usage questions, troubleshooting of deployments and other individual technical assistance, please use one of the resources below:

 - https://discourse.joinmastodon.org
 - #mastodon on irc.freenode.net

Feel free to continue the discussion of the issue here, but I'm going to be marking the ticket as "closed". This won't affect your ability to comment on it, it's just a reflection of the fact that it's not a defect in the mastodon software, just a problem with your individual deployment.

**Comment by b0hem14n** [comment]
> We primarily use GitHub as a bug and feature tracker. For usage questions, troubleshooting of deployments and other individual technical assistance, please use one of the resources below:
> 
> * https://discourse.joinmastodon.org
> * #mastodon on irc.freenode.net
> 
> Feel free to continue the discussion of the issue here, but I'm going to be marking the ticket as "closed". This won't affect your ability to comment on it, it's just a reflection of the fact that it's not a defect in the mastodon software, just a problem with your individual deployment.

i am not able to create topic there please help me here.
