### ISSUE TITLE
Extract instance list & apps into their own repositories

### ISSUE THREAD

**Issue by svenluijten** [tootsuite/mastodon#1373]
To keep this repository's issues and pull requests more related to the actual (web) application, I suggest we make a seperate repository for the lists of other instances and apps.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by mjankowski** [comment]
I haven't explored the current API enough to know how possible this is, but it would be interesting if the instances could help each other discover each other.

- When instance A gets set up it only knows about itself
- Once a user from instance A follows someone from instance B, instance A can ask instance B about what other instances it knows about, because A now knows B exists
- B returns a full list of known instances, which A adds it to its known list

This would be kind of cool because it would be distributed and automated and not require a person to do anything and not run the risk of a central instance repo being destroyed or overloaded.

There might be issues: 

- Privacy implications - maybe some instances don't want to advertise their existence?
- Performance implications - you don't want to exhaust cycles just constantly maintaining these lists
- Efficiency/storage implications - it might be weird/pointless for an instance to store a large list of other instances when many people won't even look at them that much? Not sure.

Short of that, I agree that moving the "list of instances" document to another repo (maybe also the docs?) would narrow the focus of this repo to just code improvements?

**Comment by Gargron** [comment]
This is resolved :D
