### ISSUE TITLE
Muting a user hides their boosts even if "hide boosts" is not enabled

### ISSUE THREAD

**Issue by trwnh** [tootsuite/mastodon#13744]
### Expected behaviour 

Either the "hide boosts" option disappears, or boosts can be muted or shown separately from original posts.

### Actual behaviour

"Hide/show boosts" remains available as an option despite doing nothing.

### Steps to reproduce the problem

1. Mute someone
2. Click the three-dot menu on their profile
3. Note that "Hide boosts from this user" is available as an option
4. Note that boosts were hidden from your timeline anyway

### Specifications

mastodon.social v3.1.3

**Comment by ThibG** [comment]
Just to make sure, are we talking about muting someone you follow? The only “hide boosts” option I can think of is to hide toots someone you follow boosts. As such, having boosts being muted separately from original posts seems odd (you'd be interested only in what that person boosts, and not their own toots?)
If I understand the situation well, the “hide boosts” option should indeed be hidden for people that you follow but also mute (which, tbh, sounds like a weird edge case, but probably worth keeping).

**Comment by trwnh** [comment]
Yes, muting someone you follow is the case I am talking about here.

Right now, the following use case is supported:
- Interested in original posts, but not boosts

But this is not supported:
- Interested in boosts, but not original posts

I don't think the latter is odd or an edge case, as it is easy to think of a case where someone boosts interesting things but their posts are not so interesting.

**Comment by Gargron** [comment]
Muting someone you follow is relatively niche, disabling boosts is relatively niche (if only because people don't look into that dropdown...). Muting someone you follow but leaving their boosts on is hella niche. I understand that you wanna do it but in my understanding nobody else would be using that. We might want to hide the "disable boosts" option for those who are followed & muted to avoid confusion though.
