### ISSUE TITLE
Mastodon Upload

### ISSUE THREAD

**Issue by musicsd** [tootsuite/mastodon#14154]
File more than 2 MB will never be sent on the Tor browser. (mastodon.social)

**Comment by musicsd** [comment]
I'm sorry, I can't say more than that.

**Comment by mecqor** [comment]
good job. I have the same problem; Please help.
Thank You

**Comment by Sasha-Sorokin** [comment]
Hello! From what I know, mastodon.social has limit of 10 MB uploads.

I've done some testing: I logged in my account on mastodon.social using Tor and tried to upload two example OGG files of two sizes: 2 MB and 5 MB. Both were uploaded without errors and attached to the toot, that I was able to post. Am I missing something?

What exact error did you encounter and what file type you are trying to upload?

**Comment by musicsd** [comment]
First, Mastodon is blocked in Iran. That's why I use Tor to log in.
To upload a 4 MB mp3 file with the error "An unexpected error occurred." I encounter.

**Comment by Sasha-Sorokin** [comment]
I did not know it was blocked out there, glad you're still able to bypass censorship and stay connected.

Regarding the issue, such error may happen due to slow uploading speed, when request does not complete in time, browser aborts it and NetworkError occurs, which Mastodon does not currently handle, resulting in cryptic “unexpected error” message. Do you believe this may be the case? It should look like uploading is ongoing, almost completes, then stuck for some long time and error message appears. If so, not much can be done, we may improve error message, but not sure how to help with speed :(

**Comment by SuperSandro2000** [comment]
> First, Mastodon is blocked in Iran

Only certain domains should be blocked. So if you find an instance which is not blocked you could access it but you probably do not want to do that.

**Comment by musicsd** [comment]
@Sasha-Sorokin Yes that's right. My internet Upload speed is slow. Maybe that's why ...

**Comment by musicsd** [comment]
@SuperSandro2000 Yes that's right. But I like mastodon.social. thank you

**Comment by musicsd** [comment]
Is it possible for Mastodon to wait longer to upload the file? (Sorry I don't know much about the network)

**Comment by musicsd** [comment]
Could this problem be solved in the future?

**Comment by SuperSandro2000** [comment]
> Is it possible for Mastodon to wait longer to upload the file? (Sorry I don't know much about the network)

Possible yes but it makes ddosing the server easier cause you can keep many very slow connections open.
