### ISSUE TITLE
Use Nginx Proxy cache for media of other instance

### ISSUE THREAD

**Issue by Vibhigupta** [tootsuite/mastodon#14202]
Storing and cleaning media that is cached in the server from other instance takes alot of space and very inefficient way to handle media and it also increase the whole cost as it require more storage.

Using Nginx cache we won't be needing it to store in the server for longer period of time and cleaning it every once in a while and it's better and effective.

Pleroma does it this way and it's how other should also do.

**Comment by ThibG** [comment]
We can't *only* rely on something like proxying requests through a caching nginx, unlike Pleroma, because we are actually processing media files for a bunch of reasons, such as:
- provide them in a format/codec/size that is playable by the vast majority of browsers and devices on the market
- extract previews and one-frame versions of files
- compute a “blurhash” (a short string encoding a blurred version of the preview, used while loading the actual file, and when hiding sensitive media)

**Comment by Vibhigupta** [comment]
Well I see it more about experience but the cost is very high, considering the cost, the benefit isn't worth it.

Other instance encode video so it make sense to simply cache them. 

blurhash isn't helpful in anyway yeah its a bit fancy and looks good but isn't  useful in any way. 

Well I'm closing it anyway
