### ISSUE TITLE
support for monsterpit's new federation method?

### ISSUE THREAD

**Issue by SoniEx2** [tootsuite/mastodon#14353]
### Pitch

monsterpit has a new more-private federation method, and I'd like to see it supported.

### Motivation

monsterpit has a new more-private federation method, and it currently doesn't work with masto. it's good stuff and I wanna see it supported.

(there's probably already an issue for this but I couldn't find it.)

**Comment by dariusk** [comment]
I'll add more context. (I was not involved in the creation of this code or this fork but I was curious and looked into it.)

The code in question federates references to URIs rather than embedded statuses/content. The idea is that the receiving server is forced to fetch the URI on federation, which allows the originating server to respect blocks and simply not serve it up. This is the main commit:

https://monsterware.dev/monsterpit/monsterpit-mastodon/commit/b62511e61b34d2a94321f31b9cba11176c0a6ac8

This commit modifies the above, makes it turned off by default, and adds a user profile setting to turn on federate-by-reference:

https://monsterware.dev/monsterpit/monsterpit-mastodon/commit/857df3702e6b6a68aabe53393f95612d1d2c038f

**Comment by Gargron** [comment]
Boosts are always federated by reference, normal posts only go to servers you federate with, and public resources are behind authorization when secure mode is enabled.

**Comment by nightpool** [comment]
@gargron I think the idea of this ticket is that the inlining changes break Mastodon in some way, which seems like a bug? Given that they *should* be identical. We'd need more details on what exactly is broken though to start troubleshooting. 

I don't understand how this would help blocks though, since the server only has to fetch the post once for every user on the server. A better idea would be for them to deliver each post individually to user's inboxes, instead of using public inbox (although I'm just going by @dariusk's description, maybe there's some subtlety I'm missing)

**Comment by SoniEx2** [comment]
I am unsure but stuff wasn't federating until it got changed back. I am not an instance admin so I have no idea what's up. also the instance I use is on glitch-soc but - as we know - if glitch-soc doesn't handle it then neither does masto.

**Comment by dariusk** [comment]
It's possible I got this wrong! I was just going by what I could piece
together from the commits since I saw a lot of people making claims about
safety that I couldn't confirm or deny.

**Comment by Gargron** [comment]
Ah, I see, so this is about supporting Create with references on our end. Okay.

**Comment by SoniEx2** [comment]
aside: thank you darius and nightpool for helping out with describing the issue.

**Comment by ThibG** [comment]
More commits about this change:
- https://monsterware.dev/monsterpit/monsterpit-mastodon/commit/8b82dcfea9adb470511f7348a39e7c0acbe9517a
- https://monsterware.dev/monsterpit/monsterpit-mastodon/commit/e17ee1c4f00f6f82a3c874733c6a3ffe93e6cfd5

Basically the idea seem to be to fetch not on behalf of the server, but on behalf of a user likely to be allowed to see the post. To be honest, I am very unsure of the benefits of doing so (as you said, `Create`s are only sent to servers you are interested in anyway), and it could cause issues, for example, if you mention two people and the first one is blocked (ok that's really an edge case that I'm not sure is possible, as Monsterpit may not allow mentioning blocked people anyway).

In the end, I don't really like this scheme and I'm not sure it has any benefit, but I see no harm in implementing compatibility with it.
