### ISSUE TITLE
Remove the toot character limit entirely

### ISSUE THREAD

**Issue by fallerOfFalls** [tootsuite/mastodon#1446]
Why is there a character limit?

Surely there must be a better way of getting people to cut to the chase, or getting that "brief exchange" user experience than arbitrarily limiting the number of characters.

Toot length regulation should be a social issue; it shouldn't be the software that regulates how long your toots are. However it might be good to hide the bulk of toots that are longer than your screen (and perhaps indicate to the user that they are really going on and on and that most of their toot will be hidden. Soft limits are good.

And don't forget the [zero-one-infinity rule](https://en.wikipedia.org/wiki/Zero_one_infinity_rule):
> Zero-one-infinity is a design rule-of-thumb that is often ignored - usually to the detriment of the project.
> Simply stated: You will either need zero of a thing, one of a thing, or an arbitrary number of the thing.
> Programmers and architects ignore this at their own peril. Arbitrary fixed limits are a [CodeSmell](http://wiki.c2.com/?CodeSmell). --[WikiWikiWeb](http://wiki.c2.com/?ZeroOneInfinityRule)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by wxcafe** [comment]
Misclicked. Assigning @Gargron so he can explain what his reasoning is

**Comment by alexgleason** [comment]
Isn't this a constraint of GNU Social anyway?

**Comment by yiskah** [comment]
Mastodon is a micro-blogging platform. If there wasn't a character limit, it would just be a blogging platform. 

This would also be very easily abused, even with collapsible posts, as it it could affect server load.

An important design principle is that every post is roughly the same height, which creates a good UX. While some instances do modify their code to change the character limit, this is not officially supported because equality of service is one of the principles of how Mastodon decentralization is intended to work. Using one instance should be roughly the same as another when it comes to the software.

**Comment by wxcafe** [comment]
Thank you, marking this wontfix and closing then

**Comment by Shreewebs** [comment]
Can Someone guide on how to increase limit to 600 Please?

**Comment by Laurelai** [comment]
Edit the following files

app/javascript/mastodon/features/compose/components/compose_form.js
app/validators/status_length_validator.rb

**Comment by Shreewebs** [comment]
@Laurelai Thank you, I have already modified those files to 600 but no luck.

**Comment by Shreewebs** [comment]
Please assist!

**Comment by snowe2010** [comment]
@Shreewebs 	you have a typo somewhere.. run `git status` and make sure your changes are correct.
