### ISSUE TITLE
Revamp content warnings

### ISSUE THREAD

**Issue by Sasha-Sorokin** [tootsuite/mastodon#14519]
### Pitch

Currently, posters are in control of content warnings, this could have been a good approach if only it wasn't subjective to the poster what considered sensitive (with a little motivation from instance rules to mark NSFW content). Users on Mastodon hide way too much content many others won't consider sensitive.

This might sound controversial and radical, but let's remove the ability to mark your posts as sensitive. Not that we're removing all sensitive content functionality completely, but rather giving control of what users see back to the users themselves, not the authors. This effectively prevents all possible abuse and encourages people to tag posts accordingly instead.

How are we going to do this? By adding actions to the filters' functionality we already have, where one of the actions would be to treat post as sensitive. We'll also make two default filters that would do that action: when post contains `#nsfw` or `#spoiler(s)` hashtags, the posts will be treated as sensitive. Users will be able to remove these filters if they want to see these things uncovered in timelines, while being able to hide other things.

I've seen users marking many things as sensitive, but mostly it were: nudity, selfies, politics, ‘hot takes’, food and jokes. For jokes, default `#spoiler` hashtag could be fine. For other hashtags? Let's be welcoming and also introduce ‘templates’ UI, where we could suggest a few templates for users to use, which would include `#selfie`, `#food` and such (we really should get stats/feedback for that).

![Screenshot of two filters with names: “Spoilers” and “NSFW”. On the right there's a column with suggestions: “Quick templates for content you may not like” and list of 4 times: “Mark toots tagged #food as sensitive”, “Mark toots tagged #selfies as sensitive”, “Hide toots that are Twitter retweets”, “Hide toots from bots in public timelines”](https://user-images.githubusercontent.com/10401817/89453659-cd1de000-d789-11ea-8c74-ff467db32d3f.png)

For backward compatibility we may leave fields for sensitive content, but won't allow publishing new posts with these. To let users know of this functionality, in web UI <kbd>CW</kbd> toggle and checkbox (for media) can be left, but they won't do anything, but display warning message (warning means it has that red color and is bloody scary!) that to mark post as sensitive you can tag it with `#nsfw` or `#spoiler` (hashtags clickable) or put hashtags accordingly.

Finally, moderators will still be able to mark posts as sensitive as they see fit.

**But wait, hashtags are indexed and searchable!** The same applies to sensitive content currently, if you want hashtags to lose effect and your post to become unsearchable, you can use unlisted privacy level.

### Motivation 

Replacing ability to mark posts as sensitive will encourage users to tag posts accordingly, and prevents abuse in its current state (when users mark too many things as sensitive that your federated timeline experience with these posts becomes a guess game: one post will be tagged as something scary but will end up being totally fine, but the other post with no text at all will be a porn instead). It won't remove functionality completely, but rather give a powerful alternative instead.

### Blockers

- [ ] Add actions to the filters (untracked — **open issue / PR**)
  - Allows using actions such as hiding post softly, just hide or discard completely.
- [ ] Allow combining keywords under one filter (untracked — **open issue / PR**)
  - Makes it possible to combine multiple keywords under one filter, making templates more powerful by allowing regional variants (like `#food` ⇒ `#еда`). Filters will now have meaningful names!
- [ ] Add filter templates (untracked — **open issue / PR**)
  - Basic functionality to create filter templates (maybe even will be accessible to the users, one can dream).
- [ ] Add suggested filters (untracked — **open issue / PR**)
  - Eases *migration* for those, who rely on sensitive content by introducing filters described way above (like `#selfies`). Uses templates. Probably will be configurable by administrators.
- [ ] Add filters to filters (untracked — **open issue / PR**)
  - Allows hiding posts from bots via something like `~is:bot`, with nice bonuses too — `~domain:pixelfed.social` or `~mentions:*@baddomain.social`.
- [ ] Error when trying to post with CW (untracked — **open issue / PR**)
  - Will mark a deprecation of the feature.
- [ ] Web UI: Display warning when trying to add CW (untracked — **open issue / PR**)
  - Helps users to know of alternative.

**Comment by Miaourt** [comment]
I rather like it, I had the same thought a while ago, the difference here is that it also totally reworked the tags, replacing the "CW" field by a default present allowing to list the tags inside (without consuming the character limit of the post).
This coupled with a reactive real time suggestion could be very interesting (allowing to standardize hidden tags for example, at the instance level, which would indicate when sending the content which tags it considers locally sensitive).

it would also finally silence the whiners who can't bear to "hide" their violent or "normal" words for them, by simply imposing to tag them correctly >:3c

Concerning the "templates" you're talking about, at the interface level it could perhaps simply be checkboxes, with themes defined by the administrators, as well as pre-checked boxes according to the communities still up to the admins ?

**Comment by Gargron** [comment]
Look, I'm not personally a fan of how some folks decide to over-use content warnings which trivializes content warnings that are actually important, you end up developing the instinct to click *all* content warnings because people hide their cat's eye contact behind one but then once in a while it's something actually disturbing **but** I don't think your proposal is a good idea. Don't forget that the feature's most mainstream use is hiding *spoilers*. And no word filter in the world will be able to tell that a post is about One Punch Man Season 1 Episode 5 unless I explicitly write it myself.

**Comment by lawremipsum** [comment]
This encourages abuse by forcing people to make things searchable in order for them to be appropriately filtered, and so should not be implemented. It effectively is a mandatory opt-in to making content searchable. No, "you can make your post unlisted" is not an adequate response to this concern. This put a greater burden on people trying to avoid abuse, and moves in the exact opposite direction with regard to abuse than the platform should be headed.

Forcing people to tag posts by removing useful, valuable functionality because you want tagging to be the culture is user-hostile development.

**Comment by tekktonic** [comment]
Let me get this straight:
Instead of letting users write CWs because "too many people write CWs" instead you're just going to rely on them putting the same CWs in tags?I'm not seeing what the benefit is here. This is juts the equivalent of (if I'm understanding your proposal correctly) making CWs opened by default.

**Comment by renatolond** [comment]
I also like to add that I really like the current system because it's not language based. Mastodon in this sense is language agnostic: I can CW my posts with whatever language I'm writing the post in (or more than one, if I'm targeting multiple audiences). Adding "default" CWs as `#NSFW` and `#spoilers` is very english centered.

On a larger sense: There's already options for automatically unrolling CWs in the Web UI, it could be improved by not unrolling based on a couple of filters, or something of sorts. I don't think removing CWs bring any advantage, it's a very valuable feature.

**Comment by ShadowJonathan** [comment]
This would remove a feature that makes mastodon bearable over twitter, and reduce it to something that takes away control from the poster, and muddles it for the reader.

**Comment by clarjon1** [comment]
Why does this need to *replace* CWs? 

This looks like it would complement the existing tagging feature, personally, allowing for better control of managing what topics you're following. You could easily keep subjects/CWs, have this alongside so you can filter various topics, and be able to keep the CWs to deal with more sensitive subtopics within those main tagged topics.

Instead of looking to remove/replace functionality, perhaps this might be much better to be looked at as a way to give MORE power and options to the end user, depending on their needs?

**Comment by ShadowJonathan** [comment]
One rather more pragmatic approach would be to apply this system on *top* of the current poster-CW system, where an individual can create lists of keywords that'd auto-CW posts if it contains one of them, with a generic warning CW of "this post contains keywords from X" (in some sort of italics fashion, maybe also underneath existing CWs to provide a "second opinion")
 
It'd widen the area of effect for CWs, and allows the reader more control over their timeline.

**Comment by tekktonic** [comment]
@ShadowJonathan As I understand it at least one mastodon instance already has this, although I can't remember which (auto-add CWs based on filter words the receiver has configured.)

**Comment by emceeaich** [comment]
The current CW system is fine, and I'm not at all comfortable with the requirements your proposal adds to people on the Fediverse. 

Let's trust users to know best how to use CWs and encourage them instead of talking down to people who use them the way you think they should be used.

**Comment by melissaboiko** [comment]
Instead of doing this, allow hashtags to be used in content warning descriptors (#699 ). This is a much more elegant way of solving the duplication of functionality between hashtags and CWs (namely that both are meta keywords describing content) while *giving* power to posters, rather than removing (cause you can choose to hashtag or not).

**Comment by BalooUriza** [comment]
> This would remove a feature that makes mastodon bearable over twitter, and reduce it to something that takes away control from the poster, and muddles it for the reader.

I can't help but to think this is actually the intention.  Really seems like a feature that only the "you not listening to me is an infringement of my freedumbs of speech" crowd could love.

**Comment by SilverWolf32** [comment]
I would also like to come in here and say, **_please, don't do this._**

CWs are one of the things that make Mastodon better than... well, basically anything else out there.

And this makes it so I _can't warn people what's coming_. Really bad mental health post? Sorry, _have to tag it_.

**Comment by daveross** [comment]
The current system's flexibility is an advantage. It allows authors to quickly adapt to their followers' needs, like how I started seeing posts CWed for "covid-19" almost overnight. It also allows for more nuance than general tags like #nsfw provide, because there's a big difference between "visible nipple" and...er, use your own imagination.

**Comment by hmmmmmmm** [comment]
I've not contributed to Mastodon at all but as a frequent user, the custom CW feature is one of the main things that brought me over to Mastodon from twitter. Replacing it with simple tags is way too inflexible compared to what exists now, and I think even allowing tags to be used in CWs as they are opens up way more potential for search-based harassment as happens on twitter at the moment.

**Comment by SilverWolf32** [comment]
CWs even _already provide_ some filtering capability. People tend to generally use the same language in CWs, things like "mh" or "USpol", which makes filtering easier than without the CW field.

**Comment by hmmmmmmm** [comment]
> Users on Mastodon hide way too much content many others won't consider sensitive.

And is that really a problem? If they feel it's sensitive, it's up to them to mark it as such as they see fit - reducing people's ability to mark sensitive content is only a bad thing.

**Comment by SilverWolf32** [comment]
> Users on Mastodon hide way too much content many others won't consider sensitive.

Seconding this not being a bad thing. Also, sometimes your followers can have different CW needs than the rest of Mastodon. I like being able to CW _things that trigger my friends_.

**Comment by LunarLambda** [comment]
> Users on Mastodon hide way too much content many others won't consider sensitive.

This is not a bad thing. I don't understand why this is even up for debate. The ability to hide or filter content is precisely what allows me and many others to use Mastodon without it being an excessively stressful experience. Please stop trying to take people's boundaries away.

**Comment by ThibG** [comment]
I just wanted to add a few notes, as in glitch-soc, we partially address this (but it's not super streamlined and could be improved some more), by:
- having a setting to auto-expand CWs *unless they match a specific regexp* (the regexp approach was chosen for more flexibility, allowing to, for instance, not auto-expand stuff like CWs starting with a “%”, as some people adopted that as a convention for negative content)
- having a setting to not hide filtered posts with a “Filtered” placeholder but dynamically add a CW with the matched words
