### ISSUE TITLE
Crash streaming server when received invalid json

### ISSUE THREAD

**Issue by mfmfuyu** [tootsuite/mastodon#14858]
Crash streaming server when received invalid json.
I'm currentry working fix this issue, I submit PR ASAP.

### Expected behaviour

~Streaming server returns error without crash.~
Streaming server is ignore invalid message

### Actual behaviour

Streaming server is crashed.

### Steps to reproduce the problem

Send invalid json to streaming server

### Specifications

8f630552d

**Comment by noellabo** [comment]
This issue also occurred on my server and later turned out to be due to a bug in TheDesk. It has already been fixed.
https://github.com/cutls/TheDesk/issues/353

Since the streaming server crashes every time, the streaming of the user in use is disconnected, which greatly impairs the user experience.
