### ISSUE TITLE
Length validation error when searching for certain accounts

### ISSUE THREAD

**Issue by umonaca** [tootsuite/mastodon#15025]
### Expected behaviour

The search should return a normal result showing the target account.

### Actual behaviour

When searching for board@gup.pe, it shows 422 Mastodon::LengthValidationError.

### Steps to reproduce the problem

1. On mastodon.social open the search bar on web page.
2. Type in board@gup.pe and enter.
3. Wait a few seconds. Then it will show this error.

### Specifications

Tested on mastodon.social and other instances running latest version of Mastodon on master branch.

**Comment by ThibG** [comment]
This happens when fetching the account's `outbox` (to know the number of posted messages), which is nearly 3MB, while Mastodon refuses anything more than 1MB.

Instead of erroring out, Mastodon should probably consider it cannot know the number of posts.

(And Guppe should probably implement some pagination instead of returning all the items at once)
