### ISSUE TITLE
Upgrade to v3.2.1 results in "The single-table inheritance mechanism failed to locate the subclass: 'follow'."

### ISSUE THREAD

**Issue by xmflsct** [tootsuite/mastodon#15030]
After upgrading to `v.3.2.1`, I cannot access notifications. And the log shows below:

```
ActiveRecord::SubclassNotFound (The single-table inheritance mechanism failed to locate the subclass: 'follow'. This error is raised because the column 'type' is reserved for storing the class in case of inheritance. Please rename this column if you didn't intend it to be used for storing the inheritance class or overwrite Notification.inheritance_column to use another column for that information.)
```

**Comment by Gargron** [comment]
Is there a chance you upgraded to master instead of v3.2.1 somehow? The type column has been added to the notifications table in master only, and the stable-3.2 branch does not, as far as I can tell, erroneously contain any database migrations that would add it.

If you were on master before and then switched to v3.2.1, you *downgraded* and I suggest switching back.

**Comment by xmflsct** [comment]
@Gargron That could probably be. Since I am building it on Raspberry Pi, I remember during one of the building process, I wrongly build the master image.

How can I downgrade my database? I tried `db:migrate` but doesn't help.

**Comment by Gargron** [comment]
You shouldn't downgrade at this point, it is less risky to just go back to the master branch.

**Comment by xmflsct** [comment]
@Gargron Sounds good, thank you!
