### ISSUE TITLE
Disable unread notification marker

### ISSUE THREAD

**Issue by trwnh** [tootsuite/mastodon#15133]
mastodon.social latest master

The new unread notification marker seems unnecessary at best and buggy at worst. Since its introduction, I have to refresh the page to get it to go away, when I'd rather just not have it in the first place.

**Comment by ThibG** [comment]
> The new unread notification marker seems unnecessary at best and buggy at worst.

The rules for when the markers are cleared may not be the best or completely intuitive to everyone, but I don't think the current implementation is actually buggy.

Plenty of people find it useful, but a non-negligible amount of people do seem to find it confusing or unnecessary too, so that could make sense as an optional feature, indeed.

> I have to refresh the page to get it to go away

A less bothersome alternative to this should be clicking the checkmark in the column header.

**Comment by Gargron** [comment]
I think the behaviour improved significantly in single-column mode but in multi-column mode it is indeed still annoying that while my notifications column is mounted and my page is in focus it still marks stuff as unread. Also, didn't we want to change the style to be a line marker like in Discord? Is there a blocker for that?

**Comment by ThibG** [comment]
> […] it is indeed still annoying that while my notifications column is mounted and my page is in focus it still marks stuff as unread.

That's how I expect it to work, to be honest: having the notification column mounted doesn't mean I have my eyes on it at all times and cannot lose track of what I've seen and what I haven't.

> Also, didn't we want to change the style to be a line marker like in Discord? Is there a blocker for that?

We did not. We discussed doing it, but haven't done it yet. There is no blocker I am aware of, it's just more work that isn't completely obvious.
