### ISSUE TITLE
how to get rid of @domain?

### ISSUE THREAD

**Issue by jakesullyneytiri** [tootsuite/mastodon#15419]
Hi,

i recently installed mastodon and every user who signs up get's following name format @username@domain.com.

How do i get rid of so it won't add @domain.com to end of name? so the username are just @username and not @username@domain.com for example i wan't it to be @test1 and not @test1@test,com.

It looks very ugly with it showing @test1@test.com under every username.

I have gone through settings and cannot find anything there that leads to this problem!

so i hope this is a easy fix to get rid off.

/Thank You

**Comment by Gargron** [comment]
It is not possible. This is your identification in the network. It is how other people know how to mention you, or find you through search, and it is how your users remember where they can login into their account. When you give someone your e-mail address, you don't just say "e-mail me at jakesullyneytiri". They'd ask you "at what?" because there are so many possibilities.

For everyone's convenience, in the formatted posts, the domain part is hidden in a tooltip.

**Comment by jakesullyneytiri** [comment]
But on every profile it shows which is very ugly.

That's why I would want it removed. So only user itself can see it but not everyone else

**Comment by inga-lovinde** [comment]
> So if I view my profile it can show @test@test.com but when some one else views my profile I want it to show @test and not @test@test.com

But it's really like your email address. You wouldn't want other users to see your email address as "test", you would want them to see "test@gmail.com", otherwise how would they know where to send you messages?

**Comment by jakesullyneytiri** [comment]
> > So if I view my profile it can show @test@test.com but when some one else views my profile I want it to show @test and not @test@test.com
> 
> But it's really like your email address. You wouldn't want other users to see your email address as "test", you would want them to see "test@gmail.com", otherwise how would they know where to send you messages?

Doesn't make sense, on twitter you don't have @test@test.com there you have @username only and looks alot better

**Comment by inga-lovinde** [comment]
> on twitter you don't have @test@test.com there you have @username only

Because twitter is centralized and mastodon is decentralized; so username alone is enough to identify an user on Twitter, but it is not enough to identify an user on Mastodon, because there could be different users on different instances with the same username.

And you're not saying "I'm @username", you're saying "I'm @username on Twitter".
