### ISSUE TITLE
Display of private messages no longer works properly since v3.3.0

### ISSUE THREAD

**Issue by MaiaDereva** [tootsuite/mastodon#15464]
Hello,
my instance has recently been upgraded to v3.3.0, and I notice a very strong regression on the display of private messages in my Firefox 83.0 web browser: the background colour is no longer distinguishable from other messages and the messages appear in the "Home" column. This ergonomic defect can lead to serious confusion regarding privacy. Is it possible to return to the previous interface?
Thank you for your help :)

**Comment by GuyM-31** [comment]
I agreed
Je suis d'accord

**Comment by Gargron** [comment]
Hi, it's not a bug, it's intentional. Our implementation of direct messages has always been at odds with the user experience of DMs from Twitter or Discord (because visibility can be changed within a thread and threads can be interrupted). The attempt to create a more Twitter-like conversations view has run into many limitations because of this. So we are returning to old UX. Our "DMs" are more like follower-only posts, and I plan to rename "Direct" visibility into "Mentioned-only" to further solidify this.

If/when end-to-end encrypted messages are finalized, they will be closer to what people expect from DMs.

**Comment by MaiaDereva** [comment]
Good evening, I understand your explanations, but as it stands, without real private messages clearly identifiable, the interface becomes unusable. It's really a pity (and I'm not on Mastodon to find a behaviour similar to Twitter, or else, it would take a real box of DMs completely apart as we find it on TW).

**Comment by Gargron** [comment]
> without real private messages clearly identifiable

There is a consistent visibility indicator on all posts now:

|Mentioned-only|Public|
|----|----|
|![grafik](https://user-images.githubusercontent.com/184731/103319585-9c895c00-4a32-11eb-91f2-db831d6ee20a.png)|![grafik](https://user-images.githubusercontent.com/184731/103319602-a4490080-4a32-11eb-9050-5acd1feeb015.png)|

**Comment by MaiaDereva** [comment]
OK, I really understand your reasoning, but:
- this is not "consistent", it's really easy to make a mistake and have privacy accidents
- for current users (I've been using Mastodon since 2017), it would have been really more comfortable to wait for the release of a real DM system before doing this regression. I'll manage with Stylus, but 
- for an uninformed user, it's even more confusing when you discover Mastodon. 
Thank you for your answer in any case :)

**Comment by Gargron** [comment]
> for an uninformed user, it's even more confusing when you discover Mastodon

It would be vastly preferable if it led to new users using "DMs" less or avoiding mistakes that come from assuming that the system works the same way as on Twitter. Common mistakes include: tagging someone in a DM thereby making them receive it without realizing that it's going to happen; tagging someone in a DM expecting them to be able to see the whole conversation like joining a group chat; and for some reason people assume these chat-like conversations are end-to-end encrypted even though that's not a case on Twitter, Discord, or even Telegram, and only true on Whatsapp and Signal.

**Comment by MaiaDereva** [comment]
I fully agree with the initial analysis (this message system has not been ergonomic from the start) but in the absence of a real private message system, this regression makes Mastodon clearly uninteresting. Half of my activity on this social network consists of private exchanges. You can't "decide" in the users' place that this feature is not useful nor "led them using "DMs" less".
So, in my view, the analysis is correct, but the solution chosen is inadequate.
The previous version was certainly a worst-case scenario, but as long as there is no truly private mailbox, it remains important as a trick to have some semblance of functionality.
Besides, if they are not DMs, why keep this status ? For what use ? Can you give me an example ?

**Comment by MaiaDereva** [comment]
Anyway, as you said, there will be no further question "when end-to-end encrypted messages are finalized" in a separate box :slightly_smiling_face:

**Comment by dariusk** [comment]
I'm receiving complaints from panicked users about this very thing. Basically, they are seeing DMs show up 1) in their home timeline and 2) with no demarcation except for an easily missed icon, and they get a minor panic attack that they posted with the wrong permissions. As one of my users put it, there needs to be a very clear demarcation between private and public messages. I agree with the above statement that it would have made sense to hold off until implementation of e2e encrypted messages.

**Comment by Gargron** [comment]
It's a change of existing behaviour, and those always cause problems for old users. I sympathize with that.  We try to avoid it as much as possible. I just think that going forward this change makes more sense because Mastodon's post visibility system is gradual (from public to followers-only, specific-followers-only, mentioned-only ["direct"]) and it's a *post* visibility system and does not map cleanly to instant messaging and so it was always jarring that only one of the "private" visibility settings got a special background color. Now all of them have the same look: disabled boost button, visibility indicator.

I wonder if we could maybe improve the situation by moving the visibility indicator to another line, where it would either spell out "Visible to all" or "Visible to your followers", or "Visibile to x, y, and z" when it's direct. I think facebook had that? Twitter's who-can-reply also looks like that.

**Comment by MaiaDereva** [comment]
> it's a _post_ visibility system

In that case, maybe an easy solution would be to add different background colors in addition to the icons?
Instead of deleting the mentioned-only messages color, adding a slightly different one to the other types of messages would make it easy to visualise the different levels of visibility? Colour is much easier to spot than a small image or text alone... I would find it very coherent to better differentiate public messages from followers-only messages for example (after all, we can innovate compared to Twitter ;) )

By the way, I still don't understand the difference you make between specific-followers-only and mentioned-only (I don't see which icons and/or use this corresponds to). Could you show a specific use?

**Comment by Gargron** [comment]
> By the way, I still don't understand the difference you make between specific-followers-only and mentioned-only (I don't see which icons and/or use this corresponds to). Could you show a specific use?

That's the "circle" functionality that's still not finalized, some platforms already send messages to subsets of their followers, and Mastodon supports correctly displaying such messages to intended recipients, but does not yet support creating such messages (see #14666, #14384, #14370). The difference to followers-only is that it's not all followers, and the difference to mentioned-only is that you don't have to manually mention every recipient every time, you just send a post to "co-workers", or "tier 3 subs" or whatever. Another difference to mentioned-only is, since it's not based on direct mentions, such posts don't pop up in notifications, they appear normally on the home feed.

**Comment by lapineige** [comment]
>  Colour is much easier to spot than a small image or text alone... 

I totally agree on that point, it's good to have the icons here, as it fix the regression caused by the change made to the boost icon (before it was easy to spot that a message was a private or direct message, as there were a big lock/mail icon, the removal of that icon made it much more difficult and frustrating to spot what is what). But it's a very small icon that makes it way harder/longer to spot the difference, and way easier to think this is not a mentioned-only message (in particular for users accustomed to the old behavior)… Hence to make mistakes when replying (or doing a screenshot).
The integration of mentioned-only messages in the main TL makes that situation even more confusing :/
If another solution doesn't emerge, could the DM stay excluded from the main TL to keep them a bit separate from the rest, thus giving users an additional context about these toots that would make it clearer that they don't have the same visibility level ?

Also I don't understand why this change is made now (after 4 years with the previous behaviors) while an alternative solution is not ready, because to me it feels like it's breaking that feature (as it's really hard to tell it's a DM, and will increase the number of mistakes), yet without removing it, hence a 4-years old main feature is kind-of removed and there is no alternative :(

**Comment by MaiaDereva** [comment]
> That's the "circle" functionality

Thank you very much for the explanation, it's a very good news the future arrival of these circles :)
