### ISSUE TITLE
Account migration is not working in 3.3.0

### ISSUE THREAD

**Issue by chofstede** [tootsuite/mastodon#15462]
### Expected behaviour

I created an account alias on the **new** server and verified it
I tried to move the account on the **old** server and recieved the error message:

The account and it's followers should move to the new server

### Actual behaviour

Error Message:
`Something isn't quite right yet! Please review the error below
is not an alias of this account
`

### Steps to reproduce the problem

Tried in all different variants on account alias and in username-casing. Always the same issue

### Specifications

v3.3.0 on the **new** server
v3.3.0 on the **old** server

**Comment by ThibG** [comment]
Is there no other error displayed?

**Comment by chofstede** [comment]
> Is there no other error displayed?
> 
> EDIT: ah, I missed the “is not an alias of this account”
> 
> This may happen because the account is cached for up to 24h, please retry later.

Thank you. After waiting a day, it actually worked :-) Would be great to add a hint to the frontend when creating an account alias.

**Comment by jh97uk** [comment]
From a UX perspective, might it be worth noting this in the error? Or having some sort of icon to hover over to get more information for situations like this?

**Comment by DanielGibson** [comment]
The error message definitely should mention this, being told that the new account is not an alias, when the preferences of the new account clearly say that it *is* an alias, is very confusing and lets the user believe that there's something actively broken (leading to support requests to instance admins), when in reality the user just has to wait for up to 24h.

Also, I'm not familiar with the implementation details at all (to me it's not even clear which server has the outdated cache - the old or the new one?), but would it be possible to invalidate that cache when setting an alias (if it's cached on the new one) or trying to move the account (if it's cached on the old server)?

**Comment by Krinkle** [comment]
I've described a workaround at https://github.com/mastodon/mastodon/issues/19366.

The cache bug is fixed in https://github.com/mastodon/mastodon/pull/18429.

**Comment by ClearlyClaire** [comment]
> Also, I'm not familiar with the implementation details at all (to me it's not even clear which server has the outdated cache - the old or the new one?),

What would typically matter is *everyone's* cache of the new account (typically cached for up to 24h, but in Mastodon's case, a migration should trigger a cache refresh either way; the last PR to address that is #18429). Another cache that can matter is the new account's cache on the new server's remote proxy, which typically can last for up to 3 minutes.

**Comment by velw** [comment]
> I've described a workaround at #19366.
> 
> The cache bug is fixed in #18429.

The workaround described here doesn't work reliably. I just tried it over 12 hours after setting up the alias, and it didn't work.

That the cache bug is fixed is great, but that there is absolutely no mention of an up to 24-hour delay after applying the alias before many users will be able to migrate their account is very unhelpful. Most users are on servers running versions of the software installed before the fix. 

Aside from the time people are spending trying to fix a problem that is already a known and patched issue, if I had known about the delay I would have waited 24 hours after setting up the alias before telling all my followers I was moving account and trying to transfer. With the migration process also taking time, the current situation makes the whole process take 36 or 48 hours before it is complete — which is still a vast improvement on not being able to move servers, but for anyone trying to maintain use of their account through the process it's a major inconvenience, most of which could be avoided by simply adding this information to the documents or the interface.

Through its communication channels Mastodon is citing the ability to move servers easily as a major selling point for the platform, and stating that it's straightforward and relatively quick, involving only four steps. That doesn't match the reality — largely because this important information about the delay in propagation of the alias has been long known but is still not being communicated.

There's a really simple fix here that could save users and server admins time, effort and frustration, and it's hard to understand why it's not been done.
