### ISSUE TITLE
Hidden services could use re-work

### ISSUE THREAD

**Issue by stayinside** [tootsuite/mastodon#15501]
Mastodon's current implementation of hidden services makes for a clunky and unintuitive experience.

As it stands, logging in, clicking away from the main feed, and opening local users in a new window all redirect to either ssl+hidden-service domain, or the clearnet domain. For users of the hidden service this experience causes confusion, and potential mistrust or the hosted instance. Likewise it prevents users of mobile apps with a Tor VPN from using a hidden service domain as their main domain.

Apologies if this is as simple as fixing the nginx docs but its seems that it needs to be resolved within mastodons code itself

**Comment by psjbeisler** [comment]
i was beating away at this today and couldnt figure it out either, it shouldnt be that hard.

**Comment by cohosh** [comment]
It's definitely not only an nginx configuration issue (though there are some further necessary changes to the nginx config to get it working correctly, one of which is discussed in https://github.com/tootsuite/mastodon/pull/15498).

I'd be wary of using search and replace style rewrites using nginx to fix this problem.

Ultimately, it's caused by multiple layers of defaults and HTTPS redirects that are in place to ensure that all content is securely transferred over TLS. This is important for clearnet access of the site, but causes a lot of problems with instances that are also run as onion services. I'm going to list the ones that I've come across while poking through the code, but it might not be exhaustive.

## Some causes of problems with onion services

### Forced redirect to SSL for all requests

The rails command `force_ssl`, set in https://github.com/tootsuite/mastodon/blob/master/app/controllers/application_controller.rb#L8 uses several different methods to ensure all accessess are done over HTTPS. This calls a `force_ssl_redirect` function which just redirects the request to the same URL but with https according to the [documentation](https://apidock.com/rails/ActionController/ForceSSL/force_ssl_redirect) 

### Secure cookies

There are a few places in the code where the [secure flag](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#restrict_access_to_cookies) on cookies is set to true. This is supposed to prevent a user's browser from sending the cookie back to the server over an unencrypted connection. Tor Browser [is supposed to treat .onion domains as a trusted origin](https://bugzilla.mozilla.org/show_bug.cgi?id=1633015) so the issues this is causing is on the server side.

I haven't looked how rails handles this under the hood, but I also noticed that the server isn't sending these cookies over an unencrypted connection either. These cookies are necessary to verify that a user has signed in, so if a user is only allowed to access the onion service over plaintext it essentially prevents them from using the site.

### Absolute links are set to the clearnet by default

In rails, there appear to be options to make links either relative or absolute. There are many cases in which absolute links are essential. Mastodon makes pretty heavy use of absolute links, I'm not in a position to judge whether a relative link would suffice. There's a configuration line at https://github.com/tootsuite/mastodon/blob/master/config/initializers/1_hosts.rb#L20 that sets absolute links to always be the clearnet site over https. This is what's causing the mixing between onion service and clearnet versions of the site. These default url options are also setting the domain. I'm not actually sure whether we want to change this.

## Where to go from here?

I would be wary of removing too many of these layers of security without ensuring that all clearnet content will be sent securely over TLS. Anecdotally, I tried disabling each of these features in a way where I *thought* the site would respond to all HTTPS requests in kind with an HTTPS response (relying on the nginx config to redirect HTTP requests to the clearnet domain to HTTPS). But, I kept getting mixed insecure content warnings because things like images were being sent over plaintext on the clearnet site.

I was able to write some patches to get things working minimally for a test instance run on both an https clearnet site and an onion site: https://github.com/tootsuite/mastodon/compare/master...cohosh:issue/15501

This is patch is only to demonstrate where the issues are. **This work is not done !!** There are some outsanding problems that need to be solved:

- The secure flag on cookies has been completely removed. We need to set this for clearnet versions of the site. It might also be a good idea to have `force_ssl` set for the clearnet site as well just to be safe. Perhaps we could add an additional configuration option to set the onion service domain and then do a check for the request host, and only disable these features if they match the onion service domain?

- Users will occasionally still get booted from the onion site to the clearnet site because of the absolute path problem mentioned above. This might be fine, especially if the instance operator has set the [Onion-Location](https://community.torproject.org/onion-services/advanced/onion-location/) header. 

- Assets like images are loaded with the clearnet version of the site in the background without the user's knowledge. This should be fixed, redirects to the clearnet domain should be visible to the user.

- This site seems to have quite a few edge cases. It's possible I haven't tested this extensively enough.

Also: I am not a web application developer. And this is the first time I have ever tried to modify an application that uses Rails. So, I'd appreciate some feedback on this.

**Comment by psjbeisler** [comment]
https://riseup.net/hi/security/network-security/tor/onionservices-best-practices#onion-services-and-rails-4

**Comment by cohosh** [comment]
Nice find! I followed the instructions there (with a slight modification to disable overwriting the content security policy header) and it's working as expected. Cookies have the secure flag set over https://clearnet_domain and it's not set over http://onion_domain :)

I added the patch to the branch linked above. Here's the commit: https://github.com/tootsuite/mastodon/commit/f5b4b39137e58f4b64fcc143d714813ad7e31051

**Comment by cohosh** [comment]
Woo, okay. At this point, it looks like everything is loading as it should over https for the clearnet site and over http for the onion service. There's still the issue where the onion service ends up booting the user back to the clearnet site, and where resources are being loaded over the clearnet site in the background, but at least everything is using TLS if and only if it should be.

Since this state is strictly better than the current state, I might just open a pull request with what we have.

**Comment by psjbeisler** [comment]
also there are extra headers to add the address bar redirect, for documentation if nothing else
https://community.torproject.org/onion-services/advanced/onion-location/

**Comment by stayinside** [comment]
Seems there is another PR attempting to do the same thing https://github.com/tootsuite/mastodon/pull/15666

**Comment by psjbeisler** [comment]
I just pulled v3.40 and onions finally work!

**Comment by stayinside** [comment]
> I just pulled v3.4.0 and onions finally work!

Me also! Will close this issue. Thanks for doing this everyone :)
