### ISSUE TITLE
lbry.tv Thumbnail Support

### ISSUE THREAD

**Issue by JonBoyleCoding** [tootsuite/mastodon#15566]
### Expected behaviour

When a user pasted a link to a lbry.tv video, a thumbnail/video link appears with full video thumbnail, similar to youtube.
### Actual behaviour

![image](https://user-images.githubusercontent.com/630329/104856167-e3b78e00-5908-11eb-8afa-49040c35be31.png)
Post and video details blurred out, but as you can see, the embedded player loads with no thumbnail. The video is playable so it partially gets the information.

### Steps to reproduce the problem

Posting a lbry.tv video in a toot.

### Specifications

Mastodon v3.1.3. Noticed in chromium based browser on Windows and Linux. I'm not the owner of the instance, so I have no further version details.

**Comment by Mennaruuk** [comment]
Interesting. I'm using Firefox, I grabbed this screenshot of a lbry.tv video, and thumbnail shows. Instance is mastodon.social (v3.3.0rc2). I'm guessing this is due to an older Mastodon release?

![lbry](https://user-images.githubusercontent.com/52135169/106395685-8ffd7800-63d1-11eb-82fb-e4ec871253fb.jpg)

**Comment by JonBoyleCoding** [comment]
If that's the case, then I presume there's actually no need for this issue anymore, so I'm closing it. Thanks for your response @Mennaruuk !
