### ISSUE TITLE
Wrong default language in settings

### ISSUE THREAD

**Issue by SansPseudoFix** [tootsuite/mastodon#1558]
My instance is configured like this: first, browser language auto-detection, next ``fr``, but in my ``/settings/preferences``, language is set to english (so, basically, if I'm changing anything and press ``Save``, my interface use english).
My browser is using Fr locales.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by yookoala** [comment]
I encountered similar situation in my instance. The preferences page **sometimes** do not follow my language site preferences.

* I set the preference to English my browser
* The Accepted-Languages in my browser has "zh" before "en"

When entering the preference page, the page sometimes display as Simplified Chinese instead of English. Strangely, the page is correctly showing that my prefered language is English. When this occur, if I press the "Save" button in this page, the page can then display English normally.

There is something wrong about the RoR language preference detection.
