### ISSUE TITLE
An account migration request may be processed repeatedly

### ISSUE THREAD

**Issue by project-concerto** [tootsuite/mastodon#15595]
### Expected behaviour

A user may send the same account migration request for several times, but the account should be migrated only once.

### Actual behaviour

Because there is no RedisLock or transaction provided for account migration, two same request may both pass validation in [account_migration#validate_target_account](https://github.com/tootsuite/mastodon/blob/69763b6385250902fdb329d030457159976f70ed/app/models/account_migration.rb#L70), which would cause repeatable account migration.

### Steps to reproduce the problem

1. Add sleep(5) after [account_migration#validate_target_account](https://github.com/tootsuite/mastodon/blob/69763b6385250902fdb329d030457159976f70ed/app/models/account_migration.rb#L72) as shown below:
```ruby
def validate_target_account
    if target_account.nil?
      errors.add(:acct, I18n.t('migrations.errors.not_found'))
    else
      errors.add(:acct, I18n.t('migrations.errors.missing_also_known_as')) unless target_account.also_known_as.include?(ActivityPub::TagManager.instance.uri_for(account))
      errors.add(:acct, I18n.t('migrations.errors.already_moved')) if account.moved_to_account_id.present? && account.moved_to_account_id == target_account.id
      errors.add(:acct, I18n.t('migrations.errors.move_to_self')) if account.id == target_account.id
    end
    sleep(5)
end
```
2. Let a user send two same account migration request continuously
3. Both two requests passed the validation and the account was migrated twice 

### Specifications

commit hash->49eb4d4ddf61e25c5aaab89aa630ddd3c7f3c23d

**Comment by ThibG** [comment]
Trying to understand the implications of this issue: a local user can issue two simultaneous migrations to two different accounts, and there is some slight chance a race condition would occur, triggering the `MoveService` for both migrations. In this case, the local server will issue two different `Move` activities and how they are handled by remote parties is undefined. The two `MoveWorker` may then run concurrently, in which case the original account local followers might get split across the two accounts, or in some cases, duplicated to the two accounts.

So this can't happen by accident, but it could be used by an “attacker” to try and get people to follow two accounts instead of one, albeit with extremely low probability of success.

It seems there is a similar issue in processing remote `Move`, in that we do set a Redis value but don't atomically check on it.

I will try to fix both issues.
