### ISSUE TITLE
Content-Warning isn't sanitized the same way as toot's content

### ISSUE THREAD

**Issue by NicolasConstant** [tootsuite/mastodon#15608]
When adding a `<img` tag in CW, it will not be be sanitized as the documentation [state](https://docs.joinmastodon.org/spec/activitypub/#sanitization). 

### Expected behaviour

CW content should be sanitized the same way as toot's content. 

### Actual behaviour

CW content isn't sanitized the same way out of the API: 

![image](https://user-images.githubusercontent.com/5437247/105258713-57030f00-5b58-11eb-817b-af95d118e61f.png)

### Steps to reproduce the problem

1. enter an image html in both CW and status content like `<img src="https://miro.medium.com/max/1200/1*mk1-6aYaf_Bes1E3Imhc0A.jpeg"> `
2. submit it
3. when looking to the API outputs the format aren't the same

### Specifications

Seen on Mastodon 3.1.5

**Comment by nightpool** [comment]
This is because CWs are strings, not HTML, and should be escaped entirely,
not sanitized, before being inserted into the DOM. Additionally, the page
you linked is talking about incoming ActivityPub posts. But you can
reproduce this just by typing <img> into the CW field, so the documentation
you linked is unrelated

**Comment by NicolasConstant** [comment]
Ok thanks, just wanted to make sure.
