### ISSUE TITLE
Change CDN_HOST not work for Mobile App and remote instance

### ISSUE THREAD

**Issue by OmmyZhang** [tootsuite/mastodon#15706]
After I changed CDN_HOST, apps(It's strange, I thought apps and web use the same API) and other instance still try to use the old one for images in statuses, which causes error.
I have tried reload,restart and precompile, as well as clear storage of my mobile app.
 
Just removing CDN_HOST works fine, but changing doesn't.

That's what happened:
`CDN_HOST=static1.example.com`  => apps use static1.example.com
↓
`CDN_HOST=static2.example.com`  => apps use static1.example.com
↓
`#CDN_HOST=static2.example.com`  => apps use example.com
↓
`CDN_HOST=static2.example.com`  => apps use static1.example.com

**Comment by OmmyZhang** [comment]
Update:
 I have try to get statuses with the same url and token the mobile app used, and get statuses with right media url. So, maybe it's not the problem of backend.
But I still wonder how to solve the problem of remote instance. `grep` told me there's not string `static1.example.com` user `~/live`, very strange..

**Comment by ClearlyClaire** [comment]
Changing `CDN_HOST` changes how assets/media URLs are built.

This retroactively affects how your instance renders toots, accounts etc., but remote instances and mobile apps usually hold on the version they first retrieved. There is no real mechanism to update copies of already-fetched objects, except re-fetching them, which most software usually do not do (because that is expensive for everyone).

So, if you change `CDN_HOST`, it will affect new content correctly, but for older content this will depend on when remote instances and mobile apps fetch the content.

Your best bet, if you change `CDN_HOST`, is to also set a redirection so that “outdated” copies of older toots/accounts/etc. aren't broken.

**Comment by OmmyZhang** [comment]
Thanks for your response, but the new content also uses the wrong URL for media and user avatar (otherwise I will not think it's a bug).

This problem disappeared after I stop use Cloudflare as CDN for API (i.e., `example.com`). I will close this issue as I believe this problem is not related to Mastodon. Sorry for bothering you.

(Although I still don't understand why using cf will affect the media URL, which is part of the API result. API result shouldn't be cached, and even cached, new statuses shouldn't use the old CDN_HOST. So strange...
