### ISSUE TITLE
[Security] Default nginx config: gzip should not be used in SSL

### ISSUE THREAD

**Issue by umonaca** [tootsuite/mastodon#15839]
This file
https://github.com/tootsuite/mastodon/blob/main/dist/nginx.conf
uses gzip together with SSL. However, It is said that using compression with SSL opens up to vulnerabilities like BREACH, CRIME, or other chosen plain-text attacks.

**Comment by umonaca** [comment]
Anyone reading this issue?

**Comment by Gargron** [comment]
> However, It is said that using compression with SSL opens up to vulnerabilities like BREACH, CRIME, or other chosen plain-text attacks.

Do you have a source for that? It sounds a little outlandish. Platforms like Cloudflare deliberately offer brotli/gzip compression for assets served through it despite using SSL (and while some people distrust Cloudflare, this is such a surface-level practice that it would not go unnoticed if it was the wrong thing to do). And it is wild to imagine the bandwidth increase from all websites never using compression again (since every site uses SSL nowadays).

**Comment by umonaca** [comment]
https://nginx.org/en/docs/http/ngx_http_gzip_module.html  
```
When using the SSL/TLS protocol, compressed responses may be subject to BREACH attacks.
```

Static assets are not vulnerable to BREACH attacks since the attacker cannot inject plain text to it. Cloudflare caches those static assets by file extensions, so it's safe for Cloudflare users.  

After a lot of reading, I think this issue can be marked as resolved. Mastodon added the `SameSite` attribute for Cookies 4 months ago. Chrome and Firefox rolled out an update to set `SameSite=Lax` as default starting from 2020.
