### ISSUE TITLE
Big avatars (after last upgrade?)

### ISSUE THREAD

**Issue by quimgil** [tootsuite/mastodon#15847]
### Expected behaviour

Profile pages in public view show avatars with the correct size. The same size as they are shown in personal, local, and federated timelines.

### Actual behaviour

All profile pages in our instance show posts with big avatars, only in the public view. Personal, local, and federated timelines look just fine. 

See for instance: https://red.confederac.io/@niboe

### Steps to reproduce the problem

n/a

### Specifications

v3.3.0

Can be reproduced with all browsers.

We have upgraded Mastodon recently, and maybe this is something related. However, since we don’t look our public pages often, there is a chance that this is an older problem.

Other than waiting for the next release to upgrade, I don’t know what I can do as an admin. Is there at least a way to regenerate these images?

Initially reported at https://discourse.joinmastodon.org/t/big-avatars-after-last-upgrade/3286

**Comment by Gargron** [comment]
You’re missing latest assets (assets:precompile step of the upgrade)

**Comment by LETRA** [comment]
> You’re missing latest assets (assets:precompile step of the upgrade)

I repeated the upgrade and it didn't fix. is that the problem or should we downgrade first?

**Comment by Gargron** [comment]
Error reporting from webpacker is very unsatisfactory. It simply exits instead of explaining what happened. Moreover if the work was partially done, on a repeat run it detects this and says that there is nothing to be done.

Using assets:clobber before assets:precompile will force it to really compile.

If webpacker crashes because of a lack of memory, you may need to stop mastodon-web before doing it, [or create a swapfile](https://www.digitalocean.com/community/tutorials/how-to-add-swap-space-on-ubuntu-20-04).

**Comment by LETRA** [comment]
Perfect. It has worked correctly. Thank you very much for your help. I leave here the commands in case someone else needs this information:

Follow this: 

https://docs.joinmastodon.org/admin/upgrading/ 

& this:

https://github.com/tootsuite/mastodon/releases

But stop the mastodon-web service. In Debian:

`systemctl stop mastodon-web.service`

And add to the command to force the compilation of assets so that it looks like this:

`RAILS_ENV=production bundle exec rails assets:clobber assets:precompile`

When it is ok, restart the service:

`systemctl stop mastodon-web.service`

And follow the steps.

**Comment by quimgil** [comment]
Thank you everyone! This was fast and clear.
