### ISSUE TITLE
encoding "UTF8" does not match locale "en_US"

### ISSUE THREAD

**Issue by x011** [tootsuite/mastodon#15897]
I'm getting the following erro while installing mastodon :

```
Running `RAILS_ENV=production rails db:setup` ...
PG::InvalidParameterValue: ERROR:  encoding "UTF8" does not match locale "en_US"
DETAIL:  The chosen LC_CTYPE setting requires encoding "LATIN1".
: CREATE DATABASE "mastodon_production" ENCODING = 'unicode'
Couldn't create 'mastodon_production' database. Please check your configuration.
rails aborted!
```

The system locale is already `en_US.UTF-8` so I don't know what to do.
How to solve this?

**Comment by nightpool** [comment]
We primarily use GitHub as a bug and feature tracker. For usage questions, troubleshooting of deployments and other individual technical assistance, please use one of the resources below:

 - https://discourse.joinmastodon.org
 - #mastodon on irc.freenode.net

Feel free to continue the discussion of the issue here, but I'm going to be marking the ticket as "closed". This won't affect your ability to comment on it, it's just a reflection of the fact that it's not a defect in the mastodon software, just a problem with your individual deployment.

**Comment by x011** [comment]
This is a bug because installation should work as instructed on the official website and it doesn't. I guess it's easier to close and ignore the problem than understand what wrong and help.

**Comment by x011** [comment]
The solution for this problem is here:

https://gist.github.com/joshteng/9895494
