### ISSUE TITLE
Cannot skip boost confirmation window

### ISSUE THREAD

**Issue by nykh** [tootsuite/mastodon#1594]
#1507 implemented a confirmation window before boosting (#621) but the "Press ALT to skip this window" part doesn't work in my environment.

Behavior:
When press ALT + click nothing happens (no boosting, but also no window). Didn't see any error message in the console.

Environment:
Ubuntu 16.04
Firefox & Chrome

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by mkody** [comment]
Can confirm, it doesn't work with my Debian Jessie (LXDE; Chrome and Firefox).  
But it works fine on my ArchLinux environment.

**Comment by carlinhush** [comment]
Can confirm: Alt+[boost] working fine on Win10 Pro (Chrome and Firefox), but not on Windows Server 2012R2. 

On Win Server 2012R2 in Chrome and Firefox Alt+[boost] does not do anything, [boost] only brings up confirmation overlay.

**Comment by wxcafe** [comment]
This is (apparently) due to the fact that the desktop environment catches Alt+click and uses it for moving the window. That being said, it's weird that it would work on win10 and not on win server 2012 (though why are you using a browser in windows server? ^^), except if microsoft removed alt+click catching in win10? Need someone to check this (and also find out how Tumblr, for example, manages to use Alt+click for reblogs without triggering this)
