### ISSUE TITLE
User's preference to exclude user page from being indexed by search engines

### ISSUE THREAD

**Issue by symac** [tootsuite/mastodon#1599]
Hello,
I have noticed that most instances keep the default robots.txt file, which allows any page to be indexed by search engines. As privacy is a concern for many users in the fediverse, I believe it would be nice to add a preference in users settings excluding you own user's page from search engines by adding it to the robots.txt.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Fastidious** [comment]
Privacy. LOL. Sorry, couldn't help trolling a little.

**Comment by Reventl0v** [comment]
In addition to the existence of a preference in user settings, I'd love to see some "active" request from Mastodon at the account creation. For example, at the first login, a window could ask what's the choice for the user:

- Denying the bots to index the toots and the bio;
- Authorizing the bots to index the toots and the bio;

Why? Because the bio and toots may contain "personnal data", and I believe to allow the indexing of this kind of data legally, in some countries, a deliberate choice must be done by the user[1].




[1]: (In french) « Il convient toutefois de différencier les données personnelles affichées sur ces sites (par exemple issues des réseaux sociaux), qui sont elles soumises à un régime d’autorisation spécifique, des autres données. Si les données sont indexées, conformément à la loi LCEN de 1978, il est systématiquement nécessaire d’obtenir l’autorisation de la personne concernée pour cet usage (par exemple via un outil d’opt-in lors de l’inscription sur un site) » https://www.legavox.fr/blog/maitre-matthieu-pacaud/extraction-indexation-donnees-crawlers-internet-22421.htm

**Comment by Reventl0v** [comment]
Also, the bio and the names are currently replicated accross the mastodon network on the "following"/"follower" pages of people following or being followed by the members. Should one instance block, using robots.txt for example, the crawling of its website by indexing bot, it does not prevent the indexation of the name and the bio of one member using other mastodon instances. How should this be managed? The creation of "meta" robots.txt for each following and follower pages? Disabling the indexation of the follower and following pages, by default, with one opt-in?

**Comment by Kimik0** [comment]
I agree with the OP that a lot of people chose Mastodon because of privacy concerns. The default setting should be to disallow crawling of all but the /about and /about/more pages.

In addition, according to https://en.wikipedia.org/wiki/Robots_exclusion_standard#Meta_tags_and_headers , it might be possible for crawlers to see user, toot, tags and whatnot pages if they are linked to from elsewhere.
I propose that as an extra protection, the `<meta name="robots" content="noindex" />` tag be added by default to all pages except the /about and /about/more ones.

**Comment by symac** [comment]
I am not sure that preventing anything from being indexed by default is the solution. Because even if privacy is a concern for many users I am pretty sure that we also have many (more ?) users who want a network that is visible and can welcome more and more members. That's why I was suggesting in my initial message a method that would allow users who are concerned about their activity on mastodon not being too much visible to be able to opt-in to be hidden.
The other risk with defaulting to noindex would be that it could be understood by some as : "great, I can safely post on mastodon without my content being searchable", whereas we know it's untrue, robots.txt and all theses directives are just suggestions and nothing prevents someone with bad intentions from ignoring them.
