### ISSUE TITLE
Set the anti-FLoC server header

### ISSUE THREAD

**Issue by fbausch** [tootsuite/mastodon#16034]
### Pitch

Mastodon servers should set the Permissions-Policy response header as follows: `Permissions-Policy: interest-cohort=()` (https://github.com/WICG/floc#opting-out-of-computation). It disables the FLoC tracking method in Chrome browsers for users that visit the Mastodon server.

### Motivation

Currently, the new Google tracking method called FLoC is in the media. It cannot be deactivated by Chrome users easily. However, site admins can disable FLoC for their sites by sending the Permissions-Policy header with correct value.
If Mastodon servers send them by default, this has a huge privacy impact for all Mastodon users, since tracking is harder within the Fediverse even if users are unaware of this new kind of tracking.

**Comment by ClearlyClaire** [comment]
## Background

### What is FLoC

(Just paraphrasing what I understand of FLoC, since I haven't looked into it before today)

From what I understand of FLoC, it's a mechanism that Google is experimenting with, basically computing a fuzzy hash from the user's browsing history in order to let advertisers group users with similar browsing habits, without uniquely identifying the user nor revealing any precise bit of the actual browsing history. The exact algorithm isn't specified (yet?) as it is mainly what they're experimenting with at the moment.

This means cohort IDs are, in themselves, not directly identifying users nor revealing a specific bit of the browsing history. However, this adds a significant number of identification bits. Even if those IDs are supposed to change over time, in a given timeframe, a website may very well be able to discriminate between individual users if its user base is low enough. Furthermore, even if those IDs do not directly reveal information, their purpose is to group people by interest, so they do reveal information about the user anyway.

### Opt-in and opt-out

Apparently, whether FLoC should be opt-in or opt-out (both on the publisher's side and the end-user's side) isn't completely defined yet. From what I understand, the current Google experiment includes websites using ads and not explicitly opting-out.

## Within Mastodon

Mastodon surely doesn't need to access FLoC IDs, and in itself wouldn't benefit from instances being included in cohort computation.

As Mastodon instances generally do not use ads, it's unlikely they would contribute to cohort calculation with the current experiment (although I have not found anything more precise about that than “sites which load ads or ads-related resources”), though I guess maybe loading embedded video players or such could end up enabling it.

Therefore, I think there is no urgency in adding that header, but it shouldn't hurt to add it either.

(Sorry, such a long post for such a simple conclusion, but FLoC is a mess I wanted to get my head around before giving an opinion on this issue)

**Comment by nightpool** [comment]
> Apparently, whether FLoC should be opt-in or opt-out (both on the publisher's side and the end-user's side) isn't completely defined yet. From what I understand, the current Google experiment includes websites using ads and not explicitly opting-out.

The final version of FLoC will be opt-in. To test out FLoC, Chrome is running a 0.5% A/B test where it uses the [Ad-Tagging heuristic](https://chromium.googlesource.com/chromium/src/+/master/docs/ad_tagging.md#) (defined based off of EasyList filters) to determine which sites are "likely" to adopt FLoC in the future or likely to do the kind of cross-site tracking that FLoC replaces.

**Comment by ClearlyClaire** [comment]
Thanks, I had missed that!

We will see at that point. Note that for instance, it would make sense for Mastodon to keep setting the header, depending on how iframes are handled, if the following ends up being chosen:
> e.g., pages that use the API would be included in FLoC calculation

**Comment by nightpool** [comment]
iframes need an explicit feature policy permissions (i.e.
allow=interest-cohorts) to be able to use the API. they can't just use it
silently without the host page giving them permission to do so

**Comment by Wonderfall** [comment]
I'd like to jump on the occasion. From both a security (XSS mitigation) and privacy perspective, it wouldn't hurt for Mastodon to provide by default a safe Permissions-Policy, which will disable some APIs Mastodon won't ever use anyway. It's a bit out of the scope for this issue, but since we're talking about it, what do you think?

See:
- [Permissions-Policy explainer](https://github.com/w3c/webappsec-permissions-policy/blob/main/permissions-policy-explainer.md)
- [List of features that can be disabled](https://github.com/w3c/webappsec-permissions-policy/blob/main/features.md)

If there's interest in this I can prepare a PR, otherwise I'll just keep setting it at a proxy-level.

**Comment by Gargron** [comment]
Headers aren't free. An unnecessary header on every request across the entire fediverse, that's gigabytes of traffic.

**Comment by Wonderfall** [comment]
> Headers aren't free. An unnecessary header on every request across the entire fediverse, that's gigabytes of traffic.

Of course they aren't, nor CSP is (which is by far much larger than a simple & safe Permissions Policy).

But point is, this isn't really unnecessary and there are far more advantages than drawbacks to have secure headers implemented by default. Administrators can just set them at a reverse proxy level, and they will, eventually.

**Comment by Gargron** [comment]
CSP is a layer of protection against XSS attacks, e.g. where scripts can get executed from. Permissions-policy is a layer of protection against scripts you choose to include on your page. Since we do not load any third-party scripts, there is no point in us protecting us from ourselves. CSP protects us against including unexpected scripts anyway.

**Comment by Wonderfall** [comment]
I know very well what CSP is for, but my point was Permissions-Policy is not redundant at all with it. They're complementary. CSP should be thought as, like you said, a layer - a mitigation among others. CSP is basically designed to prevent loading content (including scripts) from untrusted sources, nothing new.

Here comes Permissions-Policy: instead of controlling the origins of the content, it controls the access to the browser APIs. Thus, an additional layer. Why would we want that? Well, there were instances of [CSP bypass](https://nvd.nist.gov/vuln/detail/CVE-2020-6519) in the past. Permissions-Policy could help prevent a disaster. Another mitigation would be (like Twitter) putting *nonce-hash* in the CSP heaers, but yeah, it would be too much. In general, it's best to follow the *principe of least privilege* (a layer of zero trust); here by only allowing browser APIs Mastodon needs.

While I wouldn't be so dismissive of this layer (*better safe than sorry*), I understand your stance.
