### ISSUE TITLE
Don't allow emojis on usernames

### ISSUE THREAD

**Issue by carlosjs23** [tootsuite/mastodon#1614]
It can be confusing for some users that come from other social networks, to see emojis that usually are used for "verified users" next to some usernames.
* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by bortzmeyer** [comment]
Which name? The one in the address or the one displayed? 

Seriously, stupid idea, I suggest to drop it.

**Comment by mkosler** [comment]
Emoji's allow for more personal expression in usernames and I can guarantee quite a few people would be very upset if this wasn't available. The confusion is fleeting.

**Comment by wxcafe** [comment]
Not "allowing" people to put emojis in their username makes no sense: anyone can make an instance that does. Not *displaying* emojis in usernames would make more sense.

This is still a bad idea imo: it doesn't add anything. If people are confused because someone put a checkmark in their usernames, it's not that big a deal, and they'll learn quick enough

**Comment by 0xabad1dea** [comment]
Twitter has a blacklist for emoji specifically to avoid the impression that someone is locked or verified while still allowing creative freedom. I'm sure you can find the actual exact list somewhere but it's something like ✅☑️🔒🔓🔐🔏

**Comment by carlosjs23** [comment]
@bortzmeyer The idea is stupid as are your arguments.

Thanks to others for letting me understand why is not a good idea.
