### ISSUE TITLE
Column filters do not search content warning text

### ISSUE THREAD

**Issue by mkosler** [tootsuite/mastodon#1635]
When I add a regex filter on a column, it does not search the content warning text.

Here is what it looks like when I am NOT filtering the word "hippo":

![hippo_filter_off](https://cloud.githubusercontent.com/assets/1159095/24973662/3216d8a6-1f85-11e7-9ad1-fc242f599ea0.PNG)

Here is what it looks like when I am filtering the word "hippo":

![hippo_filter_on](https://cloud.githubusercontent.com/assets/1159095/24973611/0c5134cc-1f85-11e7-8191-8dbf7d397719.PNG)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by mkosler** [comment]
This has been brought up again today after people started posting a meme that used the content warning part as the main part of the post. You couldn't avoid it on your timeline.

![hemingway](https://cloud.githubusercontent.com/assets/1159095/25295889/38169dfe-26ab-11e7-9ecf-a0019e7aab24.PNG)

**Comment by rtucker** [comment]
I have confirmed this issue is still present in 1.3.2.

Steps to reproduce in Vagrant environment:

1) Toot a message with a word in the CW that doesn't appear in the body
2) Attempt to filter out the CW word
3) See the toot not disappear
4) Attempt to filter out a word in the non-CW part
5) See the toot disappear properly

![screenshot_2017-04-30_16-11-40](https://cloud.githubusercontent.com/assets/97437/25567616/da98d0cc-2dbf-11e7-8158-e5acda26266f.png)

![screenshot_2017-04-30_16-12-17](https://cloud.githubusercontent.com/assets/97437/25567625/018eedf6-2dc0-11e7-9d78-2bff5a1c98e9.png)
