### ISSUE TITLE
"Bot" and "Commercial" Profile Tickbox

### ISSUE THREAD

**Issue by shivian** [tootsuite/mastodon#1641]
Idea: a tick box that is required to be checked if the account is a bot, and another if a bot is a commercial entity. Profiles found to be ignoring these boxes can be removed from a server without warning. All users could then have a set of options in their profiles like "mute all local bots," "mute all federated bots," and even "mute all commercial profiles," allowing them to easily control their bot / brand exposure in a flash

**Comment by N07070** [comment]
So the user it self should tick an option to display this on there profile ? I see a conflict tho, if a brand pays the admin to allow the brand to not have a tick box, how should we react ?

**Comment by tchoutri** [comment]
@N07070 well after that it's a matter of how you tolerate this kind of behaviour on the instance. Either you leave it, or you stay.

**Comment by Dragnucs** [comment]
If running their own instance, bot-makers and commercials will not tick this box. You will have no way to prevent them.

Anyway, this is a good idea and people respecting it will make the fediverse a better place.

**Comment by spiderrobotpig** [comment]
Yeah, but if they did that, then you could always just block that instance, preventing the issue.

This honestly seems like a really good idea tbh

**Comment by sandhawke** [comment]
I like the approach of solving these problems with metadata, but I doubt there's anything like a clear definition of 'commercial'.  Like, people who mention their patreon?

**Comment by Gargron** [comment]
Bot implemented, commercial probably not possible.

**Comment by trwnh** [comment]
I'm not sure "commercial" is 100% accurate, but AP actor types include `Application`, `Service`, `Group`, `Organization`, `Person`. The real issue is that these 5 terms are rather vaguely defined -- right now, I think Mastodon handles `Application` and `Service` both as Bot nameplates. I think what most people would refer to as "commercial" would probably fall under `Service` in the sense that the profile is providing some sort of service. Aside from `Group`, which is defined as a collective of other `Actor`, it should be possible to allow defining each profile as one of the other 4 types. At that point, the only issue would be in adding multiple types.
