### ISSUE TITLE
remove the first @ in handles.

### ISSUE THREAD

**Issue by faultydev** [tootsuite/mastodon#16488]
### Pitch

My suggestion is to remove the first @ in the handles.
so it goes from:  
`@faulty@mas.to`
to:  
`faulty@mas.to`  
OR anything else that makes it look less bulky...  
e.g.
```
faulty[mas.to]
(@)faulty/mas.to
faulty>mas.to
```
it could be a big thing but i think it would be worth it.

### Motivation

Everyone would benefit from it since it would look way nicer.
It's not *needed* but definitely worth the effort.

**Comment by LeeteqXV** [comment]
On Sun, Jul 11, 2021, at 2:51 AM, Didier wrote:
> My suggestion is to remove the first @ in the handles.
> so it goes from:
> ***@***.***@mas.to`
> to:
> ***@***.***`
> OR anything else that makes it look less bulky...
> e.g.
> 
> `faulty[mas.to]
> (@)faulty/mas.to
> faulty>mas.to` 

Since the "@" prefix indicates that it is a user name/handle, not to be confused with (or used as) an email address, it is IMO practical and even important.

Since many other systems also use that character for the same purpose, it is also uniform. Another practical aspect is that the @ character is also the main character associated with "a point of contact", be it email, messaging or other.

Not sure if replacing it with a "less bulky" character would be good, but perhaps interesting to dwell upon some alternatives. (It might even reduce some confusion for newcomers/novices reacting to the presence of 2 @-characters in the same "address".)

Less bulky alternatives:
- The universal currency symbol ("¤") is not used much, but perhaps most importantly not sufficiencly easily available on many keyboard layouts(?).
- Could the exclamation symbol serve this purpose..?
- Or even the slash?

Another way which I personally prefer more, is how the Matrix system does it, using the same @ prefix, but replacing the domain separator with a colon, like this: ***@***.***:matrix.org`, which much clearer distinguishes it from an email address.

Some examples along those lines:
- ***@***.***`
- ***@***.***`
- ***@***.***`
- ***@***.***:mas.to`
- `¤someone:mas.to`
- `!someone:mas.to`
- `/someone:mas.to`

--
Regards,
Teqleez

**Comment by ClearlyClaire** [comment]
The leading `@` is useful both for humans and computers to quickly understand something is supposed to be a mention. It's been used for years in Mastodon, it's used in Twitter too, and in most fediverse software. Removing or changing it will only lead to confusion and headaches for the current users and implementations, and none of the suggestions above seem inherently better.
