### ISSUE TITLE
Remove follows/follower counts

### ISSUE THREAD

**Issue by talon** [tootsuite/mastodon#1660]
I think perhaps that quantification of followers/following incentivizes a culture of performer/audience and/or creates stigmas around the ratio, which aren't desirable.

It may be nice to replace the counts with just a "mutuals" count or remove them all together.

At the very least it would be nice to have this discussion.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by talon** [comment]
toot.cafe has had this discussion regarding their instance
https://github.com/tootcafe/discussions/issues/16

**Comment by otterwillow** [comment]
for me personally removing follower counts would be incredibly anxiety inducing and I would have to leave mastodon.

I have been harassed by folks who would follow me and then harass me, so I need to see who follows me to feel safe.
I need to know and see who follows me, so I can block if necessary, I also need to know if they follow someone who is bigoted as that could bring me into contact with someone who could hurt me? 

And I need know how many folks follow me on my accounts to know if I feel comfortable saying certain more private things on those accounts? to gain an idea how far a post I might make would travel?

like I can see why folks might want to remove it, but it could be very unsafe for some folks who need to check who follows them and who others follow as a matter of safety?

**Comment by Cassolotl** [comment]
I like the idea of a mutuals count, but that for me wouldn't be replacing anything else - just added!

**Comment by ultimape** [comment]
Echoing otterwillow's sentiment, I think there is a lot of unspoken utility in follower counts aside from the overt incentive to game the numbers.  I use follower counts and information as a rough gauge to figure out if someone is interesting or worth investigating further. I also find it useful to gauge where I am in the social graph. For a comparison to twitter: knowing that someone following me there has 150k followers means that I need to watch what I tweet and be aware that stuff that gets retweeted by them might attract questionable attention.

That being said, I'm not sure if follower count is actually the most useful way to gauge this kind of concern as it's more of a rule of thumb and heuristic for other issues. But being able to get a good measurement is complicated by the fact that a federated node can potentially fake or fudge the numbers when reporting it. This makes me think that the safety concern might be better alleviated by some other feature instead of depending on a lossy heuristic.

**Comment by Gargron** [comment]
I am not interested in removing those numbers, sorry!
