### ISSUE TITLE
compose wrapping issue from "nsfw" text when uploading image

### ISSUE THREAD

**Issue by lae** [tootsuite/mastodon#1686]
When attempting to upload an image from the composer, a "nsfw" toggle appears which seems to break wrapping for me in Firefox 52.0.2.

before:
![before](https://up.lae.is/i/1492085196-c7e62.png)
after:
![after](https://up.lae.is/i/1492085182-9ec0f.png)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by tomfhowe** [comment]
This appears to be due to the length of the translated toot button text being longer than expected. Submitting a pull request to fix this in a second. See the following screenshots:
![toot too long](https://cloud.githubusercontent.com/assets/19882099/25019333/370a790c-2058-11e7-8970-5c36974a70b7.JPG)
![toot short enough](https://cloud.githubusercontent.com/assets/19882099/25019332/370a8348-2058-11e7-8bfd-50896dcc902d.JPG)

**Comment by tyrosinase** [comment]
It's not just translations. (I mean, unless American English is a translation, which I'll allow is a possibility.)

This is on Linux Firefox ESR 45.9.0, in full screen on a 1920x1080 monitor.

![2017-04-22--1492896329_1920x1080_scrot](https://cloud.githubusercontent.com/assets/9473609/25308386/fdde153c-2780-11e7-8cad-a660e36b7834.png)
