### ISSUE TITLE
Expand to embed on video links

### ISSUE THREAD

**Issue by unsmell** [tootsuite/mastodon#169]
For both video files hosted elsewhere and youtube links, etc

**Comment by ineffyble** [comment]
I can see two options/ways here:

1. This is part of the scope of #463 - services like YouTube provide a Video URL in their social metadata. That's scraped by the server, and that data is accessible via API, and can be handled by client.

2. This is a front-end feature, that detects URLs for video services such as YouTube, and renders an appropriate inline iframe/player.

Thoughts @Gargron?

**Comment by ofaurax** [comment]
I came here searching for an issue about image preview of youtube videos.
I would say that this is a front-end feature, because some client might want to display a static preview rather than an iframe, some might provide auto-play, or displaying the stats of the video in the client.
Also, analyzing the metadata of every youtube shared link could be an additional load for the instances.

**Comment by mjankowski** [comment]
Related https://github.com/tootsuite/mastodon/pull/2268
