### ISSUE TITLE
timeline pause in the web interface

### ISSUE THREAD

**Issue by xcombelle** [tootsuite/mastodon#1711]
Now that mastodon is popular, the federated timeline is regulary updated. When you scroll down the timeline, it makes it disapear the toot you are currently reading.

**Comment by tomfhowe** [comment]
I don't have the skills to implement this, but what if it only updated if you were scrolled all the way to the top?

**Comment by xcombelle** [comment]
yes @tomfhowe it would be the ideal setup.

**Comment by BjarniRunar** [comment]
Hello! Thanks for Mastodon!

I'd like to add some detail to this issue: IMO it is actually quite a serious usability problem. Because the time-lines jump around sporadically, there is a significant chance users will click something unintended. This will result in boosting or staring the wrong Toot, or exposing "NSFW" content that you hadn't intended to (which in the absolute worst case could result in a user accidentally ending up with some illegal content in their hard drive cache).

So this is quite a bit more serious than just annoying the user, it actively causes mistakes. I've already boosted the wrong things a couple of times because of this.

I agree with the proposed solution that updates are paused unless the user has scrolled to the top, that should resolve the issue.

**Comment by gellenburg** [comment]
+1

I made this suggestion within the first hour of using Mastodon (that the timeline should be paused unless the column is at the very top) because it was hard to read a couple of weeks ago, and downright impossible now. :-)

**Comment by Gargron** [comment]
>if you leave it scrolled to the top it updates in real time, if you scroll down it doesn't update, so you can keep your place while reading.

This is what was implemented, and I think it works this way currently, too. There might have been an intermediary bug with it at the time this issue was made.
