### ISSUE TITLE
Migrate from Browserify to Webpack

### ISSUE THREAD

**Issue by Gargron** [tootsuite/mastodon#1712]

**Comment by hnrysmth** [comment]
That commit 1a51ec7 gets the [rails/webpacker](https://github.com/rails/webpacker) Hello World running in the console on my `mastodon.dev` VM. It's not much, but maybe it's a starting point.

![screen shot 2017-04-14 at 13 24 53](https://cloud.githubusercontent.com/assets/566159/25042142/f5c29d76-2115-11e7-952a-88c5dd05039f.png)

Dunno if webpacker is the way you wanna go with this, but I was in the mood for a bit of exploratory work and I really don't mind at all if it turns out to be a dead end.

I made one other change to the vanilla `webpacker:install` config that I forgot to note in the commit message: by default it sets up a new `app/javascript` directory and I changed that back to `app/assets/javascripts`.

**Comment by skhameneh** [comment]
I'm all in for this.  @Gargron should a separate branch be made to get this started?
Let me know if you create one, I'll check out the branch and begin work.

**Comment by skhameneh** [comment]
Suggested task list:
- [ ] CSS Loaders: css-loader?minimze=true -> postcss-loader (w/ postcss-cssnext)
- [ ] JavaScript Loaders: babel-loader  
***In .babelrc, change ["es2015"] to ["es2015", { "modules" false }] to enable native modules.  
***May need to disable for streaming until node has native modules.
- [ ] Images Loader: url-loader?limit=1000 (maybe higher limit)
- [ ] Fonts Loader: url-loader (generic settings)
- [ ] Consider adding babel "nofn" support.
- [ ] .babelrc & React: 'tarsnform-react-inline-elements', 'transform-react-constant-elements', 'transform-react-remove-prop-types', 'transform-react-pure-class-to-function'
- [ ] .babelrc: { compact: true, comments: false, minified: true }
- [ ] UglifyJS: compress: { unused: true, evaluate: true, booleans: true, drop_debugger: true, dead_code: true, pure_getters: true, negate_iife: true, conditionals: true, loops: true, cascade: true, keep_fargs: false }, mangle: false
***There are some others that can be used in unsafe=true, but a few would need to be disabled in unsafe as well, avoid for now.  Must use mangle=false for code splitting to work in Webpack
- [ ] Consider moving to CSS Modules (major rework of CSS)

**Comment by Gargron** [comment]
@hnrysmth @skhameneh I am interested in this. And yes, I think webpacker is probably the way to go, seeing as that's an official Rails thing that's gonna be included starting with Rails 5.1 (or 5.2?). Separate branch is the only way we can do this because you can only merge something into master from a pull request.

**Comment by skhameneh** [comment]
@Gargron still waiting on a branch :)

**Comment by expenses** [comment]
This might now be easier with the [new rails release](http://weblog.rubyonrails.org/2017/4/27/Rails-5-1-final).
