### ISSUE TITLE
Link @username@twitter.com to Twitter profile pages

### ISSUE THREAD

**Issue by Cassolotl** [tootsuite/mastodon#1849]
For those of us who like to be on both Mastodon and Twitter, I imagine it might be pretty handy to have @username@twitter.com become a link to people's Twitter profiles that opens in a new tab/window. I would like this a lot.

I understand that there would be no notifications Twitter-side, no ability to search for @username@twitter.com, no federation, and so on. It's just an instinctive urge I have sometimes when posting, because sometimes I post something and I want to correctly credit someone who's on Twitter. All this would do would turn @username@twitter.com into a link to a Twitter profile, and maybe (?) for tidiness remove the @twitter.com from the end.

I can imagine this will not go down well among the "ugh Twitter gross" crowd but... I understand that Twitter does some things that OStatus founders and contributors would find *completely abhorrent*, but then... there will presumably be SJW safe spaces and white supremacist spaces both using OStatus-based sites, and that's totally fine too! People just say "that's the beauty of it, people can block other instances if they make content that is unwanted" etc. And, this bit is hard to describe but I feel like it would be a nice making-friends gesture. Like, in the unlikely event that Twitter somehow magically became FOSS and federate-able, wouldn't that be cool? But even if they never do (way more likely), it's a usability feature that expresses good intentions in addition to being intuitive and functional and helpful.

* * * *

- [Yes] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by almafeta** [comment]
For one, it could be genericised:  @username@plus.google.com, et *multiple* cetera.

But on the other hand, it seems ripe for abuse for turning Mastodon into a tool for the mass assault of Twitter accounts without being readily visible through Twitter's own analytics.

**Comment by lutoma** [comment]
I don't think this should be an inherent feature in Mastodon, but is rather something that people should be free to implement using their own OStatus instances. For the record, I'm currently building just that and hope to have a twitter instance up in the next days.

**Comment by Cassolotl** [comment]
@lutoma I have very little technical knowledge and I've been yearning for a good Twitter bridge that I can use for like two years.\*sigh\* Is there some kind of online presence I can follow to see how it turns out?

**Comment by lutoma** [comment]
@Cassolotl No online presence or anything yet, but I'll try to notify you (and everyone else) here in this issue once it's done/on Github. Does that work?

**Comment by Cassolotl** [comment]
@lutoma That works for me! I'm subscribed so I'll see it. Thank you! :)

**Comment by Shnoulle** [comment]
@Cassolotl and @lutoma for information TwitterBridge plugin work  (on GnuSocial) . I make some improvement currently : https://git.gnu.io/gnu/gnu-social/merge_requests/147 . See my twitter account for working part.

But the general concept is complicated ... some ostatus user don't want to see their status repeated on touitre (and it's totally Ok and understandable) for the 1st example.

**Comment by ticki** [comment]
You NEVER get Twitter to do this, so it has to be hard coded for it to work. Unless you of course want another domain, which would be a bit annoying, but it could work.

**Comment by Cassolotl** [comment]
@Chronister has done this on cybre.space and I've seen plenty of positive comments on it. :)

**Comment by Chronister** [comment]
relevant feature branch is here: https://github.com/cybrespace/mastodon/tree/feature_hotlink_twitter_mentions

but I wouldn't recommend using this outright, necessarily. it doesn't generate entities for the JSON for example.

**Comment by rugk** [comment]
Let's face it: Twitter exists. And it is often referred to in toots. And they are unlikely to change their domain (or implement OStatus or whatever…)

So at least for Twitter this is reasonable, IMHO. Reality is Twitter users are mentioned and such a simple link can make it a lot more convenient to check the source of a (re-tooted) tweet or so.

Also, users currently even start to use this strange **ActivityPub bridge** at 
https://activitypub.actor. E.g. you can mention the user at and it will end-up as https://twitter.activitypub.actor/rugkme. This is basically the same, as a workaround, for this feature here.

However, I don't like it, because although there is a big link to Twitter then, you really need to click two times to get to your actual destination…
But it certainly **shows the need of a simple feature like this** and that people use it… IMHO. :smiley: 

---

IMHO for now supporting Twitter is enough. Other profiles on other platforms are rarely mentioned anyway (at least compared to how often Twitter users are mentioned).

----

As such, consider reopening this issue. https://activitypub.actor is certainly worse than a simple included (hardcoded) feature of this kind in Mastodon. (I mean you can make it optional, but twitter.com will stay at twitter.com.)
