### ISSUE TITLE
Safari account creation bumpy

### ISSUE THREAD

**Issue by JanX2** [tootsuite/mastodon#2037]
I created an account on <https://chaos.social> using Safari 10.0.3. This was not a seamless process, mainly due to the complication, that Safari automatically offers to store credentials. In this case, it was the username/password pair. Login requires email/password though. At least, as long as #1177 has not been resolved. 

This has yet to come up in another web app. At least in my experience, this is not common behavior in Safari. 

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by wxcafe** [comment]
I believe this is a byproduct of #1177 as you pointed out, and you should comment on that issue. I'm closing this issue, if you feel the two issues are really different feel free to open it up again

**Comment by daprice** [comment]
For what it’s worth, I just tested this and was able to fix it on my local copy by changing the `aria-label` on the username field from “Username” to “Nickname” (I suspect something like “handle” or “short name” would also work). It looks like Safari uses the field’s associated `<label>` and/or `aria-label` attribute to determine its autofill type, and assumes that “username” means it's a login credential (I couldn’t find this documented anywhere). Interestingly, Firefox already correctly saves email/password (not username) for the registration form in its current state.

If it’s decided in #1177 not to allow logging in with usernames, then it might be worth reopening this issue so that fix can be applied, but if logging in with usernames ends up being allowed, then it’s moot.
