### ISSUE TITLE
Better discoverability of toot permalink

### ISSUE THREAD

**Issue by JanX2** [tootsuite/mastodon#2039]
In the web UI, it was not immediately apparent to me, how I could get from a post in a timeline to a thread.

After some trial and error/searching I found that via clicking on the date/age link for the post, you can get to its thread. 

On Twitter, this links to a permalink for the post, which is similar. But you can also click on the post background, which is much easier to discover.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by wxcafe** [comment]
on tweetdeck you have to click the timestamp too, and since the Mastodon UI is inspired by tweetdeck... but idk

**Comment by ericblade** [comment]
... having used TweetDeck for several years now, I just discovered, after reading your post, that the timestamp is clickable.  I believe most people probably use the menu option "Copy Link to this Tweet". . . . unless most people routinely try to click on timestamps, disregarding that they show no active indicator that they are hyperlinks.  And why would a normal user expect clicking on the time to open the link to that message?  I'd expect that it would give me other things that happened around that time.  Except that since it's dim, and it's not underlined, I wouldn't really expect it to be active at all.

**Comment by wxcafe** [comment]
I didn't even know there was a "Copy link to this Tweet" tbh ^^ I don't know, I guess it really depends on usage and we'd need an UX designer to settle this.

**Comment by cwh1te** [comment]
Looks like this issue may be the same as #738

**Comment by wxcafe** [comment]
good point, closing this in favor of #738
