### ISSUE TITLE
Content Rating and User Score

### ISSUE THREAD

**Issue by Zenithar** [tootsuite/mastodon#2097]
Hello,

In order to control publications (NSFW, not for children, etc.) from user (pornography, etc.), users could (down) vote for a content so that the user will be evaluated by the content published.
Due to distributed apsects of the user account, it could be attached to the user account on his instance and broadcasted to followers with an OStatus extension, or simply attached to a status.

In addition, up vote should be less valuable than downvote, in order to prevent self-promotion using multiple accounts. And I know, it could be easily restarted by using another account, but like all content control system, it's a cat and mouse game.

I know it sounds like a distributed censorship system, but I think it will become mandatory, in order to keep mastodon accessible for all. Such content could be kept in "private" instances. 

Maybe something like ELO Chess rating could do the work.

**Comment by expenses** [comment]
Debates about whether this is wanted aside, I'm not sure if it is do-able from an API perspective. Up/down voting within an instance is possible, but if you allow anyone from any instance to be able to up/down vote content on any other instance, you run into lots of problems.

For one, how are you going to check if the request to `/api/upvote` (or whatever) came from a 'legit' (how would you tell?) Mastodon instance instead of a random IP?

**Comment by wxcafe** [comment]
This is definitely not how we want mastodon to work, and it won't be implemented. Sorry.

**Comment by Zenithar** [comment]
OK quite brutal request close, I think discussion should be open for a subject like that. 
But I understand that it's not a priority or in product philosophy ^^
