### ISSUE TITLE
Keyboard mappings

### ISSUE THREAD

**Issue by mjankowski** [tootsuite/mastodon#2102]
It would be nice to map the `esc` key on keyboards to fire the "Back" navigation element in the right column in the UI.

When scrolling through a timeline view and viewing a status or a person, sometimes a quick glance is all that's needed, and going back with a quick keypress is better than seeking with mouse.

**Comment by tomfhowe** [comment]
Why not backspace/browser standard back key command?

**Comment by wxcafe** [comment]
It would also be nice to map the numbers to the respective columns (1 to home, 2 to notifications, 3 to the other one) like tweetdeck does (pressing the number gets you at the top of the column and selects it for future keyboard events)

**Comment by jeepfromoil** [comment]
Pressing `page down/up` and `up/down' arrows don't scroll any column on Firefox 53 (MacOS 10.12). I'm not sure if it's a bug or a feature.

Here are a few suggestions for more shortcuts (inspired from Tweetdeck):

* `↓`: move selection down
* `↑`: move selection down
* `⇞`: move selection to the top
* `⇟`: move selection to the bottom
* `←`: move selection left
* `→`: move selection right
* `⏎`: opens selected toot
* `⌫`: takes you back to the main column
 * `1`-`3`: navigate through columns 1 through 3
* `esc`: close pop-up/cancel search
* `s`: search
* `?`: show full keyboard shortcut list
* `t`: new toot
* `r`: directly reply to toot from a column
* `b`: directly boost a toot from a column
* `s`: star the toot
* `d`: direct message the toot author
* `p`: show user profile for toot author

**Comment by jbond23** [comment]
Would love to see some indication of which column has focus, and then J, K for next, previous toot scrolled to the top of the column.

**Comment by jbond23** [comment]
I'd prefer it if ↑ or k: move selection down & ↓ or j: move selection down, moved the highlighted toot to the top of the column.

**Comment by wviechtb** [comment]
When using the numbers (1-9) to focus a particular column, the column feed jumps back to the very top. That makes it very difficult to go through a particular timeline, because whenever a particular post is opened and one jumps to that column (to use j/k to go through the replies) and then jumps back, one is back to the very top. Ideally, using a number should scroll to the top of a particular column **if that column is already focused** and otherwise it should just focus that column at the current position.
