### ISSUE TITLE
Access a list of someone else's favorites from their profile page

### ISSUE THREAD

**Issue by Artoria2e5** [tootsuite/mastodon#2117]
The bird site allows one to see what someone else has fav'ed from their profile page. GNU social (quitter, at least) lists both favourites (by a certain user) and public mentions (to a certain user) on a user's profile page. A fav-list can provide a distilled view of what a user is interested in reading, which is yet another good source of higher-quality content. (Someone make up a case for a mention list please.)

* * * *

(Yes, I searched or browsed the repo’s other issues to ensure this is not a duplicate. I checked the search results for `favorite`.)

**Comment by Gargron** [comment]
This is intended behaviour. While you can see who favourited a status, *from* the status, you can't easily get a list of all statuses someone has favourited. That is private. Consider them like bookmarks with a tint of acknowledgement to the author.

**Comment by DandelionSpiral** [comment]
Agree. Accessing someone else's like/fav list is an integral part of social network experience, since fav list is a list for user-curated higher-quality content, as well as it provides an important part of user interactions. Users can know other's interests from their fav list and decide whether they would interact with them more or not. If Mastodon is truly meant to be a centralized SNS (i.e. Twitter) replacement, adding this function would be very helpful.

**Comment by Gargron** [comment]
There is a different function for sharing curated content (boosting). The current favourites behaviour is an established part of Mastodon culture and expectations.

**Comment by Artoria2e5** [comment]
\*vanishes from discussion after posting an issue for someone else\*

**Comment by DandelionSpiral** [comment]
This sounds much like Twitter's Moment function. Still, it takes more clicks to do so than a simple click on a fav/like button. Plus, Twitter users already has established their various ways and methods for using like fuction as a list, it would take much effort for them to get use to an SNS w/o their favorite functions.

**Comment by NelsonTriesCoding** [comment]
👍 for @DandelionSpiral 

I think it could be nice for people like me who have been using Blue bird's Social Media for a few years to find functions they are used to

**Comment by Gargron** [comment]
Mastodon will always differ from other platforms in some ways. I think this feature is exactly as it should be right now, sorry.

**Comment by pmes** [comment]
I like mastodon, but leave favorites private then, and give people the option to share. 6 years is long enough to put this off.

there's no scientific reason to prevent people from sharing their favourites. it's just your gut feeling to prevent sharing of favourites, apparently. mastodon is great, but because of the public utility and openness of mastodon, this favourites issue needs to be adressed in an adult fashion, and not simply dictated forth.

favourites are an excellent way for passive dicoverability... give me the option to have public bookmarks then, if you want to compare the two. honestly

**Comment by Chillstice** [comment]
Yeah I find it strange that it has been decided for the users that this can't be an option. A simple toggle for a 'favorites' profile list will make everyone happy because it allows users to decide for themselves.
