### ISSUE TITLE
Mastodon media doesn't federate

### ISSUE THREAD

**Issue by picsi** [tootsuite/mastodon#2148]
Case in point: https://mastodon.cloud/users/caiocgo/updates/263326

Clicking the link doesn't open an image, but prompts you to download a .bin file. This means that other non-Mastodon GNU social instances can't parse it correctly: https://quitter.se/notice/11134865

**Comment by lutoma** [comment]
That seems to be an issue specific to that instance because they serve their files externally. That image's URL is on https://assets.mastodon.cloud, and if you go to that URL you end up on a [Minio](https://www.minio.io/) instance.

I don't have a CDN set up for my instance, and files load directly in the browser (probably because they have the file extension or a Content-Disposition header set).

**Comment by wxcafe** [comment]
This sounds like their setup is borked yeah, it works fine on my instance: https://social.wxcafe.net/@wxcafe/394318. Please contact the admin for this instance about this. I'm closing this issue

**Comment by picsi** [comment]
@lutoma @wxcafe which instance are you referring to? quitter.se? Here's the relevant issue for qvitter: https://git.gnu.io/h2p/Qvitter/issues/101

**Comment by wxcafe** [comment]
mastodon.cloud.
