### ISSUE TITLE
Character count in bio shouldn't be a byte count

### ISSUE THREAD

**Issue by KellerFuchs** [tootsuite/mastodon#2156]
In bios, the “character count” is a byte count, not a Unicode-character count.
This is quite confusing for users of non-English languages; even (most) European languages have at least diacritics and special characters that aren't ASCII.

This was noticed by @hypatian.

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by hypatian** [comment]
My best guess here is that the form field is somehow coming in and being treated as raw bytes ("8BIT" encoding?) during validation, but when it gets stored wherever it's going it is correctly interpreted later as UTF-8. I'd try to be more precise, but I don't know enough about Rails stuff to be able to figure out how the params are coming in or why they might be interpreted that way.

I *was* able to see that the length validation appears to just use the length of whatever it is handed, unless it doesn't have a length in which case it converts it to a string first:

`value_length = value.respond_to?(:length) ? value.length : value.to_s.length`

That's why my suspicion is that the data is coming in as effective an array of uninterpreted bytes, since Ruby appears to count the length of a Unicode string in terms of the number of Unicode codepoints.

**Comment by ashfurrow** [comment]
Took a look at this, it's a JavaScript issue. Really frustrating.
