### ISSUE TITLE
Always show domain in username, even for same instance?

### ISSUE THREAD

**Issue by Ragzouken** [tootsuite/mastodon#226]
it seems like the idea is to try not to hide or discourage the federated nature of mastodon, but hiding the domain feels like it privileges users of mastodon.social to appearing to have "normal" usernames and that might put people off using a different instance?

**Comment by Gargron** [comment]
I'm not sure, I mean it's just so much longer. The convention "local users don't need to specify a domain since it's the same as yours" makes a lot of sense to me.

**Comment by Ragzouken** [comment]
i guess that's the point though - if you use a different federated instance everyone else sees you as an ugly username. i agree it's ugly but the current prettiness is a special case of almost everyone being on the same instance atm?

**Comment by Gargron** [comment]
GNU social does something else, it hides the domain part even from remote users, and I think that's worse because 1) you can't tell which user exactly is meant without looking at URL or opening it 2) it hides the fact that there's federation. I think federation should be celebrated, i.e. having a @ part on your name should be cool/normal. But like, I don't want to impede practicality either, who needs to see 20x "mastodon.social" on their feed if it's obvious anyway?

**Comment by hach-que** [comment]
I think if we support account aliasing through #177 is becomes kind of a non-issue anyway?  Because I can make an account on mastodon.social like "hq" and make it an alias of "@hq@gamedevs.melbourne".  Anyone interacting with me on mastodon.social just sees "@hq".

**Comment by Gargron** [comment]
I'm gonna close this because I'm quite happy with how it works now.
