### ISSUE TITLE
More useful filenames for image & media uploads

### ISSUE THREAD

**Issue by paralithode** [tootsuite/mastodon#2293]
I understand that a randomised element in file renaming is important for various reasons, but if it wouldn't bust the system I would personally really like filenames to be prepended with an identifying string, e.g [username@instance]. This would make it easier to find & sort saved media files, credit them to their uploaders/creators &c. I suspect this would be especially useful on mobile, where renaming files can be a bit more of a hassle.  

Barring, or in addition to that, I also think it might be cool if there were a sequential aspect to the number strings, if that can be done in a way that isn't too easy to exploit. That way sets of images would be filed together if saved.

* * * *

- [x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate. (Apologies if I failed, searched variations on 'media' 'file' 'filename' :) )

**Comment by ashfurrow** [comment]
Interesting idea! I'm curious where on mobile you were finding yourself renaming files? 

We use [Paperclip](https://github.com/thoughtbot/paperclip) to manage attachments for tweets; at first glance it doesn't appear to support the kind of use-case but we can look into it further if it's something we want to prioritize.

**Comment by paralithode** [comment]
@ashfurrow oh, by that I basically just mean I never find actions like copy & paste on a phone quite as fluid as on desktop, so I breathe a sigh of relief whenever something has a clear filename. :) Maybe I just have clumsy thumbs!

**Comment by ashfurrow** [comment]
It's definitely not just you :)

**Comment by stephenburgess8** [comment]
In order to provide meaningful alt tags on images, preserving the original filename would be useful. For individual media items (https://github.com/tootsuite/mastodon/blob/master/app/assets/javascripts/components/components/media_gallery.jsx#L147) we only have the following information:

1. id
2. remote_url
3. type
4. url
5. preview_url
6. text_url

For accessibility reasons, useful fields would be:
1. display_name (most useful, no UI to set this at the moment, could be set by default as original filename)
2. original_filename
3. uploader (less useful, but could be useful)

For filenames, something like {uploader}-{uri encoded original_filename}-{random 6 alphanum} would maintain uniqueness while providing context.

**Comment by Gargron** [comment]
Original filename is scrambled deliberately to improve privacy.

Alt tags for images has its own issue: #117
