### ISSUE TITLE
Follow limit

### ISSUE THREAD

**Issue by kawax** [tootsuite/mastodon#2311]
Some users send a lot of follow requests by API.
Please add follow limit feature.
ref : https://support.twitter.com/articles/66885

- No limit until 2000-5000 follows.
- Deny if follows > followers*1.1

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ashfurrow** [comment]
Interesting idea! We could let the administrators set their own limit as well.

**Comment by siuying** [comment]
How about we add following options to .env:

- USER_FOLLOWING_BASE_LIMIT (default: 1000, 0 = unlimited)
- USER_FOLLOWING_FOLLOWER_RATIO (default: 1.1)

when follow request is made, following check is performed:

1. if following_count < USER_FOLLOWING_BASE_LIMIT, request is ok
2. if following_count >= USER_FOLLOWING_BASE_LIMIT AND following_count <= USER_FOLLOWING_FOLLOWER_RATIO * follower_count, request is ok
3. otherwise request failed 

If this is good, I can prepare a PR for this.

**Comment by ashfurrow** [comment]
That makes sense to me! What do you think @Gargron ?

**Comment by ineffyble** [comment]
Do we only want total limits? I'd think you might want daily limits instead of/as well as total.

**Comment by ashfurrow** [comment]
I think daily makes sense too.

**Comment by siuying** [comment]
Agreed. So revised the above:

- USER_FOLLOWING_BASE_LIMIT (default: 5000, 0 = unlimited)
- USER_FOLLOWING_DAILY_LIMIT (default: 1000, 0 = unlimited)
- USER_FOLLOWING_FOLLOWER_RATIO (default: 1.1)
- Counters to keep track of every user "today" following count
- Daily tasks to reset the counters

**Comment by ashfurrow** [comment]
@siuying Makes sense! I think having a solution where a daily task isn't necessary would be ideal, but it sounds like a lot more work. Nice solution 👍

**Comment by siuying** [comment]
Maybe we can do it with Redis. I have not read the source code of the project yet, don't sure what is best.

**Comment by S-YOU** [comment]
Followers can make up by creating dummy instance and creating a lot of accounts.

**Comment by ashfurrow** [comment]
It's definitely possible, just as circumventing anything is possible. But I think this will help with no or little downside.

**Comment by kabuakan** [comment]
Good Idea!
In my Instance, some spam account follows many many account. because of this, my Federated Timeline gets faster. it exceeds the permissible of our server.

I also want to clean the Federated Timeline after we remove such spam account. after we remove spam account, the Federated Timeline is full of noise account(no follow and no follower on our instance). I wanna remove there account from Federated Timeline.

thanks
