### ISSUE TITLE
Modify privacy of a toot after publishing it

### ISSUE THREAD

**Issue by MaiaDereva** [tootsuite/mastodon#2314]
Hi!
Would it be possible to modify the level of privacy of a toot after its publication? 

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by mjankowski** [comment]
This would be challenging to do in a predictable way, since things are syndicated and federated immediately after they are created ... it's likely that a change to status would be "too late".

There are separate open issues around allowing a user setting to delay (for a few mins) the sending of a status after creation, which would allow a privacy setting change within a small time window, as a side effect.
