### ISSUE TITLE
Launch onboarding tutorial on demand

### ISSUE THREAD

**Issue by thomaskuntzz** [tootsuite/mastodon#2352]
As it's been discussed in #1850 and more specifically [here](https://github.com/tootsuite/mastodon/issues/1850#issuecomment-294757073), I think it would be good if we could launch the onboarding tutorial on demand.

What are your thoughts on this? :slightly_smiling_face:

**Comment by ashfurrow** [comment]
Makes sense, some of the users on my instance have requested something similar. Any thoughts on where this functionality should go?

**Comment by thomaskuntzz** [comment]
Well, as I say in the comment I linked to, I think we could put a link to start the tutorial in the menu where there are other links such as those for federated or local timelines or the controversial "Get started".

**Comment by ashfurrow** [comment]
Gotcha. Hmm, I'm a bit unsure of putting the link there only because it already has quite a few things and smaller screens are already having a hard time displaying the list.

So for example on 1366x768 it already makes the furry elephant friend under the list scroll up and down:

<img width="1143" alt="screen shot 2017-04-24 at 8 25 16 pm" src="https://cloud.githubusercontent.com/assets/498212/25352417/3da77954-292c-11e7-8af3-45c086278905.png">

I'm wondering if there might be a better spot for it, maybe at the far lower left hand corner of the screen, under the toot box? There's lots of room down there :smile: Maybe someone with a more authoritative design sense from the project can chime in here?

**Comment by ashfurrow** [comment]
Looks like this is actually a duplicate! Let's move the discussion over to https://github.com/tootsuite/mastodon/issues/2019 . Thanks again @thomaskuntzz – I'll take a look at adding this once we get some UI input from the project developers 👍
