### ISSUE TITLE
Is there a way to see a list of our favourites?

### ISSUE THREAD

**Issue by nevillepark** [tootsuite/mastodon#238]
Maybe it's really obvious and I'm just missing it. But if there isn't, there should be.

**Comment by clhendricksbc** [comment]
Yes! As Mastodon gets larger and we are involved in more conversations, I find myself wanting to star something to go back to later to reply to a conversation thread that it will be hard to find otherwise because my "home" stream is filling up! Big thumbs up for this one to be implemented quickly if possible!
