### ISSUE TITLE
"Something went wrong" error message when viewing "Authorised apps"

### ISSUE THREAD

**Issue by imshyuan** [tootsuite/mastodon#2411]
I noticed the said error message in v1.2.2. I'm not too sure when this error starts to appear. But on both of my Mastodon instances, the same issue exists.

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by imshyuan** [comment]
Both of my instances were upgraded from v1.1.2 a few days ago.

**Comment by mjankowski** [comment]
Can you show us a server log with the exact error?

It might be this issue which was introduced by me here - https://github.com/tootsuite/mastodon/commit/532bec6e564884c2bd5b2bcc7cab929f4f2cabf5 -
 and fixed by me here - https://github.com/tootsuite/mastodon/commit/092fdc89fa5b2a1ba2ac0a0dfe5149814a179ec8 (4 hours ago)

**Comment by Gargron** [comment]
This should be fixed.

**Comment by imshyuan** [comment]
Hi @Gargron, I don't get what you mean by "this should be fixed". Did you mean it will be fixed in the next release?
