### ISSUE TITLE
Feature request : Poll to ban/exclude an instance

### ISSUE THREAD

**Issue by foxmask** [tootsuite/mastodon#2499]
Hi,
It will be nice if we could poll to ban an instance that is very annoying for us ( or even does not match the policy of  the current instance)

By "we" I mean the users, when it's too anoying, then the admin could take a decision related to the poll
I dont know if we could start a poll by on our own, or If a button beside a given user could be used to exclude the instance from where he comes from

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by mjankowski** [comment]
There is WIP for a user-controlled instance block.

Instead of a poll, it might be nice to expose to the admins "here are the most-blocked instances by your own users", to help them in determining if/when to add a full-on instance block of the remote instance.

**Comment by foxmask** [comment]
if you think the admin can guess that, then ok ;)

**Comment by yiskah** [comment]
We could also just add... polls... and not specifically polls about instance blocks

**Comment by Cassolotl** [comment]
I'd love that. :D That'd be #1629 (Polls) - and instance-only polls could combine nicely with the possibility of making posts that make it to the local timeline but are not federated out to other instances, which is #861.

**Comment by yiskah** [comment]
yeah it's important that this kind of poll isn't public to remote users as it sure would stir up drama

**Comment by fsnk** [comment]
What @mjankowski suggested. Being able to see what users/instances are being most blocked could be a useful metric for picking up on issues. (Especially in the absence of user reports.) 

Though I wouldn't assume because an account (or instance) has a high rate of blockage it automatically indicates a behavior issue. If you see a lot of blocking of botsin.space, for instance, it could just be that many users aren't interested in most bots, but there's nothing problematic occurring and users are capable of filtering it themselves.

**Comment by Gargron** [comment]
>We could also just add... polls... and not specifically polls about instance blocks

Agree. This is too specific to be a feature.
