### ISSUE TITLE
Browser back button loads timeline without posts from push update

### ISSUE THREAD

**Issue by fap-** [tootsuite/mastodon#2593]
Reproduction:
1. Load https://mastodon.social and wait till the timeline updates with a new post.
2. click on link in a profile for an hashtag [0] -> loads in same tab
user profile used for test: https://mastodon.social/web/accounts/11282
3. hit "back" button <- in browser

[0] eg., https://mastodon.social/tags/nobot

Expectation: Mastodon loads with the new posts that got loaded after initial page load

Actual behavior: timeline reloads in initial state, without the posts that where loaded after initial page load

Browser: Chromium Version 58.0.3029.81
Mastodon Version: 1.3.1

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Kimik0** [comment]
This issue is worded kinda confusingly. What I see happen is
* usually, clicking the "Back" link at the top of the rightmost column returns to the previous thing that was shown in that column, regarless of what links were clicked to get these views
* in case of hashtags though, clicking the "Back" link instead returns to the "getting-started" state, not what was previously shown in the column

(that's v1.4.0.4 btw)

**Comment by fap-** [comment]
This is confusing since mastodons behavior changed since I've reported this.
When I was talking about the "Back" button I meant the browser button, not the back button in the mastodon UI.
Also hashtags now seem either to be opened in the third column or in a new tab.
I couldn't come up with a scenario where a link is opened in the mastodon tab so I'm closing this for now.

**Comment by Kimik0** [comment]
Eh? But it is a bug. The "Back" link usually behaves just like the browser's back button. But for hashtag searches it doesn't. Guess I'll open a new issue then.
