### ISSUE TITLE
Empty home timeline after period of inactivity

### ISSUE THREAD

**Issue by robcee** [tootsuite/mastodon#2619]
Didn't log in for a week. Came back and my Home timeline was empty. Also seen on Tusky.

Whatever mechanism caches a person's Followed toots doesn't seem to work if not actively logging in.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ashfurrow** [comment]
Interesting. Thanks for opening an issue to let us know – could you go to the "Extended Instance Info" page and let us know what version number is in the bottom right corner (if it's there at all, it might not be)?

**Comment by adamipc** [comment]
I had this same issue, and possibly related, my home timeline doesn't load most new toots unless I hit shift+reload in my browser.

**Comment by wolfteeth** [comment]
I just bumped into this issue on an instance I hadn't logged into for a month or so. It's still pretty bewildering, and probably discouraging for users who haven't logged in in a while. The obvious conclusion to come to is "no one has posted anything since I've been gone" which leads to the not-necessarily-truthful impression that their friends are all inactive.

At the very least it seems like their timeline should collect and hold onto a certain amount of recent posts to avoid this. OR the timeline should clearly communicate that it is regenerating, and then actually regenerate -- not just start following again at the moment the user logged in.
