### ISSUE TITLE
Emojis on RTL stylesheet

### ISSUE THREAD

**Issue by BoFFire** [tootsuite/mastodon#2645]
Hi, noticed an issue on both Desktop Mozilla Firefox and Chromium Web browser
![Screenshot](https://pic.op.tn/SAcRnY0w/QItPgtA2.png)

**Comment by ashfurrow** [comment]
Yikes, thanks for opening an issue!

**Comment by mabkenar** [comment]
I confirm this bug on Mastodon 1.3.2 running on https://social.tchncs.de/.
However, this issue is fixed in master, or at least in whatever version [glitch](https://glitch.social/) is running (which I believe is very very close to master). See below:

![selection_195](https://cloud.githubusercontent.com/assets/3006332/25748509/9eefe502-31ab-11e7-851c-ce679daac910.png)

**Comment by BoFFire** [comment]
Hi @mabkenar :) Yep, I confirm : on Glitch instance, it seems okay :)
Can we close this issue ?

**Comment by mabkenar** [comment]
Yes please :)
