### ISSUE TITLE
UI performance regression since v1.3.0

### ISSUE THREAD

**Issue by codl** [tootsuite/mastodon#2648]
Since v1.3.0 the web ui is very slow on chrome for android, on my oneplus 3t it often takes over five seconds to expand a toot or switch to a different tab

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by kyzh** [comment]
I have the same story here on oneplus1, firefox.
I'm also having more firefox crashes, which were non existent before.
Do @ me here or in mastodon.social if you need more data or help to test a PR

**Comment by nolanlawson** [comment]
I'm not seeing anywhere near 5 seconds for expanding a toot in Chrome 57 on Mastodon V1.3.2 (more like 1-2 seconds) but I am interested to look into this.

**Comment by nolanlawson** [comment]
Well I tested this on a Nexus 5 Running Chrome 37, on toot.cafe (currently Mastodon 1.3.2). The first one is switching from the "*" menu to the notifications, and the second is expanding a toot.

![screenshot 2017-04-30 16 31 05](https://cloud.githubusercontent.com/assets/283842/25568998/b44bc71e-2dc2-11e7-9554-5337a0f523f6.png)

![screenshot 2017-04-30 16 31 59](https://cloud.githubusercontent.com/assets/283842/25569000/b8968bc4-2dc2-11e7-8514-5624ee300aec.png)

A bit impenetrable since most of it is framework code (to me anyway; I'm not experienced with React), but I do recognize some expensive layouts/style recalcs (the purple part). Unless it was something that changed in Mastodon's CSS or DOM structure, it looks instead like something may have changed in the React part. I'd have to have a v1.2.2 server to compare against, though.

**Comment by codl** [comment]
if it helps I recorded [a chrome dev tools profile](https://f.codl.fr/1705/Profile-20170502T202645.json) of chrome freezing for 35 seconds (!) while switching to the home tl

**Comment by Gargron** [comment]
I believe v1.3 is where we added a thing that hides some columns instead of unmounting them, when switching between them, which makes them keep their scroll position without a repaint (which was source of a ~100ms lag prior). Could this be it? Storing lots of hidden elements in the DOM instead of unmounting backfiring/crashing on phones?

**Comment by borisulianov** [comment]
Not sure if it helps, but I can confirm this behavior in SeaMonkey 2.4x. In mstdn it eats lots of CPU instead, but the UI is fluent AFAIK.

**Comment by nolanlawson** [comment]
@codl According to that trace you posted, the browser was blocked on the network for 35 seconds, not the UI:

![screenshot 2017-05-04 19 23 36](https://cloud.githubusercontent.com/assets/283842/25731913/4c14109e-30ff-11e7-8266-3510f618b786.png)

In particular it was waiting on two requests for `/card` and `/context`. May be a server-side problem with `chitter.xyz`.

**Comment by Gargron** [comment]
I just realized why the UI would start eating CPU so much. It's obvious in hindsight. Even if the part of DOM in question is invisible, if it's a mounted React component, it will get updated. Having the local timeline, public timeline, etc etc be secretly mounted means they're all getting updated at the same time. This might be reason to revert #2271? Perhaps there is an alternative way to avoid the scroll layout lag?

**Comment by nolanlawson** [comment]
Is there a way to tell React to de-prioritize those hidden components and then update them using [requestIdleCallback](https://developer.mozilla.org/en-US/docs/Web/API/Window/requestIdleCallback)? Skimmed the React docs, but it seems the answer is no. In that case maybe it is worth it to unmount for the memory/CPU savings even if it's a bit more expensive to switch views.

**Comment by fceschmidt** [comment]
I am noticing this issue too. If I look at the federated TL on hex.bz the CPU usage goes up to 90-100%, and stays there until I close the tab. It's really making my 8 year old notebook unresponsive.

**Comment by nolanlawson** [comment]
Can you post a trace by any chance?
