### ISSUE TITLE
I need a simple message

### ISSUE THREAD

**Issue by xor256** [tootsuite/mastodon#2662]
Private simple text message to other user

**Comment by ashfurrow** [comment]
Hi there! You can select message audiences from this dropdown:

<img width="285" alt="screen shot 2017-04-30 at 9 03 57 pm" src="https://cloud.githubusercontent.com/assets/498212/25567182/8b854410-2de8-11e7-87db-847ff83d6b6e.png">

Use "direct" to go only to the other user. Be aware: the privacy of these messages isn't guaranteed.
Your post will be delivered to mentioned users. Post privacy only works on Mastodon instances. If the user is not on a Mastodon instance, there will be no indication that your post is not a public post, and it may be boosted or otherwise made visible to unintended recipients. So don't send private information over direct messages. 

Does that answer your question?

**Comment by xor256** [comment]
in my account not working i can only send message to mastodont, normal toot
i 'm not have any other options.

I have polish translation settings but only some settings is in polish language. 
![screen](https://cloud.githubusercontent.com/assets/17579697/25717506/f429a354-3102-11e7-92f8-fddbbd42d0a0.png)

**Comment by rysiekpl** [comment]
@xor256 the settings are under the little "globe" icon, not the toot button. @ashfurrow's screenshot is a bit unclear, admittedly.
