### ISSUE TITLE
Typo on Edit Profile

### ISSUE THREAD

**Issue by Cassolotl** [tootsuite/mastodon#2678]
Another minor thing. :) On /settings/profile:

![screen shot 2017-05-01 at 10 53 52](https://cloud.githubusercontent.com/assets/6607512/25577231/83f8be60-2e5c-11e7-8164-62140a9b4ba2.png)

When the number of characters remaining is 1, it should say "character" instead of "characters".

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by stephenburgess8** [comment]
Ideally, we would dynamically set the word character to change from plural to singular when the count reaches one (or negative one?). That doesn't seem straightforward, and may become odd to translate into other languages since languages will likely treat pluralization different in this case.  Embedding dynamic content in sentences makes it hard to translate, though with Mastodon's open source translating going on that may not be as significant of a problem. 

Here's the line where that text is set in English: https://github.com/tootsuite/mastodon/blob/master/config/locales/simple_form.en.yml#L10

What about changing it to `Characters left (1)`? 

https://ux.stackexchange.com/questions/81814/should-i-use-singular-or-just-default-plural-in-labeling-the-followers

**Comment by Cassolotl** [comment]
Yeah, something like "Characters remaining: number" would be fine!

**Comment by akihikodaki** [comment]
Closing with #2685.
