### ISSUE TITLE
Admin option to "mute" a user, blocking them from federation

### ISSUE THREAD

**Issue by lynncyrin** [tootsuite/mastodon#2691]
idea sourced from `@kaniini@mastodon.dereferenced.org`

As an admin I would like the option to block a user from federation when they are engaging in behavior that is harmful to the federation, but not breaking any local rules

So when I can federation mute `@MeanUser@lynncyrin.me`, so that when they mention `@small_child@mastodon.social`, `@small_child` doesn't receive any notifications.

This ideally would come with a new profile value that shows that a user has been blocked from federation, something like `a field to webfinger, "muted": [true|false]`

---

> in your own house, if you want to break all the pots your plants are in, it's fine.  right?
> but if you go to your neighbour and break their plants, they are going to be upset.
> it's the same thing here.

^ there are different rules for breaking pots in my own house, versus in neighbors houses. that's the justification for creating this feature

---

Similarly to https://github.com/tootsuite/mastodon/issues/1284, this option should come with a timed variant

**Comment by Chronister** [comment]
To elaborate based on the discussion around this topic, the local effect of this would be to simply not push their statuses to other servers and maybe not return their post-mute statuses when other servers request their activity stream.

The purpose of the new profile field would be to expose this mute status to other servers so that they can display to their users that the remote account on your server is muted, and they will not receive new statuses, in order to prevent users from being confused if one of their follows seems to stop producing new statuses.

**Comment by rainyday** [comment]
I'm concerned this will break backwards compatibility with current versions of mastodon or other platforms to a degree since to anyone without support of this new muted field will just see the muted user suddenly stop sending or receiving messages with no explanation. Changes that cause problems with backwards compatibility like that should be done extremely sparingly and this just doesn't seem worth the problems it will cause to me.

**Comment by yiskah** [comment]
I'm not entirely sure what this would accomplish rather than just sandboxing your user. Is this like sandboxing them from other instances but not your own? Could you better elaborate who is applying the mute and what that does? What's the use case for this? Could you elaborate?

**Comment by mal0ki** [comment]
Similarly to @yiskah I actually thought that sandboxing served this purpose. 

@lynnco could you elaborate please, in case there is a misunderstanding on what you are requesting, and what is already available?
