### ISSUE TITLE
Change text of the "NSFW" feature to "Hide Image" or similar

### ISSUE THREAD

**Issue by lynnco** [tootsuite/mastodon#2696]
The label "NSFW" is not suitable for the feature's use case, for several reasons

- In practice, I have never hidden an image because it was "Not Safe For Work", I hide the image because it contained sensitive content. I believe this aligns with other people's use of this feature
- What is / is not safe for work depends on differing cultural contexts. Is me wearing a tank top NSFW somewhere? Mastodon is quite good at not requiring users to think outside their default culture context, but the NSFW button is the exception to that
- The word NSFW is, in general, used to hide erotic content. This is made explicit in an existing PR, even https://github.com/tootsuite/mastodon/pull/1974. The thing about that though, is that for sex workers erotic content is not NSFW, **erotic content is their work**. This goes beyond a mere semantics argument, its actually a tactic used to silence sex workers (the overwhelming majority of whom are women, which makes this issue functionally misogynist)
- ([I'm told that](https://toot.cat/@polymerwitch/456191)) the NSFW button does not have a translation option, so any resolution to this issue should also add this button to the translation interface

And just to be totally clear, my suggestion is that "NSFW" be changed to something akin to

* sensitive image
* hide image
* hide
* CW imagery

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [N/A] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by noiob** [comment]
This also makes the button easier to understand. The current CW/NSFW buttons are a bit confusing in my opinion, since it's not clear whether CW hides images or not, for example.

**Comment by lynnco** [comment]
@noiob I believe that's a separate issue that may be noted already. I definitely think that adding a CW to a post should auto-apply the hidden image feature

**Comment by fwenzel** [comment]
Looks like atm, this isn't localized at all either: https://github.com/tootsuite/mastodon/blob/1948f9e767c5c8f7cb52337ce777a61b5ad1a599/app/assets/javascripts/components/features/compose/containers/sensitive_button_container.jsx#L34

That does not work in an international context at all (I guarantee, very few non-English speakers have any clue what NSFW means).

How about an Icon + meaningful hover title?

**Comment by noiob** [comment]
Yeah, I know that's mostly a separate issue, just wanted to point out another reason for this change.

**Comment by fwenzel** [comment]
Besides, the dark image overlay is *already* called "sensitive image".

**Comment by gleneivey** [comment]
Agree both with the intent of changing it from the acronym (you don't know what my work is like PLUS I'd like to see it used for content that would be disturbing whether I was at work or not), and that if it is going to be touched, it should be made localizeable.

**Comment by noiob** [comment]
Something like this might be a useful icon, in combination with a good hovertext:
![hide-48](https://cloud.githubusercontent.com/assets/8197071/25598456/70bb3bce-2ed5-11e7-9183-10ece85a92a1.png)

**Comment by Vavassor** [comment]
I think most of the reason for the change from a "hide sensitive media" toggle to "NSFW" was to make an icon-sized shorthand.

I've talked about this for [Tusky](https://github.com/Vavassor/Tusky)'s interface and folks have suggested something like a dotted-line camera icon. I liked that because it implies the media will hide and not necessarily anything else.

Sidenote: in Tusky the media button is a paperclip for "attachment" and a dotted-line paperclip was totally unrecognizable, so I didn't go with that.

**Comment by Gargron** [comment]
Needless to say it was not intended to be anti-sex-work. I just took over an existing concept as it existed on reddit, twitter hashtags, tumblr tags etc. Funnily enough Japanese translators had an issue with that term as well, since apparently it's not a well-known concept in Japan because people generally don't browse any non-work-related sites during work time. So it probably needs to be changed anyway? But there isn't a lot of space in that area, which is why I opted for abbreviations instead of text. A crossed-out eye is definitely an icon but I know if I saw it for the first time I would be confused, at least with NSFW I immediately know what is meant (but again, that's different depending on experience)

**Comment by lynnco** [comment]
I like the crossed out eye, but want to propose the "no photography" icon as another alternative
![191688-200](https://cloud.githubusercontent.com/assets/5768468/25598808/0ae56ee4-2e8c-11e7-8b53-dfc703e144d0.png)

**Comment by ginsterbusch** [comment]
There is indeed no real translation for this in German. Would translate as "Ungeeignet für die Arbeit" or "Nicht während der Arbeit ansehen", which is giving it a totally different meaning (the first one: "content unusable for work", the second one: "Not to be watched during work").

@lynnco "no photography" is rather weak .. or even strange. "Do not make screenshots of this"? Maybe just use the "Missing Image" / "Broken Image" icon lots of browser display.

cu, w0lf.

**Comment by ghostfromicosahedron** [comment]
changing it to "hide image" seems like the most common sense approach, and i think this is an excellent idea that needs to happen. "sensitive image" might be a more consistent way to do it, since that's what the hidden preview says, too. my preference is "hide image."

i've never hidden an image because it's not safe for (most) workplaces, but i've hidden them because they're punchlines, to save bandwidth, or just to incorporate it into a CW'd post. anyway, i also see more non-sexual NSFW posts than sexual NSFW posts.

NSFW is definitely the well-known terminology, but in light of it being anti-sex work, and in light of the way the feature is actually being used now that it's been around awhile, it's time to rename it.

**Comment by stephenburgess8** [comment]
UX researchers often test questions like this rather than relying on people's opinions. A researcher would take two protoypes, for instance one with NSFW and one with "Hide", and have some users try them out to get their opinions. 

I like the idea of "Hide" as opposed to "NSFW." NSFW speaks to the nature of the content, but there are many other good reasons to hide an image. As early as 1999, [LiveJournal](http://www.livejournal.com/support/faq/75.html) had <lj-cut> and <lj-spoiler>, which were more about the action of hiding than addressing the nature of the content. Coming from an experience like that, having this feature known by its action rather than the content would be familiar to me.

Iconography has different meaning across different cultures, so you can't be sure your meaning will get across if you use icons without labels.

**Comment by Kimik0** [comment]
I agree that it should be changed to something other than "NSFW", for both reasons (anti-sexwork & not-quite-translatable).

For an icon, the slashed 👁 is more understandable than the "no photos" one. If the icon to add images is a 📷, then a 📷 + 🛇 naturally means to remove images, which isn't what is intended.

There's also the related issue #1010 that the NSFW and CW features should really be merged into one interface item.

**Comment by Cassolotl** [comment]
How about a rectangle with a cross through it? I'm thinking in terms of... this is going to be a small button, so it needs to be accessible for people - folks need to not be squinting in order to understand it!

![image strike](https://cloud.githubusercontent.com/assets/6607512/25614128/9f07f758-2f28-11e7-8c3f-ee6f7c145b68.png)

**Comment by fsnk** [comment]
"Hide" isn't any longer than "NSFW" and if there's a tooltip that says "hide sensitive or adult images" function should be clear.

I agree that NSFW doesn't really cover the usage, it also doesn't immediately suggest to people to use it non-adult material.

One thing I *do* like is the ability to CW & NSFW separately. I thought it was non-intuitive at first, but now I think it's a good design choice in practical use.

**Comment by ginsterbusch** [comment]
@Cassolotl yep, that was exactly my thought. but I didnt want to kick-start an a11y discussion :)
thus the idea with the classic "broken" or "crossed image".

cu, w0lf.

**Comment by joyeusenoelle** [comment]
With an icon (like the crossed-out eye or camera icons) there's a secondary concern: is the icon intended to represent the *current* state or the *target* state? In other words: if I upload an image and see a crossed-out eye, does that mean the image will be hidden without further input from me and I can click the eye to un-hide it, or does that mean I have to click the eye to make the image hidden?

In the default UI this can be accomplished by changing the color of the button - but Mastodon accepts different styling that may override that behavior - and/or by using mouseover text. 

Just something to consider.

Also worth noting: **noiob**'s suggestion bears a strong resemblance to the [Material Icons "visibility off" icon](https://material.io/icons/#ic_visibility_off); if we're willing to include Material (Mastodon may already and I just don't see it), then that set includes a standard "visibility" icon as well (the same eye, not crossed out).

Synthesizing this, I propose: 

* The default state is "unhidden". The button has the Material "visibility eye" icon, with the mouseover text "Label this as a sensitive image (currently: not sensitive)".
* Clicking the button changes the state to "hidden". The button has the Material "visibility off" icon, with the mouseover text "Do not label this as a sensitive image (currently: sensitive)".
* Clicking the button again returns to the "unhidden" state.

Does that make sense?

**Comment by Cassolotl** [comment]
I just want to emphasise that these icons will be very small and must be usefully visible to folks with less good eyesight! For example, here's the crossed-out-camera icon, at 25px, which is about the same size as the other icons in that area seem to be on my laptop:

![nophoto](https://cloud.githubusercontent.com/assets/6607512/25766828/f9f1bd36-31ec-11e7-9c22-6b525320c75d.png)

**Comment by nightpool** [comment]
yes, icon design is complicated and this is why we should use existing designs where possible. here's the matdes visibility off icon at about 20px:

<img src="https://cloud.githubusercontent.com/assets/233815/25767573/af1c312a-31c8-11e7-94f3-ecac45a19294.png" height="40px">

**Comment by lynnco** [comment]
I'm working on this now, PR inc

**Comment by lynnco** [comment]
The PR for this issue is https://github.com/tootsuite/mastodon/pull/3759
