### ISSUE TITLE
Render 'old school' emoticons as emojis

### ISSUE THREAD

**Issue by jeroenpraat** [tootsuite/mastodon#2708]
When someone uses :-) ;-) :-( ;-P :-D etc, they are not rendered in a toot as corresponding emojis. Can this be fixed? We don't need the complete set of emoticons, only e.g. the most used (starting with western and Japanese style). https://en.wikipedia.org/wiki/Emoticon

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Cassolotl** [comment]
I dislike this. So if it happens, can it be a toggle setting?

**Comment by Kimik0** [comment]
I don't think this is a good idea.

Too many variations are possible to cover even a fraction of them. For eyes, there's : ; 8 B etc. For a nose - o O ` or nothing. For a mouth there's a bazillion options too, and then there are reversed ones to make the meaning of D different. Same with vertical-oriented ones.

But more importantly, people use these text emoticons instead of emojis because what an emoji conveys depends on the exact set of emojis used on the recipient's end. Take a look at some of the entries at http://emojipedia.org/people/ . Often different vendors' emojis have rather different expressions that don't quite match. If I use ^_^; it'll look like an embarrassed smile regardless of what the recipient's vendor thinks 😓 or 😅 should look like.

**Comment by Cassolotl** [comment]
What Kimik0 said. Typed emojis are good *because* the software doesn't change it into something else on your behalf!

**Comment by jeroenpraat** [comment]
Yes maybe you are right when people use Japanese style emoticons, but using :-) ;-) or :-( is for a lot of people here in the West normal to use in text nowadays. Almost every social network, mail app and IM app is rendering it do an emoji. So I don't see any reason why Mastodon shouldn't offer this.

**Comment by Cassolotl** [comment]
The apps that do this, I've turned it off so that the app doesn't change my typed characters. If I want to send an emoji (picture) I use the emoji keyboard, which is built into the app.

So, if this is added, I would like it to be an optional feature.

**Comment by Gargron** [comment]
I always disable this kind of feature. If I type text, I want it to stay text. If I wanted an emoji, I'd either paste the unicode or use the shortcode. I won't make this.

**Comment by jeroenpraat** [comment]
Let it than be a feature request for someone else. As an option, not default. I never asked you had to do it @gargron. Please re-open.
