### ISSUE TITLE
Popular or trending hashtags

### ISSUE THREAD

**Issue by Thann** [tootsuite/mastodon#271]
I think it would be cool to be able to see some of the most popular hashtags of the last 24 hours. It could fit nicely at the top of the "public" panel.

**Comment by lou1306** [comment]
Just my two cents, which I tooted some days ago:
* Instance-level trending list should not be so difficult. Basically, replicate what TrendingBot already does and integrate it in the UI.
* Could an (eventual) "federated trending list" construction be seen as a distributed consensus problem? With instances exchanging their local trending lists until convergence is reached?

**Comment by erinarbleizez** [comment]
yes federated topics would really be great (as trending topics on twitter is a good way to know what is happening now) and would not be that difficult to implement:

federated timeline already share toots, they can share their local TT with number of toots. We merge duplicate at reception
When we want to show TT, we just need to sort and take the last 10 (or any number we want)...

**Comment by erinarbleizez** [comment]
for information I have an almost working Federated Trending Topics  SQL Request:

for that I use this sql request:

select name,COUNT(name) from statuses_tags left join tags on tag_id=tags.id left join statuses on statuses.id=status_id  where statuses.updated_at >= NOW() - '1 day'::INTERVAL group by name order by count desc LIMIT 10;

problem, I don't know how to put it on top of the federated timeline ><

**Comment by wxcafe** [comment]
Updates on this? Is this something we want to implement in mastodon @Gargron ?

**Comment by hhassey** [comment]
Reading the other **Feature Request: Trending Topics #1473** tread, It seems that this was abandoned due to privacy reasons?, I have no idea why it messed with privavy, but seems that Mastodon really needs this feature at least on the local server. @Gargron any updates on this?

**Comment by mbajur** [comment]
What's up with that? Would you accept a pull request for a local trending topics?

**Comment by Cassolotl** [comment]
I feel like this new site I found out about today might be relevant to our interests. :) https://mastodon-tags-explorer.hcxp.co/

**Comment by picsi** [comment]
A Fediverse-wide list would be pretty awesome

**Comment by sirjamesgray** [comment]
Anybody have any thoughts on this as the interface for this? Any feedback or changes you'd like me to make? 

to summarise the sketch:
- use the empty search page to show trends 
- split up trends by timeline; Home, Local, and Federated
- for each row item, show: (1) trend text (2) number of posts in past hour* (3) sparkline of past hour*

*hour, 24 hours, etc, whichever we decide.

<img width="1171" alt="screen shot 2018-05-24 at 4 51 26 pm" src="https://user-images.githubusercontent.com/16139439/40516179-43fb9a62-5f75-11e8-9d02-42361c69e6cc.png">

Also, for those interested, I've added this as a [blog post](https://jamiegray.net/ux-ui/mastodon-trends), with some gifs of the sketch and stuff.

**Comment by renatolond** [comment]
Home trends would be trends of people you follow? I feel like it might be a bit empty, unless you follow lots of people.

Federated trends are partial (since it's very unlikely the server sees the whole fediverse) and I feel that the interface should reflect that somehow (the same way there's the "profile might be incomplete" message when you see a profile of someone from another instance)

**Comment by Gargron** [comment]
@sirjamesgray I really like your mockup and animation.

**Comment by hhassey** [comment]
Home trends should be from the whole home server, not only those who you follow. I think the main reason to have trending topics is to be able to jump into threads that you may not know are going on and you are interested in, as well as to meet new people.

**Comment by sirjamesgray** [comment]
perhaps this feature could not only show hashtags, but trending words (like what twitter does) so it can populate more data (especially for Home and Local timelines) 

Obviously we'd remove common language like "the" and stuff like that. 

Also, in alignment with the whole concept of mastodon's openness, we could have an info button to show the methodology (and code) used to identify these trends.

**Comment by Cassolotl** [comment]
Mastodon deliberately doesn't have text search for all available toots, only hashtag search, so I'm not sure that would work?

**Comment by trwnh** [comment]
would rather NOT have simple text tracked in the same way as hashtags. tracking words implies low-level analytics that users don't explicitly consent to, and by having words be visible as trends, it implies that loading the results would perform a full-text search for that term across all accounts.

**Comment by Gargron** [comment]
@sirjamesgray Any idea where that section would/should go on the desktop layout?

**Comment by sirjamesgray** [comment]
@Gargron we could show the top trends in the search pop-up on desktop, and clicking on the header would open up all trends in a column view, and clicking on a trend would open up that trend in the column view. 

( the ↗️ icon probably doesn't make sense here since opening a column isn't an external link, but we should find some way to communicate to the user that clicking the header will open up all trends in a column view ) 

<img width="1039" alt="screen shot 2018-05-28 at 12 20 23 pm" src="https://user-images.githubusercontent.com/16139439/40624629-4372f2f6-6273-11e8-844d-6e8b47be9704.png">

<img width="745" alt="screen shot 2018-05-28 at 12 20 28 pm" src="https://user-images.githubusercontent.com/16139439/40624634-45cee622-6273-11e8-8c09-b65b50d10fe7.png">

would you like me to post this answer in the other issue that we merged this into?

**Comment by trwnh** [comment]
re: those suggestions

1) the default layout already scrolls on some screens, especially at around 1200px wide (say, if you have a 1280x720 monitor, or a vertically rotated monitor). one more column doesn't really feel like *too* much extra.

2) can display only a few trends, if you're worried about the absolute height of the viewport.

3) assumes that putting a button into the Getting Started column isn't enough discovery, but it includes many navigation and settings links that are seemingly important.

If you're trying to reduce the size of the GS column then consider which elements are less important than others, and if any can be moved elsewhere. For example:
- "Keyboard shortcuts" can be moved closer to "FAQ / User guide / Apps"
- So can "About this instance", but even moreso because it doesn't actually load inside the webapp and instead redirects to a different page
- "Pinned toots" can perhaps be managed from the profile view
- "Preferences" and "Logout" are redundant with the buttons in the upper left

**Comment by Thann** [comment]
Thanks for the adding this feature! <3

Adding "Trending tags" to Getting Started makes the most sense to me =]

**Comment by koyuawsmbrtn** [comment]
I can agree to @trwnh. The getting-started column needs cleanup if a lot of features are getting added. Otherwise it will be bloated pretty easily.

**Comment by kensanata** [comment]
I just saw the announcement and heard that it was counting each *use* of a hashtag. My fear is that it will lead to bots trending ([#bbc](https://mastodon.sdf.org/@cosullivan/100122461927571375)). I saw that we also have this number: "total times the hashtag has been used during each day, and by how many unique people" and I'm thinking: wouldn't the number of unique people using the hashtag be a better measure of trending?

**Comment by Cassolotl** [comment]
Admins have the power to make bots post unlisted, right? And account owners and admins are able to mark accounts as bots, so perhaps there can be an instance setting for admins - "include bots in hashtag counts y/n?"

**Comment by kensanata** [comment]
Maybe. I’d still ask, though: when would we ever want bot tags to trend?

**Comment by Cassolotl** [comment]
If their hashtags varied over time, maybe? I know there are newsbots that automatically include tags from articles, and there's usually a few, and they vary from article to article. I'd probably want to see those articles posted by bots in the hashtag searches and trending topics.

**Comment by kensanata** [comment]
Hm. Indeed a tricky problem. I'd like deforestation and SoutheastAsia to trend, maybe even environment and asia, but news? That's as annoying as seeing bbc trend only because the bot is posting so much. So perhaps we just need a way to kick certain hashtags out of the list. Or perhaps that also leads to a lot of work for admins as they keep maintaining this list as new bots (and spammers) join the federation. I'm out of ideas. That makes me think that perhaps counting hashtags only once per person and day is best, i.e. "total times the hashtag has been used during each day, and by how many unique people".

**Comment by Gargron** [comment]
So this feature is in an RC right now and I am expecting to gather feedback from people when it's in production use. So yeah some parts of it may totally change yet.

**Comment by johynpapin** [comment]
Maybe one solution to this problem is to also count the boosts and favs of the toots of the hashtag?
That may not be possible, I still do not fully understand the complexity of the system.

**Comment by Laurelai** [comment]
Since were being asked to comment here on the validity of the feature itself i think people failed to realize what an exploitable vehicle for harassment this is.

**Comment by Laurelai** [comment]
Examples of the kinds of abuse that can happen with it are rampant on facebook and twitter and im not sure why anyone thought this would be a good idea. Admin control over tags is not enough as then you leave it up to each instance admin to moderate out things that incite targeted harassment , and if they are willing by the time its sorted it might be too late, they can also abuse those tools to pick and choose things that arent harassment/evil content just to manipulate the userbase. Plus the admins might be party to the harassment, or indifferent. Theres entirely too many "free speech" instances that would use this feature to harm others while the admins stood by and did nothing. 

Ive been a victim of cyber harassment mobs on and off for years and this is the kind of feature they love to see on websites because they can use it to hurt people. Its also a feature factions of various kinds love to see because they can game it to give their pet cause attention. Its all fun and games until some psychopath forces your dox into the trending tags.

**Comment by jh4c** [comment]
The whole concept seems antithetical to the mission of Mastodon. Trending topics are abused on every platform they have been implemented, and I cannot think of one decent use case to support adding them. We already have the ability to track and search for hashtags, why was this ever considered at all, let alone considered to be a good idea?

**Comment by lawremipsum** [comment]
As an admin I don't want to babysit federated trends for abuse, propaganda, or other unwanted content, which is among the reasons I asked for an off switch in issue #7702.

I add my voice to those that think this is an anti-feature and would rather it not be added. In my view, the negative effects (potential for abuse, gaming, and other unwanted, anti-community behavior) outweigh the benefits (it's neat).

Importantly it doesn't help any user discover users of toots relevant to things they are already interested in. It only draws focus to things that are already (becoming) popular. That is, it doesn't solve a problem that needs to be solved.

But if it needs to be added, it should be off by default and opt-in on the instance-level to whatever degree that is feasible. I agree that by adding a hashtag to a toot you're effectively opting in, as a user, to Mastodon's various hashtag-based discoverability features. But on the same token, if instance admins don't want to contribute to trend-oriented social media use patterns, that option should be available.

**Comment by simplyginger** [comment]
I feel as if this won’t be useful for community building at all. I agree with the points raised by Laurelai as well. 

People will use this for publicity and trying to build up their followers much more than they will use this for engagement. We already can search hashtags and explore that way, why should we add this?

**Comment by Laurelai** [comment]
Plus as it stands switter will absolutely dominate the trending tags on most days. I like switter, but it might draw the wrong sort of attention to them.

**Comment by Gargron** [comment]
>Plus as it stands switter will absolutely dominate the trending tags on most days. I like switter, but it might draw the wrong sort of attention to them.

This is not true on technical grounds. If a hashtag usage is constant, it won't trend, no matter how high the volume is. Only things that rise unexpectedly appear as trends.

**Comment by Laurelai** [comment]
Ok well its good switter wont trend all the time, the rest of my points still stand however.

**Comment by SelfsameSynonym** [comment]
What problem is this supposed to solve again? It’s not going to help people discover new things or users, it’s not going to make timelines easier to follow, it’s just going to add a way for people to try to manipulate the program into promoting their pet cause whether it’s targeted abuse or social engineering. 

Is the point to make mastodon more like Twitter?

**Comment by Thann** [comment]
> It’s not going to help people discover new things or users

This assertion is baseless and absurd

**Comment by Thann** [comment]
> Is the point to make mastodon more like Twitter?

Yes, but only the good parts obviously, and if you don't want trends, turn them off for your instance =]

**Comment by johynpapin** [comment]
I think it's important to note that it's not "trending toots" but "trending hashtags".
I'm not sure which way to go. I am currently testing this function on the instance where I am, and I find it interesting and practical.
@Gargron said in https://github.com/tootsuite/mastodon/issues/7702 that gamification features are what keep social networks alive (in other words people want to have fun). I agree with that.
However, it is true that this is one more vector for harassment, although it is VERY limited by the fact that it is not "trending toots".
I'm waiting to read more arguments to position myself.

**Comment by inmysocks** [comment]
I think that this is a horrible vector for abuse. Sock puppet accounts are already easy to make on mastodon and this is going to amplify their power and create a mostly unblock able harassment vector. Also I am not sure what trending tags adds to mastodon. I think that a tag cloud that shows all hashtags that have been used more than some threshold in the past (either full history or past 24 hours/week/whatever) is a much more useful tool in terms of discovering new content and in terms of understanding the feel of a community.

In my experience trending hashtags are only mentioned when they are used as advertising or harassment vectors.

Also people on mastodon don't see exactly how the trending tags are determined which hurts the transparency about how mastodon works which is one of the best features.

**Comment by Gargron** [comment]
>I think that a tag cloud that shows all hashtags that have been used more than some threshold in the past (either full history or past 24 hours/week/whatever) is a much more useful tool in terms of discovering new content and in terms of understanding the feel of a community.

Besides you calling it a tag cloud I am having difficulties understanding the difference to the current algorithm.

>Also people on mastodon don't see exactly how the trending tags are determined which hurts the transparency about how mastodon works which is one of the best features.

Not understanding the algorithm is a minus but realistically we're talking about 3 hashtags out of the way of any other content that you can totally ignore. Also strictly speaking the exact selling point is "chronological timelines" and that is of course untouched.

**Comment by lawremipsum** [comment]
I'm imagining a scenario like the one Twitter got into in the 2016 election: sockpuppet accounts creating astroturf trends and influencing conversations, only this time it's distributed across federated instances and no one admin can plausibly ferret out that the manipulation is in fact coming from a single source.

The broader point is that it creates new incentives and rewards for unwanted behavior, some of which hasn't even yet been contemplated, much less considered how it might be recognized and countered.

**Comment by Gargron** [comment]
>I'm imagining a scenario like the one Twitter got into in the 2016 election: sockpuppet accounts creating astroturf trends and influencing conversations, only this time it's distributed across federated instances and no one admin can plausibly ferret out that the manipulation is in fact coming from a single source.

I've gotta say I have not heard of trending topics playing any influential role in the elections. There were accounts spreading misinformation to their followers, who were in turn spreading it to theirs; there were ads that pointed to fake news, and a large number of sockpuppets replying in threads. But the end goal was afaik influencing people through those direct means, not changing which trend appeared in a sidebar. That seems like a much more serious issue, because those people can pretend to be anybody, like Antifa or BLM activists, and gather real followers for subtle campaigns. At least if your problem is trending hashtags, it's super simple to see when one is politically motivated, and then you can ban it and see who's posting under it in one swoop.

**Comment by Dar13** [comment]
I believe the fake trends issue was more prevalent on Facebook, or at least that's where I saw it most, where bots or motivated groups shared and liked false or misleading articles that then got propagated to the rest of the network via the "Trending" box on the right side of everyone's screen.

They've had so many problems with the feature that they're now removing it: [source](https://www.npr.org/sections/thetwo-way/2018/06/01/616289583/facebook-is-scrapping-its-troubled-trending-news-section)

**Comment by Cassolotl** [comment]
>How does abuse via trending tag work? If someone wanted to use a trending tag to abuse someone, how would they go about that?

([me](https://github.com/tootsuite/mastodon/issues/7702#issuecomment-394065132))

**Comment by erinarbleizez** [comment]
I think their is really to much negativity here… Trending Topics are also a good way to be informed of what happen in the world… I would have been warned of Turkish putch in 2013 without the trending topics of twitter because media didn't care… #prayfor are faster in alerting of terrorist attacks than any media or alert…

**Comment by lawremipsum** [comment]
All the same, if as an admin I don't want to expose my users to potentially manipulated trends at all, I'd like the option to not do that.

**Comment by Maverynthia** [comment]
How come I get a feeling that what tags are trending is controllable on an instance level, meaning people can choose certain tags to trend and silence other tags. Even if turning off trending for a short time. This is what happens on Twitter and Facebook, trends they don't like get silenced.
Even so I see tons of abuse in trending tags on both places. Also easy to set up a bot on an instance and game the system to allow for harmful tags to trend.
This is what we switched from Twitter to avoid is garbage like "trends".

**Comment by erinarbleizez** [comment]
I didn't quit twitter to avoid is garbage like "trends" but to host my own instance and control my data and virtual self… I loved the trendings topics on twitter for like I said, making it possible for people on different countries to inform on things that would be ignore by media…

Right now hashtags are pretty useless on Mastodon because we can see for the same subject different hashtags leading to not have all toots on a subject when searching for a hashtags… Sometimes I just don't know which hashtag to use to start sharing my though on a subject about news to reach an audience because without that, self hosted mastodon are pretty autistic...

The good sign that an open source project is big is when different people with different culture start to come with différent motivation. Trendings Topics is now a good example of that and I think that giving choice would be a good alternative but with It's drawback: shutting down on a big instance and all the trendings topics on the federation would be screw...

**Comment by ffffluffy** [comment]
In my opinion, trends would bring more problems, with abuses a it has been pointed out previously than advantages. From my habits on Twitter or Mastodon, I see what's trending when I see the people whom I am following speak about it, not because of a trends list.

Yet the idea of having a way to highlight some topics on an instance could be interesting, for exemple with a static panel displaying some interesting hashtags setup by the admin. This solution wouldn't solve everything : a harassing admin could put there hashtag promoting harassment, but it couldn't be influenced by bots at least.

**Comment by erinarbleizez** [comment]
> From my habits on Twitter or Mastodon, I see what's trending when I see the people whom I am following speak about it, not because of a trends list

that's exactly why I think federated trending topics would solve: people mostly check what their circle of people say instead of the federation timeline leading to an ostracization of self hosted mono user instance which is the main point of federation in mastodon...

**Comment by Cassolotl** [comment]
>the reasons folks are so leery is because they are a vector for dogpiling and abuse.

How does that work, what do people do? (I'm asking because I've never seen it happen, and it sounds awful but I'd like to understand!)

**Comment by Gargron** [comment]
Thank you for the example.

>If the trends were moderated/curated before being automatically amplified, I'd feel far better about it.

There is no reason this *couldn't* be the way it works, if you accept higher latency and more work for admins/mods. In fact, you could just add an `approved` boolean on the hashtags table and let admins permanently mark them as ok-to-trend, so maybe admins would get an e-mail everytime an unapproved hashtag would enter the trending tags pool, and they could choose to approve it. That way, already approved hashtags would fluctuate without intervention, and I think all abuse concerns would be solved by that?

**Comment by lawremipsum** [comment]
A local, whitelist-only trend approach would be great and would be a good along with the off switch in #7702. I might be less likely to turn it off, depending on how easy it was to administer (it would need to be reversible for when a whitelisted hashtag is appropriated for malicious use). But I can't speak to whether it would be adequate to deal with trending tags on other servers that result in inbound distributed harassment.

Though my sense of it as a net-negative influence remains. It unnaturally gooses conversations.

**Comment by erinarbleizez** [comment]
whitelisting would be the worst and I prefer no trending tags than dictatorship where 1 or 2 people has the power to say what is good or not to say in a Community… Mastodon had enough scandal with instance censorship to not had a new one...

**Comment by renatolond** [comment]
I like the idea of being able to select which tags could be allowed to appear in the trending box.
For me it would be a moderator (not only admin) config and ideally it should be automatically disabled if a tag stops trending, or over a period of time (so that a new trend of the tag should be approved once again)

**Comment by erinarbleizez** [comment]
and what? if you allow #pokemon Nothing can prevent 100 or 1000 accounts to be created and write "white supremacist are great #pokemon" and this work too even without TT, even right now the problem still exist, spamming with hundred or thousand of account would lead to local timeline flood… 1 year before a big French IT girl member of the Quadrature du Net decided to quit Mastodon because of cyber harrassment so I don't see why this idea that preventing TT to be a non censored thing would prevent Something that already exist in Mastodon...

**Comment by Thann** [comment]
There is always going to be spam, abuse, and legit things we just don't want to see.  We all have the choice to stay offline, or fight back by making great moderation tools. Instead of complaining, and saying "it can't be done and any attempt to do so is foolish" how about trying to come up with solutions? It may very well be impossible to make a perfect trending system, but how about we at least try first?  The beauty of Mastodon is that everyone gets to have their instance work the way they want, so if I want trends, and you don't, that's perfectly fine, but don't tell me I can't have them.

Also, I think a lot of people who "don't like trends cuz facebook" are overlooking one critical component: money. Things trend on proprietary social-media sites because they take money to add/remove things from the list. What were trying to do here is show *organic* trends, and we'll see what happens.
