### ISSUE TITLE
Visually distinguish threads in single-toot reply view

### ISSUE THREAD

**Issue by Skirmisher** [tootsuite/mastodon#279]
Currently, replies to a toot are organized by thread, so one complete chain of replies is above the next-oldest reply to the original toot, and so on. It would be useful to have a visual indicator that defines and separates each thread, at least to the point where reply chains are walled off from each other.

**Comment by Artoria2e5** [comment]
Some quick pointers: thread info is indicated with the [Context](https://github.com/tootsuite/documentation/blob/master/Using-the-API/API.md#context) entity, which gives you a bunch of ancestors (always forms a thread) and a bunch of descendants sorted by the way Skirmisher describes. The Statuses in descendants come with an `id` attribute and an `in_reply_to_id` attribute; two consecutive replies are in the same chain if and only if the latter is in reply to the former.

The rendering is done in https://github.com/tootsuite/mastodon/blob/669fe9e/app/javascript/mastodon/features/status/index.js#L176. The `renderChildren` part can probably be modified to check for chained-ness.

**Comment by Gargron** [comment]
Okay, so in the PR referenced above I explored the idea of visualizing this, but the concept was not received well. The alternative proposal of rendering in a tree structure, I think, is the wrong approach, because the natural flow of a conversation is a deep chain of replies, rather than one post with many replies. In those circumstances, tree rendering would look very messy and the posts would become very narrow.

So I'm gonna close this as unfixable.
