### ISSUE TITLE
Display remaining characters on profile edit screen for bio (and display name ?)

### ISSUE THREAD

**Issue by symac** [tootsuite/mastodon#2810]
When editing your profile on /settings/profile it would be great to have a "remaining characters" indicator that is updated while you type. At the moment if you input more than 160 for the bio for example, it is not until you validate the form and the scree reload that you get an error message saying that bio is too long.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Cassolotl** [comment]
I'm on a Mastodon instance running 1.3.2 and this has been implemented:

![screen shot 2017-05-05 at 14 57 46](https://cloud.githubusercontent.com/assets/6607512/25748530/4ab13bba-31a3-11e7-95b6-0b2388ccab05.png)

What version of Mastodon is your instance using?

**Comment by symac** [comment]
1.3.x according to instances.mastodon.xyz and knowing that you have this function I now find [a closed issue](https://github.com/tootsuite/mastodon/issues/1447) asking for this. I was thinking my instance was up to date but mastodon is evolving too quickly :) We can then close the issue.

**Comment by Cassolotl** [comment]
@symac Some instances wait a few days before updating because sometimes there are bugs that get discovered soon after release and need patching! So that might be why your instance is showing 1.3.x. :)

You can see the version on [your.instance]/about/more, on recent versions, if that helps for future reference. Like, [here's cybre.space's /about/more](http://cybre.space/about/more):

![screen_shot_2017-05-05_at_15_27_48](https://cloud.githubusercontent.com/assets/6607512/25749735/730f84f0-31a7-11e7-8bf3-4d6d081f9cba.png)
