### ISSUE TITLE
Docker configuration for local development and testing

### ISSUE THREAD

**Issue by alabeduarte** [tootsuite/mastodon#2936]
Hi there,

I was able to setup the app with Docker, thanks to this [well-documented page](https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Docker-Guide.md). However, I noticed that the [development guide](https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Development-guide.md) assume I need to have everything installed on my machine and I couldn't find any resource for setup a development environment with Docker and be able to run the tests/specs within it.

Have you considered have a docker configuration for development as well? If it makes sense I would be happy to help sending a PR for that.

Cheers!

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by wxcafe** [comment]
as the development guide says in the first line,

> Don't use Docker to do development. It's a quick way to get Mastodon running in production, it's really really inconvenient for development. Normally in Rails development environment you get hot reloading of backend code and on-the-fly compilation of assets like JS and CSS, but you lose those benefits by compiling a Docker image. If you want to contribute to Mastodon, it is worth it to simply set up a proper development environment.

**Comment by kholbekj** [comment]
@wxcafe As that piece of text is written by somehow who is maybe not used to work with docker in development (one can mount the code directories to regain code reloading, etc), maybe it'd be ok to accept a docker-compose development setup PR?

As someone used to working with docker and rails in dev, not having this stroke me as weird.

**Comment by wxcafe** [comment]
I'm gonna assign someone else to this cause I'm not a dev so idk

**Comment by nightpool** [comment]
I'd be worried that using docker for a development environment would be inaccessible for newbies (who really need the help setting up the environment) and cumbersome for experienced rails developers (who are fine just using their local ruby, postgres, etc. installation).

Particularly, the things I'm worried is stuff like, the actual installation process of getting docker/docker-compse up and running, having to remember the arcane/complex docker commands to run shells, figuring out how to vendor/bundle dependencies in a way that makes sense, and things like that.

does that make sense? Now, something like Vagrant I could see being a little more useful, since it's very common to see that in a "hacking on your first rails app" guide for large and complex projects. However, if you think you can create a convincing PR for docker—by all means go ahead. These concerns may just be products of my unfamiliarity with the ecosystem.

**Comment by Grawl** [comment]
I tried to use Vagrant for development purposes but I faced a ton of issues related with Fedora 31 and macOS so I don't want to spend my time on Vagrant anymore.
