### ISSUE TITLE
Instance search tool

### ISSUE THREAD

**Issue by op3nus3r** [tootsuite/mastodon#3105]
New users who want to sign up for mastodon usually go on mastodon.social.
As the server has closed its registrations, a link redirects the users to: https://instances.mastodon.xyz/

It's difficult for newcomers to find an instance in this way ... you have to go to several sites ... read the rules of use, you can waste a lot of time searching for an instance and ultimately discourage users To register because it seems too complicated for the uninitiated.

When a server closes the registrations, there should be an instance search tool that appears and allows you to redirect and facilitate new user registrations.

If each instance uses a label system on the ~about/more page, and the administrator says, for example:
- the authorized language (or all languages)
- the host country of the instance
- restrictions of use via tags of the type: (no racism) (no pornography)
- etc.

This list could be shared by the instances and allow the search tool to efficiently propose an instance to new users.

I hope I have been clear enough. I'd like to have your opinion.
Sorry for my English :)

This is just an example of interface, it is not complete:

![mastodon_interface_v3](https://cloud.githubusercontent.com/assets/22491305/26198847/ef7e1360-3bc7-11e7-87b9-3c92d40702a7.png)
![mastodon_interface_v2](https://cloud.githubusercontent.com/assets/22491305/26198848/efaad2ba-3bc7-11e7-9161-c43a6c49c1cb.png)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Kimik0** [comment]
I agree that it seems troublesome for prospective new users to find a good instance.

I'm not sure that building an instance finder into each and every front page is a good idea though. It seems better to link to a dedicated site like https://instances.mastodon.xyz/ . That said, that site currently emphasises tech stuff that isn't all that important in everyday use, like version number, IPv6 and uptime.

As for language, now that language detection of toots appears to be working well in v1.4, it seems like it wouldn't be very hard to keep track of which languages are used most on an instance and make the ones >20% (or so) available as stats to the overview site (like number of users and toots and version etc. are).

Doing the same for hashtags would be possible, but probably not as useful. For one, you might need to filter out super common ones like "nsfw". More importantly though, hashtags aren't used very often, and don't reflect what's being talked about most. For example, an instance dedicated to cats wouldn't see much use of "cat" as a hashtag because it would be redundant, even though it would be most representative for outsiders.

Having the instance admin add tags would be possible for single-topic instances, but not so much for more general ones.

Reducing rules to simple tags seems like a not so great idea. "No XYZ" can mean "please refrain from XYZ", or "don't XYZ", or "anyone who XYZ will be banned for life". That is, it doesn't tell you how serious they are about XYZ, nor how good the moderation is. Many instances use mastodon.social's About text as default, but don't actually bother to moderate.
While this is one of the most important aspects of selecting a good instance to make your home, I can't really think of a way to make it easier without oversimplifying :/

**Comment by op3nus3r** [comment]
First, thank you very much for taking the time to respond and give your opinion.
My proposal is just an example, I know it's not perfect :-)
I wanted to get feedback from mastodon users.

This post serves to discuss together whether a research tool is desirable and in what form it would be most effective.

The idea of having a search tool for instances came to me because when I registered on mastodon I wanted to choose an instance that spoke of Art but as I had no tool for it ... I took an instance at random ^^

Now it's been 1 month since I'm on mastodon and I've already seen a lot of people who have migrated from instance and I also want to do it.
In the future, there is a risk of multiplying phantom accounts if there is no effective way to export accounts or choose a good instance from the start.

We are talking about 600k open accounts on mastodon but how many are empty, migrated, abandoned for lack of a tool to properly choose its instance. :/

The search tool could be on a dedicated site of course you are right.

Detection of languages is a good thing indeed but the language filters do not help me if I search for an instance that speaks for example: "Catalan"
If i'm a new user and if I want to register on a Catalan instance for example .. I have no tools at my disposal that allows me to know if there are instances dedicated to Catalan.
So if I'm a chess player or a photographer and I'd like to know if there are specialized bodies ... I do not have a tool for that.
Either I go through a search engine type duckduckgo, startpage, qwant, google, bing, yahoo, but it's not sure I find what I'm looking for.

For the generalist instances, it would suffice to use a metatag (no theme) or (generalist).
If the admin does not specify the theme of the instance .. the tool will display it as an "instance without specific theme".

I agree with you, do not reduce the rules. This is the most complicated part it seems to me.
But we can try to summarize them by metatags to allow the tool to be more efficient in the search.
Then when you find the right instance, you can always write under the search results: * Please read the rules carefully before registering.

Example in the page:  ~about/more

[TAG]: More detailed explanation of the tag.
---
Example tags:

[No NSFW]: NSFW content is not allowed on this same hidden instance and mentioned as such.
[NSFW Refrain]: NSFW content is allowed if it's mentioned with hashtag #nsfw and hidden.

**Comment by op3nus3r** [comment]
TheKinrar is working on something interesting:
https://mastodon.xyz/@TheKinrar/4161642

**Comment by Gargron** [comment]
Not a valid issue for this repository but implemented with instances.social and joinmastodon.org
