### ISSUE TITLE
Create an app stream API

### ISSUE THREAD

**Issue by paulyhedral** [tootsuite/mastodon#3144]
Add an API that allows an app to follow the timeline, such that the stream of data contains post creation, updates, follows, boosts, etc. for all users of the registered app. The most notable application of this is to support push notifications for mobile devices.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by yookoala** [comment]
Mastodon do support [PuSH](https://en.wikipedia.org/wiki/PubSubHubbub) protocol for post and user activity subscription. It is in fact the core design of Mastodon. Did you try to use it? Or did you find it lacks certain functionality you need?

**Comment by Gargron** [comment]
PuSH != push notifications.

I understand what the issue is asking for. However, the streaming API already exists: <https://github.com/tootsuite/documentation/blob/master/Using-the-API/Streaming-API.md>

But, it is not multiplexed for "all users of an app", it returns streams for individual users. I am not sure if adding multiplexing is worth the effort and complexity.

**Comment by Gargron** [comment]
Also, because apps often have to be created on-the-fly for a single user, I think multiplexing would not be of use very often.

**Comment by Gargron** [comment]
Web Push API
