### ISSUE TITLE
column filtering, management of sensitive topics such as NSFW, the public timeline, and tagged posts

### ISSUE THREAD

**Issue by hoodiek** [tootsuite/mastodon#318]
so, there has been an uncomfortable discourse at least once about "horny" and such, and while I don't personally agree with how that sort of thing went down or turned out, i think this is a very good gateway into a much more important conversation, that is very important for the future of this platform in it's current form: how do we handle NSFW posts?

you COULD mute, say, all sensitive tagged posts, and while i don't know if this extends beyond the images posted with this, but this still seems rather incomplete, and heck, sensitive tags for posts aren't quite enough in a platform such as mastodon, which does not yet support multiple accounts being used concurrently.

So, on to the solution i have in mind: "labels", or "tags" both function essentially the same, and would allow a section of the post to be designated the labels or tags section. this would only become visible by clicking on a post, and each label or tag would act much like a hashtag, and we could also extend this system to the hashtags automatically, however I personally thing that system of hashtags mid post generally looks clunky and odd. I think it's better off as a seperate section.

REGARDLESS: users of this site deserve to choose to not see such content, and by allowing posts to be tagged like this we can allow users to customize all of their columns with any choices from the list to be excluded.

The menu i imagine for this would look a little like this:

a toggle that upon clicking would swap between "all except" or "only" and then a list of tags, that each user can add to or remove from.

for example one might remove "nsfw" from their home timeline, and the public timeline, or one might remove "news" from the main timeline, if they are bad at dealing with the impending doom and gloom most news bring.

Finally: the ability for users to apply their own tags to posts that the user has NOT chosen to tag, and reaches a threshold of tag suggestions by user the system would auto append the tag to the post. the final feature is maybe a bit not along the lines of how federation works, and this system might be something just vetoed altogether, but i think it resolves MANY difficult and necessary to be resolved problems to come as this place grows.

thank you for listening.

**Comment by marrus-sh** [comment]
I think this would work really well with the third column suggestion in #262. I did a mockup:

![image](https://cloud.githubusercontent.com/assets/3212430/20779514/cc3f5724-b729-11e6-9bb7-236bc3584154.png)

As you can see, the public menu can easily be filtered to only show posts with a given tag. (The `misc` category is used for posts with no tag.) Furthermore, the user menu has been expanded to allow specification of which kinds of tags to follow. Here I am assuming that the number and content of tags are fixed ahead of time; I think this is the best approach for this sort of feature.

The *major* concern is how to handle this with regard to e.g. GNU Social. The crowdsourced tag-adding works well from a conceptual standpoint because it allows Mastodon users to tag posts from other platforms, but is there actually a place for this information to be recorded? (Also, obviously, it wouldn't federate.)

Finally, I'll add that I think users should be able to remove tags from their own toots that other people have assigned. This will prevent spamming/abuse (anons tagging satire as `news` for example), and if an individual user abuses the tag system by removing valid tags they could always be blocked.
