### ISSUE TITLE
Retrying dead jobs in sidekiq leads to forbidden

### ISSUE THREAD

**Issue by tcitworld** [tootsuite/mastodon#3189]
With 1.4rc1 : 

Go to `/sidekiq/morgue`, click retry all, route `/sidekiq/morgue/all/retry` returns only `Forbidden`.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Wonderfall** [comment]
Yep I got the same, it works only with command line.

**Comment by tcitworld** [comment]
Same with 1.4.1.

**Comment by tcitworld** [comment]
Same with 1.4.3, now happening with retries as well.

**Comment by Gargron** [comment]
Strange, I cannot reproduce this.

**Comment by tcitworld** [comment]
Seems to be fixed starting with 1.4.4, who knows why...

**Comment by Wonderfall** [comment]
It's not fixed for me with 1.4.7.

**Comment by tcitworld** [comment]
I didn't change any config on my server.

**Comment by Wonderfall** [comment]
Me too, and I'm not the only one who has this problem since the beginning. Like I said, if I want to do something with Sidekiq, I have to use the CLI. In the WebUI, taking actions such as retry or delete always result in "Forbidden".

**Comment by rtucker** [comment]
Still broken here with 1.4.7 for both Retry and Delete.

**Comment by rtucker** [comment]
Opened issue #4070 for the continuation of this.

**Comment by rtucker** [comment]
... and closed #4070... apologies for the dupe, I didn't see a "Reopen" button and it had gone two days without anyone reopening it, so I assumed it wasn't possible to re-open an issue.

"""
This was originally issue #3189 but it was closed unresolved.

Steps to reproduce:

1. As an admin, go to Preferences -> Administration -> Sidekiq
2. Go to the Retries tab (https://hostname/sidekiq/retries)
3. Select an item then click "Retry Now" at the bottom, or simply select "Retry All" at the bottom
4. Observe the display of a "403 Forbidden" error

This also affects the Dead tab (https://hostname/sidekiq/morgue).

This has been affecting me since before 1.4, and is still present on 1.4.7. My instance is running inside of Docker using the standard installation instructions, and my web browser is Chromium (Version 58.0.3029.110 Built on Ubuntu , running on Ubuntu 17.04 (64-bit)).
"""

**Comment by nightpool** [comment]
@rtucker only the creator of the issue or collaborators on the project can edit issue state.

I can't reproduce this on cybrespace either, so I'm going to tag this with "admin support" instead of "bug", since it seems likely to be related to the configuration of your instance.

**Comment by nightpool** [comment]
What happens when you retry a job from the command line?

**Comment by rtucker** [comment]
@nightpool How do I do this?  Only obvious commands I have in my path are "sidekiq" (which starts the daemon) and "sidekiqctl" (which stops the daemon), and a search through the mastodon docs doesn't find this

**Comment by nightpool** [comment]
@rtucker `Sidekiq::RetrySet.new.first.retry` in the rails console.

**Comment by rtucker** [comment]
That works.  Seems to just be the web UI that's horked.
