### ISSUE TITLE
Converations break on federation with GNU Social.

### ISSUE THREAD

**Issue by rogerbraun** [tootsuite/mastodon#325]
Mastodon somehow prohibits GS servers from setting the correct conversation id on third-party servers.

**Comment by Gargron** [comment]
Is this still true? Some time ago I replaced Superfeedr with our own PuSH hub. Superfeedr was stripping out `<thr:in-reply-to />` tags from updates, which could've been the reason for this bug.

**Comment by IBPX** [comment]
Yes. Look at [this](https://quitter.se/notice/8538144) versus [this](https://mastodon.social/users/Gargron/updates/402676).

**Comment by rogerbraun** [comment]
I looked into the GS code, it seems that the in-reply-to tag should actually be enough. I'm still seeing the old behavior (broken conversations), though. It does work with direct replies, though, so it will be correct on the servers of both direct participants.

**Comment by Gargron** [comment]
@IBPX GNU social does not have a thread resolve algorithm for unknown statuses, and in the case of your example, nobody from quitter.se follows the user I replied to you, so the status was not known to it.

@rogerbraun I will likely need to look into conversation IDs after all.

**Comment by Shnoulle** [comment]
Related gnusocial issue https://git.gnu.io/gnu/gnu-social/issues/253

**Comment by celesteh** [comment]
This is still broken and may be linked to this bug with friendica as well: https://github.com/tootsuite/mastodon/issues/1854

**Comment by Shnoulle** [comment]
Else friendica<->gnusocial are totally OK ;)

**Comment by celesteh** [comment]
I think I may have misunderstood this bug. Sorry. My comment above is probably not helpful or correct.

**Comment by Shnoulle** [comment]
@celesteh : for me mastodon on friendica or on gnusocia have exactly the same issue .

See more detailed report here : https://github.com/tootsuite/mastodon/issues/1060

**Comment by lambadalambda** [comment]
Is this being worked on?

**Comment by annando** [comment]
GNU Social does have the ```<ostatus:conversation>``` element. On Friendica we resolve an incomplete thread by calling the API function ```/api/statusnet/conversation/``` with the conversation id.

@Gargron I can remember that you wrote a post or an issue where you suggested that Friendica should do some stuff so that Mastodon can do some thread completion. I was unable to find this again.

I really would like to find a way to complete all threads - not only from GNU Social, but also from Mastodon. It would be great if you could point out how you are doing this on Mastodon then I will implement all needed changes in Friendica as well.
