### ISSUE TITLE
The button "load more" in the follows list is not working

### ISSUE THREAD

**Issue by marcellecrist** [tootsuite/mastodon#3288]
I have tested the button in both Firefox and Chrome and the bug persists. According to @nolanlawson, the same problem happens in Edge and he doesn't see any errors in the console.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by unarist** [comment]
If you saw the issue on v1.4rc3, probably fixed on master branch (#3268).

**Comment by nolanlawson** [comment]
I don't exactly remember the issue, but it appears to be working on 1.4.1. Steps to repro:

1. Click someone's user name, preferably someone who follows a lot of users
2. Click "follows"
3. Scroll to bottom
4. Keep scrolling until you see "load more"

When I do this, it keeps loading more list items at the bottom until I get to the full list of follows, at which point there is a "load more" that does nothing. But I believe this is just how the UI works, because IIRC it does that in the Local Timeline as well, e.g. on an instance with so few toots that you can actually get to the end of it.

I think we can close this now. Please reopen if I'm wrong. :)
