### ISSUE TITLE
Scheduled Toots

### ISSUE THREAD

**Issue by duckinator** [tootsuite/mastodon#340]
The ability to schedule toots is very useful for content creators who want to send toots at a time more people will be on the service.

(Related: #286 Time-delayed reblogging.)

**Comment by swaldie** [comment]
I'd like to keep all the commenting about scheduling toots and boosts to one issue since I believe it to be related.

**Comment by expenses** [comment]
I think this is probably the sort of thing best left to a 3rd-party interface or script or the like.

**Comment by duckinator** [comment]
I strongly disagree.

It's extremely common for people to finish up some kind of work at awkward hours, decide to publicize it at a more opportune time, and not want to have to remember to do so manually. Having to use a 3rd-party interface or script for that is just needless complexity on the users' part. Some examples of groups who heavily use scheduled posts elsewhere (e.g. blogs, Twitter),

* artists (illustrators, painters, photographers, filmmakers, musicians, etc) strategically time posts to publicize their work,
* activists strategically time posts and boosts to promote a cause or bring attention to a topic,
* information security experts strategically time posts about new research, vulnerabilities, etc,
* software developers strategically time posts to announce product releases,
* as well as other groups I'm less familiar with.

Given the sheer number of artists, activists, and software developers _on the flagship instance alone_ (mastodon.social) &mdash; nevermind [this very incomplete list of other instances](https://github.com/tootsuite/documentation/blob/master/Using-Mastodon/List-of-Mastodon-instances.md) which contains at least 2 _entire instances_ for infosec, 4 for software development, and 3 for activism &mdash; I'd argue this is an extremely important feature.

**Comment by Fastidious** [comment]
The user base wanting this is so small, that I don't think it is worth it. There is an API, why not use it?

**Comment by wxcafe** [comment]
I think the userbase wanting this is pretty large, and we should consider it. It is my opinion that it's a pretty important feature and not such a hard one to implement.

**Comment by DavidLibeau** [comment]
If you didn't see, I made that : scheduler.mastodon.tools

**Comment by schiessle** [comment]
> The user base wanting this is so small, that I don't think it is worth it. There is an API, why not use it?

So if I understand it correctly only the user interface is missing, right?
I just saw that Mastalab allows you to schedule toots and I wonder if this is completely handled by the Android app (e.g. the scheduled toot is only send in time if the Android device is running) or if it is handled directly by the Mastodon server.

That said, I would also love to have this feature as part of the web interface.

**Comment by deutrino** [comment]
I make extensive use of this feature on tumblr and my engagement with Mastodon would be greater if it were supported here, especially as a curator.

**Comment by joachimesque** [comment]
A couple of people I know from Tumblr are hesitating about joining Mastodon for this exact reason, they lack the possibility to program toots or just have them in a queue to be posted later at regular intervals. This feature should be seriously considered.

**Comment by marrus-sh** [comment]
yeah seconded, all the people i know coming here from Tumblr are really missing this feature, so if you want to make that crowd feel at‐home you should give it some thought

**Comment by Gargron** [comment]
I would like this feature, but not 100% sure how to handle media attachments because unless they have status_id set they might be garbage-collected, and status_id will be nil until the status is created, which makes the most sense once it's time to be published because of how the id system works. It probably means adding another column to media attachments to mark them as scheduled so they don't get garbage-collected.

**Comment by stom79** [comment]
I use this feature since a while with the app and of course, media attachment is the main issue. Why not create a fifth visibility "scheduled" ("public", "not listed", "private", "direct", **scheduled**"). This visibility will guarantee that even people mentioned won't see the toot (unlike direct messages). And when the time is gone for schedule, the toot takes its original visibility and the time of publication is changed to the real date.

**Comment by bryanwillis7** [comment]
This isn't brain surgery. It's an important feature that is in high demand, and frankly is necessary for anyone to do social media in any kind of serious professional capacity. Arguing otherwise is just acting needlessly contrarian here.

@DavidLibeau I love that you made an effort and built something, but in its current form your script isn't complete enough for regular use. The ability to not add images to a scheduled tweet makes it basically unusable. And then all of the content warnings and NSFW filters for post also aren't there. I'd instantly use your script if those features were present.

**Comment by DavidLibeau** [comment]
@bryanwillis7 Thanks for your message! I my side, as for all project, I'll instantly code what you ask if I have the ressources (money) to code it. 😉

**Comment by bryanwillis7** [comment]
> @bryanwillis7 Thanks for your message! I my side, as for all project, I'll instantly code what you ask if I have the ressources (money) to code it. wink

I apologize if I came off rude, but my comment still stands. Your software isn't usable for a great majority of users without allowing for something as basic and essential as image posting. Artist/content creators basically can't use it.

**Comment by DavidLibeau** [comment]
> I apologize if I came off rude, but my comment still stands. Your software isn't usable for a great majority of users without allowing for something as essential as image posting. Artist/content creators basically can't use it.

It wasn't really rude. I'm sorry that you can use it and I'm sorry that I can't code more without resources.

**Comment by bryanwillis7** [comment]
@DavidLibeau Same. If you're hurting for money/resources, then I'm sorry your valuable time went towards coding something that most people can't use.

**Comment by DavidLibeau** [comment]
@bryanwillis7 I'm not specially hurting with money. It's just that I have other projects and if somebody wants new feature on existing project, he can open an issue, code what he want or pay someone do code it. And don't think that the scheduler is not used because you don't use it. 😉

**Comment by jaredcwhite** [comment]
Cool idea! However, I would welcome the ability to see in the timeline if a toot had been scheduled before it got posted…on other platforms I feel like a lot of the crappy content is auto-posted stuff on a schedule by bots (based on somebody's list of content items), and I would like to tell if a particular user is just posting scheduled stuff all the time and perhaps mute them or whatever.
