### ISSUE TITLE
animated GIF fails to upload with 422 due to size

### ISSUE THREAD

**Issue by wxl** [tootsuite/mastodon#3675]
I uploaded the following animated GIF both with `madonctl` and the web interface and received a 422 with the specific error that it was >8MB, even though it's 5.5MB. This was tested on 1.3.3, 1.4.1.

![kitty gif](https://media.giphy.com/media/l4FGkOYDr3dMMx5tK/giphy.gif)

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by unarist** [comment]
- Mastodon transcodes uploaded GIF to MP4, and checks file size of converted one.
- Our transcoding setting looks high quality (`ffmpeg ... -b 1300K -maxrate 500K -crf 6 ...`), so it increases file size from original GIF.

`File must be less than 8 MB` error sounds incorrect in this case, but I don't know what message is better because users can't guess converted file size anyway. Maybe we should check uploaded size instead of converted size.

Ttranscoding setting can be more tuned to decrease file size I think.

**Comment by unarist** [comment]
Oh, we are already set `-maxrate` option.

`ffmpeg -i "/tmp/4fbeb55ffdc4460aeaa4805cf2e2bbef20170610-15-f34r0d.gif" -acodec aac -strict experimental -movflag
s faststart -pix_fmt yuv420p -vf scale='trunc(iw/2)*2:trunc(ih/2)*2' -vsync cfr -b:v 1300K -maxrate 500K -crf 6 -y "/tmp
/4fbeb55ffdc4460aeaa4805cf2e2bbef20170610-15-f34r0d20170610-15-jgtmyu.mp4"`

but this haven't worked because we don't set `-bufsize` option.
(also this means our existent instances may have high bitrate GIFs like this)

```
Input #0, gif, from '/tmp/4fbeb55ffdc4460aeaa4805cf2e2bbef20170610-15-f34r0d.gif':
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: gif, bgra, 480x408, 31 fps, 33.33 tbr, 100 tbn, 100 tbc
[libx264 @ 0x55be464dfd60] VBV maxrate specified, but no bufsize, ignored
[libx264 @ 0x55be464dfd60] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX
[libx264 @ 0x55be464dfd60] profile High, level 3.0
...
[libx264 @ 0x55be464dfd60] kb/s:5694.41
```

So @Gargron,

- CRF value 6 seems very high quality. I don't see notable difference with 18 (or more large values maybe), and this reduces file size by half.
- Do you want to limit by 500Kbps? I think we can drop or increase the value because we don't need to streaming this and we also have file size limit.

**Comment by Gargron** [comment]
@unarist I will gladly take advice of anyone who knows better than me. Current values are taken from trial and error, I don't have much experience with ffmpeg.

**Comment by wxl** [comment]
Just to be clear, are we sure it's failing because of the converted size and not because of the inconsistent MIME types? I agree that tuning the conversion and responding appropriately makes sense but that may not actually fix the issue at hand. Both may be the issue.

**Comment by Komic** [comment]
CRF 6 is definitely too low, any value under 17 is probably a waste.
