### ISSUE TITLE
Allow gravatar for avatars

### ISSUE THREAD

**Issue by clarcharr** [tootsuite/mastodon#3722]
It would be nice to allow using gravatar for avatars, so that people can synchronise their mastodon avatars with other websites easily. This would also be useful because the avatars could be higher resolution than the default 120×120.

**Comment by AirDur** [comment]
Gravatar isn't open and is a centralized service so i'm against this feature.

**Comment by clarcharr** [comment]
@AirDur fair, but this doesn't actually remove the ability for people to upload avatars to instances and use those instead

**Comment by averageunicorn** [comment]
If this is done, please don't make it the default, rather let people click an extra thing to use gravatar. It's so bad to have an embarrassing picture from 5 years ago suddenly appear somewhere because you forgot this address had it associated. It could visibly/publicly connect someone to accounts that should have been forgotten long ago, or out trans people, etc.

**Comment by nolanlawson** [comment]
Gravatar is a centralized service but it is run by Automattic (WordPress) who have good open-source credentials. My hunch though is that we still wouldn't implement this since it defeats the point of decentralization…

The suggestion for >120x120 is a good one though, but should probably be made in a separate issue. :)

**Comment by Gargron** [comment]
>Gravatar isn't open and is a centralized service so i'm against this feature.

I agree. We could try to download the gravatar image locally once, but:

>It's so bad to have an embarrassing picture from 5 years ago suddenly appear somewhere because you forgot this address had it associated. It could visibly/publicly connect someone to accounts that should have been forgotten long ago, or out trans people, etc.

I just don't think gravatar is worth it, uploading an avatar is so simple.

**Comment by aoberoi** [comment]
I'd like to see the one-time-copy from Gravatar functionality. Seems like it would help people complete their profile more quickly. This might matter more in a time where lots of people are just "trying Mastodon out" (the exodus from Twitter).

**Comment by Timothyjchambers** [comment]
> I'd like to see the one-time-copy from Gravatar functionality. Seems like it would help people complete their profile more quickly. This might matter more in a time where lots of people are just "trying Mastodon out" (the exodus from Twitter).
> 
> If there's any indication that the project leadership would consider reviewing a PR and merging it, I'd be happy to contribute.

I love this idea, would love to see it resurrected in another feature to make it easier to onboard new users, and to automatically create a rel=me link to a gravatar.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/mastodon/mastodon/issues/3722#issuecomment-308040434

@AirDur, https://github.com/mastodon/mastodon/issues/9353#issue-384182550
