### ISSUE TITLE
Toot replies should be unlisted by default

### ISSUE THREAD

**Issue by ticki** [tootsuite/mastodon#3781]
Intuitively, you don't want generally your replies showing up on your timeline, as it quickly gets messy. Thus, the natural default for replies is unlisted. This should be the default, or at the very least, an option under Preferences to mirror Twitter's behavior in this sense.

Related to: #904 (closed)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Exagone313** [comment]
It looks a sane default for you, but not for me. A configuration option would fit more. See also #3764.

**Comment by saper** [comment]
Are unlisted toots searchable by a hashtag?

**Comment by Cassolotl** [comment]
Unlisted means it doesn't show up in the local or federated timelines - it doesn't change what appears in the home timeline.

As far as I'm aware, there is an option to hide replies in the home timeline AND replies don't currently show up in the local or federated timeline.

However, toots starting with @ don't count as replies! So they still show up in the local and federated timeline. #3618 might be of interest; it's asking that toots are hidden from the home timeline (and presumably local and federated timeline too) if they start with a @, rather than if they're part of a thread and not the first in that thread (the current behaviour).

**Comment by ticki** [comment]
@Exagone313

>It looks like a sane default for you, but not for me. A configuration option would fit more. See also #3764.

I can't stress my disagreement with this enough. When you reply to someone, you usually only want them and other people who see the thread, to see it, and not all of your followers.

Otherwise, you end up with a timeline where there are a lot of disconnected replies, and it isn't coherent without clicking every single toot.

**Comment by clworld** [comment]
> Are unlisted toots searchable by a hashtag?
It seems no.

'reply' toots are not listed in local/public timeline.
but 'reply' toots are searchable by a hashtag.
It's may be what this issue complains.

**Comment by Exagone313** [comment]
@ticki My timeline would be half more empty if it was like that.

**Comment by jeroenpraat** [comment]
Replies are already unlisted on public timelines. They are displayed in the home timeline for a reason - to stimulate interaction.

Toots that start with a mention that are not replies, should indeed be unlisted in the public timelines.

**Comment by Cassolotl** [comment]
Can this be closed, since we've established that replies are not included in the federated and local timelines (except replies-to-self)?
