### ISSUE TITLE
Add standardized way of publicizing private posts.

### ISSUE THREAD

**Issue by SoniEx2** [tootsuite/mastodon#3808]
When making private posts public, for example through boosting, the originator should receive a permission request. This permission request, if approved, will cause the private post to become public through the aforementioned mechanism.

By automating the whole requesting for permission thing, and adding an option to auto-refuse all those requests, we decrease harassment - harassers will click the publicize button instead of copypasting, making them feel good about themselves without actually doing anything.

And in case you're a good friend of the originator and you're publicizing it because it's more important than the originator originally thought, then I'm sure the originator will happily provide such permission.

(I have multiple times asked if I could repost something with permission in other social networks, being able to just click a button to request permission and have it automatically post as soon as permission is granted would be an amazing quality of life improvement.)

An extra benefit is that the originator would be able to delete such "copy-paste" posts, unlike actual copy-paste posts.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by fsnk** [comment]
I think by default, "private" scoped posts should have boost disabled. (I thought they did.) I don't really think this feature would add anything but confusion. 

If someone's intent is to harass another user, then they'll copy paste or screenshot regardless; a fake boost feature where requests are secretly declined isn't going to stop it. They're going to know the content wasn't boosted when it doesn't appear in their timeline.

Thought: this may be a way Mastodon's lack of text search enables harassment, because users are unable to do a text search and see if they're being reposted and by who.

**Comment by Cassolotl** [comment]
>I think by default, "private" scoped posts should have boost disabled. (I thought they did.)

Just confirming that private posts are indeed unboostable! They have a little padlock symbol where the boost button would be.

**Comment by SoniEx2** [comment]
Try it with GNU social. Mastodon's hack doesn't work, so we should do our best to fix it.

**Comment by nullkal** [comment]
After Mastodon 2.0.0 private toots are federated only through ActivityPub and instances which is running GNU social does not receive private toots.

And I think a person who hates the original posters tends to copypaste the original post because they don't want the original poster to be notified they reposted, so I don't think this idea works anyway.

**Comment by SoniEx2** [comment]
Person X makes post A.
Person Y asks to repost A.
Person X approves.
Person Y fucks up and makes Person X hate them.
Person X wants to cut all ties with Person Y, including reposted posts, but they can't because the system doesn't let them.

**Comment by Cassolotl** [comment]
>Cassolotl would be pleased by this.

I think this feature request is overly complicated for the benefit it would bring, so I'm not really into it. There's already a tendency on this project for people to ask to make UI things more complicated so that advanced users can configure everything before posting and this kinda reminds me of that!

Also, @SoniEx2, I've blocked you everywhere online that I can block you and you know it - but on Github, seeing posts by people you've blocked is intended behaviour. Can you please refrain from bringing me into things on a personal level and/or acting like we're friends?

**Comment by fsnk** [comment]
So to clarify, @SoniEx2 what you're asking for is the ability to retroactively undo boosts of your posts by another individual user. I.e. "We're not friends anymore and I want my toots back."

I think you're asking for a technical solution to a people problem here. Human relationships change, and when you're no longer happy with that relationship, previous interactions have already occurred. I don't think a technical Eternal Sunshine solution that erases interactions by giving one user the power to modify the content another has shared is a good or necessary feature.

I also think that the way federation works, Mastodon is not like Twitter. If I understand it properly, copies of posts are circulated to other instances and Ostatus implementations, rather than a pointer to the post on the originating instance, which means you have the same problem which exists with "private" scoping, where other implementations are not going to support Mastodon's requests to retroactively remove selected boosts, which makes this feature cosmetic.

If you're fine with scoping a post so that it's boostable in the first place, or you give someone permission to boost your posts (which, defacto, you do when you scope them so that the boost feature is enabled), then that dog has left the house. 

And if there's something you're _really not okay_ with having circulated on the internet, don't post it on the internet, even "private", because all the technology in the world isn't going to protect you from screenshots by backstabbing "friends". (It's a rough lesson to learn the hard way; I'm sorry.)

If the issue is that you're still seeing old notifications in your timeline that a user who you no longer wish to interact with has previously interacted with your posts, I think the block function should definitely hide those if it doesn't already.

**Comment by SoniEx2** [comment]
I'm not acting like we're friends. Quite the opposite. I'm implying you'd be able to delete everything I boosted from you.

Btw this is a feature on the instance that's boosting something, not on the instance that's being boosted. It just works.

**Comment by fsnk** [comment]
You already have the ability to approve boosts. 

You do this when you are creating the post, by choosing a post privacy setting (**public** or **unlisted**) that allows others to boost your posts. 

If you don't want other users to be able to boost your posts, use the **followers-only** or **mentioned-only** settings.

This is not an appropriate venue for you to pursue your personal issues with another user.

**Comment by SoniEx2** [comment]
I like to publish my "DMs" (mentioned-only posts) sometimes, e.g. if they're about software development or something.

**Comment by fsnk** [comment]
It doesn't make sense to to have sharing permissions on posts intended for limited recipients (followers only/mentioned only) so that they can be shared beyond that limited group by others.

Likewise, it doesn't make sense to limit sharing on posts that already visible to everyone. (Public and Unlisted.)

If you want to share your private post about sofware development in a way that allows others to boost it, copy and paste the content in a new post and set the permissions accordingly.

**Comment by SoniEx2** [comment]
And then we're back at the original problem, which is that that's clunky.

And, in a way, it does make sense to have mention-only posts be boostable. You wouldn't have a chat about software development on follower-only posts and expect it to become public. But for DMs, it's quite reasonable to expect them to become public after some breakthrough/idea.

**Comment by fsnk** [comment]
It's not clunky as it stands. It behaves the way people expect it to behave when they're setting post privacy. 

Public = shareable
Limited = not shareable.

I guess you could add a "boost request" button that would allow someone to request permission to boost it, but  again you _can_ (and probably _should_) accomplish this by just talking to another human being and asking them to repost their content with public visibility so you can share it. If you're following people or people are following you and/or you're DMing with them, it's a reasonable assumption you're on cordial speaking terms.

On the flip side, presumably the user creating the post has already decided at what publicity level they would like to share that content, so it could be you're basically adding a nuisance button that pesters people with demands to share things beyond the scope they've already determined is appropriate.

It's kind of ironic when feature requests for social media are focused on reducing non-automated interactions with other people. ;)

**Comment by SoniEx2** [comment]
You can still just mute ppl (that mutes boost requests). And setting that up (the manual reposting thing) is still a kludge.

**Comment by Cassolotl** [comment]
@SoniEx2

>I'm not acting like we're friends. Quite the opposite. I'm implying you'd be able to delete everything I boosted from you.

I'm not talking about the feature request. I'm talking about when you said "Cassolotl will like this" - acting like we're friends and you know what I'd like or not like, when in fact I have blocked you in a bunch of places including Github *and* you're wrong.

As I've said, I'm not into this issue. I don't want to be able to ask to boost things that other people have posted followers-only. If they've done that it's because they don't want the thing to be boosted. If I was open to a thing being boosted I would post it publicly. If you boosted things from me *before* I blocked you, I think it's fair to say that what's done is done and all I can really do is delete my posts so that they are removed from *everyone's* profile, including yours.

So no, I don't like the idea of letting selected people boost things, with the option to revoke those boosts at a later time. I think it unnecessarily complicates things for new users *and* established users who struggle with complex UIs, for very little benefit.

(Sorry for making it personal, folks - I just wanted to clarify the misunderstanding. I'll stick to the feature request now!)

**Comment by fsnk** [comment]
I think it's also a problem that the goal posts for this suggestion keep shifting. It's unclear exactly what the effect is supposed to be. Is it to change the scope of privacy settings of posts on the fly? Add per-user sharing permissions? Enable a user to retroactively remove their posts from another user's timeline? All these things? Something else entirely? I'm not sure.

**Comment by SoniEx2** [comment]
It's just the normal boost button but it sends a DM once when you click it
