### ISSUE TITLE
What is the latest way to apply custom.scss?

### ISSUE THREAD

**Issue by imshyuan** [tootsuite/mastodon#3822]
Hi,

I just upgraded from v1.3.3 to v1.4.3, I read a few places and know the customisation variables have some changes. I am also aware this: "Simplify stylesheets customization again (#3373)" in v1.4.2 changelog. However, placing the `custom.scss` file in `/home/mastodon/live/app/javascript/styles` doesn't work (I also did not create any `custom.js` since "customisation is simplified again"). I have `@import 'application';` in the `custom.scss` file. But I am still seeing default styling even after I recompile assets and restart mastodon services. May I know what am I missing?

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by imshyuan** [comment]
I figured out what my earlier problem was. I can see the customisations (specifically the colours) right after I paste the entire content in `variables.scss` into `custom.scss` instead of just part of it. So I am closing this. :)

**Comment by jpfox** [comment]
Each release breaks css customization :-(
Is there anybody to update documentation about css customization ?
https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Customizing.md
My css is not about color but column width, so $ui-***-color is not a solution for that.
This does not work any more since v1.4.2 I think (I'm using 1.4.4).

Thanks for your help
