### ISSUE TITLE
limited scrolling on notifications on iOS

### ISSUE THREAD

**Issue by clhendricksbc** [tootsuite/mastodon#387]
I noticed recently that when I go to notifications when using iOS (where I put a button on the home screen from the web) I can only scroll down a limited number of notifications and then it stops. I can't get all of them. It used to load more, but now it's not doing it anymore.

I'm using iOS 10.2 (recently updated, if I remember correctly, so maybe something happened there?).

**Comment by yipdw** [comment]
I think I ran into something similar on Mobile Safari (iOS 10.2):
https://files.mastodon.social/media_attachments/files/000/058/163/original/media.m4v?1483602730

In the linked video, you can see that touch events are affecting elements in the page, but they are not affecting the timeline element.  Letting the scrolled element settle down seems to make scrolling work again (also in the video).

**Comment by Gargron** [comment]
I've added a "load more" button to the bottom of all scrolling areas so you have a fallback when scrolling doesn't work.

**Comment by daprice** [comment]
Not sure if I should open a separate Issue for this, but I'm still running into the same problem demonstrated by @yipdw when scrolling in timelines. It doesn't always happen at the bottom of the timeline, either – I'll just be scrolling along and suddenly scrolling won't work for a few seconds. It looks like it's caused by something about iOS's inertial scrolling.

Using iOS 10.3.1 and mastodon.technology
