### ISSUE TITLE
[Feature Request] Instance-level whitelist

### ISSUE THREAD

**Issue by thedeadparrot** [tootsuite/mastodon#3880]
It would be nice for the admins of instances that are more concerned about privacy/leaking information to be able to choose between using the instance blacklist and an instance whitelist. This is already implemented for awoo.space, the code of which is publicly available.

https://github.com/vahnj/mastodon/commit/2cf7a096bf642ba75b3fe327038ee598f701db44
https://github.com/vahnj/mastodon/commit/2fca7e899aebc37fb45190951c1c2d46c72eb646

I am sure it needs to be cleaned up, have tests added, and so on, but I would love to see this feature more widely available for admins.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by nightpool** [comment]
Searched for a while but couldn't find an issue for this, which feels weird to me—this code has been around for a while.

**Comment by Gargron** [comment]
Whitelists go against the spirit of decentralization. If you can't start your own server and join in, but have to go through some kinda review process with every single other node, then you can't really start your own server. So whitelists will never be in the upstream repository.

**Comment by TheDiscordian** [comment]
This seems like a really knee jerk decision to me. The main usage I can see for private instances would be organizations communicating for a specific goal, isolating themselves from the outside world. There would be other people using it too. But if your fear is most people just won't federate, they'll do that anyways if they want to via fork.

You can't force people to federate, but you can be annoying about it I guess ...

**Comment by Shadowghost** [comment]
I don't see why this can't be an optional setting.
I agree that it's against the idea of federation, but as long as it's not the standard setting, there's IMHO nothing speaking against it to be implemented upstream.

**Comment by emollusion** [comment]
+1 on this.
Opting out of federation or keeping federation within set domains would for some organisations be required. Doesn't matter if the organisation is a private company or a small chess club, or a union of board game clubs with no profit interest what so ever.
Since GDPR within the EU those organisations need to be able to delete user data when requested to do so by the user. With federation user data gets federated and after that there is nothing stopping it.
To not go against GDPR, some other features would be nice too but keeping federation within specific network(s) is a good start.

**Comment by odecif** [comment]
+1
This is a real issue for organizations since there is a use for Mastodon as a platform but not necessarily as a federation. 

I think that opening up for the possibility of being compliant with GDPR would give significantly more interest to Mastodon than the cost it brings.
