### ISSUE TITLE
Videos only available in WebM

### ISSUE THREAD

**Issue by ticky** [tootsuite/mastodon#402]
Videos on Mastodon are only provided in WebM format, which is not supported on several major platforms.

Either allowing for transcoding to h.264 to improve compatibility or gracefully handling cases where the video fails to play would improve the experience considerably!

**Comment by Gargron** [comment]
Actually, we allow webm or mp4 and don't transcode them at all. I tried transcoding everything to webm at the beginning, and it kills server performance.

**Comment by ticky** [comment]
Yeah, it’d definitely be the kind of thing you’d wanna delegate to something-other-than-the-app-server (though I realise that’s kinda hardcore lol). I wanna at least get in a fix so that videos don’t just up and not do anything, though!

**Comment by Gargron** [comment]
I believe videos need black background, I discovered when I uploaded a webm with only one frame (which therefore didn't get a proper thumbnail since it's taken from 1st frame and not 0th) that empty space with the play button in the middle is not a good look. If there's a way to check format compatibility for the video tag/src maybe instead of the play button it should display "broken file" icon or something of that sort.

**Comment by noiob** [comment]
Webm is a problem on Safari and mobile Safari. On Safari, Videos are just a black box, on mobile Safari it starts a download, which is at least something (one could then open the file in VLC or something). I'd definitely like some kind of error message on desktop Safari.

**Comment by Gargron** [comment]
Basically the issue remains that transcoding video formats is very CPU intensive. We now convert gifs to webms, but that's worth it for the disk space and bandwidth that it saves. The API also lacks response differentiation for formats, there is a preview URL which is always an image, and an original URL. But there is no "webm" vs. "mp4" variant for the original URL. Maybe there should be.

Does anyone know if maybe Safari is planning to start supporting webm soon? I mean, it's not like it's an unpopular format. I'd say it's the most popular video format I know of, right now...

**Comment by noiob** [comment]
Would just generally using mp4 be that big a trade-off? VP8 doesn't have good hardware support, afaik

Sent from my Pok?dex

Am 05.03.2017 um 18:54 schrieb Eugen <notifications@github.com<mailto:notifications@github.com>>:


Basically the issue remains that transcoding video formats is very CPU intensive. We now convert gifs to webms, but that's worth it for the disk space and bandwidth that it saves. The API also lacks response differentiation for formats, there is a preview URL which is always an image, and an original URL. But there is no "webm" vs. "mp4" variant for the original URL. Maybe there should be.

Does anyone know if maybe Safari is planning to start supporting webm soon? I mean, it's not like it's an unpopular format. I'd say it's the most popular video format I know of, right now...

-

**Comment by Gargron** [comment]
Okay, gifs now get converted to MP4s instead of WebM.

But for videos, whatever the user uploads, that will be used. I think I mentioned when initially I insisted on converting originals to a specific format, the production system of mastodon.social creeped to a halt every time someone uploaded a video.
