### ISSUE TITLE
Blurred image previews remove loading feedback

### ISSUE THREAD

**Issue by Pbtflakes** [tootsuite/mastodon#4060]
Here is how an image looks to me while loading, note that this overrides the standard browser behaviors of progressive or baseline loading of the full-size image:
![2017-07-03-213402_1366x768_scrot](https://user-images.githubusercontent.com/5778355/27812080-1db1e464-603a-11e7-880e-5f017fba6581.png)

The initial implementation of blurred placeholders obfuscated almost all indications of how much of the full-resolution image had loaded, and recent tweaks seem to have blocked it out entirely. This user experience is far from ideal a slow connection, since there's no way to tell whether the image has stopped loading entirely or how close it is to finishing.
* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Kimik0** [comment]
Seems like another case of designers trying to reimplement browser builtin functionality in an inferior way because they think it looks better.

Please undo this change. For users with a fast connection the blurred version barely appears before being replaced by the full version, so it's pointless. For users with a slower connection the blurred version is less informative than the browser builtin behavior that shows all the data it can decode from the image at any point during download.

**Comment by nolanlawson** [comment]
I think this is worth investigating with a throttled connection to see the effect. Note that the quality of either solution will very based on the type of image (e.g. progressive jpeg).

My hunch is that the best solution is to blur the preview image with CSS to make it clear that the image is still loading. This is what e.g. Medium does and I think it's a nice solution.

**Comment by nolanlawson** [comment]
Related: https://github.com/tootsuite/mastodon/pull/3966

**Comment by unarist** [comment]
This is just my opinion. I usually click/tap thumbnail when I want to see image **in full screen**. In most case, it's not needed to be **original resolution**, especially on slow connection. So I don't want those blur effects which prevents me from seeing image until it's loaded.

I like separated loading indicator, like iOS does.

**Comment by Pbtflakes** [comment]
I second the removal of blur effects entirely. Image load status was already clear through progressive loading, while this removes all indications of *how close* it is to being fully loaded.

My biggest gripe is that it will sit there indefinitely when my connection speed drops, and I can't tell whether it's loading taking a long time or failing entirely. This could perhaps be rolled into a slow connection setting.

**Comment by Pbtflakes** [comment]
My question is whether any of this loading indication needs to be added when none of the solutions seem to *improve* upon native browser behavior rather than reinventing the same thing.

**Comment by ThibG** [comment]
Oh, I hadn't noticed that Mastodon behaved this way. I mean, I often noticed the preview image was blurry, but I thought it was because of its size. Disabling this blur actually makes for a much better experience, to be honest. So I second @unarist's suggestion.

Also, I'm wondering why a canvas is used for the preview image, rather than a standard “image” tag?

Finally, we might scrap that altogether and use `srcset`, I guess. Although I am not sure if it will display any previously-cached image data that isn't the best match for the display size.
