### ISSUE TITLE
Muted users should not show up in notifications [Anti-harassment]

### ISSUE THREAD

**Issue by yiskah** [tootsuite/mastodon#4172]
The primary function of muting for me, as a high follower-count user, is to remove someone's comments from my notifications without them knowing I have done so (via not seeing my posts etc). Block = "I don't want this person to see me", Mute = "I don't want to see this person." If I block a troll they claim it as a victory and I just get more trolls. If I block someone who is an "overzealous fan" I've had quite a few incidents of them tracking down my contact info (via my website, the mastodon discord server, etc.) and interrogating me on what they did wrong, when I never wanted to bother with that conversation and wished I could use mute to avoid that social drama. I also sometimes get others hearing I blocked someone and asking what they "did wrong" when it was really just that they replied to my posts too much with inane comments.

Expected behavior: A muted user's mentions or replies of me do not show up in my notifications, as on other social media.
Actual behavior (v1.4.1): A muter user's replies and mentions of me show up in my notifications.

Muting is essentially useless to me when it has such a large hole for harassment to go through. Blocking people who harass me always makes them go brag about it and then others seek to get blocked as well. I haven't muted any servers but if muting a server behaves like muting an individual user then that also removes that feature's anti-harassment aspect.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by unarist** [comment]
cf. https://github.com/tootsuite/mastodon/issues/3731#issuecomment-308084883

**Comment by Cassolotl** [comment]
From Gargron:

> Block: "I don't want to ever see this person"
> Mute: "I don't want to see this person's posts in the timelines"
> 
> Muting is appropriate for an annoying friend, someone you don't want to passively observe but still want to hear from if they tell you something

It seems like there needs to be a way of muting someone's mentions without them knowing, though.

**Comment by nightpool** [comment]
The amount of previous bugs here means that this is a behavior that is surprising to users and either needs to be better explained in the application itself, or fixed so that it no longer surprises users. Either is a bug in the user experience of the application. I lean towards the "fixed" side because of @yiskah's compelling arguments towards why having this behavior is useful from an anti-harassment perspective, and my own experience with the mute functionality.

I'm also down to split mute into "Hide from timeline" and "Hide from notifications", but i'm worried about the UX problems with such a distinction—how you would message it, if it would be "another form" of status filter or if we need something more general on the backend, etc. etc. It gets very complex very fast both from a user and implementation perspective.

**Comment by yiskah** [comment]
@Cassolotl If you mute someone they don't know. They still see your profile and posts the same. As far as they know you're just ignoring them.

Gargron is incorrect about the purpose of this feature like, we had to explain to him what a block is originally and then explained muting later. I think he should defer to those of us with more expertise in this area.

If you *want* muted people to be able to call you a `fucking disgusting snowflake crime against nature` because blocking will get their friends to come after you too, then I suggest that when you click "mute" a modal pops up with a check box that says `[X] Also hide from notifications?` which you can uncheck if you'd like.

**Comment by Cassolotl** [comment]
>It seems like there needs to be a way of muting someone's mentions without them knowing, though.

>@Cassolotl If you mute someone they don't know. They still see your profile and posts the same. As far as they know you're just ignoring them.

@yiskah Yeah! So it seems like the mute should be extended to notifications. :) I do agree with you.

>I suggest that when you click "mute" a modal pops up with a check box that says `[X] Also hide from notifications?` which you can uncheck if you'd like.

I like this.

**Comment by nightpool** [comment]
un-assigning since it sounds like someone else is already working on the modal dialogue box idea. I'm not sure if I'm entirely sold on the benefit of that vs making all mutes work "correctly" vs adding a separate way of muting someone from the timeline (especially if we want to do a "follow but mute boots from X" later)

**Comment by yiskah** [comment]
Gosh we are so friggin' modular over here. Maybe we should just make a like "user content visibility panel" with all of this stuff? "Manage user visibility" or something

```
[X] Allow user to see my posts
[X] Allow user to follow my account
[X] Show user's posts in public timelines
[X] Show user's posts in Home timeline
[X] Show notifications and replies from user
[X] Show posts boosted by user

[[MUTE]] // would automatically set all the settings to whatever corresponds to a mute
[[FULL BLOCK]] // would automatically set all the settings to whatever currently corresponds to a block
```
