### ISSUE TITLE
Toots on home column from users I don't follow 

### ISSUE THREAD

**Issue by Starless-Night** [tootsuite/mastodon#4210]
I'm seeing Toots on my home column that aren't from users I follow and they aren't boosted toots either.

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by clworld** [comment]
It seems it's duplication of https://github.com/tootsuite/mastodon/issues/2817 .
It occurs when boosted toot is unboosted.
See Gargron's comment https://github.com/tootsuite/mastodon/issues/2817#issuecomment-299501175 and it's root cause https://github.com/tootsuite/mastodon/issues/147 .
This bug is caused by timeline structure stored in Redis and It can't be fixed easily.

**Comment by Starless-Night** [comment]
ah! apologies. I couldn't find that.

**Comment by fsnk** [comment]
This happened to me the other day too. Good to know!
