### ISSUE TITLE
Convert gifs to webm during upload

### ISSUE THREAD

**Issue by Gargron** [tootsuite/mastodon#431]
WebM's are of smaller size and higher quality, so the cool thing would be to convert uploaded animated GIFs to WebMs before storing them.

I personally haven't figured out how to make Paperclip do that, yet.

**Comment by ticky** [comment]
(hey if you do this can you also make ‘em available as mp4s because otherwise I just won’t see gifs and that’ll be bad)

**Comment by noiob** [comment]
Yeah, webm is not supported on all platforms (i.e. Safari on mobile and Desktop). Is there any issue with just providing mp4 instead of webm?

**Comment by vjackson725** [comment]
An update:

I'm currently blocked with this approach because the paperclip [av-transcoder](https://github.com/ruby-av/paperclip-av-transcoder) extension doesn't work well when you transform the original file, erroring out on the security checks.

The paperclip [Attachment processor](https://github.com/thoughtbot/paperclip/blob/master/lib/paperclip/attachment.rb) seems to handle this okay, but I can't work out how it does that.

@Gargron submitted a [question on stackoverflow](https://stackoverflow.com/questions/41635791/how-to-convert-gif-to-webm-on-upload-using-paperclip-and-or-paperclip-av-transco).

Also, I developed for webm because that was what was in the title, but I'd vote for mp4 as well.

**Comment by vjackson725** [comment]
good work! 🎉

**Comment by saper** [comment]
Well, it seems to me that this broken static gifs (https://github.com/tootsuite/mastodon/issues/2108). 

And actually we ended up with proprietary mp4 instead of webm

I think animated gif is much better supported :)
