### ISSUE TITLE
Server- and client-side bio and display name count endlines and emoji combinations inconsistently

### ISSUE THREAD

**Issue by renatolond** [tootsuite/mastodon#4419]
Hi!

When using UTF-8 chars (multi-byte ones, I assume), there's inconsistency in the "characters left" indication. I'm using mastodon.xyz which is in 1.4.7, problem still exists in 2.5.0rc1
When I submit the edited changes, the value that comes back it's smaller than the one that it's calculated by the frontend.
* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ariasuni** [comment]
The issue is that server-side bio character counts endlines as two characters, whereas client-side count it as one character.

For example:

```
t
t
t
```

- when editing, displays 155 characters left (client-side)
- after saving, 153 characters left (server-side)
- when editing again, 155 characters left (client-side)

Emoji combinations are also counted inconsistently. [🏳️‍🌈 Rainbow Flag](https://emojipedia.org/rainbow-flag/), [🤷‍♀️ Woman Shrugging](https://emojipedia.org/woman-shrugging/) or [🏴‍☠️ Pirate Flag](https://emojipedia.org/pirate-flag/) is counted as one character client-side but four characters server-side.

This is particularly annoying when writing a bio with several endlines or emoji combinations, because you can write a bio with the client-side code reporting that it fits into the character limit, but then rejected because the server-side code counted more characters.

Please rename the issue «Server- and client-side bio count endlines and emoji combinations inconsistently» or something like that.

**Comment by ariasuni** [comment]
The issue is the same with the display name, so I guess it’s the same code that must be fixed.

**Comment by ariasuni** [comment]
Copied from #8514

---

Server-side bio character counts endlines as two characters, whereas client-side count it as one character.

For example:

```
t
t
t
```

- when editing, displays 155 characters left (client-side)
- after saving, 153 characters left (server-side)
- when editing again, 155 characters left (client-side)

This is particularly annoying when writing a bio with several endlines, because you can write a bio with the client-side code reporting that it fits into the character limit, but then rejected because the server-side code counted more characters.

**Comment by danhunsaker** [comment]
The OSes in play will likely have an influence on this...
