### ISSUE TITLE
No notifications in notifications tab for follow requests

### ISSUE THREAD

**Issue by nikkisquared** [tootsuite/mastodon#455]
If your account is private, and somebody sends you a follow request, there is no notification for this happening in the notifications tab. Having emails turned on for follow requests works fine, but it's strange for follow requests to not give a notification in Mastodon, especially when follows on a non-private account do.

**Comment by Gargron** [comment]
This has been a deliberate choice, at the time welcomed by users. The idea is that if your account is locked, you don't want to be bothered, and having follow requests in a place where you can look when *you* want it, rather than being demanded to look at it, is better.

If there is a significant movement for changing this, it would be simple enough to do, since currently follow requests are *deliberately* filtered out of the notifications column.

**Comment by nightpool** [comment]
maybe make this opt-in? So follow requests are by default filtered out (client-side, using the existing notif filter stuff) but can be enabled?

**Comment by nightpool** [comment]
I'm not entirely sold on the idea that this is the best default though, so maybe it should just be opt-out.

**Comment by Cassolotl** [comment]
How about a little number next to "Follow Requests" in the Getting Started menu? The same colour as the rest of the text, just a little number in brackets - so you only see it when your fourth column is empty, and it's fairly discreet but you can see it without having to click anything?

![screen_shot_2017-07-07_at_12_03_19](https://user-images.githubusercontent.com/6607512/27955363-62a802ea-630c-11e7-934f-676f4a6c0132.png)

**Comment by wxcafe** [comment]
it should *deffo* be opt-out imo and it really needs to exist yeah

**Comment by rakiru** [comment]
I completely missed that follow requests were filtered out from notifications. I considered this surprising behaviour, since everything else appears to show a notification, including regular follows, and smaller actions such as favouriting toots, as well as there being toggles to filter each of these things out. I also find it inconvenient as I have to check it manually every so often, whereas every other notification I get live in the pinned notifications column.

I find most of Mastodon UI intuitive, but this is one of a few things that I only stumbled on by chance and never would have guessed.

**Comment by Cassolotl** [comment]
Yeah that's a good point - if users want to be able to not see follow requests it can be a notification, and then in the notifications toggle menu people should be able to toggle them off.

**Comment by dariusk** [comment]
For any instance admins looking at this and needing a solution for their users, I have a fix  ([commit](https://github.com/friendcamp/mastodon/commit/11987c9255da1f982bcf4eb17d4fe4ee2c99c18a)) that you should be able to cherry-pick into into `v2.4.3`. The solution I came up with is not a full solution as it doesn't put the follow requests into the notifications stream, but it does at least surface the total number of follow requests in a more noticeable place (right under the TOOT button).

https://github.com/friendcamp/mastodon/commit/11987c9255da1f982bcf4eb17d4fe4ee2c99c18a

Here's a preview image (ignore the bad pluralization, that is fixed in the commit now).

![image](https://user-images.githubusercontent.com/266454/44181375-56780b80-a0b6-11e8-9257-14b4c073acd6.png)

**Comment by nightpool** [comment]
hmm. since this ticket was opened, we've implemented a callout on the menu
item and also (I think) an "unread" indicator on the tab bar of the getting
started menu.

**Comment by dariusk** [comment]
That's correct but in mobile it's still buried -- you have to switch over to the getting started menu manually in order to see the unread indicator.

**Comment by dariusk** [comment]
In v2.4.3 the only indication available is inside the body of the Follow Requests item in the Getting Started menu, nothing on tab bar itself. So on mobile you need to manually hit the hamburger icon and then you can see if you have any requests or not. That's what my users wanted changed.

**Comment by hidrarga** [comment]
Hello @Gargron ! Did you change your mind about the idea of having a notification for follow requests ? As @nightpool suggested almost two years ago, we could just have an option for those who doen't want to be bothered by these requests.

Thanks !

**Comment by Kjwon15** [comment]
I want this type of notification because I opened FTL on "getting started" column every time to reduce space wasting

**Comment by rtucker** [comment]
Any news on this? It's quite annoying to not get a notification when there's a new follower request. I have to put a note in my bio asking folks to DM me, and I'll often miss requests from people changing instances, etc.

**Comment by Phroneris** [comment]
I think not a few users take it for granted that the "notifications" notify everything that others did for their accounts.
Via web UI or preference pages, who can know that follow requests cannot be seen in the notifications?

The follow request notification should be provided as an option.
And also it should be opt-out, enabled by default, if possible.
Or, *at least*, the account lock option should have an additional description saying that we can only recognize follow requests by e-main option or in the getting-started column.

**Comment by ThibG** [comment]
Implemented in #12198
