### ISSUE TITLE
ActivityPub: Accept/Reject handling does weird things

### ISSUE THREAD

**Issue by puckipedia** [tootsuite/mastodon#4607]
The ActivityPub processing seems to assume that the the `actor` is set to the person who sent the Follow; this isn't true, as it's set to the person who accepted the Follow. This means that it'll never be possible to accept (or Reject) a follow request.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by puckipedia** [comment]
(My initial guess was incredibly wrong; replaced the main issue contents with what I think is the proper issue)

**Comment by unarist** [comment]
Really? That "fix" breaks follow interaction on my instance and other master instances I saw.

Follow object in Accept / Reject is obtained from FollowSerializer with FollowRequest. FollowRequest has follower as `account` and followee as `target_account`, regardless it's in follower side or followee side. I think there is no need to swap.

**Comment by Gargron** [comment]
alice -> follow_request -> bob
alice -> follow -> bob

bob -> accept -> [alice -> follow_request -> bob]
activity actor -> activity -> object [object actor -> object activity -> object object]

@unarist I think you're right... I don't know what I was thinking. It's confusing because sometimes account is the local user, and sometimes target_account is the local user. I was debugging this with @puckipedia in IRC and I thought that this patch was applied and was important for making everything work, but maybe this patch was *not* applied at the time? @puckipedia please comment

**Comment by puckipedia** [comment]
So after thinking about it the issue was that I misread the code, and another bug (port numbers in web_domain cause any url to be non-local) caused it to work improperly and I got confused with the wording in accept/reject.
