### ISSUE TITLE
How can i delete my instance

### ISSUE THREAD

**Issue by neoranger** [tootsuite/mastodon#4636]
I need to delete my entire instance, with all the services to. How can i do that? I can't rebuild my VPS.

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Sounds like it's already "deleted"?

**Comment by neoranger** [comment]
No no, my instance is working right now, but i need to delete it. (Sorry for my bad english)

**Comment by clworld** [comment]
What needed for instance deletion (As I know. not tested. instance version <= 1.5.1 and I don't consider about ActivityPub):
* remove all follows to instance's user.
  * if not removed, remote instance send subscribe request forever
  * run BlockService and UnblockService (please be careful about BlockService and UnblockService are executed asynchronously (by Sidekiq))
* remove subscriptions to remote instance. 
  * if not removed, remote instance send toot until subscriptions are expired
  * run UnsubscribeService for account subscription_expires_at >= now()
* (optional?) remove some interactions.
  * Blocks, follow request, favorites, and so on.. are federated and still exists in remote instance after delete instance.
  * if re-create instance with same domain after deletion, these federated interactions may cause trouble.
* (optional) remove users content federated.
  * SuspendAccountService may helps you. but it is slow and costs many(because it send delete for all toot to remote instances).

**Comment by neoranger** [comment]
Thanks!

**Comment by Neustrashimy** [comment]
Could you tell me the specific procedure?
