### ISSUE TITLE
Web client stays logged in

### ISSUE THREAD

**Issue by ineffyble** [tootsuite/mastodon#468]
If you're logged in to Mastodon in multiple tabs, and log out of one, the other doesn't automatically log out/redirect.

This gets confusing, because if you then log in to a different account, the first tab will be showing the details of the old account, but if you toot, the toot comes from the account you just changed to.

**Comment by Gargron** [comment]
This is weird. Because the web UI gets an access token on page load, and then uses that access token to interact with the API. If you logout and re-login on a different account, your two tabs should have different access tokens that belong to two different accounts. So why would the old tab post under the new account?!

**Comment by ineffyble** [comment]
I'll double-test, but I had a client showing Effy, that tweeted from Tooter (the one you retweeted, in fact).

**Comment by Gargron** [comment]
The status I retweeted showed as from "tooter" on my end

**Comment by ineffyble** [comment]
Confirmed this is a bug - see http://recordit.co/ECf8Xx0elR (will be deleting in a few minutes as it contains semi-private toots)

**Comment by Gargron** [comment]
Ughhhh wtf

**Comment by Gargron** [comment]
I'm assuming this shouldn't be an issue anymore with websockets being access-token based now.
