### ISSUE TITLE
1.6.0rc1 breaks conversation threads on OStatus instances

### ISSUE THREAD

**Issue by roikale** [tootsuite/mastodon#4791]
Posts made on 1.6.0rc1 seem to have the wrong conversation id (EDIT: apparently this is not the case, see lambda's post below), thus breaking conversation view on other instances, presumably those that only speak OStatus.

Conversation broken as seen on cybre.space (not on 1.6.0rc1):
![screenshot_2017-09-03_19-01-10](https://user-images.githubusercontent.com/26201428/30004613-4598140e-90db-11e7-888a-33816faed312.png)
![screenshot_2017-09-03_18-58-59](https://user-images.githubusercontent.com/26201428/30004608-3c7c1c26-90db-11e7-82d3-e287ea68091c.png)
Original conversation: https://mastodon.social/users/Gargron/statuses/16888523

Can also be seen happening on other OStatus implementations:
https://edolas.world/notice/36611
https://edolas.world/notice/36597
Original conversation: https://mastodon.social/users/Gargron/updates/4269359

* * * *

- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by lambadalambda** [comment]
The conversation id is correct as far as i can tell, the id in the thr:in-reply to is wrong. On 1.6 instances it is something like this: 
```xml
 <thr:in-reply-to ref="https://niu.moe/users/Pasty/statuses/2933523" href="https://niu.moe/@Pasty/2933523"/>
```
The 'ref' is an ActivityPub reference, as far as I can tell, although in this case the correct one to use would be the OStatus id.

**Comment by Gargron** [comment]
I am trying to come up with a solution to this problem, but it seems impossible. Since Mastodon was designed for one protocol, I didn't think it'd be necessary to store locally generated URIs in the database, since they can be generated on the fly. Now that we temporarily have two protocols it is a problem because we want to switch the ID format but keep it the same for old content. (Because ideally we would simply start using the new ActivityPub URI format in the Atom `<id>`)

Still thinking and suggestions are welcome but this *could* be the collateral damage from a protocol upgrade.

**Comment by noxarivis** [comment]
woop woop

**Comment by lambadalambda** [comment]
@Gargron what about using the ActivityPub id as the ostatus id, too? Is that possible? That's what I do in Pleroma.

**Comment by annando** [comment]
I, personally, would always avoid so called "collateral damage". I like it the way, Diaspora did its protocol update. It was well planned, with a long switching phase over several months and much coordination between the other systems that are using their protocol. That process guaranteed that no "collateral damage" occurred.

**Comment by hikerus** [comment]
I would like to second what @annando has written !

**Comment by Gargron** [comment]
@lambadalambda You have suggested precisely that which I described in the post you replied to, with an explanation of why it's not so simple.

If we switch OStatus `<id>`s to a different format, then, overnight, deleting old content will become impossible. Sure, the deletes will go out via ActivityPub towards instances that stored it after the switch-over, but any PuSH subscriber which would ordinarily receive the delete, would receive the delete of an ID which they did not store, since they stored it with the old ID.

Therefore, switching IDs while we still generate them on the fly is not an option. Any user, I am sure, would prefer to maintain deleteability of their own content (yes, we know about networking and server failures that can impede proper deletion) over the correctness of threading on outdated instances.

I'd also like to note that as you mention, the `<ostatus:conversation>` tag remains correct, so with your software making use of it the threads should still work alright (in GNU social and derivatives).

One potential avenue towards solving this problem is giving up the on-the-fly generation of URIs in favour of generating them at creation time and storing them in the database. This undoubtedly has ramifications on the db and index size, it might also lead to a long running migration since statuses table is very, very big most of the time. It might also have other implications which are hard to predict. But this way the URI could always be sourced from the database in both protocols, we could generate the OStatus one when encountering a null value, and store the new ones in the ActivityPub format, therefore ensuring old content keeps old format and new content gets the new format.

As you can see that is no small task, we are now experiencing time constraints, and the question is still open whether this is worth the effort.

**Comment by Technowix** [comment]
Let's put another week of testing, I'm sure nobody will blame you.

**Comment by nightpool** [comment]
@Gargron mm. what if we did 

create_column :atom_uri, null: true

atom_uri: @object['_:atomUri']

and then whenever we serialize atom we use `atom_uri || uri`?

this seems like the minimum viable fix, and it should work pretty painlessly for all instances involved.
