### ISSUE TITLE
Missing notification for external mention

### ISSUE THREAD

**Issue by LukasRos** [tootsuite/mastodon#488]
A status update posted on an external network (friendica; https://pirati.ca/display/ec054ce756587ccfd5a4139436847456) which mentioned me does not appear in my notifications. The update was syndicated into Mastodon correctly and appears in the users local representation there (https://mastodon.social/web/accounts/5913).

**Comment by Gargron** [comment]
Unfortunately Friendica doesn't seem to encode mentions correctly at this time. You can test this by clicking on your name in that last link - it opens your public profile, rather than opening your profile in a column which would happen if we had information about mentions. This may be confusing but the links in the text are just links, they could technically be anything, regardless of any @ signs - the real mention information is supposed to be encoded extra in Atom.

**Comment by LukasRos** [comment]
Just wanted to let you know that I no longer have this problem, so I assume it has been fixed from the Friendica side.
