### ISSUE TITLE
Feature Request: notifications for all toots of particular users

### ISSUE THREAD

**Issue by wxl** [tootsuite/mastodon#4890]
Birbsite has a notification option for "accounts you follow whose Tweets or live videos you don’t want to miss." [(link)][1] I certainly have some accounts I follow that aren't heavy users and I worry sometimes I lose their toots among the more chatty, so a similar feature would be great. 

[1]: [https://support.twitter.com/articles/20169887]

**Comment by rainbowmultiverse** [comment]
This would need to be opt-in from the end of the person you're subscribing to. Some people don't want to be watched that closely, even if they aren't worried about stalkers and harassers.

**Comment by wxl** [comment]
If someone's worried about stalkers and harassers, it would be
reasonable to assume they would have a locked account because they would
want to limit who is capable of following them. Assumedly, they wouldn't
mind that someone who they have accepted as a follower could follow them
more closely. If they don't have a locked account, they're certainly not
doing everything they can to protect themselves, even without the
feature requested. I'm not sure it's reasonable to make the opt-in a
blocker to this request to protect the people that aren't taking
advantage of the software. I do think the opt-in would be a great
additional feature, but not a blocker. Don't you think?

**Comment by thiagomgd** [comment]
Also, if someone has an open profile, you can just use their rss feed and use it with ifttt to receive alerts via any other system. Or even, a stalker could create a fake profile and follow just that person.

So I agree with @wxl  on this.

**Comment by Cassolotl** [comment]
>if someone has an open profile, you can just use their rss feed and use it with ifttt to receive alerts via any other system. Or even, a stalker could create a fake profile and follow just that person.

I don't think "someone with non-basic abilities can get around this feature, so there is no point having this feature" is a solid argument. That could be used to object to the ability to block people, for example - I've had to block someone who followed me from nine different accounts already. It's the same argument as "we can't guarantee that our toots are deleted from federated instances, therefore a 'delete account' feature is pointless".

>If someone's worried about stalkers and harassers, it would be reasonable to assume they would have a locked account because they would want to limit who is capable of following them.

I don't think someone should have to lock down and make private their entire account in order to minimise harassment. We already have tools and features in place to minimise harassment for people with public accounts. Just because we are posting publicly, doesn't mean we shouldn't make things difficult for harassers. It's like saying there's no point having "followers only" toot privacy for people who don't require follow-requests.

I think whether or not this feature should be opt-in and how it intersects with harassment and stalking should be a discussion to have with people who have experienced serious online harassment.

**Comment by Hootwheels** [comment]
I need mobile notifications to keep track of my favorite artists and musicians when they post new art or music. I never missed a single post from them on birdsite but I keep missing content they toot on Mastodon. I want to know when new content is there so I can look at or listen to it then boost it. I understand that the feature can be used maliciously, but not all features are perfect; instance admins can all see direct messages, for example. I believe the usefulness of this feature outweighs the drawbacks, but I guess it's easy for me to say that since I'm not a stalker.

**Comment by fbruetting** [comment]
If you follow a chatty person this way, this would blow you up with notifications. So wouldn’t a RSS-like implementation (i.e. a list of unread toots) be better, which just creates one notification about the amount of further toots (if more than one)?

**Comment by Hootwheels** [comment]
that's actually a brilliant idea. the one problem i had with Twitter's tweet notifications was how many there often were. In lieu of a toot notification function I'm using lists to make sure I see everything, but it's cluttering up my UI on the desktop and using lists on Tusky involves more menu navigation than I'd like. it's not perfect, but it works.

**Comment by fbruetting** [comment]
I just created a request for an Atom/RSS-like behviour in Mastadon, which you might also be interested in: #9048

**Comment by sneak** [comment]
This is a very exciting development, because of an awesome use case: You can get notifications when bots (your own or others') post things, which can be extremely useful for learning about developing conditions quickly.
