### ISSUE TITLE
Message digest on http signatures check

### ISSUE THREAD

**Issue by cwebber** [tootsuite/mastodon#4963]
It seems like when HTTP Signatures checks are important, the body is the most important thing to be checked.  I may be misreading, but in the [current code](https://github.com/tootsuite/mastodon/blob/72bb3e03fdf4d8c886d41f3459000b336a3a362b/app/controllers/concerns/signature_verification.rb#L5) it looks like there may ensurance that a digest is produced and attached on the signing side, but there is no check that a digest was attached on the receiving side, nor that the digest matches the body content?

I may be misreading!  But if I'm right this could mean that the digest could be left out or even not match.  So maybe in the case where http signature checks are being enforced, a check of the digest being present and correct should be done alongside the signature check.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Right here: https://github.com/tootsuite/mastodon/blob/72bb3e03fdf4d8c886d41f3459000b336a3a362b/app/controllers/concerns/signature_verification.rb#L64-L66

The digest is verified when present. Also thanks to the http sigs, the digest header cannot simply be removed, or the whole http sig will be invalidated. However, if the sender does not digest their body, well, I made the decision to accept that, because the presence of a digest header was non-normative in the spec.

**Comment by cwebber** [comment]
Ok!  Well I'd think that, again, in the cases where you *need* an HTTP signature, you still want the Digest (which you're right, is supported but is not a normative *requirement*).  It's not that the signature would be invalid, just maybe insufficient.

If you think this isn't an issue feel free to close it.
