### ISSUE TITLE
Add a way to hide someone from timelines, but not from notifications

### ISSUE THREAD

**Issue by ProgVal** [tootsuite/mastodon#4989]
One may want to hide someone else from their timelines (eg. because they write too many tweets/toots), but still see notifications in case they want to talk.

This was possible in Mastodon using the "mute" feature, before v1.5.

Could a similar feature be added again?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nightpool** [comment]
see also https://github.com/glitch-soc/mastodon/pull/100

**Comment by Gargron** [comment]
>This was possible in Mastodon using the "mute" feature, before v1.5.

Yeah, this used to be "mute". And then people were like "mute should be like *that* instead", and I told them, but surely this is useful functionality worth keeping, and they were like "nope, want it to work this way", so now it works this way, and the circle is complete.

**Comment by ProgVal** [comment]
@Gargron Yeah, I saw that discussion :/

**Comment by egypturnash** [comment]
I was wandering to the Issue Tracker to see if there was any discussion of whether or not someone mentioning you and someone you muted should or should not show up in your mentions. (Currently it does.) Clearly there is a lot of difference of opinion as to What Mute Should Do. And honestly I can see times when all of these possibilities are the Right Thing.

Possibly 'mute' could use a submenu that offers "mute their toots but show when they mention me/mute toots and mentions/mute all toots from or involving this person". There is probably a better way to express these three options. Maybe separate checkboxes for muting "their toots", "them mentioning me", and "other people mentioning them". This may, however, be the start of a slippery slope that leads to something like DeviantArt's watchlist management page. (see attached)

![screen shot 2017-09-17 at 8 10 41 pm](https://user-images.githubusercontent.com/403223/30528100-7d6cb0b0-9be4-11e7-8d81-fefb0b0bd3cf.png)

**Comment by Cassolotl** [comment]
How about...

* **Sneaky block** - you don't see them at all, no notifications or anything, but they can see all your stuff. They have no way of knowing that you've sneaky-blocked them.

* **Obvious block** - you don't see them at all, no notifications or anything, *and they can't see you either, even if they look really hard.* It is obvious that they have been obvious-blocked because they plug in your username to look at your profile and they get a big error.

* **Mute** - for when you don't want to unfollow someone who talks too much, but if they mention you you want to know about it.

**Comment by ProgVal** [comment]
@egypturnash I would like that, as an advanced feature; as long as simple block and mute buttons exist.

**Comment by egypturnash** [comment]
playin' with some names, because names are important

**mute**: don't show this person on my timeline
**shush**: don't show this person on my timeline or in my notifications, other people talking about them is okay though
**obliviate**: don't show this person on my timeline or in my notifications, don't show toots that mention them
**block**: NEVER TALK TO ME OR MY SONS AGAIN

**Comment by ekiru** [comment]
If the [implementation](https://github.com/glitch-soc/mastodon/pull/100/files) and [design](https://glitch-soc.github.io/docs/features/optional-notification-muting/) of the glitch-soc support for this would be acceptable, I should be able to separate out those changes from the rest of the glitch-soc changes and submit a PR pretty quickly.

**Comment by ProgVal** [comment]
ping?

**Comment by ProgVal** [comment]
uh, forget the ping, I just noticed there is a PR. thanks ekiru!

**Comment by fsnk** [comment]
This is how I think it should work:

**Block**
I don't want to see anything this account posts, I don't want to see it in any timelines, I don't want to see notifications, I don't want to see boosts of its posts by other users. Nada. 

Not only that, it shouldn't be allowed to follow me. It shouldn't be allowed to interact with my posts - no boosts, no replies. It shouldn't even be able to view my profile when it's logged in. Even though it could just log out or open a private tab.

This account is dead to me. It doesn't exist. And it should know it.

**Mute**
_Case 1: I don't follow this account_
I don't want to see anything this account posts, I don't want to see it in any timelines, I don't want to see notifications, I don't want to see boosts of its posts by other users.

This account is uninteresting to me. I just don't care.

_Case 2: I follow this account_
I don't want to see anything this account posts in my timelines, but I do want notifications if this account mentions me.

I like to have conversations with this account sometimes but it's also super into something I'm not interested in.

**Comment by fsnk** [comment]
I like what @cassolotl said. I think maybe:

**Block** (normative behaviour for a block)
I don't see any posts by this account in any of my timelines. I receive zero notifications from this account. I do not see posts where other users mention this account. This account does not see my posts and cannot interact with them. I can't follow this account and it can't follow me. When I view this account, I don't see any posts, just a page that tells me I've blocked it. When this account goes to my profile it sees no posts and a message saying my account is private* and suggesting some other users to follow instead. 

This account is dead to me. It doesn't exist. And it should know that. 

**Sneaky block** (love this name!)
I don't see any posts by this account in any of my timelines. I don't receive any notifications from this account. I don't see posts where other users mention this account. When I view this account, I don't see any posts, just a page that tells me I've blocked it. 

This account can interact with my posts normally; there should be no indication (other than my absolute lack of response) that it is blocked.

**Hush**
I don't see any posts from this account in my timelines unless I'm mentioned; I see notifications when they interact with my posts, and I see posts by other users which mention this account.

I'd also like some sort of soft hush that allows me to turn off boosts from a specific user, but otherwise see their posts and interact with them normally.

**Comment by Cassolotl** [comment]
@fsnk This sounds perfect to me! :)

**Comment by coderemy** [comment]
With the upcoming list feature, I'd like to be able to mute people on my home timeline but not in lists

**Comment by Cassolotl** [comment]
We can choose whether to mute someone completely or just in replies now. :)

![screen shot 2018-01-19 at 14 14 59](https://user-images.githubusercontent.com/6607512/35152569-2b5e73da-fd23-11e7-8be5-4fd3ef4af85c.png)

This feature request is probably dealt with now, right?

**Comment by ProgVal** [comment]
Indeed!
