### ISSUE TITLE
add ability to change the size of columns

### ISSUE THREAD

**Issue by Moth-Tolias** [tootsuite/mastodon#499]
context: as it is mastodon is just a centimetre too big to fit on my screen. if i could make them just a tad smaller, they would fit.

alternatively: being able to "minimise" the tooting column as with tweetdeck would also solve this problem for me, but i imagine there are others who would benefit from customisable column sizes

**Comment by nevillepark** [comment]
It's a centimetre too small on mine. Would adjusting the CSS so that (above a certain screen width) each column takes up 25% of the screen solve the first problem?

**Comment by elad661** [comment]
Right now the column width seem to be hardcoded as `width: 330px`.
To work better on wider screens, this could be changed to have both `min-width: 330px` and `width: 25vw`, so that it takes 25% of the screen and doesn't get too narrow if the screen is not wide enough (the min-width can be lower than 330 if needed I guess, but probably not much narrower than that because otherwise it'd be too narrow to use).

I don't think allowing the user to change column sizes individually is a good solution. In my opinion the best solution is to use media queries and the css "vw" unit, to provide *everyone* with a default that works and doesn't require the user to fiddle with column widths.

I guess automatically "collapsing" the "tooting" column with a media query if the screen is too narrow is a good solution for narrow screens (having the columns narrower than 330px will make them not very usable, I think).

**Comment by flashcode** [comment]
On my screen, the 4 columns use ~60% of total width, it would be very nice to have something like 25% for each column and then use full width, so I don't spend my time to scroll columns which can contain some long posts.

**Comment by Gargron** [comment]
See #3207

**Comment by gsuberland** [comment]
#3207 does not currently resolve this at all. I recommend that this issue is re-opened.

**Comment by Fishrock123** [comment]
I'd also like this to be reopened.
