### ISSUE TITLE
Shortcode parsing inconsistency between custom and standard emoji

### ISSUE THREAD

**Issue by MightyPork** [tootsuite/mastodon#5044]
Standard shortcodes must be surrounded by whitespace, whereas custom emoji do not.
They use two different parsers, one server-side and one client-side.

This discrepancy will be confusing to users. I think it should be fixed to either work without spaces on both sides (preferred), or at least require them consistently.

example by wryk @ witches.town
![screenshot_20170922_175749](https://user-images.githubusercontent.com/2041118/30753432-91c6f3e8-9fbf-11e7-9d75-9d217860017f.png)

**Comment by Gargron** [comment]
So this is the original solution that @wxcafe asked me to adopt: <https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/10647>

That is why shortcodes not separated by whitespace are not converted to unicode characters.

Currently I am wondering why that solution didn't just make a special case for :100:, because I am not familiar with any other false positives.

**Comment by MightyPork** [comment]
from yesterday's discussion on glitch-soc slack, we know of at least the following that would also cause problems:

- `:bee:` :bee:
- `:a:` :a:
- `:b:` :b:
- `:ab:` :ab:
- `:abc:` :abc: 
- `:abcd:` :abcd:
- `:cd:` :cd:

One idea was to simply ignore all inside square brackets, which is the usual format of ipv6 URLs (and when you want to specify port).

There's no guarantee custom shortcodes won't use [0-9a-f] as well, so if we care about IPv6, this must be done in the JS replacer too.

**Comment by Gargron** [comment]
@MightyPork Messing up text via the JS replacer is not a big issue because it's only the display layer, the underlying data is correct and can be retrieved later. The server-side code *modifies* the text forever by converting shortcodes to UTF8, so messing up would be permanent.

That being said, I don't have a solution to this if it's not just :100: and if we're not ready to give up IPv6 addresses.

**Comment by wxcafe** [comment]
I mean we're just talking about IPv6 addresses here but there's other formats that can appear later or that we're not aware of that can crop up (for example, MAC addresses are also written with hex numbers surrounded by colons, so `:ab:` 🆎  can happen).

It's pretty much a niche problem tho tbh. I don't know that it should be such a big thing. The best solution imo is having the textbox ask like it does on github ![screenshot from 2017-09-22 23-23-08](https://user-images.githubusercontent.com/3009327/30764860-1d4ab40e-9fed-11e7-9c88-9608cb9974b1.png) when you start typing an emoji code, so that you can escape and that it doesn't replace... but we don't have a textbox suggestion thingy yet.

**Comment by MightyPork** [comment]
_we_ do have one: https://github.com/glitch-soc/mastodon/pull/149 (+ https://github.com/glitch-soc/mastodon/commit/c89cce0219646502b4d338213d112a528373bdc4), you're more than welcome to copy the implementation and add the custom shortcodes. 
But I'm not sure how the suggestions box will help with someone copypasting in the ipv6 / mac address?

**Comment by Gargron** [comment]
@MightyPork Well @wxcafe's idea is that the autosuggestion will insert a unicode emoji straight away based on your shortcode selection, therefore eliminating the need to parse shortcodes on the server.

**Comment by wxcafe** [comment]
yeah, why send the whole shortcode when you can replace it with an actual utf8 char... Except for custom emojo, ofc.

**Comment by MightyPork** [comment]
I think that doesn't really solve the issue if people can still use
shortcodes for standard emoji (and e.g. on Windows 7 or Linux, utf8 emoji
are quite a miserable experience, so I wouldn't blame anyone for not using
them).

**Comment by Gargron** [comment]
@MightyPork No we mean like. Like on GitHub, you start typing the shortcode, it shows you suggestions, when you select one, it inserts the unicode into the text input. The server no longer needs to parse shortcodes at all, because then we always expect them to either already be unicode or intended to be the colons text. This is probably the best choice.

**Comment by wxcafe** [comment]
no I mean, it's like how it is on github. You can start typing shortcode, and then you have two choice, type enter to confirm (and then github replaces the shortcode with the actual utf8 emoji) or esc and then it's not replaced.

**Comment by MightyPork** [comment]
Well that's not my experience with GitHub, it completes the shortcode but doesn't replace anything. Could be it does that only on Mac.

This would solve the issue, if you completely remove server-side emojification - but not for custom emoji that don't have any utf-8 counterpart. So the JS replacer still needs to be improved, or eg. `:abba:` as a custom emoji will corrupt ipv6 address.

**Comment by wxcafe** [comment]
neither me nor eugen are on mac. but yeah, it does...

**Comment by wxcafe** [comment]
:thumbsup:

-- 

Clément 'wxcafé' Hertling
