### ISSUE TITLE
Provide a way to add Mastodon in Firefox Share

### ISSUE THREAD

**Issue by Deuchnord** [tootsuite/mastodon#5147]
Firefox provides a function, Firefox Share, that allows users to share a page on any service configured. This function is available via a button: ![Screenshot of the Firefox Share button](https://user-images.githubusercontent.com/7600265/31017831-2caa6fe2-a52a-11e7-8738-f46a7f8439d6.png).

Is it possible to add a way to add our Mastodon instance in this menus, so that it is possible to share quickly a page in this way? I've seen this kind of function has been implemented by some websites, like [Shaarli](https://github.com/shaarli/Shaarli), where you can add your instance to Firefox Share just by clicking a button in the administrator's tools.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by sorin-davidoi** [comment]
The Social API is [deprecated](https://developer.mozilla.org/en-US/docs/Archive/Social_API). We implement the [Share API](https://www.chromestatus.com/features/5668769141620736), which is an established standard. Unfortunately, Firefox does not implement it yet, but you can use it on Android in Chrome (since version 61). [This is how it integrates with Mastodon](https://toot.cafe/@sorin/1275584).

**Comment by Deuchnord** [comment]
Oh, I didn't know about the deprecation, sorry ^^
