### ISSUE TITLE
Can't get OAuth example to work

### ISSUE THREAD

**Issue by aeonofdiscord** [tootsuite/mastodon#523]
Hello. I've been trying to get an OAuth access token using the instructions [here](https://github.com/tootsuite/mastodon/blob/master/docs/Using-the-API/Testing-with-cURL.md), but! It's not working.

The command I'm using is

`curl -X POST -d "client_id=[...]client_secret=[...]grant_type=password&username=[...]&password=[...]" -Ss https://mastodon.social/oauth/token`

I'm expecting a JSON object back, but instead get 

`<html><body>You are being <a href="https://mastodon.social/auth/sign_in">redirected</a>.</body></html>`

Have I done a mess-up or is something broken?

**Comment by Gargron** [comment]
I've confirmed this behaviour locally. I believe the redirect happens when your login credentials are wrong. Please make sure you enter your e-mail as the "username", and that your password is entered correctly also.

If you are confused why you have to enter your e-mail into the "username" field (which I agree it's confusing), it's because these parameter names are mandated by the OAuth2 protocol, and we happen to be using e-mails for login purposes on Mastodon since it makes it harder to attempt breaking into someone else's account.

**Comment by aeonofdiscord** [comment]
Having messed around with this a bit, it seems like the problem only occurs for email addresses that contain a + character. Switching to a different email address or submitting the parameters using the -F option (which sends them as form/multipart instead of application/x-www-urlencoded) fixed the problem. Sending the data using the --data-urlencode option, or manually url-encoding the parameters, didn't seem to make a difference, so I'm not sure what's going on there.

I don't know if this is a Mastodon or a Doorkeeper issue but it's probably worth mentioning it in the docs.
