### ISSUE TITLE
Generating /mastodon/public/500.html not working for Docker

### ISSUE THREAD

**Issue by tateisu** [tootsuite/mastodon#5274]
in Docker case,  container's /mastodon/public is copied from source tree.
this is not volume-mapping and persistent.

then `docker-compose run --rm web assets:precompile ` is invoked,
it writes to container's  /mastodon/public/500.html, then container is removed.
500.html will be lost after assets:precompile.

quick-fix:
- edit docker_entrypoint.sh  ,add line `chgrp ${GID} /mastodon/public`
- add volume mapping for /mastodon/public/500.html to somewhere file on host machine, also set user,group correctly.

* * * *

- [x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by tateisu** [comment]
this problem is similar to "sw.js". 
sw.js is symlink to assets/sw.js ,(assets folder is volume-mapped)

**Comment by lightweight** [comment]
To successfully upgrade my Mastodon 2.0.0 instance to 2.2.0, I had to copy my 500.html and sw.js files from my separate `assets` directory (which had valid instances of that file) over the links in the Mastodon `public` directory. Otherwise I couldn't do any rebuilds or run any of the rake tasks with my Dockerised configuration... Hope this is useful to someone.
