### ISSUE TITLE
Unlisted public statuses should appear in hashtag timelines

### ISSUE THREAD

**Issue by ThibG** [tootsuite/mastodon#5463]
Hashtags in public unlisted toots are processed, but the current implementation of hashtag timelines only displays public (not unlisted) toots, just as unfiltered local and public timelines.

While this behavior makes sense, it is, in my experience, highly counter-intuitive: hashtags are meant to be searched, and many people expect their toots to be visible in the hashtag search even if they are unlisted.

This is made especially worse as there is no clear indication in either the public profiles or Web UI as whether a toot is unlisted or not, thus making it difficult to understand why a particular toot appears in a tag timeline or not.

**Comment by nullkal** [comment]
I agree. People tooting with hashtags usually means toots being searched, so I think we can change the behavior without any problem.

**Comment by ThibG** [comment]
I would also add that the current code hides replies, but I think those should be displayed for the same reasons: people use hashtags so that their content is searchable.

**Comment by SoniEx2** [comment]
This is supposed to be an *enhancement*? Feels more like a bug to me...

**Comment by ThibG** [comment]
@SoniEx2 care to elaborate?

**Comment by SoniEx2** [comment]
Say you wanna post nsfw. And the instance description says nsfw must not appear in public timelines. So you post nsfw as unlisted. Then nobody can find it. So you complain to the admins and repost it as public and put a content warning on it.

And that's how unlisted posts not showing up in tags should be considered a bug.

**Comment by ThibG** [comment]
@SoniEx2 Ah, I thought you were against the proposed change!

**Comment by Gargron** [comment]
Okay so like. Unlisted means "does not appear in public timelines". A hashtag timeline is a public timeline. I think we're pretty clear on this. Use case:

Talk *about* `#followfriday` *without* interrupting real `#followfriday` toots.

**Comment by SoniEx2** [comment]
A hashtag timeline is a hashtag timeline. It's neither the instance nor the federated timeline. It's not a click away - you need to type in a key, known as the hashtag.

**Comment by ThibG** [comment]
@Gargron I don't fundamentally disagree with that, but it's not explained anywhere in Mastodon and it's quite confusing. I think the following things should be done to limit that confusion:
- Display a short warning whenever a `#hashtag` is written down in the toot text area and the privacy setting for the toot is “unlisted”
- Somehow make it possible to see whether an already-posted toot is public or unlisted

**Comment by renatolond** [comment]
Hm, I would go with that @ThibG suggests at least. It was never my understanding that hashtag timelines were considered a public timeline, for me it was just a matter of not getting content into local/global, but that could be searched with the hashtags.

**Comment by johanbove** [comment]
Thanks for building this feature! My personal use case would be that I'd like to keep a list of "#reminder" toots, kinda like a personal todo list, which I would post through unlisted "toots". Therefore I like the idea @SoniEx2 proposed to have "unlisted tags". Therefore I could organize my unlisted toots with unlisted tags for my own personal search whenever I would like to dig back into the past.

**Comment by renatolond** [comment]
I think this use case is already supported if your instance supports searching your own toots. You could post your toots with the hashtag (even as direct toots to yourself) and look for them later without the #.

**Comment by jeroenpraat** [comment]
Outcome poll about this:

https://todon.nl/@jeroenpraat/102778601875665701

**Comment by pelegm** [comment]
I understand this hasn't changed, and unlisted hashtags are not searchable, correct?

**Comment by ClearlyClaire** [comment]
It indeed hasn't changed.

**Comment by pelegm** [comment]
That's a shame. Here's a particular use case: suppose you write a long thread. You don't want to spam the local timeline (that includes replies, if I understand correctly), so you set everything but the first toot as "unlisted". But you do want to tag some of the replies in your thread because you want people that are *actively* looking for these tags to find those toots.

You can't.

So you either spam or hide.

**Comment by joenepraat** [comment]
> That's a shame. Here's a particular use case: suppose you write a long thread. You don't want to spam the local timeline (that includes replies, if I understand correctly), so you set everything but the first toot as "unlisted". But you do want to tag some of the replies in your thread because you want people that are _actively_ looking for these tags to find those toots.
> 
> You can't.
> 
> So you either spam or hide.

I completely understand your point. I had the same problems with it first, but I changed my mind because people see the word 'unlisted'. Unlisted means that it is unlisted from timeline, including hashtags, that are practically also timelines (especially now you can follow hashtags).

A solution would be to make it opt-in in the user preferences.

**Comment by SoniEx2** [comment]
if unlisted don't show up in hashtag mentions then they shouldn't show up in @ mentions (notifications) either tbh.

**Comment by joenepraat** [comment]
> if unlisted don't show up in hashtag mentions then they shouldn't show up in @ mentions (notifications) either tbh.

This is not about mentions, but public timelines.

**Comment by SoniEx2** [comment]
hashtags are just adhoc groups. if @'ing a group with an unlisted post shows up on the group then it should show up on the hashtag too.

**Comment by ddelabru** [comment]
I imagine many users feel like there are already a lot of post visibility options, but I would personally appreciate a new option like "Quiet" or "Taggable"—something that behaves just like "Unlisted" does now except that it explicitly can show up in hashtag searches. The use case being one where someone wants to engage with people who follow a given hashtag/topic without cluttering the local/federated timelines where not everyone might be interested in that topic. (As a specific example, I can imagine that some people who liveblog Eurovision every year might want to do this so they see each other's posts without annoying people who don't follow the event for whatever reason.)

I personally did assume, as some others did, that Unlisted posts would behave this way and that I would need to mangle hashtags with punctuation (like `# tag` or `#/tag`, or even `the tag hashtag`) if I didn't want my unlisted posts to show up in the hashtag searches. But I can see that some users have the opposite assumption, and this behavior has been in the UI for several years, so it would be a bad idea to suddenly make posts that users had intentionally hidden from hashtag searches show up in them.

Some other issues have proposed new kinds of tags using something like `+tag` or `##tag` to either explicitly opt in or opt out a hashtag from the searches. I think a new visibility setting would be a little more intuitive.

If there might be interest in this proposal and it's not already covered by other issues, I can open a new issue for it.

**Comment by jonaharagon** [comment]
> Unlisted means that it is unlisted from timelines, including hashtags, that are practically also timelines (especially now you can follow hashtags).

@joenepraat This is actually the reason I assumed it *would* be possible to see unlisted posts in hashtag searches. Unlisted posts are visible if you follow a user, so I would also expect unlisted posts with a hashtag to be visible if you follow a hashtag.

> (As a specific example, I can imagine that some people who liveblog Eurovision every year might want to do this so they see each other's posts without annoying people who don't follow the event for whatever reason.)

@ddelabru I have a user on my instance who wants to do something similar to this, but with sporting events. They are looking for a way to post so that people following a specific hashtag would see their posts, without publishing every single post to the local timeline. Maybe your proposal for another visibility option makes more sense though.

**Comment by Slugger** [comment]
A use case I'm hitting: You create a bot that posts about a topic and hashtags all posts, expecting people who search for said hashtag to be able to discover that there's a bot that's monitoring and posting about a subject of interest (such as live tracking their favourite sports team/player).

The issue is that every instance I've encountered requires that all bots that post must post unlisted.  Now the bot has almost zero value.  It's tracking and posting and hashtagging what it's seeing but no one can discover it.  I understand why the bot posting policy is what it is, but I assumed that the hashtags of the unlisted posts would be searchable, allowing people to find the bot and then follow it and/or the hashtags its posting about if so interested.  As it currently stands, the only way this would be possible would be if the posts were public.  Initially my bot was posting public and people were discovering it based on the hashtags and picked up some followers. Then I was made aware that bots must post unlisted.  Once I made that change to adhere to the rules, the bot is basically talking to itself. 😆  No one is able to find the bot nor search on the hashtags its posting about.

**Comment by Mbodin** [comment]
I fully relate on the need to have a visibility which does not appear on the local and global timelines whilst being searchable through hashtags. I wonder whether “unlisted” is the best way to name it, though: as we’ve seen in the discussion, not everyone understands it the same. Maybe “quiet” or “searchable” would be less confusing terms.

It would be nice to see the usage of people currently using hashtags within unlisted toots. I currently get a warning if I do so that the hashtag won’t be searchable, and I think it wouldn’t be a good think to have toots that were said not to be findable through hashtag search suddenly becoming findable: maybe some people would felt betrayed by the warning message that was then displayed.

So here is a suggestion:
- add a new visibility status (calling it “quiet” or “searchable”),
- to prevent having too many visibility statuses confusing people, no longer display the unlisted visibility status in the interface,
- have a new option to select which visibility statuses to be displayed.

The rational is that we won’t change the behaviour of unlisted toots, thus protecting people assuming the current behaviour. But also avoid confusing new users by not showing too many options. As we have seen, the unlisted visibility status doesn’t have a full consensus about what it should do, so let us keep its current behaviour, but make it an option—not shown by default.

**Comment by Die4Ever** [comment]
We've also run into this issue with DXRandoActivity, a bot for what players are doing in the game. We make a hashtag for each playthrough ID so you can follow their journey, and we also have a hashtag for #DXRandoBeatGame for when people beat the game, and a few other hashtags too. 

https://mastodon.gamedev.place/@theastropath@mstdn.ca/110400849274113576

**Comment by Die4Ever** [comment]
Shouldn't these at least be visible locally even if they aren't federated? It's kinda silly that I can click on a hashtag and get 0 results even though it was obviously at least present in the toot where I clicked on it.

**Comment by Sushubh** [comment]
This is kind of an annoyance if you are posting your rss feeds to your brand account. I am posting content as unlisted so as not to pollute the public feed of the instance. But the content is basically invisible for anyone who might be looking for it because unlisted content does not appear in search even if account has opted for search result integration. 

Maybe I should find an instance focused on rss feed posting so that I can post the content with public privacy setting 😬 (suggestions welcome)
