### ISSUE TITLE
Dropdowns should scroll inside columns, not outside columns

### ISSUE THREAD

**Issue by Cassolotl** [tootsuite/mastodon#5466]
Chrome on a Mac.

![menu glitch](https://user-images.githubusercontent.com/6607512/31767478-279e6a00-b4c3-11e7-9927-e164670b8b8e.gif)

* * * *

- [Y] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [N/A] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nolanlawson** [comment]
Thank you for filing this. This is a known issue and was noted in https://github.com/tootsuite/mastodon/pull/5434#issuecomment-337293871.

The issue currently is that the dropdowns are drawn over the entire app as opposed to a single column. So for instance, they can span columns, which is why they don't scroll with columns.

Ideally dropdowns should be drawn on a per-column basis.

**Comment by ThibG** [comment]
I believe this has been fixed for every dropdown menu type now.
