### ISSUE TITLE
Compilation failed:The code generator has deoptimised the styling of "/mastodon/node_modules/emoji-mart/dist-es/data/data.js" as it exceeds the max of "500KB".

### ISSUE THREAD

**Issue by 84795949** [tootsuite/mastodon#5536]
docker-compose run --rm web rake assets:precompile
Starting mastodon_redis_1 ... done
Starting mastodon_db_1 ... done
Creating mastodon user (UID : 991 and GID : 991)...
Updating permissions...
Executing process...
Webpacker is installed 🎉 🍰
Using /mastodon/config/webpacker.yml file for setting up webpack paths
Compiling…
Compilation failed:

[BABEL] Note: The code generator has deoptimised the styling of "/mastodon/node_modules/emoji-mart/dist-es/data/data.js" as it exceeds the max of "500KB".
(node:174) DeprecationWarning: Chunk.modules is deprecated. Use Chunk.getNumberOfModules/mapModules/forEachModule/containsModule instead.

**Comment by corbindavenport** [comment]
This is due to the machine not having enough RAM during the build process. Try adding a temporary 1GB swap file with these instructions: https://github.com/tootsuite/mastodon/issues/5836#issuecomment-352225419

**Comment by BobLisa** [comment]
I had to seen this issue,and as this error:The code generator has deoptimised the styling of "xxx/xxx/templates.js  as it exceeds the max of 500KB " when a templates.js document was packaged for webpack.So I found some method to resolve it.  I know a  truthful thing Because we could use the different program frames.
You can find gulpfile.js and search the word "babelify", exmaple :

bundler.transform("babelify", { "compact": false,presets: ["es2015"] }); 

you can see above setting ,I only added "compact":false, Hope to help you.
