### ISSUE TITLE
More of a query than an issue - Oauth2 for log in in to external services

### ISSUE THREAD

**Issue by LordBonzi** [tootsuite/mastodon#5572]
Is there any way to use mastodon to log in to external services, e.g Gitea or whatever?.

As I can see there is OAuth2, but only for apps and not logins. If there is a way (Beta version/Plugin/Etc) to enable it, can you point me to it. If not I'd like this to be a thing as I plan to use it as the main way to log in to my gitea instance and etc as I run a little invite only collection of self hosted software for me and friends (I'm kind of tinfoil hat)

* * * *

These don't really have a place/apply to this "issue" as it really isn't an issue and more a plea for help and suggestion

```
- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).
```

**Comment by nightpool** [comment]
Yes, here's the OAuth flow:

 - ask the user which domain they want to log in to
 - If you don't already have a registered secret for that domain, [programmatically register one using the API](https://github.com/tootsuite/documentation/blob/master/Using-the-API/API.md#apps). This gives you a client ID and a client secret for that Mastodon *instance*. Make sure you pass the correct redirect URL
 - Use that client ID and client secret to do oauth against /oauth/authorize with the parameters `scope=read`. This is the same as any normal OAuth, when the user is done they'll be redirected to your redirect url. 

Does that make sense? the only difference is that rather then a normal oauth implementation—where you'll have 1 token that you manually generate per provider—mastodon's distributed nature requires you to generate tokens programmatically for each instance. This is because there's no central "gatekeeper" that could hand out tokens or authorize clients.

**Comment by LordBonzi** [comment]
Thanks a lot!

I'll give it a wizz when I get my VPS back up and tell you the results. You just saved my behind
