### ISSUE TITLE
Favorites column hides statuses on screen

### ISSUE THREAD

**Issue by nightpool** [tootsuite/mastodon#5630]
After scrolling down past two pages of favorites, the intersection observer starts going wonky and hiding posts that should be on the screen:

![image](https://user-images.githubusercontent.com/233815/32564249-ac57f324-c481-11e7-9617-c9aec3b73cf8.png)

Reproduced on:

 - v2.0.0, desktop chrome on mac (@nightpool, @cassolotl)
 - v2.0.0, mobile (android) firefox nightly (@sorin-davidoi)
 - master, mobile chrome (@beatrix-bitrot)

Could not be reproduced on:

 - master, desktop chrome (@beatrix-bitrot)

**Comment by nightpool** [comment]
We should figure out why this isn't happening on master on desktop and backport that fix for a patch release.

**Comment by TheInventrix** [comment]
This occurs on v2.0.0 in Chrome on Windows as well.

**Comment by MitarashiDango** [comment]
I will report on this matter because I have confirmed the related actions.
(この件について、関連すると思われる動作を確認したため報告します。)

When scrolling through the favorite column, multiple HTTP requests with the same max_id were sent at the same timing.
(お気に入りカラムをスクロールした際、同一のmax_idが指定された複数のHTTPリクエストが同タイミングで送られていました。)

Attach the screenshot of the developer tool when the phenomenon actually occurred.
(実際に現象が発生した時の開発者ツールのスクリーンショットを添付します。)

![image](https://user-images.githubusercontent.com/19360569/33086562-431a62ac-cf2b-11e7-957b-d5e93d6ea861.png)

**Comment by clement-analogue** [comment]
I have this issue with Firefox Nightly 59 on Linux (Ubuntu 16.04).

**Comment by nightpool** [comment]
This is still happening on master.
