### ISSUE TITLE
Composition column blinking in Firefox 52

### ISSUE THREAD

**Issue by Sylvhem** [tootsuite/mastodon#5660]
On Firefox 52.4.0 (64-bits edition) the composition column start blinking when Mastodon have been opened for some times. When it happens the content of the first column sometimes disappear for a split second. The frequency of the blink varies but can become fast enough to be really annoying.
Cleaning the cache with <kbd>Ctrl</kbd>+<kbd>F5</kbd> seems to help.

EDIT: This is what a mild blinking looks like.
![blinking](https://user-images.githubusercontent.com/5222316/32838045-0308abbc-ca10-11e7-85ac-7ac2844766d6.gif)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Aldarone** [comment]
I really should work on making the WitchesTown theme a proper custom theme… I hope it's not a flexbox bug.

Could you right clic on the header of a column and then clic on « Inspect this element »
Then click on the nearest element with `class="column"` and disable the rule « flex-grow » in the right sidebar ?

![capture d ecran_2017-11-15_14-25-52](https://user-images.githubusercontent.com/2682011/32838415-22feb172-ca11-11e7-87ff-c4515d1d34af.png)
![capture d ecran_2017-11-15_14-26-32](https://user-images.githubusercontent.com/2682011/32838444-36666a34-ca11-11e7-91a4-72fab1d2a8be.png)

And then see if the problem is still happening.

**Comment by Sylvhem** [comment]
Just tried that and it didn't change anything. So don't worry, I don't think it has something to do with Witches Town custom theme :).

**Comment by Sylvhem** [comment]
Since Mastodon 2.1.2, the Fluffy Elephant Friend that is now at the bottom of the composition column is also blinking independently.

**Comment by Gargron** [comment]
I guess it's FPS lag. The webapp is heavy because of how much it has to do (all the content getting streamed into the columns) but it's just too ambitious. There is a lot of DOM elements. That just lags out the browser. I wish I could do something but I don't think it's possible. There are way lighter clients out there, like Pinafore, that have a simpler layout and therefore can be more efficient with rendering.

Anyway, refreshing the page is the best way to fix this. The complicated part in a webapp that displays content in such a way is knowing when the content can be unloaded for sure (because columns and various elements and modals can cross-reference the same objects). For that, refer to #787

**Comment by Sylvhem** [comment]
> Anyway, refreshing the page is the best way to fix this.

Problem is, refreshing the page doesn't really help. I had the feeling it did when I opened this issue, but recently it doesn't seem to do anything.
Are you sure it's a just a normal lag? Because when I started using Mastodon, in April 2017, I didn't have this problem.
