### ISSUE TITLE
Account migration via OAuth using a TCP-like handshake and data transfer mechanism

### ISSUE THREAD

**Issue by SoniEx2** [tootsuite/mastodon#5667]
We have OAuth.

Why not add account migration the TCP way?

- Connection: https://en.wikipedia.org/wiki/Transmission_Control_Protocol#Connection_establishment
- Migration: https://en.wikipedia.org/wiki/Transmission_Control_Protocol#Data_transfer
- Termination: https://en.wikipedia.org/wiki/Transmission_Control_Protocol#Connection_termination

This solves all the issues with account migration.

Other things to consider:

- Proxying
    - As with TCP, both ends can see the proxy, since there are 2 connections and they're both terminated at the proxy. This makes blocking such proxies trivial. We already block harmful instances, what's different about blocking proxies?
- NAT
    - Network Address Translation, unlike proxying, is transparent to one end of the connection (but not both). This makes it harder to filter, but at the same time it's not an issue: it requires DNS spoofing which is trivially defeated by, among other things, TLS/HTTPS and DNSSEC (see https://en.wikipedia.org/wiki/DNS_spoofing#Prevention_and_mitigation ).

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] ~~This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).~~

**Comment by sivy** [comment]
If I'm reading your suggestion correctly, you're making a case that Mastodon use OAuth between instances to allow one instance to copy/migrate the account and associated content over from the original instance. I think this is the best way to do account migration and let's the two instance coordinate.

I'm not a Mastodon developer but could see the flow looking like:

1. User from Old Instance arrives at New instance
2. User activates the "Sign up" flow
3. After creating credentials, a new step: "Migrate Account"
4. Enter the original instance url
5. OAuth flow is triggered, New Instance asks for read privileges on Old Instance (read-only prevents bad-actor instances from posting/deleting content on the original instance)
6. With read privileges, New Instance duplicates any account settings (bio, etc, perhaps this is configurable in the wizard)
7. New Instance queues a full content migration (offline so that the user does not have to watch a spinny indicator while their toots are copied)
8. After content is migrated, user is notified that they can now delete their account on Old Instance.

Issue with migration: replies, etc could be broken unless the migration process literally updates the toots of all users on all instances that replied to your toots (impractical).

Food for thought.

**Comment by SoniEx2** [comment]
> Issue with migration: replies, etc could be broken unless the migration process literally updates the toots of all users on all instances that replied to your toots (impractical).

This is why you don't delete content. You also shouldn't recommend deleting the old account.

Oh and account migration OAuth should be separate from other OAuth and should automatically expire after some time or something.

Also I think "read" should be like "ack" and the old instance needs write perms on the new instance and "write" should be like data packets. This means you need a 3/4-way handshake, but also makes it a lot more secure. (When I said "TCP" I wasn't kidding!)

**Comment by kacealexander** [comment]
So, my thoughts on deletion here: perhaps the option (like: "Do you want to delete the old account?") would work best. See, I need to ensure I have ONE instance,otherwise people trying to follow me get very confused.

You don't HAVE to delete, but deleting content should be a personal choice. :) IF it can be done without breaking everything. 

Alternately, you could keep it all in and keep replies working, but remove all traces of "follow" option to the old account. Frex, before I got familiar, I made an account on an instance that I realized wasn't right for me, so I deleted it. Unfortunately, when people search for me, that old, deleted account shows up on the suggested follow list. Confuses everyone who tries to follow me.

And thanks again for everyone's hard work!

**Comment by deutrino** [comment]
Tagging #177
