### ISSUE TITLE
Think about renaming 'silence' to 'default block'

### ISSUE THREAD

**Issue by lambadalambda** [tootsuite/mastodon#5694]
Most people and admins think that the silence feature hides a user's posts from the public and federated TL. In fact, it hides the user's posts from every kind of interaction (except repeats), so it acts more like a default block.

This can lead to very unfortunate situations, where a user Alice on instance A is silenced on instance B, someone on instance B boosts a post by Alice so it becomes visible, and people on instance B start replying to Alice. Alice' replies to instance B won't be seen by anyone not following her, so she will appear to be ignoring replies.

Everyone I talked to about this didn't know about this behavior of the silence feature, so I suggest renaming it to something more descriptive like 'default block' and adding a separate 'silence' feature that just hides a user's posts from the public TLs.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by LienRag** [comment]
Better idea: make it do what it says it does: hide user posts from public and federated TL, nothing more.
There is already the "Block" option to block people.

**Comment by lambadalambda** [comment]
In general i'd agree, but people may already be relying on the current behavior.

**Comment by deutrino** [comment]
I'm gonna put this here and then if warranted make a separate issue if you don't like it. I'd discussed this just last night with some people on the fediverse and we came up with some ideas.

From my perspective as a new but highly interested user who's done a LOT of digging into the fascinating history of Mastodon and the fediverse... it's my perception that the "silence instance" feature really was intended to keep the public and federated timelines clear of chatter from certain instances, and _not_ to further hinder communication in any other way.

Proceeding with that belief, I think the **current behavior** - where, in a thread, **toots from users on silenced instances will be completely missing with no indication of such** - is not optimal.

However, some users may prefer it that way, and as another commenter pointed out, some may be relying on it as such (knowingly or otherwise). I'm trying to thread that needle and not contribute overmuch to UI bloat with this proposal.

**I propose that the "silence instance" feature be amended to have the following effects:**

* Toots from silenced instances do not appear on the public or federated timelines, just like now.
* When a user is reading a thread containing toots from silenced instances, those toots appear as collapsed stubs which the user can click to expand if desired.
* Users who wish not to see stubs from a given instance can use the UI which exists to hide an instance, which will also hide the stubs.
* Users who wish to always see toots from a given instance in full, rather than collapsed, can easily do so from within an expanded stub.

An example of collapsed stubs, very unobtrusive:

![stubs 1](https://user-images.githubusercontent.com/304300/32821182-fde63a66-c986-11e7-976b-55d3cd3f84a4.png)

And example UI of expanded stub, the pin button would make expanding toots from that instance permanent (sticky):

![stubs 1 expanded](https://user-images.githubusercontent.com/304300/32821186-01ab60e0-c987-11e7-8a39-a5909ee120c6.png)

In essence this is a sneaky way to request per-user instance blocking, along with a UI which I believe is a good compromise for all stakeholders.

* Users who don't want to be reminded of toots from an instance can hide them with the existing UI to hide an instance.
* Users who don't want the hiding in their way can stop it on a per-instance basis with one click from an expanded toot.
* Users on silenced instances have their interest in appearing - at the request of the reader - properly within threads, instead of being invisibly missing.

**Comment by taoeffect** [comment]
I personally think the Silence feature, as is implemented currently, leads to an absolutely horrible user experience. It's quite insulting, really. Basically a "d*ck move", something you'd probably get punched for in real life.

You there, Mr. Instance Admin, suddenly breaking someone else's timeline, without any explanation, request, or any sort of understanding between you two. IMO, the silence feature should be completely removed until it's rewritten, and then it should ***require*** giving the user a warning and a chance to "redeem" themselves for whatever offense they caused your delicate sensibilities.

**Comment by taoeffect** [comment]
Re my previous comment, I want to make something clear: the issue I'm describing doesn't appear to be mentioned in the OP. When my account was (temporarily, thankfully) silenced, it wasn't even that my toots were removed from the instance/federated timelines, it was, in addition to that:

- My own personal timeline was literally broken. Toots that were previously chained together were no longer chained together. So you couldn't follow a thread.
- You could not look at a toot and see replies to it (my own or anyone else's)

And possibly, my toots might've even been hidden from my own followers (who *want* to see them).

So I hope you can understand why I was so incensed. I would expect that sort of craziness and abuse of users from Twitter, not Mastodon.

**Comment by deutrino** [comment]
@lambadalambda Just to be sure, this issue is about silencing users, not silencing instances? I may have misunderstood when adding my comment above, which has to do with silencing of instances. The duplicate terminology is very unclear, which of course is a reason for this issue, even if it's a different one than I thought :sweat_smile:

**Comment by unextro** [comment]
Is this issue the reason some (I assume silenced because cross-posting) users' threads are broken when viewed from the original URL? For example, this is a thread of 6 posts and via client I can see the thread on my instance but when viewing individual posts from the source server the thread is broken:
1. https://mastodon.social/@seldo/101728402816341596
2. https://mastodon.social/@seldo/101728410482057550
...

This is a bug, IMO. Should I file a separate issue for that?
