### ISSUE TITLE
ActivityPub: deleting a post spams a whole lot of Undo's to followers

### ISSUE THREAD

**Issue by puckipedia** [tootsuite/mastodon#5761]
If someone deletes a post, I get a whole bunch of `Undo` messages from each user. it seems these are based on an unknown statistic:

- `mastodon.social`: 1 Undo
- `octodon.social`: 3 Undos
- `vulpine.club`: 2 Undos
- `icosahedron.website`: 17 Undos (!!!!!!)

Now I *should* dedupe these values. But! 17 Undo's is still like 16 too much. Seriously. I didn't even get the original Delete!

The post ID is `tag:mastodon.social,2017-06-09:objectId=8499030:objectType=Status`, btw
* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
Author deletes toot -> "Delete" goes out to followers + anyone who reblogged -> servers of those who reblogged forward the "Delete" to all of their followers, reblogs are deleted and "Undo->Announce" is also distributed to all of their followers

Improvements:

- Do not forward "Delete" to author of what was deleted
- Do not forward "Delete" to server that just forwarded it to us
- Skip "Undo->Announce" entirely when it's caused by original's "Delete", since removing original will implicitly remove reblogs of it
- Instead of forwarding to followers of each reblogger individually or messing with deduplication between them, maybe simply forward to *every* known (shared) inbox? (added bonus: even *more* propagation of deletes, e.g. more likely to reach servers that never reblogged or seen reblogs of toot, but instead fetched it via search, for example)

**Comment by nightpool** [comment]
this feels like intended behavior, honestly.... some implementations might
consider reblogs separate from their original post, so we can't skip the
Undo per-reblog.

**Comment by puckipedia** [comment]
You reblog an existing `Note`, so if that `Note` is `Delete`d, then you would be announcing a `Tombstone`, which contains now info. I think this was decided to be a non-issue (you aren't `Delete`ing the `Create` of the `Note` either) in the chat yesterday, see https://chat.indieweb.org/social/2017-11-20#t1511221429822000
