### ISSUE TITLE
Add UUIDs to accounts and API

### ISSUE THREAD

**Issue by SoniEx2** [tootsuite/mastodon#5826]
By adding an UUID to each account and sending that UUID together with any data from the account, it's possible to handle account deletion gracefully. If an account gets deleted, so does the UUID, so a new account with the same name gets a new UUID. So any followers get automatically unfollowed because of the UUID mismatch.

Kinda BS that "impersonating someone on the same instance" is a valid issue but "impersonating someone on another instance" is not.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Sylvhem** [comment]
> Kinda BS that "impersonating someone on the same instance" is a valid issue but "impersonating someone on another instance" is not.

It's because on OStatus and AcitivityPub, the identifier is <code>username@example.com</code> and not just <code>username</code>. <code>username@witches.town</code> isn't more an impersonation of <code>username@mastodon.social</code> than <code>username@outlook.com</code> is an impersonation of <code>username@gmail.com</code>.

**Comment by SoniEx2** [comment]
And email lets you delete and re-create accounts.
