### ISSUE TITLE
Issue template makes searching for issues difficult

### ISSUE THREAD

**Issue by SirCmpwn** [tootsuite/mastodon#5847]
I tried to search for "search" and got nowhere fast. The template is silly, it should probably just be removed. It seems like a solution looking for a problem.

Template deliberately omitted from this issue.

**Comment by nightpool** [comment]
just to be clear I understand the issue correct, the template doesn't make searching for issues hard in the general case, right? Just in the case where your search term happens to overlap with the template text?

the template isn't for users who know they can remove it. it seems silly to you because you're not the target audience. (although i'm not incredibly predisposed to it myself, so I guess I wouldn't be too sad if it disappeared)

**Comment by SirCmpwn** [comment]
>just to be clear I understand the issue correct, the template doesn't make searching for issues hard in the general case, right? Just in the case where your search term happens to overlap with the template text?

Correct

>from a broader perspective, the template isn't for users who know they can remove it. it seems silly to you because you're not the target audience. (although i'm not incredibly predisposed to it myself, so I guess I wouldn't be too sad if it disappeared)

That might make it more convenient for non-noobs submitting issues, but it still pollutes the search results when your search terms intersect with the issue template. The issue template was added pretty early, I think it was just someone ticking off a checklist of "how to make a GitHub repo" and not someone fixing an actually observed problem.

**Comment by SirCmpwn** [comment]
So, @Gargron, the resoultion here is?

**Comment by Gargron** [comment]
I think that the issue template is useful because oftentimes end-users submit bug reports about things that are already solved in master, and before the template was added people submitted a lot more duplicates than they do now (still a lot now though). It sucks if you need to search for "master" or "tagged" but usually you do not...

**Comment by SirCmpwn** [comment]
Or "search", which is what led me here. Given that Mastodon has a search feature...

How about wrapping the issue template in a comment? `<!--` works in GitHub flavored markdown.

**Comment by Gargron** [comment]
Would that actually exclude it from search?!
