### ISSUE TITLE
Implement Web Share Target

### ISSUE THREAD

**Issue by sorin-davidoi** [tootsuite/mastodon#5850]
The [Web Share Target API](https://github.com/WICG/web-share-target/blob/master/docs/explainer.md) would allow native apps (e.g. on Android) to share text (and possibly other media) with Mastodon.

Use case:
 - You find a nice quote you want to post on Mastodon
 - You select it and click "Share"
 - You select Mastodon from the share options (it will show up like a native app)
 - Mastodon opens and the text is pasted into the compose field.

This is currently supported in Chrome Canary on Android ([source](https://twitter.com/kennethrohde/status/935762149116465154)) - but you can feature detect it such that it will automatically become available to everyone as soon as the feature lands in Chrome Stable (and other browsers).

**Comment by yuntan** [comment]
I've implemented this at https://github.com/yuntan/mastodon/pull/3. I want to test it with Chrome canary on my Android phone but can't do because someone caches invalid manifest file. I can't estimate how long time to take to settle this incomprehensible behavior...

**Comment by sorin-davidoi** [comment]
@yuntan Do you have any updates? Did they fix the issue?

**Comment by yuntan** [comment]
@sorin-davidoi Sorry for inactive. I've been busy for job hunting and cannot respond to this issue until next week. Please refer https://groups.google.com/a/chromium.org/d/msg/blink-dev/_oUskZTzQxg/w4R_YnSXCQAJ about the incomprehensible behavior I experienced. Also note that I've not yet tested @rinsuki 's solution but may be good solution if you want to use `/share` endpoint instead of `/web/statuses/new`.
