### ISSUE TITLE
User inbox URLs are not updated from webfinger when they change

### ISSUE THREAD

**Issue by dlowe-net** [tootsuite/mastodon#5873]
Reproduction:
- Start new mastodon instance with HTTPS_LOCAL=false
- Create user, follow someone on mastodon.social
- Destroy db, and recreate with HTTPS_LOCAL=true
- Recreate user with same username, try to follow *anyone* on mastodon.social

What I expected to happen:
- Recreated user inbox is updated on mastodon.social account table
- Recreated user successfully follows the user on mastodon.social

What actually happens:
- mastodon.social rejects any message with an opaque 422 error 

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by dlowe-net** [comment]
Correction: mastodon.social does not actually create a new duplicate user - it just fails to update the old one.

**Comment by unarist** [comment]
Well... in that case, an ID of the account has been *changed* from `http://your.domain/users/foo` to `https://your.domain/users/foo`. It would be considered *different* account in ActivityPub, but Mastodon doesn't allow different account to use same domain/username pair, so we refuse new account.

Since admins would easily run into this problem, can we have some remedies or prevention for this issue? @cwebber @Gargron

**Comment by nightpool** [comment]
yeah this is actually about the ID issue...... hard to say what the right
call here is

**Comment by nightpool** [comment]
some relevant issues:

https://github.com/tootsuite/mastodon/issues/5593
https://github.com/tootsuite/mastodon/issues/5523

**Comment by trwnh** [comment]
Has this actually been fixed, or does it depend on the larger migration issue a la #177?
