### ISSUE TITLE
Unlisted tags

### ISSUE THREAD

**Issue by SoniEx2** [tootsuite/mastodon#5877]
Tags of the form `##name` should be "unlisted tags" - tags which show up on the post, but aren't searchable.

A post with utag `##hello` wouldn't show up in search results for `#hello`.

Automatic NSFW tag (as part of image hiding) should use the utag mechanism, that way non-NSFW hidden images don't show up in `#nsfw`, making it easier to search for actual NSFW.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Cassolotl** [comment]
A post with the privacy level "unlisted" will already not end up in hashtag searches, which is intended behaviour. So I guess you would like this for situations where you want a post with a clickable hashtag to show in the public timelines, but NOT hashtag searches?

This is a level of complexity I'm not into, myself, but others may feel differently.

**Comment by SoniEx2** [comment]
Also relevant: https://witches.town/@SoniEx2/99110477593352498

**Comment by SoniEx2** [comment]
Mostly they're just for client-side filtering tho, without polluting the global namespace.

**Comment by Cassolotl** [comment]
>Also relevant: https://witches.town/@SoniEx2/99110477593352498

You've already commented in #5463 ("Unlisted public statuses should appear in hashtag timelines") so you know that's an issue on this list, I guess!


>(Btw "automatic NSFW" being searchable is still bad. manual NSFW and automatic NSFW should be separate.)

In your toot you refer to searching for #lewds instead of #NSFW. People creating a tag that's not #NSFW makes a lot of sense because as you say, #NSFW is already being used for another purpose and sex workers generally say that NSFW is not a very helpful tag anyway, because what if you work for yourself, what if your work *is sex*, etc.


>Mostly [##hashtags are] just for client-side filtering tho, without polluting the global namespace.

So it's just for people who want to hide posts containing particular hashtags? In that case, you might want to check out #3848 and #1158.

**Comment by SoniEx2** [comment]
keyphrase being without polluting global namespace >.>

think of it like very highly advanced CWs where you can not only hide the post contents but also hide the whole post if you feel like it.

**Comment by Cassolotl** [comment]
In that situation I would use the regex filter to filter out things that contain "trypophobia" - it wouldn't have to be a hashtag for it to be filtered out. And, as you say, it would be a very effective CW, where I wouldn't even see the post at all, I would never know it even existed.

So if people wanted to find things with holes they could search for #trypophobia, and if they wanted to not see those posts they could put just "trypophobia" in their regex, no hashtag, to hide entire posts that contain that word, hashtag or no.

So it sounds like what you want is:

- A good keyword filter (already exists but could be a lot more user-friendly)
- Unlisted posts to show up in hashtag searches but not the federated timeline (feature has been requested)
- A universally understood hashtag for lewd stuff that is not #NSFW so that it's actually useful for finding lewd stuff (you already proposed one, so here's hoping it or something else is adopted widespread)

Is there another use you'd have for it that's not covered by these?

**Comment by SoniEx2** [comment]
So how do you talk about trypophobia and correct ppl on their understanding of trypophobia?

You wanna see ppl talk about trypophobia. You wanna be able to search those posts. You don't want images and things showing up, tho.

The solution is to have #trypophobia be ONLY for DISCUSSION of trypophobia, with ##trypophobia as a way to filter tryphophobia-triggering content.

One could also describe as #tags as search-tags and ##tags as trigger-tags, instead of just tags and unlisted tags.

**Comment by Cassolotl** [comment]
>So how do you talk about trypophobia and correct ppl on their understanding of trypophobia?

You could have to *not* mute posts containing "trypophobia", and trust people to hide their triggering images. At the moment you can post something *without* a CW, but still hide the media, like so:

![screen shot 2017-12-03 at 16 53 14](https://user-images.githubusercontent.com/6607512/33527536-91b3ceee-d84a-11e7-8e7b-db665a8ab7df.png)

So you could discuss the topic in a meta kind of a way, without images being visible.

**Comment by SoniEx2** [comment]
Can we just have non-searchable actual tags as opposed to post text? You can put hashtags as part of post text, or you can put hashtags as not part of post text. Why not have the same for filter tags? It would be useful.

**Comment by Cassolotl** [comment]
I think I'm just not going to understand. I don't get why someone would want to include a hashtag unless they wanted it to be findable with a hashtag search, if you take into account that we already have a regex filter that can filter things that aren't hashtags. So I will duck out, and hopefully someone else understands what you mean.

**Comment by SoniEx2** [comment]
toot that wouldn't get filtered, and would show up on search results:

"I am looking for ppl with #trypophobia for a survey <images of survey>"

toot that would get filtered, and wouldn't show up on search results:

"it's so pretty ##trypophobia <images of holes>"
