### ISSUE TITLE
Any custom.scss gives precompile errors

### ISSUE THREAD

**Issue by jeroenpraat** [tootsuite/mastodon#6038]
_Non-Docker installation, installed using the Production Guide on Debian 9._

When I modify ~/live/config/themes.yml to:

`default: styles/custom.scss`

...the assets will not precompile (see the output file below).

[output-assets-precompile.txt](https://github.com/tootsuite/mastodon/files/1563779/output-assets-precompile.txt)

To make sure it uses the modified ~/live/config/themes.yml you have to do:

`rm -r ~/live/tmp/* `

...also when restoring ~/live/config/themes.yml to `default: styles/application.scss`.

Results are that I can't customize my instance anymore.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by jeroenpraat** [comment]
FYI: I was able to put some CSS from custom.scss at the end of mastodon/components.scss. This worked like expected, no precompile errors and displayed in the web-app. So this proves that there is something wrong with the themes code.

**Comment by jeroenpraat** [comment]
For other people with the same issue:

The complete workaround is to paste all content of `custom.scss` (without `@import 'application';`) at the end of `application.scss`. Make sure config/themes.yml is set to `default: styles/application.scss`

**Comment by unarist** [comment]
Maybe...you have `app/javascript/packs/custom.js`? The file was introduced at v1.4.1 as a loader of custom.scss, but no longer needed at v1.4.2 (#3373). While its deprecation, we had special handling for that file for a long time...until v2.1.0 (#5584).

> const entryPacks = [...packPaths, ...localePackPaths]**.filter(path => path !== join(entryPath, 'custom.js'))**;

What happens if `.filter(path => path !== join(entryPath, 'custom.js'))` is removed?

Since we load `custom.scss` from two entrypoints, `custom.js` and `default` (generated from `themes.yml`), CommonChnkPlugin extracts those "common" styles to `common.css`, and Webpack omits generation of blank `default.css`.

Therefore, Mastodon will fail to find `default.css`.

**Comment by jeroenpraat** [comment]
@unarist YES, this was the problem! Now it works. Thank you!

I'm wondering why this file wasn't removed from my local repo? So it is still an issue for others. Can this be fixed for the next release?

cc @Gargron

**Comment by ashfurrow** [comment]
I just ran into this problem, too, and the suggestion from @unarist **worked**. After deleting the `custom.js` file, everything compiled fine: https://github.com/ashfurrow/mastodon/commit/1390a8af6446f545715a053a33f23ef6d5100b22

If having this (previously required) file is a failure as of 2.1.0, should we update the release notes to mention removing it?
