### ISSUE TITLE
Toots aren't getting everywhere they oughta to be

### ISSUE THREAD

**Issue by ghost** [tootsuite/mastodon#605]

**Comment by Gargron** [comment]
I think there might be disconnects happening during which the toots get missed. First of all I found that my streaming API design is not optimal (redis pubsub connection per client connection is not scalable, if 200x people are subscribed to the public channel that's the same channel for everyone but 199 extra redis connections) so that could be improved, maybe the disconnects happen because redis gets exhausted. Second solution is to do a refresh whenever streaming API reconnects, that's a good thing to do in either case

**Comment by Gargron** [comment]
UI fetches missing toots after reconnect, so this issue should be resolved
