### ISSUE TITLE
[Suggestion] Add user to list, from context menu on toots + from their profile, and populate new lists.

### ISSUE THREAD

**Issue by trwnh** [tootsuite/mastodon#6058]
Loving the new lists feature, but it's pretty hard to add people to lists right now.

Current behavior: You have to go to the Lists column, then search through people you're following, then add them to the list. Their toots don't populate the list, and the list remains empty.

Expected behavior: You should be able to add people to a list from their profiles, or from clicking the three-dot menu on one of their toots. Upon adding a person to a list, some of their recent toots should be added to the list so that it isn't empty.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by acarback** [comment]
I came here to post exactly this, haha. Well done.

**Comment by jelv** [comment]
+1 Add or remove from list on profile context menu
+1 Add recent toots to list so it isn't empty

**Comment by trwnh** [comment]
Related: #5938

**Comment by aquariusdev** [comment]
Bringing these mockups over from a post I made a few days ago about this:

Mockup 1, borrowed a bit from Diaspora:
<img width="321" alt="mastodon aspects dropdown mockup" src="https://user-images.githubusercontent.com/28520002/38939888-e2933ab8-42f6-11e8-9ae5-fd64b15d8056.png">

Mockup 2, using existing menus on Mastodon:
<img width="429" alt="mastodon add to remove from lists thru profile" src="https://user-images.githubusercontent.com/28520002/38940962-7c4d5380-42f9-11e8-93ab-ead43691a455.png">

Mockup 3, using Twitter's Add to/Remove from Lists pop-up:
<img width="543" alt="twitter multi-select" src="https://user-images.githubusercontent.com/28520002/38941533-c0510d6e-42fa-11e8-8de8-9364f880de2e.png">

**Comment by tateisu** [comment]
some client (SubwayTooter and Tootdon) already have it, but we have to follow the user before add to list.

SubwayTooter has half automated suggestion  ”follow-then-add-to-list".

**Comment by LeeteqXV** [comment]
On Mon, Apr 23, 2018, at 03:44, tateisu wrote:
> some client (SubwayTooter and Tootdon) already have it, but we have to 
> follow the user before add to list.
> 
> SubwayTooter has half automated suggestion  ”follow-then-add-to-list". 
> 

To me, that requirement to follow in order to use lists is a complete showstopper.
Considerations related to who one would like to follow using the follow functionality (and consequences) are different than what is related to wanting to include an account in a list.

I would for example use lists to evaluate people I MIGHT want to follow for a while using lists, and then if their contributions prove to be of high enough interest/quality (consistently)(and with a sensible focus without being "all over the place", topicwise), I then might start following them.

Furthermore, the whole concept of "following" needs a review. It is far from perfect.
A more intelligent Follow function would also help us tempt more people away from the bird site.

Regards,

**Comment by ldexterldesign** [comment]
Hey all,

Hope you're well

Thanks for software

Twitter lists do the job TBF so something implemented like that would be great; although with the addition of being able to order/filter/search lists

It's unbelievable I need a browser extension[n] for Twitter to order lists alphanumerically, which indicates they don't give a f#ck (excuse the language)

I often use functionality in some of these tools[l] (see "stats tag)" to do the filtering/searching

Hope this is clear/useful

Regards

[l]
http://crowdfireapp.com #followers #unfollowers
http://klear.com #stats
http://moz.com/followerwonk #stats
http://proporti.onl #stats
http://statusbrew.com #followers #unfollowers #stats
http://threadreaderapp.com
http://tweriod.com #stats > http://buffer.com #scheduler
http://twopcharts.com #followers #unfollowers #stats
http://unfollowed.me #followers #unfollowers
http://unfollowspy.com #followers #unfollowers #stats #scheduler

Tags:

followers
unfollowers

scheduler
stats

[n] https://chrome.google.com/webstore/detail/twitter-lists-redux/kcincllgjifchjihkklkcfdniofcjahb
[s] https://twitter.com/ldexterldesign > https://twitter.com/ldexterldesign/lists

**Comment by LeeteqXV** [comment]
> Twitter lists do the job TBF so something implemented like that would be 
> great; although with the addition of being able to order/filter/search 
> lists

Yes. The Twitter (read: Tweetdeck) lists features are what keeps me using that platform for everything news related.
Without a competitive feature in Mastodon, Mastodon will simply not be the solution that finally replaces Twitter for me.

And, for the record/perspective related to this:

Since Twitter has not either "seen the light" related to combining multiple identities within one account, then my current use of Twitter (Tweetdeck) for my "news consumption" (and equally important: subsequent sharing) have led to this situation:

- ~30 accounts with specific focus/purposes to enable separation and topics-based following for others (to help others limit "information overload")
- in Tweetdeck, those accunts are connected with each other in various ways (permissions-based tweet-on-behalf, vs. administer other accounts)
- each account has its own set of lists, some private (only visible to other connected/admin accounts (not followers), some public
- Tweetdeck gets slower and slower when adding 40-50 columns. Creeps to a frequent 2-minute halt every few minutes if having more than 50 columns. I have estimated that to be effective, I would want to group some 300 columns (lists + collections), and switch between such topic-related "sets" in the interface, moving back and forth between sets of open columns. Only those that belong to the currently open "set" should keep updating. No background updates should go on from columns that are not in the current active set (on-screen). I think I would work with roughly 300 such columns normally, having roughly 15-30 columns in each active "set" which then serves as "topic focus".

-- 
Regards,
Teqleez

**Comment by Angular-Angel** [comment]
I, also, would like this feature. It would make the lists much easier to use, for me. Perhaps even a drag and drop capability, if we really want to get fancy? :/

**Comment by ashkitten** [comment]
voting no for drag and drop because it's difficult to use for anyone who can't use a mouse perfectly

**Comment by trwnh** [comment]
@ashkitten drag and drop can still be an option for adding people to lists. you should be able to do this from their profiles, from their toots, or from your following page (and/or a dedicated list management section).

**Comment by raingloom** [comment]
please, no drag and drop or nested menus, just make it a "tag" list under the profile name, see my comment on a duplicate issue: https://github.com/tootsuite/mastodon/issues/7187#issuecomment-384664101

if you know how tagging works on youtube, tumblr, deviantart, etc: this is basically that, except it's list names

this would make "adding" lists unnecessary, when you add a "artist" to a profile, if the "artist" list didn't exist, it gets created automatically

> To illustrate why and just how badly the current lists UI doesn't work:
> 
> I find someone who toots interesting things about, idk, ducks. I want to add them to my `ducks` list. Currently, I have to:
> 
>     1. open the Getting Started menu
> 
>     2. click on Lists
> 
>     3. click on the `ducks` list
> 
>     4. click Show Settins (which is quite easy to miss)
> 
>     5. click Edit list
> 
>     6. search for the person
> 
>     7. add the person from the search results
>        7.1. the person has gone through 14 instances and I didn't memorize which instance they were on, the lists UI does not give me a preview of their posts
>        7.2. I have to go back and check which instance they are on
>        7.3. (repeat steps 1 through 6)
>        7.4. finally add the person
> 
> 
> **And let's not list what I'd have to do to see what lists a person is in.**
> # Alternative solution
> 
> Show what lists a person is in beneath their profile description in the app and let the user edit that as text. Same way toot tagging works. It can even have autocomplete.
> 
> This also makes creating new lists easier.
> 
> ![asd](https://user-images.githubusercontent.com/8085052/39312258-6ede7036-496f-11e8-978f-c5fb467ef9da.png)
> 
> What @aquariusdev suggested is not bad but this would make adding a person to multiple lists faster, especially if someone has many lists. (because they can just type the name from memory instead of looking through them all)

**Comment by raingloom** [comment]
The whole thing is backwards imho. It shouldn't be thought of as "creating lists and adding users to them" it should be "categorizing users by hashtags".

**Comment by ldexterldesign** [comment]
Hi @raingloom,

Providing a user can be added to>1 list then just think of lists as tags

I can't think of a use case where one would want to conflate lists and tags but I'm curious to know your idea(s)

Regards

**Comment by Angular-Angel** [comment]
Hmm. The "Adding tags to users" Idea has a lot of merit. Though I'd still appreciate an option to drag and drop profiles into said tags, if possible. :P
