### ISSUE TITLE
Magnet URIs are not clickable

### ISSUE THREAD

**Issue by SoniEx2** [tootsuite/mastodon#6248]
URIs have existed for a while. Granted, they are newer than URLs. But they don't seem to be supported in even relatively recent software such as mastodon.

This strikes me as really odd. URIs should really be supported in mastodon. I wanted to share a pic but the magnet URI wasn't clickable. This is really important when trying to avoid selling yourself to imgur and the like.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by moggers87** [comment]
@SoniEx2 could you change the title of this issue to be a bit more descriptive? Something like "Magnet URIs are not clickable"

**Comment by voronoipotato** [comment]
Yes clickable magnet-uri would be a good first step, peertube is probably not long from being released and will likely try to federate with mastodon by sharing the magnet links. We can either use webtorrent to directly download the video and images via p2p or I think more conservatively and with less effort just make the magnet link clickable. Can you please rename this issue @SoniEx2 it currently has a very ambiguous and confusing name. There are over 800 other issues.

**Comment by voronoipotato** [comment]
https://github.com/Chocobozzz/PeerTube/issues/183 here you can see they're already trying to federate with mastodon. We should probably communicate with them once they get closer to release to make sure that everything is going smoothly.

**Comment by nightpool** [comment]
We already have worked with peertube on federation. Magnet URIs are not clickable because there is very little client software that supports it. Mastodon only supports two types of clickable links, http and https. See #6072 for more information

**Comment by voronoipotato** [comment]
webtorrent uses it so there would be no need for client software. it could be done entirely clientside

**Comment by SoniEx2** [comment]
I use magnet URIs myself.

**Comment by voronoipotato** [comment]
all URIs? even ../../../resource.txt

**Comment by nightpool** [comment]
Again, two acknowledge the two completely different issues that are being talked about here:

 - Mastodon currently only turns *plaintext* IRIs in LOCAL status into links if they have a protocol of https or http. This is due to the twitter library, as discussed in the issue I linked upthread. It has nothing to do with federation, which parses links from html, not plaintext.

 - Mastodon will cache *locally* assets that use the http or https protocol. This is because Mastodon is a microblogging service, and it's ill-suited for transferring large files or videos. PeerTube federation is accomplished by showing users a link to the source of the activity (it's page on the originating peertube instance) so users can easily click through and watch the video if they're interested. This is analogous to, e.g. how YouTube and twitter crossposting works and it matches the goals of the software well while still being fully open and compatible not just with peertube, but with any activiypub compliant software.

Let's make sure to keep this two issues separate.

**Comment by SoniEx2** [comment]
@voronoipotato Uh the scheme is required https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Syntax

**Comment by voronoipotato** [comment]
Anyway this is still actually a good idea and someone should submit a pull request.
