### ISSUE TITLE
revert some parts of #6142 to not hardcode the image into HTML/Javascript

### ISSUE THREAD

**Issue by Technowix** [tootsuite/mastodon#6461]
Hi, I was using an [handy line of css to theme my instance](https://github.com/Technowix/niu.moe/commit/1eea1a07c678916c53226f319103e888811068f5#diff-5fefff9e1a7c598254d3f286f5a8cdbbR34)
but right now it's impossible since #6142 .
If this is possible, I would love if this feature can be done in a more css-friendly way !

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by akihikodaki** [comment]
> If this is possible, I would love if this feature can be done in a more css-friendly way !

It is possible, but I am not for such a change because of two reasons:
1. `img` is preferred to represent semantics for machines.

A computer can find it is an image if it is `img` element. The most common scenario it is helpful would be the right-click-to-save feature. Google Chrome does not allow to save the image if it is drawn by CSS. Mozilla Firefox would say something a bit nonsense like "save a background image"; it is not a background.

2. CSS is not a stable API and an instance owner using it for customization should be aware that it can be broken, and editing some code may be necessary to maintain his theme.

CSS is not stable, especially when it comes to each classes rather than common variables. You should be aware that your styles can be broken when updating if you are writing definitions for such classes.

Editing JSX in such a case is completely fine in my opinion. It may cause an extra conflict when merging, but you should be careful enough to pay attention to it even if you are just overriding classes with CSS. The only difference between adding a new CSS and editing JavaScript is whether it makes noise when it gets broken just like type check system. That does not change the fact that it can be unexpectedly broken in a future version.

**Comment by Technowix** [comment]
Sorry for late reply.
The thing is that it completely disable the ability to have different "themes" like natively supported since some months now o:
I ended using CSS to _hide_ the image and add another one with css :/

**Comment by akihikodaki** [comment]
Well, I do not think your instance has several themes. Please tell me if it does. In such a case, I think the path should be specified with `config/themes.yml`.
The only reason why I didn't make such a change is that I don't know an instance utilizing the feature to have a different elephant on each themes (except glitch-soc, which has a more complex modifications on the elephant.) The design may be revised if there is such an instance.
