### ISSUE TITLE
SAML attribute "full_name" should be used or become "first_name" & "last_name"

### ISSUE THREAD

**Issue by ineffyble** [tootsuite/mastodon#6535]
The SAML patch provides support for a "full_name" auth attribute by setting `SAML_ATTRIBUTES_STATEMENTS_FULL_NAME`.

However, this attribute is never used. `models/concerns/omniauthable.rb` sets `display_name` based on joining a `first_name` and `last_name` if provided.

The result of this is the display name is not able to be automatically set for users registering with SAML.

cc @moritzheiber

**Comment by ineffyble** [comment]
@gloaec I can probably make the patch for this one, which approach do you think is better?

- Change it so there's SAML_ATTRIBUTES_STATEMENTS_FIRST_NAME and LAST_NAME
- Make `omniauthable.rb` use `full_name || first_name + last_name`?

**Comment by gloaec** [comment]
@ineffyble I think most LDAPs will have a single attribute "displayName" or equivalent. But the approach doesn't have to be exclusive. You can keep `SAML_ATTRIBUTES_STATEMENTS_FULL_NAME`, add `SAML_ATTRIBUTES_STATEMENTS_FIRST_NAME` + `...LAST_NAME` and :

    display_name = full_name || [first_name, last_name].join(' ')

Also, CAS strategy already gathers `first_name` and `last_name`, so that totally makes sense.
