### ISSUE TITLE
A post with media and a Content Warning shouldn't add the og:image

### ISSUE THREAD

**Issue by treyssatvincent** [tootsuite/mastodon#6712]
Step to reproduce :
1) Someone post a media with a content warning
2) Someone link this toot on a site who display the open graph image (on Mastodon for example).
3) The og:image is displayed.

(Example : https://social.treyssatvincent.fr/@nino/99653223552329791 NSFW :warning:)

To avoid such disturbance on every sites, not only mastodon's instances, I think we should remove the og:image on post with CW.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
I have deliberately chosen this to not unfairly disadvantage adult content creators.

1. Other platforms have much lower expectations of warnings
2. When sharing with someone, you know your audience.
3. By hiding or obscuring the actual content in the previews, the people you share it with are less likely to open it to look at it - because other platforms don't have content warnings, it's absolutely not obvious that the reason the post doesn't look like it should is because of some warning.

See also: #6479

**Comment by deli73** [comment]
There has to be a better way to deal with this that doesn't have the potential for harm of just _unconditionally showing the entire content in the preview_.
For once i do actually see your reasoning here, Garg, but i don't think this is an okay way to handle it.
