### ISSUE TITLE
Make adding image descriptions more comfortable

### ISSUE THREAD

**Issue by averageunicorn** [tootsuite/mastodon#6713]
There are two things that I've been thinking about:

– Make the option more visible. I've heard from a few people that they didn't realise they could add a caption until someone told them, because they never hovered over their images.

– Make it more comfortable to write a description that is longer than the input field width. When I, for example, post a picture of a poster that has some text on it, I tend to switch back and forth between my browser, and a different window where I look at the picture to copy the text. But each time I switch back, only the beginning of the image description is visble and I have to use the arrow key to get back to the end.

It would be cool to either have it remember the position (the way it /sometimes/ does when you're only switching tabs or smth, couldn't quite figure it out) or make the field get bigger, so the whole text is visible (that would be really nice when doing corrections as well, it really helps to see the whole thing), and make it stay big when you switch around, too.

**Comment by noiob** [comment]
Small addition I'd like to make: Allow the Ctrl+Enter shortcut while typing a description, since that's usually the last thing I do before sending the toot and it's annoying that it doesn't work. If the description interface ends up being a popover similar to how Twitter handles it, disregard this.

**Comment by penduin** [comment]
at least on mobile, the description field is hidden by default, but should absolutely be shown, i'd say even focused upon inserting an image.

there are several user-facing options to confirm when boosting etc, i'd love to see one to confirm posting with alt-less embedded media.

**Comment by Fidgetcetera** [comment]
@noiob There's an issue over at #5892 for the ctrl+enter stuff, though I do agree that if the image description field gets overhauled it'd probably not be necessary, maybe just ctrl+enter closing the overlay or something.

**Comment by trwnh** [comment]
ref: https://icosahedron.website/@Xkeeper/100086156746540486

concerns expressed:
- "after i write a caption the entire post editing area stops responding and the caption vanishes for several seconds"
- "also the new crop / etc options introduce even /more/ tabstops so if you're primarily a keyboard user you can just go fuck off i guess"
- "the "undo" and "crop" options on an image are invisible unless you hover over them, but still accessible via tabbing
  - "(??? why is it "undo" on an inserted image instead of "remove"?????)"
  - "to edit a caption, you […] have to [select the compose box then press tab 4 times, with no visual feedback that you're selecting "undo" or "crop" before getting to the caption]"
    - [also perhaps caption should be prioritized above removing or cropping the image?]
    - "if you edit it you get dumped back into the textbox”
  - "if you want to adjust the privacy options, have fun adding even *more* tabs to that list. and to cw, you have to also go BACK as many tabs plus one to get to the cw editor"
