### ISSUE TITLE
Mastodon Resource Usage

### ISSUE THREAD

**Issue by alfiepates** [tootsuite/mastodon#672]
I'm planning to deploy an instance Mastodon on a small server of my own, but I've heard mixed things about the resources required for Mastodon. 

For a 10-20 user instance, what are the expected/recommended resource allocations? I'm trying to get away with running it on a cheap VPS of some kind, so, around 512MB memory for the entire box.

**Comment by Gargron** [comment]
You need to have some swap because bundler, yarn (installation of dependencies) and the compilation of front-end assets takes a lot of RAM. However 512MB is enough of runtime memory. Please mind that the default settings are tuned higher than this (see tuning Mastodon documentation for details). 10-20 users is almost nothing in terms of load

**Comment by alfiepates** [comment]
Yup, that's what I was afraid of. I will experiment with using a second virtualised build environment which is functionally identical to the server in terms of OS, libraries available, et cetera.

**Comment by exadeci** [comment]
Any new infos on the subject? 
It would be interesting to know so we can limit the number of users on a instance based on the average resources usages per user.
