### ISSUE TITLE
Closed registration message is tiny when it doesn't have to be

### ISSUE THREAD

**Issue by noiob** [tootsuite/mastodon#6760]
The login column is really tall with the new start page, so I don't see why the message about closed registrations has to be 12px. It's kind of a thing that people should read and it was normal-sized on the old start page.

I turned off the CSS rules for font size and line height on closed-registration-message and it looks a lot better? I can probably figure out where those are and make a PR but I wanted to make an issue first because it seems like it was specifically set to that size.

See my screenshots:

12px, 18px line height (now):
![grafik](https://user-images.githubusercontent.com/8197071/37300883-67dd048e-2627-11e8-8903-0b7d7174008b.png)
16px, 30px line height (how I'd like it to be):
![grafik](https://user-images.githubusercontent.com/8197071/37300920-7d77f47a-2627-11e8-842d-bd6928d91dc8.png)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by nightpool** [comment]
the smaller text size gives visual heiarchy to the overall style of the
block. with the larger text size, the eye is confused about where to look
first, and has a hard time processing the much longer text all at once.
with the smaller text size, the eye processes the button first and
foremost, and then moves on to the explanation.

IMO, your closed registration message is pretty old and it can be tightened
up—now that the button links to join mastodon.org, there's no need for
redundant instances.social links. And there's definitely no need to link to
instances.social and instances.mastodon.xyz, since those are the same
website haha.

**Comment by noiob** [comment]
I know, I removed the link to instances.mastodon.xyz. But a shorter message would look even weirder in the small font? And I didn't make this issue to talk about our message, it's just an example. The button is big, orange (default blue, but still pretty visible), I don't think it has a visual hierarchy problem against anything. It just looks like some legal disclaimer one can skip rather than the reason why the sign up button isn't there.

**Comment by nightpool** [comment]
ultimately, it's a personal style judgement. I think there are arguments
both ways, but the general rule of thumb is less text = more clicking.

**Comment by noiob** [comment]
fair, I guess I'll think about patching it locally

**Comment by Gargron** [comment]
The style is consistent with the "I agree to the rules and terms of service" text when registrations are open.
