### ISSUE TITLE
Allow special characters in usernames

### ISSUE THREAD

**Issue by tigre-bleu** [tootsuite/mastodon#6830]
Currently, the username can only be letters, numbers and underscores.

The users in my LDAP directory have uids like "firstname.lastname" with their mail "firstname.lastname@example.com".

With the current implementation, mastodon does not create a profile for the users as there is a "dot" in the username.

I think that my situation can be quite common, especially with LDAP integration as sysadmins will not want to create a new ID just for mastodon.

Why doesn't mastodon support extended usernames? Am I missing some obvious reason?

As another solution, it should be possible to authenticate to mastodon with the email adress from the LDAP directory. With the current solution (setting LDAP_UID=mail), the user creation fails with the error regarding the "letters/numbers only".

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
>Why doesn't mastodon support extended usernames? Am I missing some obvious reason?

The regex for detecting mentions is widespread between different systems and it does not expect a dot in the first part of the username. So this really cannot be changed.

I suggest maybe stripping out the dot, so it becomes firstnamelastname, or firstname_lastname

**Comment by tigre-bleu** [comment]
I understand the difficulty but it is quite annoying if mastodon is the only service that have a specific username.

For regular accounts, it is possible to login via email. In this case I see no limitation on the email adress. What about the following workflow for LDAP connection:
- Admin configures LDAP_UID=mail
- User connects the first time with his email adress
- Mastodon searches LDAP for the user based on the email and authenticates
- Mastodon asks the user for a username
- Mastodon creates the user in the instance with this username and associates the email adress
- In the future, the user connects with his email address

**Comment by tigre-bleu** [comment]
As far as I understand, this issue is not really fix so it should not be closed.

@Gargron, What do you think of the workflow above?

**Comment by SaadAK96** [comment]
this definitely needs to be fixed!

**Comment by ettmetal** [comment]
Is there any chance of opening this back up for discussion?

I found this issue after trying to set up a username that used a character I don't think of as particularly 'special': à.

An inclusive web needs better representation than 'only Latin script without diacritics'. We should be past the days of technological limitations preventing use of characters outside of an anglo-centric set of letters.

**Comment by beedell-roke** [comment]
@ettmetal, indeed. For not the entirety of UTF-8 to be supported by default is nonsensical, when surely all that is necessary is sanitization by quotation of the username string when it stored and processed.

**Comment by jaacko-torus** [comment]
Should a new issue with this name flagged as "suggestion" be created? BEcause I agree with @ettmetal and @rokejulianlockhart.

This is supposed to be the federated social network, if this was Twitter (or X now lol) I would be told that the company resides in the USA, so English characters is good enough, and if I don't like it I can go away. This is Mastodon though.

Is there a technical reason for closing this? If mountains have to be moved, it might not be worth it. I'm not a collaborator, but I ask that this be open so that it can get more exposure and get worked on eventually. I think UTF8 usernames would be incredible for a lot of people outside of English speaking countries (That's a lot of them).

**Comment by rokejulianlockhart** [comment]
> Unicode contains many invisible and other tricky characters that would make phishing easier (We are already seeing the consequences of .zip domains, so you can imagine how this could be a problem). If you want your username to contain "special" characters such as "à", you can add those in your display name.

@jaacko-torus, surely the solution then is to use a blacklist rather than a whitelist (by default)? Or, if an instance's administrators are seriously concerned about security, allow them to switch the rules to a whitelist instead.

**Comment by ettmetal** [comment]
@jaacko-torus, I think you referenced the wrong issue? The one you linked is about the UX of the follow button on a profile that has been migrated. If that's the right issue, I'll need to more context on how you believe that's demonstrating the issues you're talking about, if you can 😅

---

A user handle **is** a user's identity on a service. It's not about having characters in a username, it's about being able to genuinely represent _identity_.

In most definitions, 'à' is not even a special character. Special characters are usually defined as something along the lines of 'non alphanumeric characters' or 'letters and numbers'. 'À' is a letter.

I understand the security issues inherent in having all of Unicode available. I suppose that you referencing the `.zip` issues is the strong phishing attacks that it can be used for (Here's an article explaining it for anyone interested: https://medium.com/@bobbyrsec/the-dangers-of-googles-zip-tld-5e1e675e59a5)

Crucially, the character which makes that phishing tactic so strong, "∕" (U+2215), is **not** an alphanumeric character. It is indeed a special character. It's not commonly used to form words, and isn't commonly used as a way to define a person's identity. There are literal names that use the character 'à'.

I agree with @rokejulianlockhart: settling on "it's good enough" because you can meet your needs for expressing your identity within the limits seems dismissive. When we talk about what is "good enough", I think it's always important to consider "for whom". Is the character set being limited to the set of Latin characters used in English and some other languages good enough for all users?

**Comment by jaacko-torus** [comment]
- @ettmetal Whoops, I meant to reference https://github.com/misskey-dev/misskey/issues/8503
  - I just assumed that it was a Mastodon issue.
- As for the id, I have the same perspective
  - The issue being fixed would be good :+1:
  - A blacklist would be preferable to a whitelist
  - It would be more culturally inclusive (And at least **I** want Mastodon to be the nice and friendly alternative)
  - I'm against this issue being closed, I have no idea why it was decided to be completed

But: I do not have any security background, and it's quite the serious and heavy topic. As such, I believe non developers can be satisfied. The reason is simple, the `id` is this internal thing, users don't see the `id` except when they copy-paste. My `id` can be literally anything, a UUID if I'd like, it really doesn't matter, it is meant to be copy-pasted. If you are looking for someone in the search bar, you have two options: (1) copy-paste their id, (2) copy-paste their display name. The display name can have any character, so, imo inclusive enough.

Why are dots `.` prioritized over Greek and Arabic? No clue. But I will not argue about things that are already done, and that's my message to non-devs.

---

We can talk about it, or we can fix it. Let's go. The regex for user names is the following:

```ruby
USERNAME_RE = /[a-z0-9_]+([a-z0-9_\.]+[a-z0-9_]+)?/i
```

It can be found in [this file](https://github.com/mastodon/mastodon/blob/3d65dbc48e0e11a304dc5e9f5e8578ed98055e49/app/models/account.rb#L50), which was modified by @Gargron when the issue was closed.

Once more, I am no security expert, and as such, any recommendations as to what the actual characters that we are blacklisting are, should be thoroughly inspected by you guys.

---

Let's define scope. I believe all "word" characters should be included, that is, everything that can be rendered by, say Noto Sans, minus symbols and characters that can be used for phishing.

Looking through the [character classes](https://www.compart.com/en/unicode/category), I would say that includes: Ll, Lm, Lo, Lt, Lu, Mn, Nd, Nl, No, Pc, Pd, and Sk.

Does that sound good?

**Comment by jaacko-torus** [comment]
Ah, almost forgot, the database that collects this information would also need to be modified, since most databases don't allow willy nilly UTF characters in strings without some more custom setup (This is another one of those, idk why, but it's that way problems). [Here's a Stack Overflow QA that goes over the issue](https://stackoverflow.com/questions/28935228/novice-postgresql-using-unicode-symbols-in-a-table).

**Comment by julian-a-avar-c** [comment]
Welp, I suppose I can document my work here publicly, and hopefully someone will come fix and commit it. I'm not a Ruby dev, but here's a skeleton.

[Source](https://ruby-doc.org/core-3.0.1/Regexp.html#:~:text=A%20Unicode%20character%E2%80%99s%20General%20Category)

```ruby
USERNAME_BLACKLIST_RE = /[^∕]/i # The mentioned character
# I think that we only need [_\-] from the punctuation classes (Pc, Pd)
USERNAME_WHITELIST_RE = /[a-z0-9_\p{Ll}\p{Lm}\p{Lo}\p{Lt}\p{Lu}\p{Mn}\p{Nd}\p{Nl}\p{No}_\-\p{Sk}]/i
USERNAME_INTERSECTION_RE = /[&&#{USERNAME_WHITELIST_RE}&&#{USERNAME_WHITELIST_RE}]/i


USERNAME_BEG_RE = /#{USERNAME_INTERSECTION_RE}+/i
USERNAME_MID_RE = /[\.&&#{USERNAME_INTERSECTION_RE}]+/i
USERNAME_END_RE = /#{USERNAME_INTERSECTION_RE}+/i
USERNAME_RE = /#{USERNAME_BEG_RE}(#{USERNAME_MID_RE}#{USERNAME_END_RE})?/i
```

I'm going for legibility. Or should it be an uber-regex? I'm not familiar with Ruby's regex machine. I'll be looking at problematic characters + how to match accented latin characters during this week.

**Comment by ettmetal** [comment]
> First of all, I would like us to define "special characters" as anything that is NOT in the regex please, otherwise, give me an alternative, I don't want to say "anything that is NOT in the regex" every time.

Do you mean in the context of this discussion, usernames, something else?

> Does that sound good?

I'm really not sure what you're proposing tbh, as your statements seem contradictory 😅

> - the issue being fixed would be good
> - I have the same perspective (as was written in my original post)
> - - "to me the current solution is good enough, so I won't argue. This is good enough."

In addition

> We can talk about it, or we can fix it. Let's go.

We can do both? I genuinley don't know how we'd be able to work towards something without actually understanding what each other mean 😅

**Comment by julian-a-avar-c** [comment]
@ettmetal 

> Do you mean in the context of this discussion, usernames, something else?

In the context of the discussion. It's related to your own comment:

> I found this issue after trying to set up a username that used a character I don't think of as particularly 'special': à.

I'm tired of that discussion. I want to move on to implementation.

---

I just looked through the [Ll](https://www.compart.com/en/unicode/category/Ll) class. But I would think this also applies to [Lu](https://www.compart.com/en/unicode/category/Lu)

Should we blacklist the mathematical letters? That would be:

- `[\u{1D41A}-\u{1D433}]` - Mathematical Bold Small A-Z
- `[\u{1D4EE}-\u{1D467}]` - Mathematical Italic Small A-Z
- `[\u{1D482}-\u{1D49B}]` - Mathematical Bold Italic Small A-Z
- ... - there's a lot more

---

What about all the stylized characters? What would be any character classes that are specifically: Bold, Italic, Script, Fraktur, Sans-Serif, or Serif.

---

Then there is latin alpha (ɑ) and greek alpha (α). Which can be easily confused. Should we include both? Should users be notified about one versus another like VSCode does, highlighting characters that look like _common_ characters?

---

Looking back I think we should get rid of the [Lm](https://www.compart.com/en/unicode/category/Lm) and [Lt](https://www.compart.com/en/unicode/category/Lt) classes. And [Lo](https://www.compart.com/en/unicode/category/Lo) class should be reviewed by people who are fluent in those languages.
