### ISSUE TITLE
[BUG] Cannot dismiss "drag to upload" dialog

### ISSUE THREAD

**Issue by yiskah** [tootsuite/mastodon#687]
If you accidentally drag anything (including a link) while your mouse is over a mastodon window, it will bring up the "drag and drop to upload" dialog. If it is not a valid file to upload (for instance, if i click a button and drag) or if after moving the object over the window you then do not drop the object, the dialog stays open and you are unable to interact with the page or dismiss the dialog unless you refresh the page or find a photo on your computer and drag it onto the window so it has something to upload

**Comment by nclm** [comment]
Yes, this is quite annoying. I came here to open the same bug.

To illustrate the issue, two examples of cases when it happens: when dragging some text from Mastodon to look it up (which happens to me all the time), and when dragging a unrelated file purposelessly over Mastodon.

![ezgif-3-40fe195c53](https://cloud.githubusercontent.com/assets/923008/25064150/aee2f2e0-21f4-11e7-82e6-4406b5cbb34f.gif)

![ezgif-3-9296d2b824](https://cloud.githubusercontent.com/assets/923008/25064170/ee96d33e-21f4-11e7-89bf-b32d4de1d81a.gif)

**Comment by Technowix** [comment]
This issue is still here on v1.2

**Comment by fwenzel** [comment]
The easiest way to fix this is probably hooking up a keypress handler for Esc on the upload dialog. That won't auto-dismiss, but at least you can do something that's *not* reloading.

**Comment by stephenburgess8** [comment]
@yiskah @nclm Dragging text should no longer trigger the upload modal. Even when dragging files, this should be triggered (less) often. I'm still able to reproduce this behavior in Firefox when dragging from the window into the URL area, because for some reason neither dragEnd nor dragLeave is triggered. ¯\_(ツ)_/¯ Since I wasn't able to completely get rid of it, I added the escape listener. I confirmed this works in Chrome, Safari, and Firefox. Let me know if there's any further changes you think would help.
