### ISSUE TITLE
Add a meta tag for language and let everyone enjoy the public timelines

### ISSUE THREAD

**Issue by Lomplac** [tootsuite/mastodon#691]
Recently many french speakers came on mastodon.social 
Then the public timelines became multilingual, which [is a problem](https://mastodon.social/@pinesky/1340029) for most people who only want to read understandable toots

A way to fix that problem would be to prohibit other languages than english on the public timelines, but i don't think it's fair for non-english speakers who also want to meet other people and enjoy those timelines
What i suggest is to **add a new meta tag** which specify the language of every toot, and the possibility of **filtering the public timelines**
![Screenshot of the filtered timeline](https://cloud.githubusercontent.com/assets/26697634/25049826/0b29ea10-2144-11e7-9f82-c8f61a4d2e0d.png)

We could determine which language a toot contains automatically ([with a bot or something](https://github.com/tootsuite/mastodon/issues/691#issuecomment-291613355)), or just **let the users choose in the settings in which language they toot**
For multilingual users a button as below would be great
![toot box with language button](https://cloud.githubusercontent.com/assets/26697634/25049677/51bc4410-2143-11e7-8b71-36c3b0139c1b.png)

### April 14th, update that includes some suggestions:
- [ISO 639-3 acronyms](https://github.com/tootsuite/mastodon/issues/691#issuecomment-293363844)
- [Language option in the toot box](https://github.com/tootsuite/mastodon/issues/691#issuecomment-291835725)
- [Option in settings to pick the default languages there will be in the toot box](https://github.com/tootsuite/mastodon/issues/691#issuecomment-291835725)
- [Option in the settings that will indicate the languages of every toot](https://github.com/tootsuite/mastodon/issues/691#issuecomment-294130237)
- New notification-like filter but for langages
- Temporary and permanent language filters
- Filter that allow to show only specific languages
- [Shortcut to mute the language of a toot](https://github.com/tootsuite/mastodon/issues/691#issuecomment-294130237)
- [No filter by default](https://github.com/tootsuite/mastodon/issues/691#issuecomment-294130237)
- [Toots without text won’t be filtred](https://github.com/tootsuite/mastodon/issues/691#issuecomment-294128842)

![many flags](https://cloud.githubusercontent.com/assets/26697634/25049878/4350e948-2144-11e7-9ed7-ee4187300a5d.png)
![only a picture, can't be filtered](https://cloud.githubusercontent.com/assets/26697634/25049865/340d1b8c-2144-11e7-952a-8c6b9e2d7b38.png)
![muting shortcut](https://cloud.githubusercontent.com/assets/26697634/25049871/36980cea-2144-11e7-943c-6a809580cdfe.png)
![new options in settings](https://cloud.githubusercontent.com/assets/26697634/25049933/85614a1c-2144-11e7-9aab-67bb646713aa.png)

**Comment by kennethlarsen** [comment]
This would be amazing and I think the key here is automatic language detection since most people would forget or be to lazy to assign it manually. This would be possible with libraries like: 

https://github.com/wooorm/franc
or
https://github.com/peterc/whatlanguage

**Comment by zuglufttier** [comment]
Please, no automatic detection! The browser will send a default language and 95% of people will be happy with that.
I, and I'm surely not the only one, write in two languages and want to keep this ability, just add the option to change the default language which could be set by the browser.

**Comment by kennethlarsen** [comment]
I agree that using the default browser language will not work. This might be the way to do it:

- Add an option to manually assign language in the toot box
- Add option in settings to pick default language in the toot box
- Sort streams by language

This can then later be refactored into automatic detection by using one of libraries mentioned before. This does not mean detecting the default browser language but instead analyzing the toot before it's being sent and then setting the language meta tag based on the specific toot. This way you can write toots in all the languages you want to and still have automatic detection.

**Comment by ThomasLeister** [comment]
Totally agree with @kennethlarsen. That might be the best compromise between convenience and flexibility.

**Comment by Ravenbird** [comment]
i also prefer that the user can choose the language of the post. But we need a solution for this problem.

**Comment by nclm** [comment]
All of this is a very good idea.

An easy way to this for the user without adding specific filters would be to build a new setting in the options panel: “Languages I understand”. The user sets there the languages they can read and/or write.

The write box would only list languages from these, and if set, the timelines would be filtered to display only toots in these (without segregating them), with an option to “Display all languages” in the columns filters.

If not set, the write box would default to the browser’s language (with a visible invitation to set the option), and the timelines would not be filtered at all.

**Comment by KonomiKitten** [comment]
I would really like to see this idea happen at the moment I just mute people who I can't read the languages of which is rather tedious, having the ability to select which languages I can understand in my profile and see only those would be beneficial for everyone.

**Comment by jeanbaptisteb** [comment]
If this feature is implemented (which would be great), it may be relevant to use the ISO 639-3 code list (https://en.wikipedia.org/wiki/ISO_639-3). 

This standard includes the possibility to tag a language as "undetermined", or to tag the content as not including text. Think for example about people just tooting a photograph (or a more complicated case: someone tooting just a link to a video with subtitles in multiple languages).
 
ISO 639-3 also includes codes for some artificial, rare, or ancient languages. Contrary to ISO 639-1 (for example), this standard tries to be as comprehensive as possible; it would be more inclusive to use it.

Besides the question of the standard to choose, another thing is to do is to separate the notions of "languages I'm able to understand" and "languages I'm able to express myself in". Some people are able to understand a language, but are not able to express themselves in it.

There is also the cases of multilingual toots. We should be able to choose more than one language when tagging manually a specific toot.

**Comment by jeanbaptisteb** [comment]
Another thing is that we should beware of a too exclusive filter system. 

For example, toots without language (e.g. just a photograph, to take this example again) shouldn't be excluded from users' timeline, even these users chose to see toots only in Japanese or Spanish (for example). 
Otherwise, toots without a defined language won't be seen by other users, except those who chose to see all languages.

**Comment by Toub** [comment]
What about:
- don't exclude anything by default
- when a message is tagged (automatically or manually), show the language flag: EN, FR, ...
- when the user right clicks on the language flag, show an option in the menu: "Filter messages in this language"

Because you may want to filter messages if you receive too many of them (e.g. in French or English), but you will probably be happy (or don't mind) to receive other languages if it is just one message a week.

**Comment by Cassolotl** [comment]
I was asked to pass on [a message here](https://mastodon.social/users/Jessiscah/updates/1877083):

> IDEA:
> a per account/per instance language(s) tag that can be used to filter visible toots.
> 
> I really, really would like the federated timeline to be useable again.

**Comment by pnathan** [comment]
This is going to be a problem as Mastodon increasingly goes global.

While I respect other users of Mastodon in Japan, Brazil, India, China, France, etc - and I wish them the best! - I can only read English and German. I can only scroll past toots which I can't read. I would like a way to, with the most polite respect, not see the toots I can't read when I am generally scrolling by.

It seems that a box where a user can set "my default toot reading/writing language is", and otherwise the user can override in their toot (perhaps under an advanced options dialog) if they want to read or write a toot outside of the defaults.

**Comment by NthTensor** [comment]
I think the simplest solution is to ask new users to select the tags when creating accounts, and use @Toub's suggestion for existing users. Essentially leaving the language filter blank to grandfather people in.

**Comment by jeanbaptisteb** [comment]
Too many features and options could make the interface more complicated, when the purpose of filtering by language is originally to make Mastodon more user-friendly. 

For this reason, I think **we should remove the "only show specific languages" option**:
 
![language options](https://cloud.githubusercontent.com/assets/26697634/25049826/0b29ea10-2144-11e7-9f82-c8f61a4d2e0d.png)

This option is a good idea, but it makes the preferences' interface a bit more complex. And the @Toub 's [solution (basically a blacklist system)](https://github.com/tootsuite/mastodon/issues/691#issuecomment-294130237) already solves the original problem of seeing too much toots we don't understand. 

A language blacklist system is more inclusive and already takes into account complicated cases (images, links to multilingual content). Plus, a white list system has some problems (i.e. excluding content I could actually understand). Moreover, I fear that the coexistence of a whitelist and a blacklist systems would make the interface more complicated for users who are not tech-savvy. 

So my preference would go to the implementation of a blacklist system exclusively.

Any thoughts?

**About the "mute temporarily" feature** (@Lomplac), I think it could be simplified, by using just a "mute" button, instead of "mute 1 hour", "mute 1 day", and "mute definitily". It's definitely an interesting option and I'd probably use it when I'm too tired to read foreign languages (even those I understand ;) ). But I don't know how many users would use "mute 1 day" or "mute 1 hour". Should these options be available if we want to keep the interface simple? I suspect that just a simple "mute" button would be enough for most users -- but of course I may be mistaken. 

**About the ISO-3 languages**, Wikipedia provides tranlations of their names in 6 languages: https://en.wikipedia.org/wiki/ISO_639%3aa . We could use it to make the interface more user-friendly. For example, in my case (I'm French), "Japonais" would be displayed instead of "Japanese" here : ![screenshot](https://cloud.githubusercontent.com/assets/26697634/25049871/36980cea-2144-11e7-943c-6a809580cdfe.png)

When the translation of the language name isn't available in the user's language, then we could display its name in English.

**Comment by sramkrishna** [comment]
The other issue is scrolling.  On mastodon.cloud, the federated and even the local timelines are scrolling by so fast that I can't even read it.  There are usually 'peak times' for various countries and denizens of those countries will be more chatty than others.  Filtering will help at least in languages for those who cannot participate in languages we don't know.  Unless of course, there is some on-the-fly translator.

**Comment by Lomplac** [comment]
@jeanbaptisteb
Only showing the "Muted languages" option and having a "Show more options" button below would be a great way to let the users have a user-friendly and complete interface that focus on inclusivity
Also it seems obvious that it's either the blacklist or the whitelist, the "muted languages" options would be disabled when one use the "only show specific languages" option

Showing the full name of languages on every toot would be unpleasant to read imo, if you want to know the language name, you just have to click on it ("Mettre le _japonais_ en sourdine")

**Comment by lanodan** [comment]
Actually I think the thing should be flexible enough to allow both whitelist-style (I want only english and no-lang) or backlist-style (I don’t want to see german).
Also tagging by the browser just won’t work, manual tagging might work if there is a choice-list(text-form might be nice too for like non-recognised languages/dialects) based on previous use and automatic tagging done client-side might be a good idea (users are lazy?).

**Comment by ernix** [comment]
I think we only need a regex option for Local/Federated Timeline.
Filtering is a matter with viewers, we shouldn't make users to choose what language they are using.
Tagging language is not work for trolling and ads.

Regex filter is already implemented in Home.
Use `[^ -~]` to keep your timeline ascii.
Use `.{200}` to filter out long toots.

Simple, isn't it?

**Comment by jeanbaptisteb** [comment]
@Lomplac : Agreed. 

About the way of showing the whitelist and blacklist in the interface, what about a list of languages that you can check and uncheck, with options "select all" and "deselect all"? 

The list of languages may be long, but we could show 10 main languages by default (for example), with an "expand" option for people who need to see more languages in the list.

"Showing the full name of languages on every toot would be unpleasant to read imo": agreed too.

**Comment by ernix** [comment]
@jeanbaptisteb Yes, filtering by regex is another topic.

But when combining multiple filtering rules, the situation will be undesirable.
I wouldn't to be mad with filtering order and conditional filtering rules.

BTW, you can also allow diacritical marks in regex: `[^ -~À-ÿ]`

**Comment by Cassolotl** [comment]
I'm a normal user with non-technical knowledge, and I'm fine with regex being used as long as it's not the *only* way. I want to be able to see only French and English posts, but I know nothing about regex. Regex only would not be accessible for me.

**Comment by jeanbaptisteb** [comment]
@ernix  : @Cassolotl is right, it's not accessible for non-tech users. And anyway there are a lot of cases where you cannot filter languages with only regular expressions. 

For example, if I toot the phrase "Il fait beau ce matin", an English speaker who uses regexp to filter non-ascii character will see my toot, even if it's not in English.

**Comment by ernix** [comment]
@Cassolotl @jeanbaptisteb 

Have you ever set `Content-Language` or `Accept-Language` headers on your emails?
https://tools.ietf.org/html/rfc3282

I've never ever seen them before.  Language tagging is totally useless.
Plus, everyone can setup dedicated instances for specific languages.

**Comment by Cassolotl** [comment]
As things stand, I'm sad that I can't change the language per-toot, because sometimes I post in French (very rarely, but I do!) and I know other people who post even half-English half-German or something. So I'm not sure how this is going to go down, but I'm a little worried.

@ernix I'm not really sure what you're talking about, so I can't take your point! Could you clarify?

**Comment by jeanbaptisteb** [comment]
@ernix 

We can make language tagging user-friendly: for example defining a language by default, then being able to change language of each toot manually for users who want to do so. Or even tagging languages automatically (I think it's already the case BTW). 

I think it would be a terrible idea to force users to tag their toots, if it's what you're afraid of.

But language tagging isn't useless for the large number of users who complained about being unable to filter by language.

**Comment by ernix** [comment]
@Cassolotl 
If you want to toot with language tags, you can just put language hash-tags like `#ja #en #de #fr`.
If you want me to toot with language tags, I'm sorry but I wouldn't.

@jeanbaptisteb 
That's not friendly at all.  I would rather prefer to add all language tags on every single toot so that I can avoid selecting tags each time.  I don't want my toots to be tagged automatically.

As you said, there is no deterministic method to define what language the sentence is.
e.g. I'm a Japanese/Chinese speaker, "手紙" is a word that has two different meanings for each languages.

I need to keep my expression as is.  You can judge it by yourself, but nobody can label it on specific language.

I hope this makes sense to you.

**Comment by jeanbaptisteb** [comment]
@ernix ix "That's not friendly at all. I would rather prefer to add all language tags on every single toot so that I can avoid selecting tags each time. ". You could tag your toots as "language undetermined" by default, or not choose any language by default. But it doesn't mean that we have to forbid other users from tagging their toots if they want to.

**Comment by Cassolotl** [comment]
@jeanbaptisteb @ernix Yes!

My ideal is an option in settings to set a default language, and you can leave it Unspecified.

And then in the "new post" interface, a language dropdown box, which is set to your default choice (for me English, but for ernix perhaps it would be Unspecified) - and if I write a post in French, I can use the dropdown to change it to French.

And then, in the various feeds and timelines, I would like to be able to filter to show only posts set to English, French, and Unspecified. But the default would be "view all posts in any language."

So everything is optional and Unspecified by default, and people can use hashtags like #fr if they want to. But there are user-friendly tools available that reduce work for people who want to be more specific.

**Comment by ernix** [comment]
@jeanbaptisteb 

> You could tag your toots as "language undetermined" by default

Yes, I can.  But why I have to do so?
I don't think it's effective to filter timelines when anybody can pick multiple languages.
There is no incentives for me to make my toots to be censorable by others.

> Who knows that the language code for Irish is "ga"?

I do believe people who talk Irish language know the name, GAeilg.
Otherwise they can't select their own language from the Language list in Wikipedia.
https://en.wikipedia.org/wiki/Irish_language


@Cassolotl 

> And then in the "new post" interface, a language dropdown box, which is set to your default choice (for me English, but for ernix perhaps it would be Unspecified) - and if I write a post in French, I can use the dropdown to change it to French.

Yeah, It is completely OK that some client applications have features to append language hash-tags from drop-down UI.  I don't care if these clients hide language hash-tags on the toots.

But I oppose system-wide language meta tag as @Lomplac said.

I don't want to see someone toot `六四事件`(Six-Four incident) with `zh`(Chinese-Simplified) tag.

I also wonder why nobody commented with language tag on this thread.
You are talking "How language meta tags is useful" without language tags.

**Comment by jeanbaptisteb** [comment]
@ernix  
"Yes, I can. But why I have to do so?". You wouldn't have to make any action. You could choose to not tag your toots. Then, the system would consider that no language has been defined for your toots.

You're talking about using hashtags like #fr, #ga, etc. If I understand well you're position, you're saying that users should be able to manually tag their toots, but that we shouldn't make it easy for them by implementing natively a way of doing it in the interface (with a button, for example). I don't understand what is the argument in favor of this position.

**Comment by ernix** [comment]
> we shouldn't make it easy for them by implementing natively a way of doing it in the interface (with a button, for example).
Ah, this makes sense to me now.  So you said user-friendly is about user accessibility on your browser, right?
You prefer to click/tap a tagging button rather than to type 3-4 keys.

I was thinking why dividing people into fixed language sets could be user-friendly.  That's my mistake.

**Comment by lanodan** [comment]
[ @ernix ]
> Have you ever set ``Content-Language`` or ``Accept-Language`` headers on your emails?
> https://tools.ietf.org/html/rfc3282

Yes, I also receive many emails containing it. (probably because people are often using/setting languages pack/spelling)

Also for the issue of Japanese/Chinese : that was my point earlier, autocompletion of the language tag/header/… (people are lazy), but the user can set something else if it’s wrong/undetected.

[ @jeanbaptisteb ]
> If you're against the idea of filtering, I think you should say it and to give your arguments for this.

I don’t really like idea of language filtering right now but few years back I really like that feature on friendica because I understood only english and french.
Also note that friendica UI’s put a spoiler/CW-like for posts in "foreign" languages.

[ @jeanbaptisteb  ]
> When the translation of the language name isn't available in the user's language, then we could display its name in English.

Actually, I prefer wikipedia’s way, original name in original writing system first, as when you know a language you often know how it’s written, but not how it’s written in other languages, and maybe user’s language and fallback to english.
English should not be so much "default" everywhere.
As said showing full-name would be horrible, ISO-codes are made for that, but full name would be useful when you toot. (As you can make a mistake between ISO-codes)

**Comment by yookoala** [comment]
Is there any room for mixed language contents? There are post on my timeline with Japanese, Chinese and English translation of the same content. Can a post be of Japanese, Chinese and English at the same time?

**Comment by Kimik0** [comment]
Please allow tagging toots with multiple language tags. I'm on an instance where several languages are used, and it's pretty common for people to include a translation into one or more other languages. Automatic tagging should also take this into account and add tags for all detected languages.

**Comment by Kimik0** [comment]
And please base the language detection on the full text of a toot, not just the part below a CW.

**Comment by jadykes** [comment]
This would be a terrific help; just about every toot in both timelines is now in japanese. I can't find toots I can read, which makes Mastodon completely unusable at times.

**Comment by Gargron** [comment]
This is now more or less in master.

**Comment by jadykes** [comment]
Sorry, I'm new in GitHub - that means it's in the master...to-do list?

And thanks for the swift response, wow!

John

**Comment by nightpool** [comment]
@jadykes that means that it's been implemented

**Comment by tmladek** [comment]
Hello,
I see that this issue has now been closed, but:
- I don't see an option to filter out specific languages in Federated or Local timelines
- I don't see an option to only see a specific language in Federated or Local timelines
- No public toots seem to have their language marked
- There is nothing in Preferences or Filters that suggests filtering by language

So, what's the solution as of 2020?

**Comment by Gargron** [comment]
Go to Preferences -> Other to find Filter languages section. There is no differentiation between "federated", "local" or any hashtag timeline (they are all considered "public timelines"). All toots have a language that's either detected automatically (not always accurate) or a language the author of the toot has deliberately selected ("Posting language") (sometimes wrong).

**Comment by tmladek** [comment]
Oh wow, no clue how I missed that.

Thank you!
