### ISSUE TITLE
Hashtags in content warnings don't work

### ISSUE THREAD

**Issue by nevillepark** [tootsuite/mastodon#699]
Currently, hashtags in the content warning field just behave like plain text. [Here's an example.](https://mastodon.social/@nev/1372994) 

This is inconvenient if, for example, a user wants to hide their #introductions post behind a content warning, but wants other users to be able to find other #introductions posts by clicking on the hashtag. It also prevents the effective use of hashtags for things some people may want to filter out and others may want to follow, like #food or #discourse. 

![screenshot from 2017-03-30 16-01-55](https://cloud.githubusercontent.com/assets/16054979/24523780/3b7dcb34-1562-11e7-8082-5ca3ddbee3f5.png)

**Comment by ProgVal** [comment]
If a hashtag is in the content of a toot, it appears in the search even if the toot has a content warning.
So I don't think it's an issue.

**Comment by nevillepark** [comment]
Sorry, this is what I mean: https://mastodon.social/@nev/1529407

If the hashtag is *in* the content warning, it isn't clickable and it doesn't appear in search results.

**Comment by ProgVal** [comment]
Indeed, I misunderstood.

However, since content warnings are not displayed on non-mastodon instances, allowing tags there would create a gap between mastodon and the rest

**Comment by skddc** [comment]
> However, since content warnings are not displayed on non-mastodon instances, allowing tags there would create a gap between mastodon and the rest

Maybe that's a good thing. If it works and is being used and liked by users, then it could make adding it to the underlying protocols and getting it adopted by other implementations a bit easier. If it's already outside of specs, then we might as well improve the feature based on user feedback and needs. No?

**Comment by nevillepark** [comment]
Hmm. I wonder if there is a way to maintain the CW functionality on Mastodon, but degrade gracefully for non-Mastodon instances, in the Atom feed, etc. E. g. ```CW: {cw field} | {status}```.

**Comment by Gargron** [comment]
We have attempted to make content warnings contain rich text, including mentions, links and hashtags. However, this meant that content warnings could not be copied into new toots automatically any longer. It is simpler to think of them as a plain text label on top of the actual content.

**Comment by sparr** [comment]
@Gargron "this meant that content warnings could not be copied into new toots automatically any longer"

why not?

**Comment by sparr** [comment]
@ProgVal why aren't content warnings displayed on non-mastodon instances? Can they not just be included at the top of the post?

**Comment by melissaboiko** [comment]
In my opinion it would make a lot of sense to allow hashtags in CWs. CWs are essentially keyword descriptions of the content... *and so are hashtags*. The semantics overlap a great deal.

Suppose I am in an instance geared towards professional communication,  but I want to post selfies. Following local policy I might want to use a CW like "transgender selfie", so that only people interested in this kind of stuff will see my picture.  But I also want people from the fediverse to find the pictures if they're interested, so I'll want to add tags like... `#transgender #selfie`. If I could just put the tags in the CW, I'd avoid insistent,  bothersome repetition,  *and* save up precious ~17 characters that I could use to complain about my lipstick brand or other matters of high relevance.
