### ISSUE TITLE
Federated report shows up on remote instance as being from local admin

### ISSUE THREAD

**Issue by chr-1x** [tootsuite/mastodon#6994]
I know federated reports need to be "anonymized" but surely there's a better way? Encountered some confusion this morning when a remote admin tried to follow up on a report which showed up as being from "me".

This would be fine if everyone was aware of how it works but as it is it's confusing, since there's not much differentiation between reports made locally and reports made remotely, so the default interpretation of whatever is shown as the sender is "this person directly sent the report". In short, it increases the learning curve for admins and increases the likelihood of a slip up.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ThisIsMissEm** [comment]
Yeah, I thought the report came from @chr-1x, but it didn't. Would be better to just label it as "from a federated instance" — even though the report(s) where not actually anything against policy on our server (not sure about your server)

**Comment by Gargron** [comment]
This just needs to be fixed in the reports UI when reporter is a remote account.

**Comment by ThisIsMissEm** [comment]
@Gargron I'm open to suggestions as to how?

**Comment by nazco** [comment]
Same problem happend here at chaos.social and another instance today.

**Comment by Gargron** [comment]
```haml
- if report.account.remote?
  = t('admin.reports.someone_from_another_instance')
- else
  = report.account.username
```

(pseudocode)

**Comment by jebuskrust** [comment]
Greetings,

Not sure what runs in the back-end for these reports however... Why not just simple case statement the output, if the domain of the account is not null it would be considered remote correct? Therefore, you could just swap the output for the username with the domain depending  on whether domain is either set or not for the account in question..  Otherwise, display the username for that report.

Example:
select report_id, case when domain is not null then domain else username end as username, content 
from report_notes, accounts where report_notes.account_id=accounts.id;

**Comment by Gargron** [comment]
I offered a solution in the comment above yours and there is no need to do it inside the SQL query.

**Comment by jebuskrust** [comment]
Yeah I saw, but just throwing it out there. Miloki was seeking input, bless her heart.

**Comment by ThisIsMissEm** [comment]
I think this can be closed, can't it?
