### ISSUE TITLE
Is development environment broken?

### ISSUE THREAD

**Issue by notlmn** [tootsuite/mastodon#7051]
Hey developers of mastodon,

i've been trying to setup a mastodon environment multiple times (5 to be exact, from scratch in VMs, since May 2017, yes 2017). I followed all the instructions in [dev-guide](https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Development-guide.md), and the [production-guide](https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Production-guide.md), and other possible combinations of those commands.

And always one or the other kind of error pops up like [this](https://github.com/tootsuite/mastodon/issues/6161), and require hacks like [this](https://github.com/tootsuite/mastodon/issues/6161#issuecomment-354914483). I'm a JS dev and most of these ruby errors seem almost alien to me.

For example, to run the rails server `bundle exec rails server` doesn't work for me, and need `RAILS_ENV=production` prefix (what happened to development?). And then this needs the `.env.production` file, which needs secrets, and all of this is not documented. And things like webpacker, why not just use webpack, why not separate mastodon backend and frontend.

*If you do not believe me, try setting up a mastodon instance (developlment, not production) from scratch.*

(I know I'm asking a lot of questions and posting random issues that should be discussed on their own, because I'm frustrated, all I wanted to do was write a theme!).

What I think mastodon needs is a simplified development process, or improved docs.

All I ever end up is installing all the packages, but I never end up setting up mastodon. If I'm dumb and missing something I should know, please do let me know! (Or just point me to a some article on detailed setup of mastodon).

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by notlmn** [comment]
Yes, I did use `bundle install` to install all the development dependencies and not with the  `--deployment` flag.

And if you want to see what I've been doing for the past four hours, [you're welcome](https://gist.github.com/notlmn/88aa2be6edc7b3bc20d50bf1365c8d42).

FYI, I am a mastodon user on toot.cafe!

**Comment by renatolond** [comment]
Hey!
I took a quick look in your log and it seems that your bundle install ( https://gist.github.com/notlmn/88aa2be6edc7b3bc20d50bf1365c8d42#file-log-log-L4160-L4360 ) does not include annotate (which is from the development set) and might be missing some other dev gems. (like better_errors, rubocop, etc)
This might be because your first bundle install had a --deployment flag ( https://gist.github.com/notlmn/88aa2be6edc7b3bc20d50bf1365c8d42#file-log-log-L1743 )
It probably generated a `.bundle/config` file which remembers which sets you chose to ignore. If you remove that file and bundle install again you'll stop having the annotate issues (and everything related to having to use the production env)

**Comment by notlmn** [comment]
> It probably generated a `.bundle/config` file which remembers which sets you chose to ignore

Ruby noob!

-------------------------------------------------

Will keep trying to setup mastodon though!

**Comment by notlmn** [comment]
Closing this as I've figured how to setup Mastodon.
