### ISSUE TITLE
SSL_ERROR_RX_RECORD_TOO_LONG

### ISSUE THREAD

**Issue by Effendil** [tootsuite/mastodon#7071]
I only become this message if i try to go to my mastodon site internally:

Ein Fehler ist während einer Verbindung mit 192.168.99.100:3000 aufgetreten. SSL hat einen Eintrag erhalten, der die maximal erlaubte Länge überschritten hat. Fehlercode: SSL_ERROR_RX_RECORD_TOO_LONG

I search massive for this error but i dont found anything to fix that. With older Mastodon forks the site works but not with the official latest....

**Comment by codl** [comment]
> An error occurred while connecting to 192.168.99.100:3000. SSL has received an entry that has exceeded the maximum allowed length. Error code: SSL_ERROR_RX_RECORD_TOO_LONG

It seems like you are connecting with https, most likely being redirected to https, but connecting directly to the app server and not to nginx (which should be handling https).

Is this a production installation? Since v2.1.2, mastodon enforces https on all productions installations.

> Wow noone can help or want to help or do anything? Great Community -.-

This is a community of volunteers, and you are asking a tech support question on a sunday while providing very little detail. Please exerce patience.

**Comment by Gargron** [comment]
This is not a tech support forum. We want to hear about bugs and feature requests, not guide you through installation instructions. But yeah @codl is right you are connecting to a HTTP Puma server via HTTPS. You need Nginx or Apache in front of Puma, if you are running in production mode.
