### ISSUE TITLE
Add abbility to change an instance default theme from the administration panel

### ISSUE THREAD

**Issue by Sylvhem** [tootsuite/mastodon#7092]
The only way to change an instance's default theme is to edit the `config/themes.yml` file to rename the chosen theme to "default". Sadly, it prevents admin without a sysadmin access to do so. Since there is more and more instances hosted on plateforms like [Masto.host](https://masto.host/) and [MaaStodon](https://maastodon.net/), it may start to be problem.
So, that's why I think there should be way to change an instance default theme from the administration panel.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ThisIsMissEm** [comment]
To add more info for any beginner wanting to work on this, you'll need to look at:
- app/views/layouts/application.html.haml
- app/controllers/application_controller.rb
- app/views/admin/settings/edit.html.haml
- app/controllers/admin/settings_controller.rb

And read up on the ruby gem `rails-settings-cached`, particularly, you'll just want `Setting.theme`.

**Comment by Cassolotl** [comment]
Related to *Wanted: ability to import and export themes via the admin settings page #5614*, I think? Not sure if duplicate! But this one has helpful technical pointers so it should stay open. :)

**Comment by JMendyk** [comment]
Hi, I would like to work on this feature. I've implemented draft version of this feature, but I have some questions and would like to ask maintainer/contributor for help and opinion.

Currently, default user's theme points to "default" but is named "Mastodon" in UI. Users that want to use *real* Mastodon theme won't see what they expect when selecting "Mastodon" (bad UX) if sysadmin changes path of default theme in `config/themes.yml`. Likewise, Mastodon doesn't provide users with the clear option to use instance's default theme.

**My target for this feature is to:**
- separate real "Mastodon" theme from concept of instance's default theme,
- let (non sys)admin set default UI theme from a set of existing themes,
- let the user select real "Mastodon" theme,
- let the user select instance's default theme.

**To achieve this, I proposes following steps:**
1. Rename "default" theme to "mastodon" in `config/themes.yml` and in locale files.
2. Treat theme's value "default" as intent to use instance's default theme 
*or* introduce special value for this intent (e.g. "instance_theme")
3. Add instance's default theme selection option to admin settings UI.
4. (translators' help required) Add translation of "Use instance's default theme" to locale files.

**My issue:**
I am having doubts regarding implemention of step 2. One way to do it, would be to not add default/special value to `Themes.instance.names`, then `ApplicationController#current_theme` could be left almost as-is (because default/special value wouldn't be in `Themes.instance.names`:
```ruby
def current_theme
    # changed Setting.default_settings['theme'] to Setting.theme
    return Setting.theme unless Themes.instance.names.include? current_user&.setting_theme
    current_user.setting_theme
end
```

However, the default/special value is required in user's settings view, 
https://github.com/tootsuite/mastodon/blob/2aeeffc3ec421111f751cab61a15642cbddd9f0d/app/views/settings/preferences/show.html.haml#L37-L38
thus new method could be introduced which returns `Themes.instance.names` with appended default/special value (e.g. `Themes.instance.names_with_default`).

I would like to ask for help and opinion whether this is a good solution or a better one could be used.

**Comment by Sylvhem** [comment]
Thank you a lot for your work on this @JMendyk! I really like what you have proposed, except for one thing: the third step. I don't think we need to have an entry "Use instance's default theme" in the theme selector. I think it'll just had confusion to the feature.

**Comment by Sylvhem** [comment]
Yes @JMendyk, it's what I meant :).
