### ISSUE TITLE
Add number of notifications as badge to notifications tab title

### ISSUE THREAD

**Issue by hoodiek** [tootsuite/mastodon#710]
single column mode is very well implemented i think, except for a single flaw, most people do not want to spend the majority of their time in their notifications window, but otherwise you cant at a glance look whether you have notifications when the sound is off

![2017-03-31_23-04-22](https://cloud.githubusercontent.com/assets/23704040/24574825/b88bfc7c-1666-11e7-9197-824c98a37229.png)

i would suggest adding a "badge" as they're called in windows ten, when on a taskbar button, with the number of notifications, right over the button that takes you to the notifications column

**Comment by joyeusenoelle** [comment]
I'll take a look at this and see what I can do.

Issues that come immediately to mind:

- Can this be done without actually fetching the mentions?
-- If so, can it tell the difference between total mentions and mentions that aren't included in the column?
- Can this be enabled by user preference rather than being the only/default behavior?
-- Is it better to have this be enabled or disabled by default?

**Comment by hoodiek** [comment]
i would argue it's better enabled by default, and that the code probably already knows/fetches mentions, as it beeps when you have the setting turned on, and are in another screen. "difference between total mentions and mentions that aren't included in the column" is a good question

**Comment by joyeusenoelle** [comment]
I agree that enabled by default is probably the better option, I've just seen some people note that they appreciate that Mastodon *doesn't* tell them how many new mentions they have.

A thought that occurred to me today: do we need to show how many new notifications there are? Or just have a badge for when there are new notifications? Like:

    Notifications (new!)

vs. 

    Notifications (42)

**Comment by beatrix-bitrot** [comment]
i think having the number is nice, but if having it makes it significantly more complicated or causes display issues then i'm not sure it's worthwhile

**Comment by hoodiek** [comment]
what bea said. honestly i'd be happy/it might be prettiest if it just changed the color of the bell. probably best for all platforms overall, too.

**Comment by Cassolotl** [comment]
>honestly i'd be happy/it might be prettiest if it just changed the color of the bell. probably best for all platforms overall, too.

This is now the case - maybe this issue could be closed?

**Comment by hidrarga** [comment]
> This is now the case - maybe this issue could be closed?

Uh? When I receive a notification, the color of the bell doesn't change :confused: 

I'd be really interested in this feature, as I recently noticed that I could hide the notification column (on desktop view). What would be great now is to see that there are new notifications on the taskbar (the top menu). I know that the number of unread notifications appears on the "start panel", but then I must check that regularly... :disappointed:

**Comment by Cassolotl** [comment]
![screen shot 2018-03-29 at 23 54 59](https://user-images.githubusercontent.com/6607512/38117407-b0f305be-33ac-11e8-96e8-08df44008254.png)
![screen shot 2018-03-29 at 23 55 30](https://user-images.githubusercontent.com/6607512/38117410-b3689ad4-33ac-11e8-8a20-012977d188b2.png)

But you're right - it only happens when you're scrolled down a bit and you can't see the most recent notification. I think I misunderstood you the first time I read this issue! Sorry about that. 😳

The option to be at the top of the notifications column and *not* autoscroll when new notifications come in would be nice. And then the bell would turn blue and you'd have to scroll up to read them.

**Comment by hidrarga** [comment]
Ohh I see what you meant ! But indeed that's not helping me, because I'm hiding this column :)

![image](https://user-images.githubusercontent.com/2971096/38117825-86b5e4c8-33b7-11e8-80c0-90ece58b9d13.png)

Here is a picture to help understanding what I mean when I say:
> I know that the number of unread notifications appears on the "start panel"

I'd like to have the same feature, but on the top menu (desktop view): 
![image](https://user-images.githubusercontent.com/2971096/38117930-0e3a7f44-33b8-11e8-8b39-c00508237166.png)

Something like this would be nice as well:
![image](https://user-images.githubusercontent.com/2971096/38117981-4cd3e862-33b8-11e8-90d4-a713cde9c0e5.png)

**Comment by Cassolotl** [comment]
Ohhhhh that's nice! Now that we have the ability to unpin the Notifications column, little changes like this would make things a lot easier. Thank you for the mock-ups, they help a lot!

**Comment by hidrarga** [comment]
@Gargron why did you close this issue ?!! Does that mean that you don't want to implement the feature I proposed ? or did you already implement it ?

Or did you just close this issue without any reason ?
