### ISSUE TITLE
Confusing UX of content warning

### ISSUE THREAD

**Issue by GyrosGeier** [tootsuite/mastodon#722]
When I have a toot with a CW, only the CW text is shown with a "Show more" button.

This looks ugly if I use the CW field for keywords only, so I'd be inclined to write a free-form tl;dr here, which makes filtering more difficult -- also, the text entry field is single-line, so likely not intended for long form.

It would be good if the UI would guide users to either make a long (replacement) toot, or use keywords only (e.g. by giving a different rendering to the CW field to make it obvious that this is not the actual text).

**Comment by chris-martin** [comment]
I think the displays of the toot composition form and the resulting toot in the timeline are conceptually backwards from each other.

* In the form, the hidden part is the primary content of the toot, and the visible part is a minor addendum which you can add by clicking the CW button.
* In the timeline, the visible part looks like the primary content of the toot, and there's a hidden part added on that you can click to get to.

Either paradigm would work, but the problem is they're not consistent.

**Comment by Skirmisher** [comment]
I guess part of this is the perception of how the CW is used. @GyrosGeier, you say just using it for keywords "looks ugly", but in other circles, those keywords are common practice, and having functional UI for that fits right into that niche, so everything checks out for them and the current implementation stands. Now, long-term Mastodon users like myself have adjusted to how that looks in toots, the "show more" button being a strong enough signifier that the only text immediately visible isn't the main content.

On the other hand, since the CW text is not visually different, you can also type a tl;dr as you said, and I've seen folks use it for joke setups or other such things where the "warning text" is part of the content itself. Even if they're as short as a word or two, the critical thing is that they're as important to the toot as the rest of it, which could mean that a visual distinction would break the flow. That depends on the exact changes, naturally, but it's something to be cautious about.

You could argue that the CW feature shouldn't try to accommodate anything other than keywords, and to be fair, the intended use is getting the most mileage, from what I can tell. But that feels a bit draconian, and the current versatility seems important to me. Maybe certain slight changes to CW text formatting could balance both ends, but I'm still skeptical. Plus, like, I really appreciate the sort of emergent use it's gotten. I mean, think of the first line to All-Star and tell me you don't wanna run over and toot that with the CW right now. ^_^;

Oh, and another thing is that CW text isn't parsed like normal text--you don't get links, mentions, or hashtags, and you can't even input newlines. I don't recall the how and why of this backend-wise (plus something about federation to non-Mastodon instances?), but that in itself discourages using CWs for longer-form stuff, though new users won't figure that out until they try to use a tag. It might be nice to have hashtags at least, so they can serve a dual purpose by being the CW and tagging the post appropriately.

I'm not sure how the CW *field* itself isn't indicating you're not typing the actual content in there...but now I see, there's nothing to say "all the big text will be hidden, only the small text shows". You can hover over the toggle and it says "*Hide* text behind warning", but that's it. Hm. But is that a problem that needs to be solved?

Anyway, to accommodate more text in the CW box without making it bigger by default, it could just grow with each line added. I can see that being a reasonable bridge between holding longer messages and still strongly discouraging using it as the main message. Though really, most of the longer CWs I've seen are jokes, and they know they're subverting the UX and don't care what it's telling them, and that kind of adds to the humor. So I wouldn't mind leaving the box as-is, either. Since the CW text really isn't treated the same way as main text, anything beyond keywords you put in there is gonna be pushing against that signifier, and it's just up to you if you're comfy with using it that way. And that's fine!

**Comment by yiskah** [comment]
The content warning feature is intended to be used with keywords. Not blocks of text. That is why the box is single-line. It was developed to replace the old ROT13 system which was being used. We'd try "CW // Violence" etc. and the rest was ROT13. 

It used to be that that switch was the entire phrase "Hide text behind warning." When you click CW" now it  still says "Content Warning" in the field, which makes it clear that it is a *warning.*

I guess we could add minor changes to make that more clear but I think it becomes clear the moment you make your first post using a CW and see what it does. Users often do make test posts with it. It's a natural exploration of the UX, We don't want to present people with a manual every single time they use a feature.

The onboarding modals which will be finished soon explain the compose box and say "You can hide your post behind a warning by clicking CW." That is all the explanation needed imo.
