### ISSUE TITLE
No card on local URL.  Card appear on remote URL.

### ISSUE THREAD

**Issue by luzi82** [tootsuite/mastodon#7224]
2 cases:

Case A:  Post a local status URL.  Result: no card.
https://mastodon.social/@luzi82/99901586977699696

Case B:  Post an URL of status in other instance.  Result: Card appear.
https://mastodon.social/@luzi82/99901950805132861

It seems related to the bad_url function in fetch_link_card_service.rb .  And it seems it is "designed" to ignore local URL.  But I dont know why.  ( If you hate mentioning other status, you may also need to bad_url all the remote instances.  But I dont agree doing this.  Mentioning is good. )

Related stuff:
#2572 450ad431801b5f2c716041920842a9851b9d133c 1efda1c4535d453b3f9e71c61a225d7cc0d7e75f f8fe394e7a03edacb06c336b3990d6e488336361
https://github.com/tootsuite/mastodon/blob/master/app/services/fetch_link_card_service.rb

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by mal0ki** [comment]
This is partially intentional, and because we don't want quote toots to be a thing (as it's partially used in a very negative manner on some other platforms). 

However, it doesn't display on the "Web-UI" but rather only when you go to the actual page of the toot (which not a lot of people do). 

See photos below:

![image](https://user-images.githubusercontent.com/28316305/39467747-e13a1b3a-4d2f-11e8-8e12-3340176e40ad.png)

![image](https://user-images.githubusercontent.com/28316305/39467765-f7ae4c6a-4d2f-11e8-8ad0-f3a448ec7931.png)

**Comment by luzi82** [comment]
If it is intentional then it is fine.
I may try to disable that filter in my own instance.
I wish there is no critical bug.

Moreover, I can see preview card in your reply.  I guess it need time to load.

![screenshot_2018-05-03_23-05-02](https://user-images.githubusercontent.com/48815/39585456-70a4d50a-4f27-11e8-957f-e8b619de2830.png)
