### ISSUE TITLE
#Enhancement As a user, when I upload images, I want them to display in full resolution so users can read text

### ISSUE THREAD

**Issue by ldexterldesign** [tootsuite/mastodon#7242]
Hi all,

Hope you're well

Thanks for software

As title

Screen shot(s)/cast: https://mastodon.social/@ldexterldesign/99908794887475961

Original for comparison[n]

If anyone else reading this agrees please up-vote or reply "+1"

Let me know if you have any issues - happy to help

Hope this is clear/useful and to hear back

Yours faithfully

* * * *
[n]
![a4cf2c3f-cdcf-47d0-b60e-ad4fa74ecea4](https://user-images.githubusercontent.com/1715809/39135252-d569d0a6-4718-11e8-81b5-da96bb3e0fa8.png)

**Comment by trwnh** [comment]
I think currently, images are downscaled if they are bigger than 8MB or bigger than 1024px. #7229 might have something to do with this? Also related to https://github.com/tootsuite/mastodon/issues/2252#issuecomment-379544259

**Comment by ldexterldesign** [comment]
Hey @trwnh,

Thanks for reply

That image is 717KB though?

Cheers

**Comment by mal0ki** [comment]
@nightpool does that mean that the scale down we're providing right now is flawed? (am I understanding you correctly here)

**Comment by Gargron** [comment]
>The image is scaled down to 1280 in the largest dimension which is prrrobably not the behavior we want...

@nightpool Is it not? There's gotta be *some* maximum. An image that's at least 1280px in just one dimension can get very, very big. I am almost sure that tumblr uses the same rules (I took the number from them because it seemed like something users would be used to)

**Comment by trwnh** [comment]
In that case, why not limit by filesize instead of by dimension? 1280px isn't enough for legible text. Images should be scrollable in the canvas.

**Comment by Gargron** [comment]
Images are often uploaded larger than what is recommended for the web and our 8MB upload limit is for that. But displaying an 8MB picture in a browser window? That's not reasonable. Thinking in terms of dimensions is actually easier here than in terms of file size, because well, you can't tell imagemagick "reduce dimensions until the output fits in this file size limit", you can only tell it "change the dimensions"

**Comment by glubsy** [comment]
>I am almost sure that tumblr uses the same rules (I took the number from them because it seemed like something users would be used to)

@Gargron  indeed, tumblr does that, but that doesn't mean that's what we should be doing. Tumblr users hate this platform for many reasons, and this is one of them. Up until recently, there was a trick to access the original ("raw") files by changing a few characters in the file URL, but this is not the case anymore since a few days ago. So users are looking for alternatives to tumblr, and Mastodon could be one of them if the original files where accessible somehow, even if that meant changing the URL "manually".

**Comment by Gargron** [comment]
Image resizing has been improved.

**Comment by ldexterldesign** [comment]
Hi @gargron,

Hope you're well

Thanks for follow up

[Updated toot
](https://mastodon.social/@ldexterldesign/99908794887475961)

[Before](https://files.mastodon.social/media_attachments/files/003/618/763/original/b4833185fdfe9a90.png)
[After](https://files.mastodon.social/media_attachments/files/007/347/184/original/53b3ec21075de3ab.png)

For my use case I wouldn't say this is a fix

What's the problem with just showing the raw 717KB file?

If you have any issues (e.g. questions/queries) happy to help

Hope this is clear/useful and to hear back

Cheers

**Comment by glubsy** [comment]
Thanks for taking the time to look into this, @Gargron , but this is clearly not enough.

I noticed that GNU Social also allows storage and access to the original files. I couldn't determine if this is a default setting, or a per-instance custom setting yet, but I have a feeling this is the default behavior. 

Twitter also stores the original files, but serves a downscaled version by default, which is the sensible approach. Users can still access the original file by changing the URI slightly (file.png:large -> file.png:orig) 

As of now, Pleroma, GNU Social and Twitter still have better media file support than Mastodon.

Sysadmins who would prefer not to serve the original files under any circumstance (for bandwidth reasons) can configure that on the server side, until Mastodon provides this restrictive feature natively.

I think the best compromise would be for proxies to serve the downscaled files, but users could still access the original (raw) file directly from the originating instance, perhaps by tweaking the URI slightly.
Replacing the "/original/" bit with "/raw/" perhaps? Although, it would make more sense to rename the current "/original/" to "/scaled/" instead, and /original/ should point to the raw file, but that might break previous versions.

**Comment by ldexterldesign** [comment]
BUMP

**Comment by Pixeliz3d** [comment]
BUMP 2

**Comment by Gargron** [comment]
Originals won't be kept unless a media quota system is implemented.

**Comment by wizzwizz4** [comment]
@Gargron Why not?

**Comment by Gargron** [comment]
Consideration for admins for whom storage costs money.

**Comment by ldexterldesign** [comment]
Is there an issue for "a media quota system"?

If yes then would be useful to link this issue for context/visibility

If no then I'm happy to create one so we can continue this discussion there

I don't run an instance myself so don't know the full story but it seems very beneficial for admins to have full control of media quotas in case they're running media-centric (e.g. video, image) instances

Hope to hear back

Cheers

**Comment by ldexterldesign** [comment]
> Is there an issue for "a media quota system"?

**Comment by Gargron** [comment]
OK, created #11808

**Comment by lordkitsuna** [comment]
I would like to bring this back from the dead. I am running into this issue now as well and its infuriating. I can understand the idea of trying to limit space but mastodon does have a single user mode and i am using that. and even if i was hosting a publicly usable instance i would still like to have the option to dictate the maximum sizes and resolutions that should be my choice as the admin of the server. the current resolution limit is, in my view, tiny and just not usable for 2021. doodles i make on my tablet regularly exceed that resolution let alone photos taken from a basic smart device. 

As a default this is fine and perfectly understandable but i should have the option to change it if i wish.

**Comment by wizzwizz4** [comment]
While the perfect solution would be gated behind #11808, there's an argument not to let the perfect be the enemy of the good-enough. Being able to change the threshold values / size targets of the image resizing thingy is a legitimate feature _in addition to_ image size quotas, and it's easier to implement; I think it's definitely worth considering.

**Comment by enn-nafnlaus** [comment]
Reopening this thread. :)  There's recently been a big influx of people from Birdsite, and with them, a lot of artists - who are disappointed when they get here and find that the resolution of their images has been crushed.  Example:

https://fosstodon.org/web/@arvalis@mastodon.social/109311924798595398

Rather than waiting on quotas, I propose a simple solution that should be a trivial change:

1) Ditch the resolution limit and stick only with file size limits.  Higher jpeg compression is better for image quality than lower resolutions; let people choose that - don't forcebly downscale them.

Beyond that, another possible change: 

2) Drop the current image max file size down from 8MB down to 7MB, but then give an option to upload "high quality" images (say up to 16MB).  Make the process to do so involve clicking through more steps (including at least one "are you sure?" dialog that mentions the disadvantages of large images) so that most people will skip it unless they specifically need the detail.  I strongly suspect the savings on dropping the default max image size down to 7MB would outweigh the costs of allowing people to override it when they specifically need the resolution.

Let's make Mastodon a welcoming place for artists!  :)
