### ISSUE TITLE
Prevent boosting of blocked people

### ISSUE THREAD

**Issue by Cassolotl** [tootsuite/mastodon#7248]
At the moment it's possible to see posts by people I have blocked (#251), because they are boosted into people's profiles, and I understand that this is expected behaviour. (https://github.com/tootsuite/mastodon/issues/7230#issuecomment-383395486)

I'm okay with that if that's the final decision, though my preference is definitely for me to not see blocked people anywhere in the web UI, but it worries me that I am also able to boost someone I have blocked via someone's profile. Would it be possible to prevent that somehow?

Aside from it making me very uncomfortable that I might accidentally boost and endorse something by someone I have blocked because I'm not paying attention, it could lead to weirdness - like:

* Can they see that I have boosted them anywhere?
* If so, should they be able to, since I have blocked them and they shouldn't see me anywhere?
* If they see that I have boosted them and they tag me in a post to talk to me about that, I won't see their post and that would also make me uncomfortable to know that I have drawn their attention while unable to see their responses.
* If they see that I have boosted them and they can't see my profile when they look for it, it could lead to some confusion and awkward questions (that I will not see).
* And I obviously don't want to introduce to my followers an account that I have blocked, you know?

**Edit to add:** You can actually boost, like, and reply to someone you've blocked and they can see all of that in their notifications column. None of these things should be possible.

~

**Edit to add:** Muting them is not a solution, because muted people still show on the profiles of people who boosted them, and that is intended behaviour:

Gargron [said](https://github.com/tootsuite/mastodon/issues/7230#issuecomment-383395486):

>But: "Blocked users' toots still appear on the profiles of users who retoot them" is something completely different. It's specifically when you open someone's profile, you see everyone who they boost. And I kinda think it's supposed to be like that. If a user is boosting someone I blocked I'd rather know about it.

And [then](https://github.com/tootsuite/mastodon/pull/7231):

> The only differences between block and mute should be:
> 
> - Mutes can optionally NOT affect notifications
> - Mutes should not be visible to the muted

So it's pretty clear that muted and blocked people are intended to be visible on the profiles of people who have boosted them.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Cassolotl** [comment]
>Why is the former a problem?

See bullet points, but mainly, I have done this before by accident and it was alarming and I really don't want to do it again.

>It's not exactly expected that you'll go on to boost content that upsets you after blocking the author...

I wouldn't boost content that upsets me. But if I missed someone's avatar and username, or they had changed their avatar or username since I blocked them, I probably wouldn't recognise them. And just because I've blocked someone, doesn't mean I find 100% of their posts upsetting. So, even though it is not very common, it happens and I found it really distressing - not only can I still run into someone I've *blocked*, but I can accidentally boost them too.

**Comment by trwnh** [comment]
1) Does boosting a blocked user send them a notification?

2) I would prefer to retain the ability to boost blocked users -- if I didn't want to see them, I would mute them as well / instead.

**Comment by Cassolotl** [comment]
> I would prefer to retain the ability to boost blocked users -- if I didn't want to see them, I would mute them as well / instead.

So if I *mute* someone in order to not see them, and their post still shows up on someone's profile when boosted, I could still accidentally boost them even if they are muted *and* blocked, right?

**Comment by Laurelai** [comment]
Frankly i'm not ok with being able to boost blocked users. If i block someone, i want them gone. I don't want to interact with them, i don't want them to interact with me. I have memory problems caused by trauma and will sometimes forget the exact reasons why i've blocked them, but i tend toward my own safety. So I i trust past me to have made the right call. If you dont want to have block actually...block people then create a third mode of user level moderation that does this. I dont care what you call it. I just want an option to have an account gone from my life forever.

**Comment by trwnh** [comment]
@Cassolotl If you mute someone then their posts should not show up at all, boosted or not. I've muted plenty of bot accounts that some of my follows boost occasionally, and I no longer see them. The purpose of a mute is to filter out an account from all timelines and profiles -- as soon as you mute someone, you can't see any of their toots anymore in any location. This isn't true for blocks, although it seems to be expected behavior due to 4 years of precedent on Twitter.

@Laurelai I think many people probably want a block + mute function, and this is largely why there are requests to treat the block function as a block + mute implicitly. That just leaves "block only and don't mute" in a weird place.

**Comment by Cassolotl** [comment]
>If you mute someone then their posts should not show up at all, boosted or not. I've muted plenty of bot accounts that some of my follows boost occasionally, and I no longer see them.

@trwnh Do you mean that you no longer see them in the Home timeline? Or do you specifically not see them when you go to your friends' profiles in the web UI? I just wanted to make absolutely sure you've tested this, because as far as I know blocks and mutes are both *not* meant to hide boosts on people's profiles in the web UI, and also since I follow people I don't ever check their profiles to know whether they're boosting people I've got muted!

I just went to Gargron's profile and muted someone he boosted. Their post disappeared, but when I reloaded the page their post was back. Something's up there, it's not behaving the way it should.

@gargron Are mutes meant to work on boosts in people's profiles in the web UI too, or not?

**Comment by trwnh** [comment]
Muting someone immediately hides all toots from their profile. It also hides their toots from my Home and Federated timelines, boosted or not. It's possible that when you refreshed the page, the database hadn't updated fully yet (see #7088 for another example of this).

In https://github.com/tootsuite/mastodon/issues/7230#issuecomment-383396227 I laid out all the scenarios that need to be tested as a matrix of blocks / mutes in timelines / profiles -- I'm not sure about what exactly the backend logic is, but I can only speak anecdotally that muting an account has hidden it in 100% of the cases I've observed. I've not seen a boost of a muted account in all my time using Mastodon.

**Comment by Cassolotl** [comment]
@trwnh How long might I need to wait for the mute to hold? It's still not gone. :/

**Comment by Cassolotl** [comment]
I find it extremely weird that people keep trying to say "blocks stop people seeing you, mutes stop you seeing them." When you block someone you stop seeing them in the public timelines, hashtags, your home timeline. Mutes are intended to function exactly the same as blocks, the difference being when someone is blocked it's obvious to them whereas mutes are sneakier. We know this because of #7231, where Gargron said:

> The only differences between block and mute should be:
> 
> - Mutes can optionally NOT affect notifications
> - Mutes should not be visible to the muted

So If a mute was to hide someone's posts from the profiles of someone who has boosted them, and a block was not, that would not make sense to me. It is inconsistent with what Gargron said in that pull request, and it would be inconsistent with how mutes and blocks currently work.

**Comment by Cassolotl** [comment]
> Does boosting a blocked user send them a notification?

Just tested it - yes, people who've been blocked still get notifications when you boost and like their posts and when you reply to their posts, all via the profile of someone who boosted the blocked user.

It seems very counterintuitive and hazardous that you can boost, like, and reply to someone you've blocked and they can see all of that. None of these things should be possible.

**Comment by Cassolotl** [comment]
> Anyway, as for boosting/favouriting someone you blocked, I added guards for that in #7231

That sounds good to me! :) Thank you very much!

**Comment by trwnh** [comment]
Honestly at this point I think a great deal of confusion in this discussion is coming from the fact that it's split across 5 different issues...

>Mutes are intended to function exactly the same as blocks, the difference being when someone is blocked it's obvious to them whereas mutes are sneakier

Currently, yes. That was more or less what Twitter decided in 2014 and therefore what users expected coming from Twitter: that mutes are just weaker blocks. As I said in https://github.com/tootsuite/mastodon/issues/7230#issuecomment-383913128 , this is mostly translating a bidirectional paradigm onto a unidirectional network; in a friend system, blocking cuts off the entire relationship in both directions.

>blocks and mutes are both not meant to hide boosts on people's profiles in the web UI

the full user timeline on the profile doesn't seem to be filtered - "user timelines are not filtered, never have been"  https://github.com/tootsuite/mastodon/pull/7231#issuecomment-383418402 https://github.com/tootsuite/mastodon/pull/7231#issuecomment-383418657

because it's meant to be a full timeline - "when you open someone's profile, you see everyone who they boost. And I kinda think it's supposed to be like that. If a user is boosting someone I blocked I'd rather know about it." https://github.com/tootsuite/mastodon/issues/7230#issuecomment-383395486

>"blocks stop people seeing you, mutes stop you seeing them."

I should clarify this isn't the way it's *implemented* currently -- there were, and still are, many disparities in the way blocks and mutes work; #7231 is intended to refactor the block and mute logic to make the two functions more similar with only two differences.

Instead, I'm saying that directionality is the more *fundamental* way to define blocks and mutes; i.e., this is how it *should* work, not how it *currently* works. There's still the whole issue of https://github.com/tootsuite/mastodon/issues/7230#issuecomment-383396227 with 4 cases that need to be tested (maybe more), and about 9 different logical bullet points I came up with re: how the system should be / is currently implemented. additionally, in this thread, i made this comment https://github.com/tootsuite/mastodon/issues/7248#issuecomment-383914634 (and probably many others at this point) that the disparity is because most people mean block+mute and not simply block -- which makes muting someone in addition to blocking them even more confusing...

>nobody should be able to stealthily organize abuse campaigns (...) no way to mention someone without them seeing it.

this is good to know, as well as the rationale. I suppose that adds another dimension to the matrix in https://github.com/tootsuite/mastodon/issues/7230#issuecomment-383396227 for mentioning blocked / muted users... although at this point, it's starting to get too complex for two simple boolean states. I think it's possible to find reasonable defaults and implications for block, mute, and block+mute, but it might be better to instead remove the entire block/mute system and replace it with an access control matrix? As in, you can specify who can see your posts, who can follow you or send you follow requests, and whether their posts are visible or not (across various timelines, and whether it's boosted or not), and so on.
