### ISSUE TITLE
Account / toot deletion should be broadcast to all known instances

### ISSUE THREAD

**Issue by ThibG** [tootsuite/mastodon#7316]
Account and toot deletion should be broadcast to all known instances.
Indeed, account deletion is currently broadcast to followers, which is not nearly enough, as it is frequent for account information to be fetched by an instance without any follower.
Toot deletion mishandling is a little less frequent, but there can still be corner cases: e.g., unfollowing everyone that has boosted a toot from an un-followed user.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by mal0ki** [comment]
I actually think this is a good idea. 

I'm wondering if it could be a batch sent out once per 24/hrs or something. (this is me not being a programmer mostly just musing)

**Comment by Gargron** [comment]
Specifically toot deletion goes through forwarding mechanisms for boosters and reply threads, which increases the number of notified instances. Broadcasting to all known instances from origin alone might yield less. If you say: Just forward those too? Unfortunately I don't see a way to mark which instances have already been notified, which means each instance will send to each instance which will send to each instance etc etc and even though there's an easy way to "I already processed this, do not forward again" that's still plenty of useless back and forth traffic. For account deletions? Okay maybe, because they are mostly rare. For every deleted toot? That won't fly.

**Comment by Gargron** [comment]
A distributed ledger of pointers to deletions would actually be useful :joy:
