### ISSUE TITLE
Bio fields width issue

### ISSUE THREAD

**Issue by Gargron** [tootsuite/mastodon#7335]
After all, `<table>` seems to be a bad choice for rendering bio fields, because it acts odd with container width when one of the cells has a lot of horizontal content (text-overflow/overflow do not seem to have priority there). Use flexbox instead

**Comment by flussence** [comment]
I've got a bit of experience with this stuff so here's my 2¢:

Word breaking in tables is never going to work reliably. It's not a browser bug, it's just a consequence of [the legacy table rendering algorithm](https://www.w3.org/TR/CSS22/tables.html#table-layout) (which is a scary read, and unfortunately can't be fixed for compatibility reasons).

CSS Grid would be the best option in terms of difficulty since it's table-like, but will always do what you tell it to w.r.t. max width. Flexbox works in older pre-2017 browsers, but I'm not sure they're worth worrying over. Both methods will gracefully degrade anyway.
