### ISSUE TITLE
Endpoint for last read toot

### ISSUE THREAD

**Issue by lamnatos** [tootsuite/mastodon#7418]
(Somewhat similar idea to #4093)

It would be nice to have a synced timeline across clients (web or not) connected to an instance. This functionality suggestion is directly inspired by the (discontinued) [Tweet Marker](https://github.com/manton/tweetmarker) 3rd party service for Twitter.

It would allow clients to set & get the last viewed toot on the instance itself, thus allowing them to know where to continue from when displaying the timeline. When using multiple clients it would make switching between them easier since each of the clients could show the same point in the instance's timeline.

I cannot give implementation suggestions but maybe the [Tweet Marker API description](https://github.com/manton/tweetmarker/blob/master/documentation/v2.md) could be a helpful starting point.

* * * *
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by foozmeat** [comment]
I think this is a huge quality-of-life improvement. Reading my TL goes like this.

* Press Home to make sure my TL is up to date
* scroll backwards until I recognize a toot
* read forwards

I would like to be able to open any of my clients and the TL is pinned to the last toot I "read" and then I just scroll forward in time to catch up.

**Comment by jumoru** [comment]
I second this proposal as well. It's the one big thing I'm missing from my Twitterrific/Twitter set-up. Compared to Twitter, implementing it in the backend also would have the advantage that it would work across different clients.

**Comment by bitboxer** [comment]
I would love to start contributing to Mastodon and work on this ticket. @Gargron how do I proceed? Should I write down an api proposal in this ticket and start the discussion with that here?

**Comment by kylpo** [comment]
Just wanted to chime in to say that this is the only thing keeping me from switching to Mastadon. I've listened to a few Mastadon podcasts explaining the need and purpose, and I'm totally on board. Tweet Marker / last-read-sync is just too critical to my workflow though.

**Comment by 5teveroy** [comment]
As someone who uses Mastodon on multiple devices and with multiple apps, the lack of syncing of my timeline positions is the biggest usability issue I have. Every time I go back to Mastodon, I start reading and then realize I've read this before and have to keep scrolling until I'm fairly certain I haven't read those. Some clients always show you the latest posts (hello web) so I have to scroll down to find where I was. With some other clients (I use Toot a lot lately) I have to scroll up.

The point is, some people want to make sure they've read *everything*, others want to make sure they're not wasting their time *rereading* posts they've scanned before. Either way, timeline syncing would be the ideal solution.

Since all (most?) Mastodon clients are currently single-platform, it doesn’t help if one app implements timeline syncing. Having it built into the API so all clients can benefit and we can get syncing across apps would solve this problem perfectly.

One think to keep in mind is that Mastodon has multiple timelines so ideally each one would have its own sync marker.

**Comment by Midar** [comment]
Recent thread on this (for a few more +1): 
https://mstdn.io/@js/101527659943389929

**Comment by tomekw** [comment]
Well, that's the ONLY reason I haven't switched from Twitter (and AWESOME Tweetbot with tweet marker) to Mastodon.

Have there any design discussions / decision been made? I think I would be able to devote some of my time to implementing this.

**Comment by iero** [comment]
Any Mac or iOS Mac does uses this API already?
