### ISSUE TITLE
Private toots that are not stored yet are not shawn/fetched when boosting them

### ISSUE THREAD

**Issue by kit-ty-kate** [tootsuite/mastodon#7426]
Since https://github.com/tootsuite/mastodon/pull/6157 it is now possible to boost your own private toots.
I thought it could be taken as a good temporary substitute for https://github.com/tootsuite/mastodon/issues/34 as boosting your own public posts for example will make them appear to all your followers even if they were not present in the database of the instances receiving it (followers and followers of anybody boosting those toots).

Turns out this doesn't work the same way with private toots:
* Boosting private toots already present in your followers' database will effectively make them appear as boosted from your followers point of view
* Boosting private toots that are not present in your followers' database does nothing and do not appear anywhere from your followers point of view

*Tested with an instance running 2.4.0rc1 and with followers running 2.3.3.*

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by kit-ty-kate** [comment]
cc @ThibG

**Comment by ThibG** [comment]
Indeed. This is because the receiving instance would have to fetch the remote private toot.
For this to work, the receiving instance would have to authenticate to the remote one as one of the followers, though. Neither side (verifying remote users when serving toots, and fetching on the behalf of a user) is implemented yet.

**Comment by kit-ty-kate** [comment]
Arf :/ I see. How is it different from public toots then ? Is there any documentation around to understand how this works ?

**Comment by ThibG** [comment]
It's different from public toots because public toots are… public. You don't need to authenticate to see them. If there is a boost (or reply) to a toot that is not known to your instance, Mastodon will try to fetch it by performing an HTTP request to the missing toot. However, if that toot is private, it won't be returned.

I was wrong earlier in saying that Mastodon doesn't check the requesting user. It does. But Mastodon still doesn't fetch toots on the behalf of a local user. That could probably be changed but I'm not too sure about privacy implications.

**Comment by kit-ty-kate** [comment]
I see. Thanks for the explanation <3
