### ISSUE TITLE
Links in Report dialog are white-on-white text

### ISSUE THREAD

**Issue by riking** [tootsuite/mastodon#7431]
Screenshot of me filling out a report about myself on mastodon.social:

![image](https://user-images.githubusercontent.com/627891/39843149-a69c9ab4-539e-11e8-9bb8-f661a119af5c.png)

Links and @-mentions are almost indistinguishable from the modal's background.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ThibG** [comment]
Fixed in 3c5006ec7fa98ec53df619b0e6e52b3bbdb6f046

**Comment by CrazyJake88** [comment]
This issue seems to still come up. I was able to replicate this when the most recent toot by the user being reported has a content warning and other toots that are not CW'd

![2018-12-01 15_24_49-toot chat](https://user-images.githubusercontent.com/1314033/49332595-f67e7580-f57d-11e8-91d3-c691bd8d3fe5.png)

![2018-12-01 15_28_24-toot chat](https://user-images.githubusercontent.com/1314033/49332596-f9796600-f57d-11e8-9732-12646c76c20f.png)

My instance version 2.6.2
Desktop, chrome and firefox
