### ISSUE TITLE
Allow user to choose whether to merge or replace imported CSV data

### ISSUE THREAD

**Issue by ghost** [tootsuite/mastodon#7465]
From what I understand by reading code and experimenting, the userlist importers in the settings page currently only merge entries into the user's existing list.

Adding an option to replace the old list with the imported one would allow a way to undo big mistakes, whether they built up over time or were a result of a bad import — i.e. export the list, fix it in a text editor, and re-import. That's not perfect but it's much easier than clicking remove buttons one by one in the web interface, or writing a thing to do it via the API.

(If added, this would also need a warning when it's done on the follow list, due to the risk of unintentionally unfollowing protected accounts)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by cacheflow** [comment]
I'll take this. What about the notifications though? If you go through and unblock, unfollow, and unmute an account the notifications will be shown. Should they be hidden for tasks like this one?

**Comment by mal0ki** [comment]
Ah, sorry @cacheflow I didn't respond because my contract wasn't renewed after the 15th of May, so I wasn't paying attention to the github and my relationship with Gargron kind of went fubar with that, unfortunately. 

You'll have to ask Gargron about this.

I hope you'll be able to do this though.

**Comment by cacheflow** [comment]
I'm done with the backend aspect of this. Just need to finish the front-end part for showing the warning for purging a follower list. @mal0ki

**Comment by Gargron** [comment]
@cacheflow How did you decide to implement it? I was figuring if "replace" instead of "merge" is chosen, you don't unfollow everyone first (as it would be wasteful), but make a diff of imported and previous follows and leave the ones that overlap, and only unfollow the others. Not sure how frontend feedback is supposed to happen because you *can't* process the list in a web thread, it's too slow. Perhaps the `Import` record is supposed to linger (maybe delete only the attached file to save space) so in the UI you see the last imports you've uploaded and there you could see the status, how many accounts were followed, unfollowed, whatever.

(I was considering taking this on)

**Comment by cacheflow** [comment]
@Gargron, that's how I implemented it. For example, if you choose to replace the "unfollow" list, then it'll go through and diff the ids and only unfollow the ones that aren't present in both. 

Also, as an aside, on another branch I implemented a way to bulk upload a list to unfollow, unmute, and, and unblock. Not sure if there's a valid use case for it though.
