### ISSUE TITLE
Add CAPTCHA to sign-up process (are you human?)

### ISSUE THREAD

**Issue by bunnybooboo** [tootsuite/mastodon#7601]
With recent pummeling from spam sign-ups, it's been discussed to look at options for Captcha. It would of course be preferred such a tool would be from a FOSS provider as an alternative to Google's reCaptcha tool. Issue added to track discussion of this.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Technowix** [comment]
Plz no Google ;u;

Also, the recent bot surge where manually added bots.

**Comment by Angristan** [comment]
I also think the bots were added manually like @Technowix said, so a captcha wouldn't help here.

However a captcha wouldn't be a bad idea, as long as we don't rely on a third party service.

**Comment by bobstechsite** [comment]
Alternatively you could dodge needing one with a combination of alternatives (eg. ensure sign up forms aren't completed too quickly, honeypot hidden form field, optional requirement to verify an email address with a confirmation link before proceeding, etc)

**Comment by Gargron** [comment]
Accessebility: CAPTCHAs are hard to enter even for someone with good vision. Text-to-speech option is required, but difficult to manually implement. Google is inacceptable. Honeypot form fields are likely to not play well with screen readers, since screen reader and malicious bot see the page the same way.

Only feasible measure: #6856, so if you're getting hit by a wave of spambots, you switch to approval mode, preferably without any UX changes on the outside (to help #6951), and you'll just have to look through applicants before they even get a confirmation e-mail.

**Comment by coreyreichle** [comment]
Also, requested in #877

**Comment by Angristan** [comment]
Approval mode seems to be a good idea

**Comment by coreyreichle** [comment]
I also like the approval mode, rather than captcha idea.

**Comment by nightpool** [comment]
closing this in favor of #877 and #6856.

anecdotally, modern spam attacks can rip through captchas nearly instantly. most spammers either farm out to mturk or have their own human labor.

**Comment by d3cline** [comment]
IMO this thread doesn't really address the problem, the bot problem has become much worse, and in order to be listed on the official site we need to be open signup. Captcha needs to be added, and many of these once glanced over problems need real thought behind them.
