### ISSUE TITLE
Name rebranding? "toot" == fart

### ISSUE THREAD

**Issue by Zig-03** [tootsuite/mastodon#7667]
Sorry if it's a duplicate, really hard to search for this generic keyword "toot" which would have my context.

If you go on youtube and search for _"mastodon social"_, some top videos address mostly the branding issues saying that "Mastodon" is hard to pronounce and that "toot" ([urban dictionary link](https://www.urbandictionary.com/define.php?term=toots)) means fart.

We all would like more people to use this service **but can we really envision a public figure (after signing up on mastodon) saying smth like: "Please toot me tomorrow" or "I'll toot you when ready"?** I doubt that, the best case scenario: they'd say that while giggling.

I could see three possible solutions here:

1. outsource a marketing/re-branding specialist for suggestions;
2. just change "mastodon" & "toot" to something else;
3. or at least change "toot" to something else.

What do you guys think about it? How would you see this issue being solved (if you see it as an issue)?

Thanks.

**Comment by nightpool** [comment]
people have been sending hot takes about our "doomed" branding ever since I've been on mastodon. but so far very few actual users have complained about it, only people looking to dismiss it without engaging with it.

and on the other hand, mastodon now enjoys name recognition with millions of users and it would be a huge effort to change that, not to mention wasting a lot of existing good will. and all of that ignore the fact that decentralization means that no one even has to care about the mastodon brand if they don't want to—your local instance brand and the fediverse/ActivityPub network brand are to some extent more important to the casual user.

**Comment by bonsaiheldin** [comment]
To bring in another opinion: I've never even heard of the wort "toot" in context with farting, to be honest. Maybe it's some kind of slang? I think of playing a horn or a trumpet when i see the word. To toot a trumpet.

![](http://articulatepersuasion.com/wp-content/uploads/2014/09/toot-toot.jpg)

I wouldn't care much about that masturbation thing either. It's called masturbation, not mastorbation. I think if "masto" reminds someone of masturbating, than, for example, "master" would tool i guess or basically everything starting with "mast". Also, Mastodons are extinct animals, a type of mammoth. I like that name and i like the mascot, very much. It's cute.

Like @Cassolotl mentioned with "twitter = twit", i suggest to not let people that use words differently let destroy your ideas. Also, like @kwill said, it's hard anyway to confirm if it really has an impact and until now i've never heard about this problem. So, i guess... Let's not make it one?

**Comment by Cassolotl** [comment]
With words like Mastodon/masturbate and toot/fart, there's a line between probably fine and actually a bad idea, right? People naming things online have to ask around to make sure the names they choose don't sound offensive in other languages and whatnot, but also no two people have that line between fine/bad idea in exactly the same place.

The thing with Mastodon is that unlike Google (silly sounding word) and Twitter (can be shortened to twit/twat), Mastodon is on the border of a taboo sexual activity and a toilet thing. Both of those are, shall we say, taboo in many places at least in the Western English-speaking world as far as I know? So like, anyone who's super mature or who speaks English as a second language probably doesn't have that visceral emotional connection, but anyone whose first language is English and who's been taught not to talk about masturbation from a young age or who was taught that farts are rude are probably always going to have those associations in the back of their mind.

And that's why it keeps coming up. It's shame associated with those words, *on some level*, probably an unconscious level for a lot of people. I'm not special-interested enough in this topic to know whether it can make or break a brand or project, but that's what's going on.

**Comment by nightpool** [comment]
I speak English as a first language and honestly never noticed the
masturbation thing until it was pointed out in this thread.

don't think I've ever heard anyone mention it before either, even though
there was that whole mashable article about how mastodon was a bad name,
they didn't seem to notice the connection

**Comment by nightpool** [comment]
if anything, my immediate association would be with "masticate", for chewing

**Comment by LogicalDash** [comment]
that's weird, I don't think most people even know that word

**Comment by Cassolotl** [comment]
Yeah, I'm thinking that on the odd occasion that people *do* notice the connection it'd be taboo to mention it. But a lot of people will dislike the word and not really know why. Like "moist". :P

**Comment by Cassolotl** [comment]
>if anything, my immediate association would be with "masticate", for chewing

>that's weird, I don't think most people even know that word

When I was in school, pranksters would play tricks on people who didn't know that word. They would say "oh, are you masticating?" and watch the person go red.

**Comment by Cassolotl** [comment]
It's cool, no one cares that the Nintendo Wii has named itself "urine"!
