### ISSUE TITLE
cannot create account with email with same domain as mastodons LOCAL_DOMAIN

### ISSUE THREAD

**Issue by useltmann** [tootsuite/mastodon#7910]
I set up an instance with the domain *metaccount.de*, accessable on https://social.metaccount.de, but i cannot create an account with an email like smoe@metaccount.de. it says "invalid email-address".
No email-addess with *@metaccount.de* is working.

I deployed via docker, i used the latest prebuilt image from tootsuite/mastodon:v2.4.2

 
* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
The validation checks whether it's a real e-mail address by looking up the MX record. Does your e-mail address actually work?

**Comment by useltmann** [comment]
Yes, the email is working, but ihave no mx-record in the dns-server the mastodon-server is using. Thanks for the hint. Closing.

**Comment by l0nedigit** [comment]
@Gargron perhaps this is old, but I spent a very considerable amount of time trying to get a mastodon server stood up and user sign up working.  Turned out I was missing an MX record on my internal DNS server for the internal mail (same situation) - it may be worth adding to the docs as a NOTE to ensure the users email domain is setup properly, to include an MX record.  An added step would be to surface this information to the user in the UI based on the backend failed query for the users email.

Thankfully I found this closed issue.
