### ISSUE TITLE
Opting out of showing up in follow suggestions

### ISSUE THREAD

**Issue by headache-booth** [tootsuite/mastodon#7966]
If follow suggestions get implemented in a full release, I think it's important that users be able to opt out of showing up in follow suggestions, whether they're using Mastodon or any other software it federates with. This is something I've seen a few people other than me mention that they would like to see implemented. I imagine this would be relatively easy to implement in Mastodon, but I'm somewhat worried about how this would be handled in other software. I'm primarily a Pleroma user, I really don't want to show up in other people's follow recommendations. Only having a switch in Mastodon's settings that you can flick to opt out of showing up in follow suggestions isn't helpful for people who use other software.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
The way the suggestions algorithm works ([and I do recommend familiarizing yourself with it, given it's incredibly simple](https://github.com/tootsuite/documentation/issues/645)), you are put on a user's personal, private suggestions list after they interact with you. **By definition, they already know about your existence by the time you are in their suggestions.**

Mastodon had a follow suggestions feature at the time of its launch in November 2016. The concept isn't new. It was removed due to a technical, database-related limitation, and since then I have attempted to re-introduce it multiple times. This latest iteration is the most harmless, as I even gave up on the triadic closures algorithm; it has 0 abuse potential.

I do not think any new options are necessary.
