### ISSUE TITLE
Auto fold posts with > 500 characters.

### ISSUE THREAD

**Issue by ThomasLeister** [tootsuite/mastodon#7973]
In some cases posts are transferred from other Fediverse software systems, that allow more than 500 characters in a post. Therefore very long posts might appear in Mastodon's narrow columns. 

**Suggestion: Introduce a auto-fold feature, which only displays max. 500 characters at first, and then displays a button at the end of the post to expand the post to full length.**

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by verymilan** [comment]
I suggest making this an optional option with a short explaination to avoid confused users on max. 500char instances because they may wonder why users in the network can write more than 500chars in the first place. :thinking:

**Comment by Gargron** [comment]
This isn't the first issue about special treatment for longer fediverse posts.

We already have special treatment for longer fediverse posts, when those are correctly marked as "Article" instead of "Note" - the message becomes the title of the post and the link to the original.

I don't think that posts noticeably longer than 500 characters deserve to be considered a "Note" (short message without title) and I am not enthusiastic about building out special treatment for people who misuse the semantics of the network when using "Article" would be a lot more readable.

**Comment by Gargron** [comment]
@Toromino How about asking the developers who changed the limits to mark their posts as "Article" instead of "Note"? Raising the character limit is not an official Mastodon feature (my position on this is "just because you can doesn't mean you should"). And for non-Mastodon software it's in everybody's interest to publish stuff in a way that's most readable. If you let people post 10,000 characters you can't call yourself a microblog anymore in my opinion.

**Comment by nwtti** [comment]
@Gargron why don't you just block all posts exceeding the 500 char limit?

**Comment by Gargron** [comment]
First off I'm not complaining about anything - if I see a 10k characters post on my TL, I unfollow/mute the author, I don't complain about it. It isn't me creating these feature requests. Incidentally, I don't see any posts longer than 500 chars nowadays. Mastodon is a microblogging server and I don't see any reason to add special treatment for *macro*blogs beyond the already special treatment of longer posts that are marked up *properly*. I don't care if it's easy to do or not, or if somebody else decided to do it in their app - great, use that app then. I think it's just unnecessary clutter to make up for shortcomings we haven't caused.

Funnily enough I do literally set the rules for what code I write and publish in this repository.

**Comment by rugk** [comment]
>  if I see a 10k characters post on my TL, I unfollow/mute the author, I don't complain about it

Obviously, yes. This would be a spammer. But let's not exaggerate that thing. What do you do if you only see slightly longer posts that may still be acceptable (and not bad intend from the poster), but are slightly longer than you would like to read/scroll? Say, e.g. 500 chars or so?

This is what this issue is about. It's not about 10k chars, of course.

**Comment by zcdunn** [comment]
I have both a masto and Pleroma acct and when posting from my pleroma account I don't realize when I've gone over 500 characters. And character count isn't the main difference between a Note and Article. Articles are assumed to be thought out, edited posts. Notes are spur-of-the-moment streams of consciousness. Going over your chosen limit doesn't turn a random thought into a well written piece.

**Comment by trwnh** [comment]
I've always seen the Article/Note divide based on length, not at all on how well-thought-out it is. You can plan a short missive, and you can ramble on for two pages. The difference is in how they should be consumed.

Articles frequently (but not always) have titles, but Notes don't -- however, a CW is essentially a subject line. Could Mastodon not offer better native treatment to Articles, so that they show up collapsed in the feed? That might encourage more inplementations to use Article properly -- as it stands, there is an incentive to mark everything as a Note so that it shows up fully in Mastodon (the dominant fediverse application, and largely a monoculture whose peculiarities must be considered).

The only other things that could be done on Mastodon's side would be to reject messages above a certain length, or cutoff or auto-CW them; what could be done on the remote side is to allow users to choose Note vs. Article, or to infer based on character limit and/or title.

**Comment by Gargron** [comment]
@trwnh The reason it's better not to show an Article inline at all is that an Article, given its length, is likely to be richly formatted. Headlines, blockquotes, inline images, etc. That sort of thing will not fly in the Mastodon UI. It will also be in most cases confined to around 330px width, which will make such a post extremely long. Even in your desired auto-CW scenario, if you have the misfortune of actually expanding such a post you can say goodbye to ever scrolling anywhere other than the post. This is why I am arguing in favour of current behaviour.

Those who modify Mastodon to have longer limits may as well modify Note into Article, make CWs mandatory and modify their encoding as "summary" into "title".

**Comment by trwnh** [comment]
@Gargron We can very well say that remote Mastodon hacks _should_ re-encode as `Article`, using CW as title, and so on -- but at some point, we also have to ask how those messages are going to be received.

Expanding a CW should not scroll the page, so it should be easy to collapse it again. It's true that the default Mastodon app isn't optimized for longform content, but that just means the fallback has to be more robust. If vanilla Mastodon expects a max of 500 because that's hardcoded, then it also has to be prepared for a situation in which other servers will break this expectation.

If a `Note` is plain-text, and of arbitrary length, then **there should be ways to control that length** -- either by fully rejecting too-long messages (undesirable), or by collapsing too-long messages (configurable), or by displaying them in full length (unsightly).

Imagine a microblogging application server that expects each `Note` to be 140 characters or 280 characters, a la Twitter. To this application, even Mastodon's 500 default could be considered too much. Instances with longer limits which still send as `Note` will be even longer. And the limit of "too long" is entirely up to the server operator. Therefore, it makes sense to me that Mastodon should anticipate arbitrary length `Note` objects, precisely _because_ the division between `Note` and `Article` is left intentionally vague by the standard. This would allow each server to create an environment of its own arbitrary length, without being dependent on other servers behaving according to their personal expectations.

**Comment by lanodan** [comment]
Just so that the people here are aware of it.

I made a PR(https://github.com/tootsuite/mastodon/pull/8205) that rebases an old one (https://github.com/tootsuite/mastodon/pull/658) fixing this long post issue.

My point on this thread would be that Tootsuite’s mastodon should be aware that the whole Fediverse doesn’t works like Toosuite wants, and that anyway even with 500 characters one can make a post that is too long for the Mastodon UI. (too much newlines for example)

**Comment by kaniini** [comment]
gargron writes:

> How about asking the developers who changed the limits to mark their posts as "Article" instead of "Note"?

there is no specified post length for `Note` items in ActivityPub.  so, what limit are you talking about?

**Comment by sivy** [comment]
While I think that AP clients/servers should have better semantics for distinguishing Articles/Notes, I also think that having a "read more" *link* to view the full content of a post is a good idea, since different AP implementations have different max post lengths.

To my mind (and only IMO) I'd expect posts with any non-plaintext formatting applied (like Pleroma's excellent new HTML/Markdown support) to be classed as Article.

**Comment by Gargron** [comment]
Fixed in #8205
