### ISSUE TITLE
Provide a full list of interactions, not only positive ones

### ISSUE THREAD

**Issue by allo-** [tootsuite/mastodon#8072]
First: It is hard to find a title which captures the essence of the problem, feel free to suggest a better one and I'll edit it.

----

Major social networks have a filter bubble on positive interactions.

- There are a lot of positive indicators
  - Likes and favourites
  - You get a notice when somebody follows you
  - You get notified when somebody shares or boosts your content.
- Negative interactions are well hidden. 
  - You do not see if somebody unfollows you.
  - There is no do-not-like (downvote) button.
  - There is not even a "X users saw your post" counter, so you could guess if nobody liked your content or if there are no likes because too little people have seen it at all.
  - You do not even get feedback when you are blocked<sup>1</sup> if you do not visit the profile of the blocking user.

The incentives for the major networks are clear: Users need to feel positive, so they are prefering their network, interacting more and possibly clicking more ads. Advertising companies should not see feedback like begin blocked when sponsoring too many posts or having downvotes associated with their promoted content.

On the other hand this means, that you have little chance to tell people when you dislike their post without replying (which by itself often is no good idea), that persons do not get feedback when you decided not to continue reading their toots and so on.

Mastodon does not have these incentives, as most instances do not depend on happy advertisers. Mastodon can be an honest network, which tells you the things like they are:

  - "Your post got 100 likes, 40 downvotes and 500 people have seen it" 
  -"Account X stopped following you"
  - "Account Y blocked you"

It is easy to provide a setting "Only show me positive interactions" for the people who want it like the major networks are doing it.

----

1) Another possibly related issue: Even when networks like twitter and mastodon have asymmetric followings, blocking is symmetric.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by ThibG** [comment]
I'm not sure about dislikes (and they already exist in some commercial social platforms, like Youtube), I really think we would do without them.

Getting notifications when you are being unfollowed is likely to cause very unpleasant feelings, but it could also be useful, so I guess an opt-in setting would make sense. However, due to how notifications are architectured, it's not that simple a change (notifications are currently tied to something that *exists* in the database, like a follow relation, or a “favorite” activity).

Counting the number of views on your toot seems like a bad idea and a difficult one to achieve, especially in the decentralized setting of Mastodon.

Blocks are a bit of a mess in Mastodon, honestly… there are arguments for a blocked user not being able to see they are blocked (i.e., avoid some backlash from blocking an abuser), but that can't always work reliably (e.g., public posts you can't see when logged in, but can see when logged out), and it can make things hard to debug (especially in a federated setting, and when instance admins can block people without users necessarily knowing). There's also a lot of confusion between hiding some people's messages, preventing them from showing up in your notifications, or preventing them from seeing your content.

**Comment by allo-** [comment]
> Getting notifications when you are being unfollowed is likely to cause very unpleasant feelings

This is the whole point. Commercial platforms are dishonest to avoid unpleasant feelings. I do not think this is to your benefit, even when you are used to it now.

> I'm not sure about dislikes (...)

> Counting the number of views on your toot seems like a bad idea (...)
I think this would be good ideas to avoid a dislike function ...

But I see now the technical problems in a federated environment and a protocol which needs many instances to use the changed protocol.

> Blocks are a bit of a mess in Mastodon, honestly…

I guess again it is hard to know it in a federated network. How do you achieve hiding posts anyway? Does a post come to your instance together with a blacklist of blocked users?

> there are arguments for a blocked user not being able to see they are blocked

I think blocking is something you *should* notice, else it would not be neccessary (i.e. when you never look at tools from users which block you, the block does not affect you anyway).

> but that can't always work reliably (e.g., public posts you can't see when logged in, but can see when logged out)

Same for twitter, Facebook may work in another way if your profile is only viewable for logged in users. This way you cannot even be sure if your posts are hidden, which is what I meant with blocks being symmetric is kind of a strange idea for asymmetric followings. When I hide your posts, I do not need to want to block you from seeing mine and I cannot achieve this without a private profile anyway.

> especially in a federated setting

Thinking about it, probably some users will sooner or later use instances / clients which ignore blocks. While you now may be able to instance block known bad instances, this is probably far from perfect as blacklists are never complete and instances with this feature (from user of the instance perspective) may get a lot of people which you do not want to block.
This seems to be an argument that neither blocks nor private messages or locked profiles are really enforcable outside of your own instance especially when an admin may be reading the messages without telling anyone. Seems like this are best-efford features which only work reliable on centralised instances.

----

So I am not sure about the issue. What do we have what can be implemented without larger infrastructure changes?

- A dislike button would probably work, a seen counter rather not.
- Blocks could possible added to the notification timelime when the first post of the blocking user is filtered.
- Unfollowings should be propagated to your instance (you see your follower counter), so they could be in notifications?

**Comment by trwnh** [comment]
Most of the things you mentioned don't exist because they would go against the spirit of the software, environment, network, etc.

The possible ones:

- A block notification could be generated when receiving a `Block` Activity, but blocks are not supposed to be visible by design.
  - Users should feel free to be able to block users without making their existence known; imagine receiving notification that some person you've never met wishes you didn't exist. Or, if the person being blocked is an abuser, then you are giving them an incentive to broadcast to their followers that they should harass you, and you'll have to block a lot more people, effectively amplifying the abuse.
- An unfollow notification could be likewise be generated when receiving an `Undo {Follow}` Activity, but it's similarly a bad idea because unfollowing someone is not supposed to be a visible action, either. People should be able to feel free to unfollow others without the social anxiety of knowing they will see it and might take it the wrong way.
  - On the other hand, unfollow tracker applications can easily be written by scanning your followers and calculating changes at given intervals. There's no reason to make this official functionality.

The impossible ones:

- A dislike button cannot exist because there is no mechanism for one. ActivityPub defines a `Like` Activity and a `Liked` Collection, but no such thing for the reverse.
  - Even if something like arbitrary reactions were added via something like #4106, it wouldn't federate out properly to non-Mastodon software.
    - See also: Misskey allows for arbitrary emoji reactions (including a thumbs-down emoji), but they are all treated as a `Like` over ActivityPub. Do you want your dislike to be interpreted as a like when received elsewhere? Probably no, since that would be the exact opposite of your sentiment. 
- A seen counter cannot exist because Mastodon promises not to track users.
  - Additionally, tracking views across the entirety of the fediverse is very difficult:
    - you cannot track who opens content within another software, as it is fetched only once by a remote server and cached;
    - you cannot track who opens content on any given server, because the same cached copy may be viewed by multiple users on that server;
    - you can track who visits a public page by injecting analytics code like Piwik, but public pages are rarely visited and tracking code can be blocked
    - you can track IPs which have accessed a given resource, but at most you will only have knowledge of which servers fetched the content for one of your followers, as per the first two subpoints.

**Comment by Laurelai** [comment]
This is a terrible idea.

**Comment by Gargron** [comment]
Thank you, not interested though.

**Comment by glensimister** [comment]
I would have thought that a dislike button (preferably anonymous) is essential in order for a platform like this to be able to self-regulate. I've only just stumbled across Mastodon and it was one of the first things I looked for in the API reference. Why are developers not given this option? Disliking stuff is not negative, it's a necessary part of life. It's how we filter the good from the bad. I regularly see content on Facebook that I dislike. What are my options? Get into a argument with a friend? Surely, that's more negative?

**Comment by maltfield** [comment]
I came here by searching for "mastodon downvote", so I'm going to add some information that may be useful for others who end-up here like me.

It's highly likely that there will be a mass exodus from reddit next month, just as there was a mass exodous from Twitter last year. Already, many people (myself included) have looked to see if they can get their news from mastodon as an alternative to reddit.

Personally, I think the ability for users to downvote comments made by other users are extremely important in discussing a news article. Upvotes allow relevant commentary to float to the top (eg pointing out an error or conflict of interest by the journalist). And **downvotes are extremely critical for the community to vote to send uninformed commentary to the bottom**, without deleting it (eg a confused user accidentally making an assertion based on objectively incorrect facts).
