### ISSUE TITLE
Mark as sensitive in Report crashes

### ISSUE THREAD

**Issue by sammy8806** [tootsuite/mastodon#8168]
Got that while selecting "all" toots in a report and mark them as _sensitive_
![843bb0352341d788144e10fb8377dde8baad03dd](https://user-images.githubusercontent.com/1584070/43985953-02d5b318-9d0c-11e8-8ddf-a71109b54fa8.png)

![49d045805b658799245a368ee8ded897ffde9f72](https://user-images.githubusercontent.com/1584070/43985929-d22ec664-9d0b-11e8-83c2-a3e4cd8f6846.png)

Target: master

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ThibG** [comment]
Ok, there seem to be multiple issues:
- Checking the checkbox doesn't automatically change the various statuses' checkboxes (that's what it's supposed to do)
- Clicking “Mark as sensitive” triggers a confirmation without checking whether something is actually checked
- The backend errors out without giving a meaningful error message

Just to make sure, because it's a bit of a pain for me to test, but: are you using Mastodon or a fork?

**Comment by nightpool** [comment]
I can't reproduce this on 2.4.3

**Comment by sammy8806** [comment]
@ThibG It's Mastodon not any fork
I've tested it again and I can reproduce this on my dev instance. (which also runs the active master 018a9e4e7fdfac0f2e482f4b5fa66247afbc2ddb )

**Comment by ThibG** [comment]
@sammy8806 it might be an issue in the dev environment (I myself only develop using a “production” environment on a semi-isolated container). Is there something fishy in the JS console?

**Comment by Gargron** [comment]
I think it's some kind of JS regression because "select all" doesn't select anything.
