### ISSUE TITLE
URL unfurling in timeline?

### ISSUE THREAD

**Issue by tdfischer** [tootsuite/mastodon#819]
Hello.

Mastodon is pretty neat. I'm excited where it might go, though must admit I don't know enough Ruby to help out.

Are there plans for URL unfurling URLs in the timeline?

I would expect one in my timeline to look less like:
![screenshot from 2017-04-03 23-39-08](https://cloud.githubusercontent.com/assets/15848/24644116/c0de598a-18c6-11e7-96f4-c5dc091192c7.png)

And more like it appears when I open a toot (tootey?):
![screenshot from 2017-04-03 23-39-46](https://cloud.githubusercontent.com/assets/15848/24644129/d62f227e-18c6-11e7-9151-e677a3672f0b.png)

**Comment by expenses** [comment]
I believe this is to prevent individual toots from taking up too much of the timeline. This is (as with most things) something I believe there could be an option for in settings to turn on and off. I'll look into making a PR about it.

**Comment by Gargron** [comment]
We should discuss:

1. whether we want the preview cards to be displayed in timeline view
2. whether the preview cards should be embedded in the status JSON (more db calls, less API calls)
3. or whether the web UI should simply do API calls for each loaded status to display those (many API calls)

**Comment by thiagomgd** [comment]
I can't give an opinion about the tech aspects, but if would be great if this was a setting that we can turn on. I guess many people would agree that they take up too much space, but others (like me), prefer not having to open the toot to see the preview.

**Comment by sirjamesgray** [comment]
re: this request to show image previews being an option:

Here's how Tweetdeck handles this. They have 3 sizes & an option to hide the image preview entirely.

<img width="305" alt="screen shot 2018-05-03 at 10 52 03 pm" src="https://user-images.githubusercontent.com/16139439/39612401-ce7491aa-4f24-11e8-99cf-430f1a9d9539.png">

**Comment by steckerhalter** [comment]
most people even think Mastodon doesn't do any previews because they don't know the preview only shows when the post is expanded. the only reason I found it out is because there was this other ticket https://github.com/tootsuite/mastodon/issues/4486 where it was discussed that Mastodon does crawl links for previews. so I wondered: "where are these previews then?" and only like that, trying to find it on purpose, I discovered that they are only shown expanded.

my points:

1. the current status is that the previews are largely useless because most people don't even know they exist
2. many times the linked content is the sole purpose of a post and without a preview these posts are just a blank to me on the timeline
3. even though **I** know now that there is a hidden preview I'm not much motivated to expand a post just to see the preview. so even the existing preview is quite useless to me.
