### ISSUE TITLE
Add LaTeX/MathML support

### ISSUE THREAD

**Issue by bogdan-kulynych** [tootsuite/mastodon#822]
It would be great if Mastodon client could render mathematical equations in the toots. This can be very easily accomplished for web clients by including the [MathJax](https://www.mathjax.org/) script (62 Kb).

**Comment by RaitoBezarius** [comment]
After "working" on this issue a bit.
Some pointers are:
- ideally, we should load MathJax dynamically if user options allow it.
- then, we should hook in Redux actions creator when a new post is added to analyze if there is some kind of LaTeX in it, and then run http://docs.mathjax.org/en/latest/advanced/typeset.html on it.

I wonder if we could have a MathJax function which would turn a string of LaTeX to a bunch of DOM nodes.

Last concern: what about theming? How to integrate MathJax theme into Mastodon properly?

**Comment by RaitoBezarius** [comment]
After fighting with MathJax, I tried KaTeX and got this nice result with exactly two line changes:

→ http://screencloud.net/v/BAG8q

Basically, all that remains is:

- Load KaTeX dynamically using options.
- Hook in `status_content.jsx` a soft renderer which will output the same content if KaTeX throw or is unavailable else will return DOM nodes as strings (just filter out the `<p>` and unwanted data, check for \( \), etc…)
- Handle styling issues (when the mathematics overflows, wrapping them, etc…)

- PROFIT!!! :tada:

Also, it would be nice to handle new commands or aliases, how that would be persisted through an instance?
IMHO, ideally, I see two steps:

- Persist aliases on the local instance (we could easily imagine different aliases for different themed instances: statisticians, analysts, etc…)
- Protocol extension: Announce aliases to other instances to ensure compatibility. "Hey, this message is using these aliases, use them and not the ones on your instance!"

@bogdan-kulynych What do you think?

**Comment by bogdan-kulynych** [comment]
@RaitoBezarius 
Looks great!
There's a [gem](https://github.com/freshcodes/katex-rails) for KaTeX. It can then be included as a sprockets [conditional require](http://stackoverflow.com/questions/13180417/conditional-require-in-sprockets#13181489) in `application_public.js`. Probably `user_params` can be used directly in the require.

Aliases seems to be quite an advanced functionality. Why not start with basic maths support for this issue?

**Comment by Gargron** [comment]
I enjoy the fact that there is an instance which implements this (mathstodon), however including the Latex browser rendering runtime for everybody, even though barely anybody will use it except for very specialized cases, makes me believe we will not accept this into upstream.

**Comment by N1N74** [comment]
@Gargron MathML has seen wide adoption among browsers in the 8 years since this issue was created and most browsers today support MathML by default, see [caniuse mathml](https://caniuse.com/mathml) or try [MathML test page (github)](https://fred-wang.github.io/MathFonts/mozilla_mathml_test/) yourself. It's rendered by the browser, so no need for javascript or even CSS! Rendering MathML only needs to be done while writing post which manages efficiency concerns.

Given that much of mastodon users are technical community and I personally see more and more academicians joining in, maybe it'll be worth implementing. I can also vouch for this technology working very well on my devices, desktop and mobile, and across different generating tools like [KaTeX](/KaTeX/KaTeX), [MathJaX](/mathjax/MathJax) and [TeMML](/ronkok/Temml). It's also excellent for accessibility, in fact, mathjax v3 relied on mathml for screen reader accessibility. You'll be gaining a lot with a little imho.
