### ISSUE TITLE
CW par defaut / should be the default

### ISSUE THREAD

**Issue by GuyM-31** [tootsuite/mastodon#8229]
Hi,

Certain·s utilisent Mastodon parce qu'il·elles pensent que c'est plus "safe" que d'autres services de microblogging. Il·elles demandent que les contenus soit mis en CW pour ne pas être exposé·es à des contenus qui les dérangeraient.
Il est impossible de savoir quels sujets dérangent car tout le monde est différent.
Il est donc souhaitable que CW soit le mode de publication par défaut.
Au delà, cela permettrait de différencier plus Mastodon de Twitter en le rendant plus "safe par design".
Si ce n'est pas possible, une option devrait être disponible dans les paramètres de chaque utilisateur.

I try a translation in English, sorry for my poor language.
Some people use Mastodon because they think it's a safe place. They ask some publication to be CW to avoid to be exposed to contents they don't like.
It's impossible to know all the contents that annoy people because everybody is different.
So CW should be activated by default.
This can make Mastodon more different with Twitter and thus be more "safe by design".
If it's not possible, user have to be able to choose CW by default in their parameters.

I hope you will like this request and implemented soon.

Thank for reading me.
GM

**Comment by lapin-b** [comment]
Hi,

What's the point of making toots CW-ed by default ? I mean sure people don't want to see some stuff on social network and I get it; it's totally normal. But if people don't want to come across a specific topic, filters are already implemented since version 2.4.3 (to be precise, pull #7905) and they can mute specific topics. Do not want to see pictures of food ? Filter out toots containing "food". Do not want to see NSFW ? Filter out or silence the account and you won't be seeing it soon.
You even can precise in which context you want the filter to apply. For sure, if you don't use the tools you have at your disposal, miracles won't happen.

To give you an idea, it looks like the screenshot down below:

![Filters UI in user settings](https://user-images.githubusercontent.com/3647174/44300809-3d1ccc80-a30d-11e8-98ed-cfcf322e1f46.png)

As far as I know, every user on an instance, provided it's running version 2.4.3 or later, should have access to this feature in their user settings.

Best regards

**Comment by nightpool** [comment]
i think it's pretty safe to say this is a troll

**Comment by GuyM-31** [comment]
Why do you think it is a troll ?
A filter "food" can't filter all the toot speaking about food.
