### ISSUE TITLE
[UX] Put languages in filter list into a helpful order

### ISSUE THREAD

**Issue by Cassolotl** [tootsuite/mastodon#8236]
Here's what they look like right now:

![screen shot 2018-08-17 at 10 59 17](https://user-images.githubusercontent.com/6607512/44260557-a8cb4080-a20c-11e8-8466-29b7fa9b3d2c.png)

Having "select the ones you want to see" instead of "select the ones you don't want to see" is a great change, but it's now really hard to find the languages you do want to see! A-Z left-to-right in columns is really hard to read and impractical. Maybe A-Z top-to-bottom would be better?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by trwnh** [comment]
It looks like it's already A-Z? It just doesn't look obvious because the localized strings are used. For example, "Magyar" is the localized name for "Hungarian", so it's sorted as H instead of M. Similarly, "Suomi" is Finnish and sorted as an F. Then again, "Español" (Spanish) isn't sorted with S, and "ελληνικά" (ellenika, Greek) is sorted as an E instead of a G.

**Comment by Cassolotl** [comment]
Yeah, that's what my post says. I said that the problem is it's A-Z left-to-right. It's hard to find your languages - top-to-bottom would be much better.

**Comment by Cassolotl** [comment]
I think the second idea would be best!
