### ISSUE TITLE
Pinned posts disappear if you have more than one

### ISSUE THREAD

**Issue by trwnh** [tootsuite/mastodon#8302]
###Steps to reproduce:
1) Open a profile in the webapp with multiple pinned posts (i am using my own)
2) All pinned posts are loaded
3) Expand any post
4) Go back

###Expected behavior:
Profile loads all pinned posts normally

###Actual behavior:
Only the latest pinned post is visible. To load all pinned toots again, a refresh is required.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this). -- happens on mastodon.social

**Comment by nightpool** [comment]
can't reproduce on 2.4.3

**Comment by trwnh** [comment]
That must mean it's caused by something between 2.4.3 and whichever master is running on mastodon.social right now

**Comment by ThibG** [comment]
I could reproduce it with @trwnh's profile but cannot anymore after having forced my server to refresh it.
I would have to delve deeper into this, but the following doesn't look quite right to me:
https://github.com/tootsuite/mastodon/blob/7871d29aff992162d4558e1db25d2f78f65ab38c/app/javascript/mastodon/reducers/timelines.js#L37-L39
Indeed, `expandTimeline` will always try to only fetch what's new, so here it appears we are overwriting the toots instead of merging them.
