### ISSUE TITLE
@-replies showing up in timeline even if I don't follow the mentioned user

### ISSUE THREAD

**Issue by cliophate** [tootsuite/mastodon#8311]
There are a handful of toots that are @-mentions to users I don't follow, yet they appear in my timeline. What seems to happen is that these toots don't get flagged as replies and thus don't get filtered but slip through as simple toots that start with an @ to the username. An [example](https://norden.social/@barning/100581039740049236).

**Comment by ThibG** [comment]
I understand this is a different behavior than twitter, but as far as I know, this is intended: this starts with a mention, but this isn't a reply.
Filtering out stuff like `@foo is great, follow them!` is counter-intuitive unless you are very familiar with twitter.

**Comment by cliophate** [comment]
That definitely makes sense. So it simply looked like the linked user wasn't aware of this. In that case, I guess we can close this issue. Thanks!

**Comment by davidpmccormick** [comment]
I’d love to see this reconsidered — I would like to be able to start a public conversation with someone, but not spam the home timelines of people who don’t follow that user.

**Comment by vmlrodrigues** [comment]
Considering that Mastodon is fast becoming a Twitter replacement I think this issue should be reconsidered. There are times when you want to mention someone and cover a topic that will very likely not be relevant to your followers, however the post will be visible to your followers. Perhaps there is a better way to deal with this than using an @mention at the beginning of the post but I think it should be considered.

**Comment by vmlrodrigues** [comment]
Actually, there is a way to do with without having to use a direct message - use "mentioned people only" option when posting. That's perfect and in fact better than how Twitter does it.

**Comment by davidpmccormick** [comment]
I think 'mentioned people only' is too limiting – it makes a conversation too private when there's potential scope for more public discussion on the thread in the future (as far as I'm aware, a thread that starts its life as 'mentioned people only' cannot be made more permissive in future).

For example, if I have a support question for someone I follow, if/when they answer the question, other people with the same question in the future will be able to find the thread, and the thread could be linked to (rather than the person being asked having to repeat their answer). I know some people would rather not provide support in e.g. Twitter DMs for this very reason.

**Comment by trwnh** [comment]
>  (as far as I'm aware, a thread that starts its life as 'mentioned people only' cannot be made more permissive in future)

it can. privacy is per-post

**Comment by davidpmccormick** [comment]
You can't change the visibility of the original post from 'mentioned users only' to 'public' after the fact. Although I guess that doesn't matter too much, the point can be restated if necessary -- I think my frustration is probably misguided in light of this oversight. Thanks!
