### ISSUE TITLE
Show the user their list of muted/blocked users/instances

### ISSUE THREAD

**Issue by LibertyForTheMasses** [tootsuite/mastodon#8357]
Similar to #3874, but for user-level actions. For example, I've accidentally muted the wrong user and then couldn't find out who I muted or undo the mistake.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by LibertyForTheMasses** [comment]
@trwnh you're absolutely right, thanks for the heads up. Is that in an FAQ anywhere or anything? I searched everywhere but couldn't find it... might be helpful! :)

**Comment by MidnightLightning** [comment]
For those who come behind me searching for where this feature is (since it doesn't seem to be documented anywhere), the "three dot menu" is no longer styled that way. You can find your own user's list of muted/blocked users by looking in the main sidebar/column, next to your own profile name is a "down chevron" menu. Click that and "Muted users", "Blocked users", "Blocked domains", and "Muted words" are separate choices there to list your own out.
