### ISSUE TITLE
Translations are disapearing on Weblate

### ISSUE THREAD

**Issue by BoFFire** [tootsuite/mastodon#8451]
Hi,
I noticed that my own new translations in arabic are cleared and emptied. This happened not just once. I thought I was having Alzheimer, nope, someone is not pulling translation right from Git to Weblate.

Make test, go to arabic on Weblate translate a test string, remember that string and then you will notice that in the next push/pull via/from Git, your translation will be null.

**Comment by BoFFire** [comment]
Ok, we lost the Backend now :( https://weblate.joinmastodon.org/projects/mastodon/backend/ar/

**Comment by mayaeh** [comment]
Hi.
Maybe, have you added the same translation as "user_count_after"  to "about / user_count_after / one" ?

"user_count_after": https://github.com/tootsuite/mastodon/blob/master/config/locales/ar.yml#L36 )
"about / user_count_after / one": https://weblate.joinmastodon.org/translate/mastodon/backend/ar/?checksum=12b00029438dda8e#history

**Comment by nightpool** [comment]
cc @ykzts https://github.com/tootsuite/mastodon/commit/5538ad99db455580ecc0997140b0eb5b544e4608#commitcomment-30291993

**Comment by mayaeh** [comment]
This happened twice even in a Japanese translation as far as I know, too.
Perhaps it seems that Weblate gets an error if you add the same translation after splitting what was not translated in singular or plural form.

**Comment by BoFFire** [comment]
All my changes on Weblate. I have a role of a translator on Weblate. Cannot delete all the strings.

My history : https://weblate.joinmastodon.org/changes/?page=1&user=ButterflyOfFire

**Comment by ykzts** [comment]
@nightpool It is occurring in Weblate. I can only do git merge, so I do not know the details.

**Comment by nightpool** [comment]
Have we reset weblate to master since #8420?

**Comment by ykzts** [comment]
I do not know because I am not an administrator of Weblate.

**Comment by BoFFire** [comment]
Check : https://github.com/tootsuite/mastodon/commit/5538ad99db455580ecc0997140b0eb5b544e4608#r30292166

**Comment by nightpool** [comment]
I'll get this fixed and/or ping gargron to do so.

**Comment by nightpool** [comment]
thanks for flagging the issue!

**Comment by Quenty31** [comment]
The same here, I have to redo the latest translations on the Backend :O 
It's not the first time.
Ça comment à être agaçant quand même =/

**Comment by trebmuh** [comment]
Another one ? https://github.com/tootsuite/mastodon/pull/8483#pullrequestreview-149666906

**Comment by renatolond** [comment]
I noticed two different sets of issues on weblate:

The first one is that sometimes weblate completely removes a file. It used to happen very often with simple_form in some languages. 
The second one is that if we merge differences from weblate into the project, weblate needs to be reset because of the indentation differences. If between the creation of the PR and merge/reset of weblate there's new translations, those translations are reset too.

**Comment by renatolond** [comment]
My flow to merging weblate translations usually is:
Checkout latest master, start new branch, checkout weblate master, merge weblate master into translation branch, solve conflicts, normalize translations, revert removed files by weblate, normalize translations again

**Comment by renatolond** [comment]
Weblate reformats translation files, adding two extra spaces for indentation in the json files, and breaks some lines in the yml ones.
This causes conflicts when merging back files coming from the project (and makes merging back from weblate harder)

I will try getting some time to look into this again: http://widerin.net/blog/weblate-i18next-json-parser/

The author suggests using a script in the pre-commit script hook that weblate provides to avoid these issues. If we could use a docker image with modifications so that we can use that script and match the codebase indent, I think it would reduce a lot the problems we have with weblate.

**Comment by ykzts** [comment]
![image](https://user-images.githubusercontent.com/12539/45260282-d4ada080-b41d-11e8-9902-07237bab4b6f.png)

Did this issue resolve by upgrading Weblate?

**Comment by BoFFire** [comment]
We need to wait until we recieved new strings to translate to confirm.

cc @Quenty31 have you lost a lot of translation in Occitan?
It seems somebody wants to close the issue quickly.

**Comment by Quenty31** [comment]
Non, pas ce coup-ci !
Si je comprends bien, ça n'arrivera plus ce désagrément ?

**Comment by BoFFire** [comment]
Merci :)
Thank you !
