### ISSUE TITLE
Icon for "this person has followed you" and button for "follow them back" look identical

### ISSUE THREAD

**Issue by stuartlangridge** [tootsuite/mastodon#850]
When my notifications timeline informs me that someone has followed me, the non-interactive symbol it uses to identify this type of message is identical in appearance (other than colour) to the button that I can use to follow that person back. This meant that I just spent a few minutes baffledly clicking on that icon to find that it did nothing, before clicking the username to see their profile and following them from there. Perhaps this might be fixed by using a different symbol, or by making the clickable one look clickable and the not-clickable one look not-clickable?

![image](https://cloud.githubusercontent.com/assets/4356350/24663593/442ea5fe-1950-11e7-8a69-2d2caaa981c8.png)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by hishamhm** [comment]
Interesting UI puzzle.

Did you get the same confusion when someone favorited a status? The same thing happens, there's a yellow star next to the name at the top, and a gray star at the bottom. 

My guess is that it is less confusing because the star is part of a row at the bottom, next to other action icons:

![star](http://i.imgur.com/1gsbDpH.png)

So maybe moving the action icon _below_ would improve things, making the placement of actions more consistent?

![new follow layout](http://i.imgur.com/cRXXqLD.png)

Note that I also removed the "+" sign in the non-action icon too, not sure if that would help much.

**Comment by Gargron** [comment]
I would insist there is a clear difference in context between an inline icon and a button. Reusing the same icons should make it *more* clear, not less ("glance value")
