### ISSUE TITLE
Is there a way to enforce privacy settings to be respected regardless of mastodon instance?

### ISSUE THREAD

**Issue by maydaycaptain** [tootsuite/mastodon#8618]
I was looking at the Mastodon user guide and there was a section that says the following: 

"There is no reliable way to check if an instance will actually respect post privacy. Non-Mastodon servers, such as a GNU Social server, do not support Mastodon privacy settings. A user on GNU Social who you @mention in a private post would not even be aware that the post is intended to be private and would be able to boost it, which would undo the privacy setting. There is also no way to guarantee that someone could not just modify the code on their particular Mastodon instance to not respect private post restrictions. A warning will be displayed if you're composing a private toot that will federate to another instance. You should thus think through how much you trust the user you are @mentioning and the instance they are on."

I understand that the nature of Mastodon is being open-source where instances can be modified to the admin's liking, however, it seems extremely insecure and unsafe that privacy settings can be circumvented on someone else's end. Is there any way to make privacy settings be inalienable from the users who set them? Otherwise there's no point to them, and it's leading to some worries I have about using the platform. Could someone please tell me if I'm misinterpreting this? Thank you very much for your time.

**Comment by nightpool** [comment]
There is no technical way to prevent someone from taking a screenshot of your post and sending it to their followers, no.

**Comment by maydaycaptain** [comment]
Oh yeah, I figured that, I was worried more about the line "There is also no way to guarantee that someone could not just modify the code on their particular Mastodon instance to not respect private post restrictions" and what extent that would go to

**Comment by nightpool** [comment]
the two statements are identical

**Comment by ThibG** [comment]
The line about GNU Social is obsolete as Mastodon does not send private/direct toots using that protocol anymore.
However, no, there is no technical way to enforce the privacy setting of your toots when they reach another instance.
“What extent that would go to”: everyone meant to receive your message will (hopefully) receive it. After that, they can technically disclose it however they want.

**Comment by sireebob** [comment]
if a guarantee of post privacy matters more than anything else, all you can really do is ensure you only allow followers from instances you trust. setting your profile to locked makes this easier.

if you run your own instance, you can restrict what instances it federates with. some instances even use whitelists for this.

guaranteed post privacy across instances sounds great, and i once thought it was a reasonable request, but... from what i've gathered... technologically and design-wise, the field hasn't settled on a great way to handle this, yes.

one way to attempt this would be to use end-to-end encryption for non-public posts, so that only intended recipients could see them. this is complex and hard to get right, and often has a poor user experience, particularly when group communication is involved. there'd likely be significant user hassle along the way to ensure everything is in order and no one's up to any funny business. there would be moderation challenges as well, because only intended recipients could see your messages. standalone apps would need to be used, because web apps can't be trusted to behave any certain way. and you'd probably have situations where users who need to reset their password will lose access to any private posts that happened since they last logged in. also, no guarantee that the ability to see private posts would work across devices or if you signed in from a new device. (i'm basing this on my user experience with apps that support e2ee, like matrix, wire, and signal.)

these aren't necessarily insurmountable obstacles in general, but as far as i've heard, consensus seems to be that they'd be better solved by other software... and i agree.

**Comment by nightpool** [comment]
@sireebob none of the fanciest encryption schemes you could devise could prevent a user from making a post public after they receive it.

**Comment by maydaycaptain** [comment]
thank you for the responses, everyone. I can understand the technical roadblocks now and I hope that a way to handle this can be found in the future that doesn't compromise functionality. for now I'll get by with only accepting follows from instances that I know comply with privacy protocol
