### ISSUE TITLE
Local accounts duplicated as remote

### ISSUE THREAD

**Issue by arjenpdevries** [tootsuite/mastodon#8643]
Search results should not include the same account twice.

See e.g.:
![image](https://user-images.githubusercontent.com/642221/45213408-ba49ba80-b297-11e8-994c-4f4a9135688d.png)
(`@pixelfed` and `@pixelfed@mastodon.social` are the exact same result; though, surprisingly, the results show as if I follow the one account and not the other. I checked with mouseover that they refer to the same (webfinger?) id `https://mastodon.social/@pixelfed`.)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by trwnh** [comment]
Been seeing the same issue randomly on mastodon.social as well, with some accounts showing both local and remote entries.

**Comment by trwnh** [comment]
This is still happening and it's definitely a bug, right? #8698 was closed since it was a hostname change and a deployment issue, but this one is happening on mastodon.social which I would assume has been deployed correctly. Somehow, local accounts are being copied as remote accounts. It's hard to tell whether this was a temporary bug or a still-occuring one, but...
![image](https://user-images.githubusercontent.com/10606431/47252328-81f5da00-d408-11e8-842e-42969bbe3347.png)
