### ISSUE TITLE
Allow people to search notifications

### ISSUE THREAD

**Issue by koyuawsmbrtn** [tootsuite/mastodon#8644]
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by trwnh** [comment]
Searching your own tweets, mentions, and favorites is already possible, but it is an optional feature that requires the server admin to install the ElasticSearch dependency.

**Comment by codesections** [comment]
There are also third-party tools that allow you to download and search your notifications.  @kensanata / @kensanata\@octodon.social's [Mastodon Archive](https://alexschroeder.ch/cgit/mastodon-archive/about/) is one that I've used and it works very well.  (It can't search previously-cleared notifications, however, since those have been deleted.)

**Comment by Gargron** [comment]
I enabled ElasticSearch on mastodon.social so this should hopefully resolve such feature requests in the future.
