### ISSUE TITLE
Private mastodon instance

### ISSUE THREAD

**Issue by nathanhillyer** [tootsuite/mastodon#8668]
**Use case:** We'd like to make a private instance for our elementary school. Everyone that is registered should be able to see posts, but no unregistered users should be able to see or interact with any posts.

Is there a way to do this? I'd prefer not to default everyone as private because, from my understanding, that would entail everyone follow everyone else. I'd like all posts to be visible to members only but other aspects of Mastodon remain intact.

**Comment by TheDiscordian** [comment]
Related to #3880

Currently everything you want is there, you can via the admin interface disable registrations and hide public posts. The only content that will be public from there are the profiles, and people could follow others from other instances (because there's no whitelist feature). awoo.space has a whitelist feature though, so if their code is public, you could probably merge their changes.

**Comment by nathanhillyer** [comment]
Great, thank you.

**Comment by bricin** [comment]
When I follow the steps at https://github.com/tootsuite/mastodon/issues/8668#issuecomment-419964362 I am still able to access a given post if I know the URL.

Is there a way to completely block access with log in?
