### ISSUE TITLE
Share Toots via link

### ISSUE THREAD

**Issue by bas89** [tootsuite/mastodon#8748]
I couldn't find a possibility to share a toot outside the mastodon environment, using either a shortened link or other services, i.e. mail or other social networks.

The only, not that comfortable option is to copy the URL in the browser's address bar. Just as a proposal I would suggest to add an entry into the three-dot menu just over "Embed".

_Just as a side-note:_ Sharing toots across the net would also spread the existence of Mastodon generally :-)

**Comment by Cassolotl** [comment]
You can get the URL of the toot from the toot's timestamp, but clearly that isn't obvious enough, because people ask for this fairly frequently!

Anyway, I think this is the oldest issue like this: *URL copy-to-clipboard option in post-menus #680*

And here's another one that's still open (most get closed as duplicates): *Feature request: share button on toots for sharing toots externally #6848*

**Comment by bas89** [comment]
Already expected that there is such an issue, but couldn't find any. But fine, thanks for your answer!
