### ISSUE TITLE
You can reply to boosts

### ISSUE THREAD

**Issue by puckipedia** [tootsuite/mastodon#8794]
see https://mastodon.social/users/earthlover/statuses/100792879813955373

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by trwnh** [comment]
Is this technically a bug? It's certainly unintentional behavior in Mastodon, but it's a valid ActivityPub representation, right? I ask because Prismo (a federated reddit alternative) is planning to allow cross-posts between subs, but to have separate comment sections for each submission, and currently, submissions are treated such that each `Actor` can `Announce` a `Link`, rather than just posting a Note with text content containing that link.

**Comment by puckipedia** [comment]
In Mastodon's case it is unintended behavior, and caused the post to thread weirdly even though it was a reply. i would consider saying that it should only be fixed on the outgoing end (if you reply to an announce, which doesn't really work anyways, it should make it a reply to the original post)
