### ISSUE TITLE
Can instance name be root domain name instead of sub domain name?

### ISSUE THREAD

**Issue by fivestone** [tootsuite/mastodon#8819]
If I use a subdomain to build a mastodon instance,  - sub.myname.com
and use root domain for another personal website, - myname.com

is it possible to set the username with root domain name?  @user@myname.com

Thanks. 

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by lfuelling** [comment]
Only if your instance is also running on the root domain. You have to use the FQDN in your username.

**Comment by Gargron** [comment]
https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Serving_a_different_domain.md

**Comment by mpfaff** [comment]
> https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Serving_a_different_domain.md

For anyone looking for this in the future, it now resides in the [archive branch](https://github.com/tootsuite/documentation/blob/archive/Running-Mastodon/Serving_a_different_domain.md)

And just in case, [here](https://github.com/tootsuite/documentation/blob/a7cdb95ee9b4bddce58915d4feaf3ab03f18ce86/Running-Mastodon/Serving_a_different_domain.md) is a link to the latest version using the commit hash instead of branch names.
