### ISSUE TITLE
[Feature Request] Language Translation

### ISSUE THREAD

**Issue by NexKonig** [tootsuite/mastodon#883]
New to issue/feature requests via Git so apologies for any transgressions.

Saw several posts under different languages and would be nice to be able to translate.
Either the tweet is auto translated for a preference setting of which language(s) you know or option via toot options (three dots) to translate.

Given the difficult nature of language translation I assume:
-Even rough translations would be appreciated
-Supporting some or few languages is better than none

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
       -Found some language related posts but not a request for translate option, if I am wrong please reference it and delete/close.

**Comment by tomouchuu** [comment]
I've been working on a tampermonkey script to do just this: https://github.com/tomouchuu/mastodon-translate // https://niu.moe/@tomo/215888.

I'm not familiar with everything that much (signed up 2days ago) but I can look at just porting over the script to be natively within mastodon. Main issue is that at the moment it's using a proxy to Google Translate (https://github.com/teamsteamdev/google-translate-api) rather than calling the APIs directly as it can be pretty expensive ($20 per million characters to detect the language & then a further $20 per million characters to do the translation).

I'm looking at other potential open-source solutions rather than google such as Apertium but nothing seems to come close to google's power.

**Comment by Siltaar** [comment]
Auto-translation is a good idea, but already a way to embed translations in a toot/pouet to avoid being required to emit multiple messages (one for each languages) or compound messages like this one:
https://mastodon.social/users/yunohost/updates/1902201
Would be great, and "Twitter don't have" feature…

**Comment by tomouchuu** [comment]
With https://github.com/tootsuite/mastodon/pull/1772 & a person's language setting in their preferences it should be possible to do auto translation now.
Issue I could see though would be if a person is on a primarily foreign instance compared to their language settings and so on first load of the feed a ton of requests are going to go off to do the translations for each toot and return them. As well as the quality of the translation via a machine.

I like @Siltaar 's idea of having a dedicated way to embed a translation. It would give multilinguals more space to talk and provide a 'real' translation compared to a machine. I think the process could be complicated if people are doing more than just text like adding content warnings. Since you'd need a content warning box for each language etc. Could get messy real quick!

**Comment by dannyob** [comment]
@tomouchuu one way to handle the cost would be to offer it as an option for each instance owner -- they could choose to use the free-for-bit Bing or $20 Google APIs and fundraise locally for their users, or use the proxy. Just an idea -- I wrote a similar GreaseMonkey script for Twitter in ye olden days, so I like where you're taking this!

**Comment by Gargron** [comment]
Given there are only proprietary APIs (Google, Bing) for this, I don't think we will be implementing that. However, apps could do it.

**Comment by tachyons** [comment]
Media wiki use apertium which is a Foss alternative. But only few languages available there https://m.mediawiki.org/wiki/Content_translation/Machine_Translation/Apertium

**Comment by akarshanbiswas** [comment]
@Gargron You can use Yandex that is what fedilab uses.

**Comment by guysoft** [comment]
@tomouchuu does not work anymore.
