### ISSUE TITLE
Add functionality for OpenX ad server in timelines - minimal ads to support server hosting

### ISSUE THREAD

**Issue by chachatter** [tootsuite/mastodon#8913]
It looks like the main instance - mastodon.social - is supported by Patreon.  This may not work for all and it would be valuable to have the option for minimal ad serving in the timeline to support hosting.  Mastodon rocks!

* * * *

- [ X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by trwnh** [comment]
This is unnecessary. Any server that implements ads will instantly cause its users to leave for a server that does not introduce ads. As Mastodon is a service, it does not require making a profit, and costs can easily be covered by crowdfunding or by coordinating payments among a group of people.

**Comment by chachatter** [comment]
trwnh, thanks for the thoughts.  I"m new to this game and have just set up an instance that I'm hopeful some folks will find works for them.  I wasn't suggesting a profit exercise but trying to think through how hosting costs are covered.  Patreon is an option as used by mastodon.social.   Do you have thoughts, ideas on that other instance hosts are using?  Thanks.

**Comment by trwnh** [comment]
Sure :) Patreon / Liberapay / PayPal / etc. are all options for larger instances, but smaller instances typically don't cost as much and therefore can be paid for by one person or shared among a few people. If it costs you $10/month to host an instance and you have 100 users, then each user can pay $0.10, or 10 users can donate $1 each, or so on. That would easily cover hosting costs. As for compensating admins and moderators, similar goals and targets can be set for paying them as well. In general, most instances are small and based around a community of some sort, so costs are not that high at all. The costs rise a bit after you have to host 1000 or more users, although the costs can also be socialized more easily due to the larger userbase.
