### ISSUE TITLE
[i18n] Weblate is back to 3 weeks ago

### ISSUE THREAD

**Issue by Quenty31** [tootsuite/mastodon#9043]
Hello,
I open an issue again because weblate doesn't synchronise correctly.
The translations are 3 weeks ago...
Fortunately we can find our work on the "history" tap but this is not normal.
Furthermore the translations should be imported before the releases, even RC...

**Comment by Gargron** [comment]
I think the Weblate was "locked" for those 3 weeks. Does that mean people can still submit translations when it's locked? I mean, the whole point of locking (for me) was to avoid having conflicts, as after weblate changes are merged into master, weblate needs to be reset because otherwise it can't recover from merge conflicts. If that doesn't work, then I don't know what to do (build my own translation management app?)
