### ISSUE TITLE
Use recipients name and handle in DM column instead of the one from the last message

### ISSUE THREAD

**Issue by kit-ty-kate** [tootsuite/mastodon#9190]
### Motivation

Since 2.6.0 the DM column shows the DMs by thread. This is great and was greatly needed imo. However some people pointed out that it gets a bit cumbersome to look for a specific thread, especially when you were the last one to reply every time, then your name and handle is show for every thread. Moreover having the profile picture of the person you're talking to and your name associated with it is a bit disturbing.
Recognizing thread by profile picture might be tricky as well as the users might change their profile picture often or might have similar profile pictures.

### Pitch

I think it would be good to have the name and handle of the recipients always displayed in the thread instead of the one from the last person who sent a message on this thread.

**Comment by trwnh** [comment]
At the very least, your name should not be shown, because it is already implied that you are a participant; otherwise, you would not be receiving the message! Conversations should only show the names of *other* participants.

**Comment by lapineige** [comment]
Except on your messages, right ?

**Comment by kit-ty-kate** [comment]
> Except on your messages, right ?

No, the point of this feature request is precisely to not have your own name anywhere in the DM column. It's pointless.

**Comment by kit-ty-kate** [comment]
> But when it's your own message, it's very confusing to see another avatar (and not your avatar somewhere), as you can believe it's not your message.

The avatar is already not yours and it would be even more confusing to distinguish between each conversations.

The point is that the DM column is now a list of **conversations** not **messages**.

**Comment by Gargron** [comment]
To be fair if I look at my DMs in TweetDeck, it also shows not-my-name even if the last message shown is mine. So I guess it could be expected to work this way.

**Comment by lapineige** [comment]
I never used TweetDeck or any equivalent tool so I can't really relate, but I find it confusing this way (especially, but not only, when you're used to the old behaviour where your DM have your avatar next to it) : I can't visually know if it's a new DM or just mine, I've to make the (relatively long in comparison) effort to read the text to understand it, and when I click on my DM the avatar is changing.

Couldn't it be possible to show the recipient(s) avatar(s) as it is now, with our at the bottom to indicate it's a reply ?

**Comment by LoMakesComics** [comment]
I find it odd as well. Honestly if tweetdeck does it I'd say it's not good there either.
DMs listed as conversations as a feature is very similar to how chat conversations are listed in platforms such as facebook messenger, WhatsApp, Telegram, etc. 
Exploring those cases I've found that the usual implementation goes like this: The information of the person you're having a conversation with is always displayed, along with the last message sent in the conversation. If the message was sent by you, then "You: " is prepend to the text. Otherwise, it is implied it was send by the other person.
This is also how Twitter handles DMs on their main platform.

**Comment by slice** [comment]
Can we implement a more clear way to present DM conversations?

I understand the rationale of presenting conversations this way, but it confused me at first. I thought there was a bug because the recipient's avatar was being presented with my username and handle.

I suggest something more akin to how favorites/boosts are presented in the notifications column. Maybe something like this?

![image](https://user-images.githubusercontent.com/4206232/52616578-db699500-2e4d-11e9-8f87-4ba3bdec91e1.png)

(Of course, the boost button shouldn't be there. This is just a quick markup modification that I slapped together.)
