### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by Fastidious** [tootsuite/mastodon#932]
Are these requirements (as listed on the repo README) valid, when using Docker?

```
Ruby
Node.js
PostgreSQL
Redis
Nginx
```

Does that means I will need those installed, **plus** Docker, for Mastodon to work?

- [`N/A` ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by HashDot** [comment]
If you using Docker you need no other dependencies on your host machine.

**Comment by Fastidious** [comment]
@HashDot well, then the README needs to be mended.  I wish I had the inside knowledge to make it better, documentation is lacking.

**Comment by HashDot** [comment]
I think it is more a basic Docker understanding and not a documentation lack.

**Comment by Fastidious** [comment]
@HashDot the main reason of opening this issue was because I know pieces can be run on docker, while others might be left out. A simple example would be running `nginx` as a frontend, and databases (outside docker), while the ruby application runs under docker. 

The README isn’t clear enough for Mastodon mass adoption. Now, if the intention of the existing documentation is to the blurry, it is achieved.

**Comment by Vertux** [comment]
I would like to add another point, I ran into. The documentation does not mention that common server environments like Ubuntu 14.04 are not supported, because it does not support systemed nor openrc, which is needed for the alternative supervisord ([here](https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Alternatives.md)) - that's a little frustrating if you want to setup a mastodon instance.

**Comment by ashfurrow** [comment]
The [Docker instructions](https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Docker-Guide.md) have been updated quite a bit, but they are still lacking mention of problems with 14.04. Would someone be free to open a pull request?

**Comment by Gargron** [comment]
It seems like the new Docker instructions solve OP's problem (confusing list of requirements)

>The documentation does not mention that common server environments like Ubuntu 14.04 are not supported

Unfortunately, there are a *lot* of different platforms. Technically, I think Mastodon can run on most of them. But it is not possible to document everything, especially ad-hoc. Feel free to submit amendments to the documentation. For example, a guide for using Apache instead of nginx has been added by a contributor just like that.
