### ISSUE TITLE
[Feature] An app that allows users to sign on / toot/ message from other Social Networks

### ISSUE THREAD

**Issue by Capricciola** [tootsuite/mastodon#9334]
Is it possible Mastodon could have an application similar to Disqus that let's users opt-in and communicate with users on Mastodon in the same way Disqus uses Facebook and Twitter to post comments?

The application could let users who opt-in:

1 Log in to Mastodon through Twitter, Facebook, Tumblr etc. (Single Sign On)
2. Send and receive DM's to and from users on Mastodon.
3. Mirror recent tweets as toots. And mirror recent Facebook and Tumblr posts as threads (or just mirror the posts if we exclude the character limit). And vice versa to mirror posts from Mastodon.
4. See your Mastodon notifications from another social network through the application.
5. Since Twitter and Facebook allow users to download their data. Maybe users could upload their data through the app, and clone their past posts onto Mastodon.

This would make it a lot easier for users to migrate to Mastodon from other social networks, while also allowing users who don't want to migrate to still keep in touch with friends who move to Mastodon.

**Comment by trwnh** [comment]
This could be done by other apps; it would not be a good idea to package in all this functionality by default because it creates unnecessary reliance on external services.

- 1 and 2 are better served by ActivityPub interoperation
- 3: many different crossposting and mirroring services already exist
- 4: you can create a bot to notify you on other services, if desired
- 5: Mastodon does not currently support uploading past posts (see #177 about this), and they would not be fetched unless loaded manually (see also #34 about this)
