### ISSUE TITLE
Toots are still stored locally when request failed

### ISSUE THREAD

**Issue by kit-ty-kate** [tootsuite/mastodon#9415]
### Expected behaviour

Don't store anything (or store and then fallback) until you are sure the toot has been received by the federation or the mentioned instance.

### Actual behaviour

My instance experienced https://github.com/tootsuite/mastodon/issues/9411 which I discovered while trying to send a reply to somebody. The requests got refused with either an error 500 or 503. However after the bug has been fixed I realize the replies I try to send several times were stored in the database an thus displayed in my list of reply toots.
At least the good thing is that the toot were not sent to the person (on another instance) and are just existing locally within my instance.

### Steps to reproduce the problem

Get Mastodon 2.6.4, make the w3id.org server fail, send a DM, watch it fail to be sent. The DM is still stored locally (appear in the list of replies)

**Comment by nightpool** [comment]
delivery to foreign servers can fail for a huge variety of reasons—for example, if you have thousands of followers, it's a good bet that at least a couple of their servers won't be working at the time. since in practice it's impossible to distinguish the "fault" for an error in delivery, delivery to remote servers is handled and retried separately from local delivery
