### ISSUE TITLE
PreviewCard does not respect charset

### ISSUE THREAD

**Issue by jomo** [tootsuite/mastodon#9466]
### Expected behaviour

Cards should parse the `Content-Type` HTTP header and `<meta http-equiv="Content-Type">` element and use the specified charset to parse the `<title>`.

### Actual behaviour

The wrong charset is used and the link preview is garbage.

### Steps to reproduce the problem

Link to https://playground.jomo.tv/windows-1251.html

Content of that site, encoded in windows-1251 (pipe it to `iconv -f utf8 -t windows-1251`):

```html
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=windows-1251" />
  <title>сэмпл текст</title>
</head>
<body>
  <p>сэмпл текст</p>
</body>
</html>
```

### Specifications

Tested on a Mastodon v2.6.5 instance

**Comment by ThibG** [comment]
This is because the `CharlockHolmes` gem is used to detect the charset used by the document, and the result is used to tell Nokogiri how to parse the file. As far as I understand, `CharlockHolmes` does not have any HTML-specific understanding, so it will not honour the meta tag.

In this particular case, `CharlockHolmes` detection raises the following: `{:type=>:text, :encoding=>"ISO-8859-6", :ruby_encoding=>"ISO-8859-6", :confidence=>37, :language=>"ar"}`

*Not* using `CharlockHolmes` work. Maybe there's a better way to make `Nokogiri` and `CharlockHolmes` work together, honoring meta tags and using `CharlockHolmes` as a fallback.
