### ISSUE TITLE
Tackle hate speech on religious minorities in code of conduct

### ISSUE THREAD

**Issue by Breakfastisready** [tootsuite/mastodon#9478]
This is to bring light upon a type of hate speech used in India (and many other countries). There are religious minorities in India that are often targeted and made fun of (especially Muslims). Twitter has completely failed to take care of this menace, probably because of small number of moderators.

The code of conduct does not provide anything related to discrimination against religious minorities. (It covers sexual minority, xenophobia but not religious minorities). Can you please add this in CoC?

For example, the admin of this violent nationalistic instance called Inditoot.com defended this parody account saying that it does not violate the code of conduct. As mastodon will grow a user base in India, this should be taken care of before it becomes a menace:

https://inditoot.com/@Muneeb

(Translation can be given on request. It's basically an islamophobic parody account)

**Comment by nightpool** [comment]
Hi, thanks for making this request. 

While this github repository does have [A Code of Conduct](), this only applies to spaces directly associated with the Mastodon software project (This Github, [the forums](https://discourse.joinmastodon.org), Discord and IRC, among others). Additionally, mastodon.social (the first instance) has an additional [Code of Conduct](https://mastodon.social/about/more) that many other instances have copied, but it's not directly tracked by this repository, since it's specific to that server.

It looks like inditoot.com is run by a person named Vaibhav Gupta, also reachable @inditoot@inditoot.com. While we're happy to add such language to the mastodon.social "model policy", ultimately the decision on whether to use it or not is up to the individual server admin.

Most server admins will take action against against accounts that are behaving badly even if they don't explicitly violate any individual section of their code of conduct—i would suggest you DM or email your local instance admin to start a discussion on the issue.

Sorry I couldn't be of more assistance. Does what I said make sense?

**Comment by nightpool** [comment]
I agree, however, this GitHub issue tracker isn't really the place to raise the issue. Additionally, i would mention that we already have a policy against violent nationalism (and that inditoot has this policy as well, after copying it). So it's not like this stuff is "allowed", it's just another way of making it more explicit

**Comment by Breakfastisready** [comment]
I see. Thank you.

**Comment by tachyons** [comment]
inditoot is now silenced from mastodon.social
