### ISSUE TITLE
Ability to change the privacy post of an existing toot

### ISSUE THREAD

**Issue by spaceottercode** [tootsuite/mastodon#9479]
Issue #3933 but now that we have "delete and redraft". So why have it? Apparently confusion stemming from Lock account vs. privacy post. The ability to go back & switch old toots to followers-only without having to repost it again, if statuses are mutable, even if the change has limited propagation.

Benificiaries: new-comers

**Comment by m4sk1n** [comment]
Impossible in practice because of protocol limitations

**Comment by charlag** [comment]
Not only it is not really possible (visibility is who server sends statuses to, we can ask others to delete them but they don't have to do it), but it also has some social applications when things become public or private suddenly which can be quite confusing.
There's an update verb in ActivityPub afaik but it has nothing to do with privacy.

**Comment by trwnh** [comment]
I agree that this would be nice, but it's like unsending an email after it's already been sent. The only way this would work is for private -> public (by redelivering a public copy to your followers / etc). Public -> private would never work, because you can only ensure forward secrecy, and only to the extent that you trust the recipients to not republish or redistribute anything.

**Comment by spaceottercode** [comment]
I believe I understand and will recommend this issue closed, but just curious how are deletes handled. That is to say don't we run into some of these same issues with deletes.

In any case is it safe to say delete & redraft is the way to go then?
