### ISSUE TITLE
Websocket connection problem

### ISSUE THREAD

**Issue by apardo** [tootsuite/mastodon#9744]
Hi, I see in the browser console this lines:

WebSocket connection to ‘wss://social.ingobernable.net/api/v1/streaming/?stream=public&access_token=long_hash’ failed: Error in connection establishment: net::ERR_NOT_IMPLEMENTED

How can I solve that?

Thanks

**Comment by Gargron** [comment]
Not sure, but at least anonymous stream works for me. It's either a browser issue for you personally, or a problem for logged in users. Check `journalctl -u mastodon-streaming` for any errors (ignore missing access token errors, those are normal). I have encountered some issues similar to this in the past (except for the ERR_NOT_IMPLEMENTED part) because the streaming process could not establish a connection with PostgreSQL due to a misconfiguration.

**Comment by apardo** [comment]
When I deactivate Web VPN from Opera browser, the websockets works.
