### ISSUE TITLE
SalmonWorker / ActiveRecord::RecordNotUnique stop retries

### ISSUE THREAD

**Issue by krainboltgreene** [tootsuite/mastodon#988]
Catch the exception and gracefully exit instead of retrying.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
Not so easy. This comes from race conditions (because there are AR checks for uniqueness, but the DB constraint kicks in). But at which exact level does this occur? It could be because somewhere else a `FollowRemoteAccountService` has just finished looking up the remote account for the first time, but in the Salmon worker, we wanted to look up the account attribute a status to it. In that case, just discarding the job would lead to loss of the status.

This needs to be caught gracefully at the level it occurs.

I wish there was a test suite for discovering all race conditions at once, I'm sure this won't be the last :sweat_smile:

**Comment by krainboltgreene** [comment]
Yes, but no matter what a retry will get the same result, right? Because the data already exists and will likely exist the next N retries.

**Comment by Gargron** [comment]
No, basically everything in there checks in advance if a record exists, and uses it if it does. So retrying will just make it pick up the record it needs instead of trying to create it

**Comment by krainboltgreene** [comment]
Ah, it's a find or create.

**Comment by ashfurrow** [comment]
It sounds like technical limitations prevent us from moving forward on this. @krainboltgreene are you comfortable closing the issue, or would you like to keep it open for further discussion?

**Comment by krainboltgreene** [comment]
I believe there's still a solution here that avoids a "failed worker": Retry the worker in x n.
