### ISSUE TITLE
When clicking a local profile link in a feed / the leftmost column, use a /@handle formatted url

### ISSUE THREAD

**Issue by TaizoSimpson** [tootsuite/mastodon#9950]
### Pitch

Currently, if a link to any user's profile is clicked, the url in the address bar is changed to something in the form of `/web/accounts/\d+`.  This makes sense for remote accounts, where this is the only way to refer to them without leaving the local instance, but for accounts that *do* exist on the local instance, this seems less than ideal.

### Motivation

This suggestion is based around the idea that the "preferred" way to link to a user's account, especially from a third party domain where user's might not have heard about mastodon, or might not know the username of the person creating the post, is in the format of `/@users-handle`.  This format makes it clear that the link points to the user's profile and doesn't have any "crud".  It makes the urls clean and human-readable.

The problem with the current system is that a lot of local users find the url for their profile by navigating to their profile from the main page ― a process that almost invariable results in them getting a url in the `/web/accounts/` format.  The users then go on to share this URL on their other social media, and thus a lot of these ugly urls end up in circulation on the non-federated internet.

Yes, I know it's a relatively minor issue, but I think it would still be a worthwhile change.

**Comment by trwnh** [comment]
`/@username` currently resolves to the public web page. I'm not sure it's a good idea to confuse the public routes with the in-app routes. More specifically, `/accounts/id` is part of the Mastodon API and not the web representation via ActivityPub.

**Comment by TaizoSimpson** [comment]
Oh, that was my mistake.  I had thought that the URLs were synonymous.  Perhaps a better solution would be to add an accessible way for the users to get their profile URLs somewhere one the `/web/accounts/...` page?  I admit that this proposal is rapidly losing it's worthwhile-ness though.

**Comment by trwnh** [comment]
It would be nice if they were synonymous, but they're not. The Mastodon API is for fetching stuff from the local database, and the routes are obviously not the same on remote servers. The public pages are linked on the account view, though this might not be obvious: the avatar is a link to the public page, e.g. `mastodon.social/@trwnh`. Additionally, if you right-click a display-name or mention and choose "Open in new tab", it will open the public page. This is because all display-names and mentions are actually linked to the public page, and are translated via a background search for the internal Mastodon API ID for that account -- so a link to `mastodon.social/@trwnh` will search your instance for that account and return the internal representation, e.g. searching for `mastodon.social/@trwnh` on mastodon.social will return  `/accounts/14715` and [the associated JSON from the API response.](https://mastodon.social/api/v1/accounts/14715) This is different from [the public JSON representation that is sent out over ActivityPub.](http://mastodon.social/@trwnh.json)
